### ISSUE TITLE
Support for federated logins

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#10]
Is amplify going to be extended to handle federated logins to Cognito? like Google and Facebook?

**Comment by richardzcode** [comment]
Yes @jonsmirl  federated identities on the way. Will be added soon.

Thanks,
Richard

**Comment by jonsmirl** [comment]
I would suggest that this be a top initial goal, and then add the implementation to Mobile Hub. Over the last few years I've probably seen 500 people people asking for Javascript code to implemented Cognito Social + User Pool logins. It is not a trivial piece of code.  Most of the people posting about this end up moving over to Auth0 which has a finished widget.

**Comment by mlabieniec** [comment]
Added federated support in PR #57
