### ISSUE TITLE
Cognito Sync?

### ISSUE THREAD

**Issue by Nexuist** [aws/aws-amplify#102]
Hi there,

We have gotten to the point where we can register and login users just fine in our React Native app. Now we would like to be able to store data for user accounts using [Cognito Sync datasets](http://docs.aws.amazon.com/cognitosync/latest/APIReference/API_Dataset.html). Is there a way to do that via Amplify? If not, what is the recommended way to do this from a React Native app?

Thanks,
Andi

**Comment by undefobj** [comment]
We would recommend that you take a look at AWS AppSync for this use case: https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-reactnative.html

**Comment by stripathix** [comment]
What about the data already stored in Cognito sync? Is there any way to migrate that data?
