### ISSUE TITLE
setupTOTP issue 

### ISSUE THREAD

**Issue by ramamoob** [aws/aws-amplify#1043]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
I upgraded AWS Amplify from 0.3.3 to 0.3.4. Trying to setupTOTP results in error e.associateSoftwareToken() is a not a function in Auth.js on line number 541. I am not encountering this issue with 0.3.3. 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

I am using AWS Cognito Userpool for user management. The user pool has the following settings.
1. MFA - Optional
2. MFA Option - TOTP
3. Require Verification - Email

The user registration workflow involves user first verifying their email. After successful verification, the user then goes through the step pf associating Software MFA Token.  Here is the code snippet.

```
  handleSubmitVerification = async (event) => {
        console.log('inside handleSubmitVerification...');

        event.preventDefault();

        const {user_id, code} = this.state;
        console.log({user_id, code});

        try {
          let confirm_signup = await Auth.confirmSignUp(user_id, code);
          console.log('confirm_signup: ', confirm_signup);

          /* START of TOTP MFA */
          console.log('user has now signed up. Now setup OTP...');
          const{username, password} = this.state;
        //  console.log({username, password});

          console.log('first signin the user...');
          let signin = await Auth.signIn(username, password);
          //console.log(signin);

          console.log('Then get the current authenticated user...');
          let user = await Auth.currentAuthenticatedUser();
          console.log('user: ' + JSON.stringify(user));

          let totp = await Auth.setupTOTP(user);
          //console.log('totp: ' + JSON.stringify(totp));

          var qr_code = "otpauth://totp/AWSCognito:" + user.username + "?secret=" + totp + "&issuer=Cognito";
 
         this.setState({qrcode: qr_code});
          this.setState({user: user});
          this.setState({error: {}});
          this.setState({enterTOTP: true});

          console.log('successfully generated the totp...');
          return;
          /* END OF TOTP MFA */

        }catch(error){
          console.log('confirm_signup error: ' , error);
          console.log('response is not OK...')
          console.log(error.message);
          this.setState({is_error: true});
          this.setState({error: {'errorMessage': error.message}});
        }

    }

```

What is the expected behavior?
User is supposed to be presented with QR code. Instead it results in error e.associateSoftwareToken() is a not a function in Auth.js on line number 54. I can verify that user has valid session by printing Auth.currentAuthenticatedUser(). 

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Started seeing this issue only in 0.3.4. If I revert back to 0.3.3 it works with no change in the application code. The issue is affecting all browsers. 

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
@ramamoob can you try the latest version which is `0.4.4`

**Comment by ramamoob** [comment]
@powerful23 - Thanks for your response. I did upgrade it to the latest version and can confirm that it is working.
