### ISSUE TITLE
Could not resolve all files for configuration ':amazon-cognito-identity-js:lintClassPath'

### ISSUE THREAD

**Issue by halaharr** [aws/aws-amplify#1045]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Cannot build APK for android

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
Build APK for android

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Amplify: 0.2.9

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by haverchuck** [comment]
Hi @halaharr ,

Thanks for reaching out!  Are you using Ionic for your application, and if so which verison?

Thanks!

**Comment by halaharr** [comment]
Hi,
    I am using react native not ionic. 

RN ver 0.54

Thanks

**Comment by haverchuck** [comment]
Hi @halaharr ,

I was just able to build a APK for Android on an app I generated with the react-native cli and which imported aws-amplify 0.4.4 and aws-amplify-react-native 0.2.15.    The react-native version is 0.55.4 (so pretty close to what you're using).

Do you have any specific error output you can share?

**Comment by halaharr** [comment]
Thanks for looking into it. I had updated my build.gradle which caused this issue. Once I rolled back to the old version that error went away. I really appreciate you looking into it.

Thanks

**Comment by haverchuck** [comment]
@halaharr : no problem!
