### ISSUE TITLE
CHANGELOG.md is not up-to-date

### ISSUE THREAD

**Issue by jsyrjala** [aws/aws-amplify#1052]
[CHANGELOG.md](https://github.com/aws/aws-amplify/blob/master/CHANGELOG.md) is not up-to-date. 

It list e.g. these package versions as latest from 05/18/2018
- aws-amplify - 0.4.1
- aws-amplify-react - 0.1.47
- amazon-cognito-identity-js - 2.0.6

When actually the latests releases (known by npmjs.com) are from 04/06/2018
- aws-amplify - 0.4.4
- aws-amplify-react - 0.1.50
- amazon-cognito-identity-js - 2.0.9

**Comment by mlabieniec** [comment]
@jsyrjala the changelog in the root is no longer used and we need to remove it. We now use [Conventional Commits](https://conventionalcommits.org/) with lerna and each individual packages changelog.md is updated.

**Comment by jsyrjala** [comment]
Ok. I think that also wiki needs updating in that case: https://github.com/aws/aws-amplify/wiki/Release-Cycle

**Comment by mlabieniec** [comment]
Thanks for pointing that out, we will get that updated.

**Comment by mlabieniec** [comment]
Updated the wiki and will note in the root change deprecation.
