### ISSUE TITLE
Auth.currentCredentials returning session of user after Auth.signOut is called.

### ISSUE THREAD

**Issue by fazelmk** [aws/aws-amplify#1057]
Bug.

So I'm using federated identity to log in to a user pool ( I don't know if it's mandatory or not, but I created and I'm currently using ).

Sign in, and using ok. But after I call signOut the currentCredentials still point to the session I just sign out of.

```
Auth.signIn ( ok )
Auth.currentCredentials ( ok. returns the session )
Auth.currentAuthenticatedUser ( ok. returns the user info )

Auth.signOut ( ok )
Auth.currentCredentials ( PROBLEM!! Still returns the session )
Auth.currentAuthenticatedUser ( ok. returns "not authenticated" )
```

My amplify config

```
Amplify.configure( {
      Auth: {
        identityPoolId: environment.identityPoolId,
        region: environment.region,
        userPoolId: environment.userPoolId,
        userPoolWebClientId: environment.clientId,
        mandatorySignIn: true
      }
    } );
```

What is the expected behavior?

User credentials be removed/revoked.

log of the problem

```
[INFO] 09:39.527 Cache - Remove item: key is federatedInfo
[INFO] 09:39.528 Cache - Remove item: key is federatedUser
{[DEBUG] 09:39.529 AuthClass - user sign out: CognitoUser}
[DEBUG] 09:39.529 AuthClass - user sign out: CognitoUser {...} __proto__: Object
[DEBUG] 09:39.530 AuthClass - setting credentials for guest
{[DEBUG] 09:39.533 AuthClass - cannot load guest credentials for unauthenticated user: "cannot get guest credentials when mandatory signin enabled"}
```

Get Credentials
```
[DEBUG] 09:39.547 AuthClass - getting current credntials
[DEBUG] 09:39.549 AuthClass - picking up credentials
[DEBUG] 09:39.551 AuthClass - getting new cred promise
[DEBUG] 09:39.553 AuthClass - checking if credentials exists and not expired
{[DEBUG] 09:39.554 AuthClass - is this credentials expired?: CognitoIdentityCredentials}
[DEBUG] 09:39.557 AuthClass - credentials not changed and not expired, directly return
{[DEBUG] 09:39.533 AuthClass - cannot load guest credentials for unauthenticated user: "cannot get guest credentials when mandatory signin enabled
cannot load guest credentials for unauthenticated user: "cannot get guest credentials when mandatory signin enabled"}
```
Resolve and return the credential of last authenticated user
```
CognitoIdentityCredentials {expired: false, authenticated: true, .... }
```

Problem on Angular 5

Which versions of Amplify?
"aws-amplify": "^0.4.4",

and which browser? 
Chrome Version 67.0.3396.87 (Official Build) (64-bit)

OS?
Ubuntu 16.04

Affected before?
no clue. first version I'm using

**Comment by haverchuck** [comment]
Thanks for reaching out.  When you attempt to get the session, you are indeed getting the last session, but since it is now invalidated by the signout action users will not be able to hit API endpoints (provided that the API is private and accessible only to signed in users). However, it is admittedly confusing that the session doesn't show that it is expired, so I am submitting a feature request to remedy this.

**Comment by fazelmk** [comment]
@haverchuck Appreciate the fast response. 

If I may add I looked myself to the code to see why it does it. And it seems to only do that with `mandatorySignIn: true`. Otherwise it gives a guest session back.
Seems only a condition missing to clean the session on mandatorySingIn. 


And for those who get here with this problem `Auth.currentAuthenticatedUser` will return error, just call it after getting the sessions back from `Auth.currentCredentials` and you are safe.

And if you are worried about back-end hit, the lib is smart enough to not call the back-end when it have valid cached info ( valid meaning the credentials are valid, not the user info, it may have changed by a call to cognito from the back-end or other user with permission to do that. )

**Comment by haverchuck** [comment]
@fazelmk 

Thanks for your feedback... I'm changing this from a feature request to a bug (as you originally marked it).
