### ISSUE TITLE
CORB Problem with API Call

### ISSUE THREAD

**Issue by BrianSHenderson** [aws/aws-amplify#1061]
When using the following:
`API.get('Img', '/readQR', { headers: {}, response: true, queryStringParameters: { uri: oImg.url } })`
I'm occasionally receiving:
`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://XXXX with MIME type application/json.`

Do I need to add something to the header object here?  I'm running from http://localhost:3000

**Comment by haverchuck** [comment]
@BrianSHenderson 

Thanks for reaching out!

You may need to [enable CORs on your API gateway resource](https://aws.github.io/aws-amplify/media/api_guide#using-custom-http-request-headers).
