### ISSUE TITLE
Lib throws "Username cannot be empty" on SignUp when no "username" needed for sign up

### ISSUE THREAD

**Issue by wzup** [aws/aws-amplify#1063]
### Do you want to request a feature or report a bug?

Bug

### What is the current behavior?

Lib throws
> Username cannot be empty

### What is the expected behavior?

Accept **signUp** action without errors. 

### Example

I've set up my cognito so that it doesn't use username, only email and password.
So why your lib throws `Username cannot be empty`? This is definitely wrong behaviour!

If I call `.signUp` this way (params as strings, no `username`), all works as expected, no errors thrown:

```javascript
Auth.signUp(email, password)
    .then( data => {
        // All is OK, we here
    } )
    .catch( err => {

    } );
```

If I call this way (params as an object), your SDK throws. Why? It is not consistent. I need to call this way because I have `attributes` to pass to Cognito.

See your docs https://aws.github.io/aws-amplify/media/authentication_guide#working-with-user-attributes, I need to use object params, but it doesn't work when object!

```javascript
Auth.signUp( {email, password, attributes: {
    foo: 'bar'
}})
    .then( data => {
    } )
    .catch( err => {
        // `Username cannot be empty` // Why?
    } );
```

**Comment by dallinwright** [comment]
I had a very similar issue too, when you go into AWS cognito make sure that the signup type is set to email not username or email aliases configurations. I would recommend walking through in the UI the creation of the user pool in the aws mobilehub to see what you can do.

**Comment by wzup** [comment]
@dallinwright 
It is already set. That's why I don't understand their error

![screen shot 2018-06-20 at 5 34 29 pm](https://user-images.githubusercontent.com/3880497/41665365-6ee04f84-74b0-11e8-8ee6-b2f54663b8e9.png)

**Comment by dallinwright** [comment]
Ah I see a potential error. Even though it is set to email, you have to pass the email as the username like my function below. I would agree that it makes 0 sense from a logic standpoint but you have to do it this way.

```
      Auth.signUp({
        username: this.signupForm.get('email').value.toLowerCase( ),
        password: this.signupForm.get('password').value,
        attributes: {
          email: this.signupForm.get('email').value.toLowerCase( ),
          given_name: this.signupForm.get('given_name').value,
          family_name: this.signupForm.get('family_name').value
        },
        validationData: []
      }).then(() => {
          this.router.navigate(['unverified']);
        }).catch(err => {
          this.errorMessage = err;
        });
```

**Comment by powerful23** [comment]
Feel free to reopen it if you are still facing this issue.

**Comment by Josecc** [comment]
I have the same issue using the react `aws-amplify` lib.

**Comment by JuanjoFR** [comment]
Here is the documentation about this topic:

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases-settings-option-2
