### ISSUE TITLE
Error: Network Error generic message

### ISSUE THREAD

**Issue by dallinwright** [aws/aws-amplify#1064]
I think I have experiencing a bug.

Current I am trying to do a simple get for my webapp. Currently I am trying to do a get and getting a generic network error response. My function looks like this and I am tyring to simply log to the console the response from my lambda.

```
    async getOwnerDecks() {
        const authToken = await Auth.currentSession().then(data => {
            return data.idToken.jwtToken;
        });

        const authHeader = {
            Authorization: authToken
        };

        this.result = await this.amplifyService.api().get('decks', '', {headers: authHeader}).then( resp => {
            return resp;
            }).catch(err => {
                console.log(err);
        });
    }
```

And that is it. I can invoke via Postman, via this command from awsmobile `awsmobile cloud-api invoke decks get /decks` and get successful responses but from the function above I get nothing. I have tried using API.get and angularService.api().get and all fail.

Error Message: 
```
Error
​
columnNumber: 15
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
fileName: "http://localhost:8080/vendor.js"
​
lineNumber: 96651
​
message: "Network Error"
​
request: XMLHttpRequest { __zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "https://xxxxxx.execute-api.eu-west-1.amazonaws.com/MobileHub_Deployments/decks", __zone_symbol__ON_PROPERTYreadystatechange: handleLoad(), … }
​
response: undefined
​
stack: "createError@http://localhost:8080/vendor.js:96651:15\nhandleError@http://localhost:8080/vendor.js:96194:14\nwrapFn@http://localhost:8080/polyfills.js:3510:30\n./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:8080/polyfills.js:2743:17\nonInvokeTask@http://localhost:8080/vendor.js:40796:24\n./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:8080/polyfills.js:2742:17\n./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:8080/polyfills.js:2510:28\n./node_modules/zone.js/dist/zone.js/</ZoneTask.invokeTask@http://localhost:8080/polyfills.js:2818:24\ninvokeTask@http://localhost:8080/polyfills.js:3862:9\nglobalZoneAwareCallback@http://localhost:8080/polyfills
```

Here are the response I should get 

```
{ requestBody: null,
  pathParams: '/decks',
  queryStringParams: null,
  headerParams:
   { Accept: 'application/json, text/plain, */*',
     'CloudFront-Forwarded-Proto': 'https',
     'CloudFront-Is-Desktop-Viewer': 'true',
     'CloudFront-Is-Mobile-Viewer': 'false',
     'CloudFront-Is-SmartTV-Viewer': 'false',
     'CloudFront-Is-Tablet-Viewer': 'false',
     'CloudFront-Viewer-Country': 'ES',
     Host: 'xxxxxxxxxxxxx.execute-api.eu-west-1.amazonaws.com',
     'User-Agent': 'axios/0.17.1',
     Via: '1.1 xxxxxxxxxxxxxxx.cloudfront.net (CloudFront)',
     'X-Amz-Cf-Id': 'iNPucPQXZybc7Zg1AfA005rE-W30Qs-TG1V2pDK5fDHAPWSNSBg==',
     'x-amz-date': '20180620T143059Z',
     'X-Amzn-Trace-Id': 'Root=1-5b2a6523-3c88e3d2f77853e8cbf4351c',
     'X-Forwarded-For': 'xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx',
     'X-Forwarded-Port': '443',
     'X-Forwarded-Proto': 'https' },
  stage: 'Development',
  stageVariables: { stage: 'Development' },
  cognitoIdentityId: null,
  httpMethod: 'GET',
  sourceIp: '37.14.161.126',
  userAgent: 'axios/0.17.1',
  requestId: '8cec8ff3-7496-11e8-a737-9d1996926e66',
  resourcePath: '/decks' }
```

I am using the latest version 6 angular/cli, aws-amplify and aws-amplify-angular npm packages.

I have verified it is not cors related, as I was getting a cors header issue before and now the error has gone away once I added the required headers to the awsmobile lambda.

**Comment by haverchuck** [comment]
@dallinwright 

Thanks for reaching out!  Have you tried passing '/decks' as the path parameter in .get()?

`this.amplifyService.api().get('decks', '/decks', {headers: authHeader})`

**Comment by dallinwright** [comment]
Thanks for responding! I ended up figuring it out, it turns out that if you click and enable the cors header through the aws mobile UI, it doesn't necessarily add it to the api gateway and it doesn't update your lambdas. You have to do a `awsmobile pull` and verify inside the yaml that it is actually set. It seems the UI is wonky and doesn't do it.

In case others stumble upon this here is what I did to troubleshoot.

Open up the network view in a browser, this will help you break down what exactly is going wrong. I was receiving a 502 trying to access the path when I received the generic network error. This was a red herring as this is returned as a 'cloudfront cache miss' since api gateway can't write to cloudwatch when it received events. 

You also need to add the cors response headers to your generated lambda, as the default one doesn't include it and when you enable it from the aws-mobile-config yaml file it doesn't update it either. Even though cors is enabled in the API, the lambda still needs to process and do stuff with it.

Also, this library has a bug with the last couple versions of RXJS in that you have to edit a file to change the path when importing subject, otherwise webpack/typescript start throwing errors. Every install or update of the library you have to do this.

All in all, it was problems with the generated configs within AWS from the automated setup, it does about 70% of the work for you and you need to look for the needles in the haystack to get the rest.
