### ISSUE TITLE
Jest failed in react native project when import aws-amplify

### ISSUE THREAD

**Issue by fangleen** [aws/aws-amplify#1077]
Do you want to request a feature or report a bug?
**report**
What is the current behavior?
Jest fail with the simple test in Expo project.

All I did was add in Amplify, now my Jest tests fail on testing components in React-Native (using Expo) I get the fail for: "TypeError: window.addEventListerner is not a function at Object. (node_modules/aws-amplify/lib/common/ClientDevice/browser.js" (and one for index.js in same directory, and just "common/broswer.js"

The test is the default Expo test that is in the project when you create it (passes if I just remove all of Amplify:

```
import React from 'react';
import { View } from 'react-native';
import Amplify from 'aws-amplify'; // If I remove this line, jest will pass the test

import renderer from 'react-test-renderer';

it('renders without crashing', () => {
  const rendered = renderer.create(<View />).toJSON();
  expect(rendered).toBeTruthy();
});

```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
Run the above test in a project created by create-react-native-app and add amplify support.

What is the expected behavior?
The test should pass when import the  aws-amplify library

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
"aws-amplify": "^0.4.4",
"aws-amplify-react-native": "^0.2.15",

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
@fangleen I think you need to tell Jest that you are running the tests in react-native environment so it should pick up the right file which should be https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Common/ClientDevice/reactnative.ts

**Comment by fangleen** [comment]
Thanks @powerful23, after change the preset from "jest-expo" to "react-native", the test pass.
` "jest": {
    "preset": "react-native"
  },
`

**Comment by powerful23** [comment]
Cool, feel free to reopen if you are still facing this issue.
