### ISSUE TITLE
AWS S3 + CloudFront + Route 53 build and deploy howto

### ISSUE THREAD

**Issue by josoroma** [aws/aws-amplify#1080]
Is there any recommendation or guide available that explains how to build and deploy to AWS using `awsmobile init` instead of the manual conf (no using awsmobile publish)?

**Comment by haverchuck** [comment]
Hi @josoroma 

Please see [this documentation](https://aws.github.io/aws-amplify/media/quick_start#automatic-setup)

Thanks!

**Comment by josoroma** [comment]
@haverchuck thanks!

Yep, I follow every step there. It works with npm run start but not with awsmobile publish. No console logs.

**Comment by mlabieniec** [comment]
@josoroma can you let us know how you setup the CLI and what version of node you are using? awsmobile publish should push your app to your configured S3 bucket. But you need to make sure hosting is enabled, check `awsmobile features` and make sure hosting is enabled on your project.

**Comment by josoroma** [comment]
I will try to use the manual conf and not the automatic conf:

https://serverless-stack.com/chapters/configure-aws-amplify.html

**Comment by josoroma** [comment]
my current `.gitignore` file:

```
# See https://help.github.com/ignore-files/ for more about ignoring files.

# dependencies
/node_modules

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local
.idea

npm-debug.log*
yarn-debug.log*
yarn-error.log*

#awsmobilejs
appsync-info.json
aws-info.json
project-info.json
aws-exports.*
awsmobilejs/.awsmobile/backend-build
awsmobilejs/\#current-backend-info
~awsmobilejs-*/
```
