### ISSUE TITLE
301 when attempting to upload to S3

### ISSUE THREAD

**Issue by RedHatter** [aws/aws-amplify#1083]
I'm attempting to upload a file to S3 using the follow code.

    Auth.currentCredentials()
      .then(credentials => {
          return Storage.put(this.state.file.name, this.state.file, {
            contentType: this.state.file.type,
            credentials: Auth.essentialCredentials(credentials)
          }))
      })
      .catch(console.error)

It produces an network error.

    Failed to load https://s3.amazonaws.com/dealerdigitalgroup.printmanager/public/test.csv: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Looking at the network request it looks like Amplify is using the wrong url.

    Request URL: https://s3.amazonaws.com/dealerdigitalgroup.printmanager/public/test.csv
    Request Method: OPTIONS
    Status Code: 301 Moved Permanently
    Remote Address: 52.216.232.157:443
    Referrer Policy: no-referrer-when-downgrade
    
    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message> 
    <Bucket>dealerdigitalgroup.printmanager</Bucket>< 
    <Endpoint>dealerdigitalgroup.printmanager.s3.amazonaws.com</Endpoint>< 
    <RequestId>70DC5084D36426E2</RequestId>
    <HostId>a3Iu7KPVdiJ97bYlW1F/qXXTDlWOgaaPROyecNW0QWeJQn3xDui8e4bsGvNxqAQ3L4FVdessHFo=</HostId></Error>

**Comment by haverchuck** [comment]
@RedHatter 

Did you [setup your S3 bucket's CORS policy](https://aws.github.io/aws-amplify/media/storage_guide#setup-amazon-s3-bucket-cors-policy)?

**Comment by RedHatter** [comment]
I have to CORS set exactly as the link shows.

**Comment by mlabieniec** [comment]
@RedHatter you do not need to set the credentials this way on the Storage category. Please check out the [Quick Start[(https://aws.github.io/aws-amplify/media/quick_start) to configure your Auth. Once that's configured, you can just do `Storage.put(file,path)`.  The Storage category will automatically use the configured credentials and session if you authenticate with Auth prior.

**Comment by RedHatter** [comment]
Setting the credentials as shown in the quick start does not fix the issue.

Why is amplify using urls in the format `https://s3.amazonaws.com/mybucket/public/file`? Isn't that legacy?

**Comment by RedHatter** [comment]
Turns out I had the storage config set to the wrong region.
