### ISSUE TITLE
Manually set current session credentials.

### ISSUE THREAD

**Issue by aaayushsingh** [aws/aws-amplify#1084]
Do you want to request a feature or report a bug?
Support Request / Feature Request

What is the current behavior?

I'm using Nativescript, and session is cleared after app refresh. I get no user from Auth.currentSession()

However I store the jwt from login and can access endpoints manually by passing that as header. 
I would like to use this to make Amplify believe that a user is logged in to use it in other parts of the application.

**Is there a way to manually set credentials to use all the functionality of Amplify?**

**Comment by praveshkhatana** [comment]
Looking for a solution. **Auto Login after APP relaunch**, so they have no need to manually sign in again n again (until they sign out manually). Just like any other APP, AMAZON etc.

**Comment by mlabieniec** [comment]
@aaayushsingh we don't have official support for NS yet. The way the persistence is set is with storage on a PER platform basis. So on react native it uses AsyncStorage, in browser local storage etc. Similarly some bridge would need to be provided to NS to use to store the session and the library would need modifications to support it. Looks like there is a module here:
https://www.npmjs.com/package/nativescript-sqlite

and would need to be implemented somewhere in cognito sdk similar to:
https://github.com/aws/aws-amplify/blob/master/packages/amazon-cognito-identity-js/src/CookieStorage.js

**Comment by mlabieniec** [comment]
tracking support feature request in #1035
