### ISSUE TITLE
No matching version found for aws-amplify@^0.4.6

### ISSUE THREAD

**Issue by garyfanglee** [aws/aws-amplify#1086]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

The following error prevents install:

> executing npm install ...
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for aws-amplify@^0.4.6
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of 'aws-amplify-react'
> npm ERR!

For some reason, a non-existent version of Amplify is being looked up.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**

Run "awsmobile run" after downloading **react-project-2018-06-21-21-28-14**. I'm trying to follow the README at [https://github.com/aws-samples/aws-mobile-react-sample](https://github.com/aws-samples/aws-mobile-react-sample) and I can't get past step 2. I haven't done anything else.

**Comment by josoroma** [comment]
@garyfanglee same her! 

Temporary solution: use yarn instead of npm.

Good luck!

**Comment by wenruiliau** [comment]
Encountering this error as well whilst working through https://github.com/aws-samples/aws-mobile-react-sample.

**Comment by CHR15-** [comment]
RIP anyone under "0.x" versioning! Not sure how this was forgotten 👎

**Comment by haverchuck** [comment]
This should be resolved, please try again.

**Comment by mlabieniec** [comment]
Just to add a resolution/clarification here. Our build system (circleci) does publish to npm. Npm had a recent outage that seems to have caused this version from not getting published correctly. We verified that our system said successfully published but npm's website didn't show the version. We published again and it worked. We then also verified it was part of the issues there.
