### ISSUE TITLE
console.log statements pollute developer console

### ISSUE THREAD

**Issue by oluckyman** [aws/aws-amplify#11]
There are plenty `console.log` statements in the source. Some of them may be useful for library users. But these are just polluting console on every request and have no value if you are not a library maintainer:
![image](https://user-images.githubusercontent.com/642673/33086100-efd8d504-cee6-11e7-99f4-7a210bc7dce3.png)

**Comment by richardzcode** [comment]
Thank you @oluckyman for pointing this out. Overall AWS Amplify uses Logger: https://github.com/aws/aws-amplify/blob/master/media/logger_guide.md

Those ones you found were oversights. Our developer just corrected those.

Thanks again!

Richard
