### ISSUE TITLE
federatedSignIn with Google provider not working if Unauthenticated Identities not enabled

### ISSUE THREAD

**Issue by qispark** [aws/aws-amplify#1106]
**Do you want to request a feature or report a bug?**

Bug, I think

**What is the current behavior?**

I'm currently using 'react-native-fbsdk' and 'react-native-google-signin' in conjunction with Amplify to provide social sign-in.

With Unauthenticated Identities enabled, I have Auth.federatedSignIn working with both providers and returning a Cognito Federated IdentityId.

However, when I turn Unauthenticated Identities off, Auth.federatedSignIn only works with the 'facebook' provider. When I attempt to login using the 'google' provider, I get the error "Unauthenticated access is not supported for this identity pool."

I'm not sure whether this is a bug or if there's a reason why this is happening.

**What is the expected behavior?**

Auth.federatedSignIn should work regardless of whether Unauthenticated Identities are allowed.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

    "aws-amplify": "0.343"
    "aws-amplify-react-native": "0.2.17"

**Comment by powerful23** [comment]
Hey thanks for your feedback. Did this error pop up when you are signing In using `Auth.federatedSignIn()`? Can you provide some code snippets?

**Comment by qispark** [comment]
Yes, I was using Auth.federatedSignIn().

My approach is very similar to to the example here: [https://github.com/patw0929/react-native-amplify-cognito-example](https://github.com/patw0929/react-native-amplify-cognito-example).

**Comment by powerful23** [comment]
@qispark I tried to reproduce it but it works for me. Can you confirm this error shows up after you sign in with google? Thanks

**Comment by qispark** [comment]
My bad - looks like I put in the wrong Google Android Client ID in the Mobile Hub User sign-in setup. After putting in the right ID, it now works.

Though, I find it strange that "Unauthenticated access is not supported for this identity pool." comes up as the error, maybe that can be altered to be more useful?
