### ISSUE TITLE
Support for TOTP Software Token MFA

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#111]
Can we get support in the UI for TOTP? Polling my users, they say they prefer that to SMS based MFA. Sometimes it takes several minutes for an SMS message to arrive and TOTP is immediate. I recently turned it on for my main AWS account and I like it too.

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa.html

Can you bug the Cloudformation people to add TOTP as a creation option for a user pool? Or maybe it is there and missing from the docs.  The support for it is already in Cognito.

**Comment by richardzcode** [comment]
implemented in #407
