### ISSUE TITLE
awsmobile-cli using wrong/old aws credentials

### ISSUE THREAD

**Issue by edzillion** [aws/aws-amplify#1111]
### Do you want to request a feature or report a bug?

Bug

### What is the current behavior?

````
$ awsmobile configure aws

configure aws
? accessKeyId:   NEWACCESSKEY
? secretAccessKey:  NEWSECRET
? region:  eu-central-1

$ awsmobile configure -l

IsUsingProfile: false

{ accessKeyId: 'NEWACCESSKEY',
  secretAccessKey: 'NEWSECRET',
  region: 'eu-central-1' }

$ awsmobile init
...
backend awsmobile project creation error

the security token included in the request is invalid

...

$ awsmobile configure -l


IsUsingProfile: false

{ accessKeyId: 'OLDACCESSKEY',
  secretAccessKey: 'OLDSECRET',
  region: 'eu-central-1' }

````

I can't figure out what is setting the old credentials. I uninstalled awsmobile-cli and also the normal aws-cli just in case that was conflicting. Once I reinstall awsmobile-cli it already has the OLD credentials set.

I checked my environment variables just to see if something was set there. nothing. 

### What is the expected behavior?

awsmobile-cli to use the credentials set when I run `awsmobile configure aws`

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
awsmobile-cli version 1.1.4
amplify version 0.4.6
windows 10

worked fine previously

**Comment by edzillion** [comment]
OK I found [this help page](https://www.npmjs.com/package/awsmobile-cli#awsmobile-configure) on the awsmobile-cli npm package page

which states

> When you run awsmobile configure outside of a valid awsmobilejs project, it sets the general configuration. The general configuration is applied when you run awsmobile init or awsmobile start command. And its values are copied as the initial per project configuration for the newly initialized project

Running `awsmoblie configure aws` outside the project directory **and** inside fixed this problem.

I guess if it is a bug it is something to do with the cli not using the local settings.

**Comment by UnleashedMind** [comment]
yes, when init or start is executed, the general configuration is used.
