### ISSUE TITLE
Changelog not updating

### ISSUE THREAD

**Issue by youngbob** [aws/aws-amplify#1112]
The root `CHANGELOG.md` has not been updated between the 0.4.1 and 0.4.6 (currently) releases.

**Comment by powerful23** [comment]
Hi recently we are moving on to use `lerna` to produce change logs automatically so that one is deprecated. We will update it later on

**Comment by mlabieniec** [comment]
@youngbob apologies for the confusion here. We've been working this sprint moving towards automatic publishing and conventional commits. This updates each individual packages/**/changelog.md files. We have a PR to update this file currently
https://github.com/aws/aws-amplify/pull/1115
