### ISSUE TITLE
What is verifiedContact method? Why?

### ISSUE THREAD

**Issue by wzup** [aws/aws-amplify#1128]
What does it do in React Native environment?

https://aws.github.io/aws-amplify/api/classes/authclass.html#verifiedcontact

**Comment by mlabieniec** [comment]
This method provides a map of verified contact methods e.g. email and/or phone number and which ones are/have been verified:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html

**Comment by jordanranz** [comment]
Closing this issue for now. Please reopen if you have any more related questions or comments.
