### ISSUE TITLE
Angular: Cannot read property 'Storage' of null

### ISSUE THREAD

**Issue by goldenbearkin** [aws/aws-amplify#1129]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
<img width="1139" alt="screen shot 2018-06-27 at 10 11 49 pm" src="https://user-images.githubusercontent.com/11225712/41979548-fac96732-7a56-11e8-9b44-9d01b035c462.png">

Steps to reproduce:
I haven't done much, just
1) ng new test-amplify
2) add below to main.ts
```js
import Amplify from 'aws-amplify';
import awsmobile from './aws-exports';
Amplify.configure(awsmobile);
```
What is the expected behavior?
no error

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
````js
"aws-amplify": "^0.4.6",
"aws-amplify-angular": "^0.1.6",
````
<img width="456" alt="screen shot 2018-06-27 at 10 14 48 pm" src="https://user-images.githubusercontent.com/11225712/41979732-5c011a40-7a57-11e8-89c4-3d47ad7df2eb.png">

**Comment by goldenbearkin** [comment]
My bad. Need to fill some of the parameters even the amplify configure states optional.

**Comment by sarafgaurav** [comment]
@goldenbearkin Can you share which additional parameters you had to configure to get this to work? I have the same error but it looks like I have everything configured correctly. Thank you!

**Comment by goldenbearkin** [comment]
sure. I use angular and the Amazon Cognito Hosted UI. Below is my configure passed to Amplify.

````js
auth: {
    region: 'xx-xxxxxx-x',
    userPoolId: 'xx-xxxxxx-xxxxxxxxxxx',
    userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxx',
    identityPoolId: 'xx-xxxxxx-x:xxxxxxxxxxxxxxxxxxxxxxxxx',
    mandatorySignIn: false,
    oauth: {
      domain: 'your-login-domin',
      scope: ['openid', 'aws.cognito.signin.user.admin'],
      redirectSignIn: 'redirectSignIn',
      redirectSignOut: 'redirectSignOut',
      responseType: 'code',
      options: { AdvancedSecurityDataCollectionFlag: false },
    },
  },
````
