### ISSUE TITLE
What is returned by Storage.get when the file doesn't exist?

### ISSUE THREAD

**Issue by benevolentprof** [aws/aws-amplify#1135]
If I make a call to Storage.get, such as the code snippet below, and test.txt doesn't exist in the S3 bucket, what is returned?

Storage.get('test.txt')
    .then(result => console.log(result))
    .catch(err => console.log(err));

I'm finding that it returns a URL that results in a 404.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

0.4.6 in Chrome on OSX

**Comment by mlabieniec** [comment]
That is correct. 404 is a file not found http error code which is correctly returned.

**Comment by powerful23** [comment]
@benevolentprof you can use [Storage.list()](https://aws.github.io/aws-amplify/media/storage_guide#list) to get all the keys under a specified path and then you can check whether the file is among those keys.
