### ISSUE TITLE
Amazon transferutility

### ISSUE THREAD

**Issue by jcharbo** [aws/aws-amplify#115]
Hi, the aws-sdk-react-native seems to say that it is deprecated in favor of this library but this library does not seem to support the amazon transferutility or any other method for background uploads.  Is that correct?  If so, is there going to be any react native support for the transferutility?
thanks

**Comment by powerful23** [comment]
@jcharbo Thanks for the feedback. It's already in our backlog for the issue #61 .

**Comment by jcharbo** [comment]
Thanks @powerful23 .  Do you have an eta on this?

**Comment by mlabieniec** [comment]
@jcharbo we are still working on prioritization of the feature requests, but we will use this as a +1 to bump this functionality up. We are tracking this with the #61 issue so we will reference that one once the pr is out.
