### ISSUE TITLE
AWS Rekognition in Amplify

### ISSUE THREAD

**Issue by SrujithPoondla** [aws/aws-amplify#1150]
Do you want to request a feature or report a bug?
Request for documentation 

Is there any way to call rekognition service using amplify. I tried using rekognition endpoint to post the data. 

I was getting the below response:
```
Object {
"Output": Object {
"__type": "com.amazon.coral.service#UnknownOperationException",
"message": null,
},
"Version": "1.0",
}
```
I couldn't find any documentation related to calling other services such as rekognition using API endpoints. It would be flexible if we can have some documentation to use other services like rekognition from amplify.

**Comment by mlabieniec** [comment]
You can call any underlying service via the SDK as long as your Authentication credentials have permission see docs [here](https://aws.github.io/aws-amplify/media/quick_start#working-with-aws-service-interface-objects)

**Comment by Sonic-Ninja** [comment]
Did this work for anyone, i did use the setup instructions and have an authenticated user.  Here is my code from [this](https://medium.com/@glen.bray/text-detection-with-mobile-camera-using-react-native-and-aws-rekognition-7826b3e2aeef) tutorial. I've tried it both with the tutorial and a new build with authentication using the the link above but still get the same response as above.

`
Amplify.configure({...aws_exports,
  API: {
    endpoints: [
      {
        name: "rekognition",
        endpoint: "https://rekognition.us-east-1.amazonaws.com",
        service: "rekognition",
        region: "us-east-1"
      }
    ]
  }
});


async function detectText(bytes) {
  const apiName = "rekognition";
  const path = "/detect-text";
  const body = { Image: { Bytes: bytes } };

  const headers = {
    "X-Amz-Target": "RekognitionService.DetectText",
   // "Host": "rekognition.us-east-1.amazonaws.com",
    "X-Amz-Date": `${moment().format("YYYYMMDDTHHMMSS")}Z`,
    "Content-Type": "application/x-amz-json-1.1"
  };

  const init = {
    body: body,
    headers: headers
  };
  
  console.log(init)

  return API.post(apiName, path, init)
  .then((result) => {
    console.log(result)
    return Promise.resolve()
  })
  .catch(err => {
    console.log(err)
    return Promise.resolve()
  })
}`

**Comment by tmjordan** [comment]
@SrujithPoondla @Sonic-Ninja, hi guys,  have you find a way to use amazon rekognition with amplify?
Thanks

**Comment by giovanib02** [comment]
@SrujithPoondla @Sonic-Ninja @tmjordan i have the same problem

**Comment by SrujithPoondla** [comment]
I tried modifying this but didn't work for me. @tmjordan I have used firebase text recognition and it worked well.

**Comment by tmjordan** [comment]
hi @giovanib02 did you find a solution?

**Comment by tmjordan** [comment]
Hi @mlabieniec , please how do we fix this? Can you please show some example?

**Comment by giovanib02** [comment]
> Hi @mlabieniec , please how do we fix this? Can you please show some example?



> hi @giovanib02 did you find a solution?

Not yet.
Finally i had to use google vision API https://cloud.google.com/vision/?hl=es.
Has the same services that rekognition https://cloud.google.com/vision/?hl=es and better documentation, works well with React Native.
