### ISSUE TITLE
no userPool aws-mobile-react-sample

### ISSUE THREAD

**Issue by ndgreen** [aws/aws-amplify#1157]
Hi,

Following the example at https://github.com/aws-samples/aws-mobile-react-sample

When I run I get 'no UserPoo'l for login and signup in orange. I noticed some others on here ran into the same issue but the issue was closed without resolution or comment.

My aws-export seems to have the right values from my cognito user pools.

Any ideas?

**Comment by jonathantzh** [comment]
Try adding this to where you're importing your aws-amplify packages:

```
import Amplify from 'aws-amplify';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
```

Solved the same problem for me when I building with create-react-app based on the guide here: https://aws.github.io/aws-amplify/media/quick_start

**Comment by powerful23** [comment]
@ndgreen the error was caused by two duplicate `aws-amplify` libraries under the `node_modules`, we have made an update in the package.json to use the latest aws-amplify and aws-amplify-react which should fix that problem. Please pull the latest sample and run `npm install`

**Comment by ndgreen** [comment]
Thanks @powerful23 that did it
