### ISSUE TITLE
Merge amazon-cognito-auth-js PR #141

### ISSUE THREAD

**Issue by erothmayer** [aws/aws-amplify#1187]
There has been a long-standing bug in correctly using cookieStorage in a coordinated way between the main Cognito auth libraries and the OAuth hosted UI.

https://github.com/aws/aws-amplify/issues/841
https://github.com/aws/aws-amplify/issues/812

@powerful23 made a fix in this PR: https://github.com/aws/aws-amplify/pull/967

However, a coordinated change in amazon-cognito-auth-js did not update all versions of the distributable code. That library is currently vending pre-1.2.1 behavior to some clients (specifically lib/ and es/ do not include the changes made here: https://github.com/aws/amazon-cognito-auth-js/commit/8091d83e8eebf080b3da1c33c2beafbbe098869f)

This PR has been open for over month to update all variants of the build files with the latest code (https://github.com/aws/amazon-cognito-auth-js/pull/141) but has received no response.

Opening this issue here since Amplify is a primary consumer of this library, and its functionality is currently broken by this gap. Please help to get this reviewed and merged so all users can access the new functionality cleanly.

Thanks!

**Comment by powerful23** [comment]
Closing the issue. The latest version of amazon-cognito-auth-js has been published.
