### ISSUE TITLE
Support USE_PASSWORD_AUTH on AWS.signIn for User Migration

### ISSUE THREAD

**Issue by brendan-lovepop** [aws/aws-amplify#1207]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
Auth.signIn uses the default `SRP_AUTH` flow which will not allow for automatic user migration in Cognito via the User Migration Lambda

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
A passed in Authentication Flow Type is used by Amplify on sign in
Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
The feature has been merged. Please feel free to reopen if has any question.
