### ISSUE TITLE
"NetworkingError: Network Failure in mobile analytics and "CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by 7772** [aws/aws-amplify#121]
<img width="1269" alt="error" src="https://user-images.githubusercontent.com/22615385/34637309-b5037efa-f2f6-11e7-836c-747e79201e0c.png">

I use mobile hub and aws-amplify but I've been constantly getting this error since I started my react-native project.
What is the reason of this error, and How to fix?

**Comment by powerful23** [comment]
@7772 I think this issue has been fixed in the latest release by removing the AMA dependency from the lib. Please reopen it if you still get this error. Thanks you.

**Comment by 7772** [comment]
@powerful23 Thank you for you answer! 👍 👍 👍
