### ISSUE TITLE
Reduce the bundle size

### ISSUE THREAD

**Issue by baharev** [aws/aws-amplify#122]
I have a small React web app, and the bundle size (optimized build) is ca. 2.0 MB, most of which comes from amplify and aws-sdk (at least ca. 1.7 MB as far as I can tell). As a result, loading the application on slow networks and/or older devices is unacceptably slow.

I looked around in the bundle js file, and in the corresponding source map (ca. 9MB) to figure out why, and I am under the impression that almost everything from the aws-sdk ends up in the bundle:

- Various AWS services that I do not use in my app: DynamoDB, VPC, Redshift, Polly, Lex, Rekognition, CodeCommit, Gaming stuff (as far as I can tell it is this product: https://aws.amazon.com/gaming/), EC2 stuff (EC2, spotfleet, auto scaling group), etc.
- French and Spanish text (for the sign in / sign up, etc), although I did not ask for it (i18n).
- MFA stuff which I explicitly disabled.
- I disabled analytics and messaging (which I currently do not need) but it did not make an impact on the bundle size. Mobile analytics still leaks into the bundle.
- The closed issue #25 also asked for smaller bundle size, but as far as I can tell, he did not get it.

I could go on, but I think you see the problem. I get this bundle with create-react-app, and using the default settings.

How can I reduce the bundle size?

How can I put only that code into the bundle that I actually need? Is there a way to automate this process?

Is there a way to do code splitting to make the initial load of the application faster?

**Comment by jonsmirl** [comment]
Currently there are several megabytes of unneeded junk getting brought in due to the inclusion of the full aws-sdk. My hope is that when things settle down we can stop including the general purpose aws-sdk module which contains 10,000 APIs and instead switch over to one specifically generated to match the needs of this project. 

This tool will make much smaller SDK packages.
https://sdk.amazonaws.com/builder/js/

But even that tool could be significantly improved by letting you only pick the functions you need instead of every function in the service.

These pointless, multi-megabyte SDKs are an enduring mess when using AWS.  In two of our projects we have stopped using the AWS SDKs and instead build the function calls in our own code. The AWS CPP SDK is the worst. Due to it's use of virtual functions there is no way to shrink it. That's the one we stopped using.

If Amazon would put their SDKs up on a free CDN URL like Google and FB do I think we'd see the SDK size shrink very quickly. Instead us customers have to deal with the bills from these bloated downloads.

**Comment by baharev** [comment]
@jonsmirl Thanks for your feedback! My primary concern isn't the bill but the very poor user experience. As I said, loading the application on slow networks and/or older devices is unacceptably slow.

**Comment by jonsmirl** [comment]
Is this the problem? Check out the mobile analytics SDK.
https://github.com/aws/aws-sdk-mobile-analytics-js/blob/master/lib/MobileAnalyticsClient.js

Top of the file... isn't it including the entire SDK? Shouldn't that be require('aws-sdk/global') instead?

var AWS = require('aws-sdk');
var AMA = global.AMA;
AMA.Storage = require('./StorageClients/LocalStorage.js');
AMA.StorageKeys = require('./StorageClients/StorageKeys.js');
AMA.Util = require('./MobileAnalyticsUtilities.js');

**Comment by mlabieniec** [comment]
Thanks for the feedback @jonsmirl and @baharev. Reducing the dependancies and trimming the bundle is top of our backlog. PR #101 already removes the AMA sdk dependency and we hope to merge that this spring (ending friday). Then we are working on trimming other deps as well.

**Comment by baharev** [comment]
@mlabieniec I am relieved to hear that trimming the bundle has high priority. Looking forward to the new release of the amplify library!

**Comment by baharev** [comment]
@jonsmirl Thank you for looking into the issue. As Michael says, they will hopefully get rid of this dependency soon.

I do not care about the AMA: I tried it, but I find its reports utterly confusing. Let's leave it at that.

My app is a React + Redux app, where literally everything is recorded anyway. By submitting the user's session to the cloud, I could replay the session on my machine, etc.

**Comment by jonsmirl** [comment]
I have no need of AMA either, but there is no way to turn it off. Plus it made me add support for unauthenticated users to my identity pool to keep it from generating piles of error messages. That makes me end up with thousands of unathenticated user ids created in my pool since they get created before the user has a chance to authenticate.

**Comment by baharev** [comment]
@jonsmirl This particular issue will hopefully go away very soon.

**Comment by undefobj** [comment]
@baharev can you give a bit more feedback on confusion with reports in Pinpoint? We'd be happy to give the feedback to that team.

**Comment by baharev** [comment]
@undefobj Sure, but it really doesn't below to the amplify project. Should I open an issue at 

https://github.com/aws/aws-sdk-mobile-analytics-js

and give feedback there? It would be my pleasure to do that.

**Comment by baharev** [comment]
@undefobj Oops, I was so disappointed that I deleted all the analytics in Pinpoint. :( Well, I vaguely remember what my problems were, but it will make my feedback less useful. Sorry...

**Comment by baharev** [comment]
@mlabieniec @powerful23 Awesome, thank you for acting so promptly! Dropping AMA reduces the bundle size from 2.0MB to 775kB, and the source map from 8.9MB to 4.8MB, that is pretty good!

**Comment by baharev** [comment]
@jonsmirl The new version of amplify halves the bundle size! I am so glad we got this quickly.

Could you give me some advice how to reduce the bundle size with https://sdk.amazonaws.com/builder/js/ further?

I guess I select the packages I need, then download the generated file, and then how do I proceed from there?

Sorry if it is a dumb question but I am beginner in JavaScript (I have a background in C++ and Python).

**Comment by jonsmirl** [comment]
It is not worth the effort needed to push the size down any further. The SDK builder tool is not going to make things smaller unless it is enhanced to allow picking specific APIs in a service.

775KB is small enough it does not matter.  If you really want to shrink the next most obvious thing to remove is the S3 support from amplify. S3 support adds about 80KB compressed and I am not using it. Hopefully amplify will get modularized in the future.

You can use this to poke around in webpack and see where the space is going.
https://github.com/webpack/webpack/issues/690

**Comment by baharev** [comment]
@jonsmirl Thanks for the advice! I use React, and I also need S3 (user files are being uploaded there). It is probably difficult to reduce the bundle size further, you are right.

Now, I followed the instructions and enabled gzip compression in CloudFront, and the browser does send the right header (accepts gzip) too, but CloudFront does not want to compress the JavaScript bundle. I see both in Firefox and in Chrome that the bundle is transferred uncompressed.

Any ideas why?

That would bring it down to ca. 190KB. I greatly appreciate your help and feedback!

**Comment by baharev** [comment]
For future reference, here is how to enable gzip compression in CloudFront:

- Follow the instructions here: https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/
- Add to S3 > Bucket > Permissions > CORS Configuration:
  `<AllowedHeader>Content-Length</AllowedHeader>`
- It unclear whether a complete cache invalidation is necessary, I did it with `*`.

After these 3 changes, the bundle is transferred gzipped, so the size is now down to 187KB from 2.0MB, and the page loads pretty fast!

**Comment by mlabieniec** [comment]
@baharev @jonsmirl going to close this now as the AMA dep is merged, we are also working towards more enhancements on bundle size and deps in general. Please feel free to open this again if you fee necessary.

**Comment by baharev** [comment]
@mlabieniec Should I open an issue to add how one can enable gzip compression on CloudFront? See [above](https://github.com/aws/aws-amplify/issues/122#issuecomment-356448126). This was the final piece, and now I am OK with the 187KB gzipped bundle size.

**Comment by mlabieniec** [comment]
@baharev thanks, I'll get this added to the docs.

**Comment by baharev** [comment]
@mlabieniec Great thanks! Also many thanks for acting so promptly with this issue, and reducing the bundle size!

**Comment by dnutels** [comment]
You guys seriously stopped at this?

> 775KB is small enough it does not matter.

775KB is **ENORMOUS**. It **TRIPLES** the size of my application, even when gzipped and minified.

Besides, most normal people bundle their applications today, so the bundle builder is a really messy way of going about it. It doesn't allow dependency or version management and is **MANUAL**.

The amount of disappointment in AWS FE team is at an all time high.

**Comment by mlabieniec** [comment]
@dnutels we are absolutely not stopping here. We are actively working on decoupling the categories so that users can include only parts (just Auth, or just Storage). The majority of the size is the aws-sdk for javascript. We have a few PRs already in review here to decouple the Auth credentials piece specifically, which was more the "most"  difficult part. We plan on completing this asap. Lately we've been very focused on stability and framework support. Everything being included does make the bundle size larger than we'd like, and we are continuing to actively work on this as you can see in some of the modularization labeled PRs. Gzipped is better, and if you compare to something like [Angular](https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.17/angular2-all.umd.min.js), the size IS comparable, but we are also not happy with this and should have the modularization complete in the next couple sprints.

**Comment by dnutels** [comment]
Looking forward to it @mlabieniec

**Comment by dnutels** [comment]
@mlabieniec Is there a tracking issue for the decoupling we can subscribe to?

**Comment by powerful23** [comment]
@dnutels we have just published the Amplify version 1.0.0 which breaks current library into several modules which could reduce the bundle size for you. For details please check doc and the wiki: https://github.com/aws-amplify/amplify-js/wiki/Amplify-modularization

**Comment by dnutels** [comment]
@powerful23 It only lacks installation instructions, but I assume that:

1. `yarn add @aws-amplify/core` is the main one
2. add as needed ` yarn add @aws-amplify/api`

**Comment by tuhinkarmakar** [comment]
I am trying to use v1.0.0 of AWS Amplify and AWS Amplify Angular. I have read the wiki available at https://github.com/aws-amplify/amplify-js/wiki/Amplify-modularization. But I wasn't able to make things work.

First of all, the "Apply modularized Amplify to other packages" section on the wiki page instructs us to add `@aws-amplify/core` as a dependency which I did. Then it says, "Export module references from `@aws-amplify/core/Amplify`". But the example there imports the module with the statement `import { Amplify } from "@aws-amplify/core"`.

Neither `import { Amplify } from "@aws-amplify/core"` nor `import { Amplify } from "@aws-amplify/core/Amplify"` worked. What worked was `import Amplify from "@aws-amplify/core"`. But even then I'm getting a error during production builds.

`ERROR in node_modules\aws-amplify-angular\lib\components\interactions\chatbot\chatbot.component.core.d.ts.ChatbotComponentCore.html(20,43): : Expected 1 arguments, but got 0.
node_modules\aws-amplify-angular\lib\components\interactions\chatbot\chatbot.component.ionic.d.ts.ChatbotComponentIonic.html(59,19): : Expected 1 arguments, but got 0.`

I have configured Amplify in `main.ts`  by calling `Amplify#configure`. I have imported the `AmplifyService` from "aws-amplify-angular". I haven't imported  the`AmplifyAngularModule`.

What am I doing wrong?

**Comment by powerful23** [comment]
@dnutels we have a section about how to use those modularized lib under each category's doc, for example, for auth: https://aws-amplify.github.io/amplify-js/media/authentication_guide#using-modularized-module The doc for now is quite simple. We will definitely improve that and add more code samples about that.

**Comment by powerful23** [comment]
@tuhinkarmakar sorry but if you are using `aws-amplify-angular` then you need to import the entire `aws-amplify` like `import Amplify from 'aws-amplify'`. We will work on to make it fit in the modularized library.

**Comment by dnutels** [comment]
@powerful23 

Sorry, that one made me more confused. So, instead of doing the configuration via `Amplify` I can now do it directly via `Auth`? Provide it with pool and such? Perhaps a more explicit example would have been better suited there...

**Comment by powerful23** [comment]
@dnutels yes, when you call `Amplify.configure`, you are in fact calling the configure method in every category. So it makes no difference between `Amplify.configure({ Auth: {} })` or `Auth.configure({})`

**Comment by dnutels** [comment]
I know that's not the place to ask, but for completeness sake...

So, if I configured `Auth` directly **without using `Amplify` at all, not even calling `Amplify.register(Auth)`**:

```
Auth.configure({region, userPoolId, userPoolWebClientId});
```

will calling `API` work (since it needs the session/credentials and used to get them via Amplify, I believe)

```
API.get(...)
```

**Comment by haverchuck** [comment]
@kwoxford - Thanks for reaching out. Are you using the interactions component from the newest version aws-amplify-angular, and if so are you passing it the bot, title and clearComplete parameters?

**Comment by kwoxford** [comment]
I have aws-amplify-angular ^1.0.0, but the odd thing is that I'm not using chatbot at all. It's not enabled on mobile hub. Are you saying that I should configure it anyway?

Here's what's in app.module:
```
import Amplify from 'aws-amplify';
import aws_exports from '../aws-exports';
import {AmplifyAngularModule, AmplifyService} from 'aws-amplify-angular';

Amplify.configure(aws_exports);
```

**Comment by haverchuck** [comment]
@kwoxford - What is the context of this error - is it happening during the build? Or in the browser console?

**Comment by kwoxford** [comment]
During the build. But since then I've completely rebuilt the app and the issue has gone away. Some of the dependencies in the chat starter app seem out of date and maybe something went wrong when I updated to more recent versions e.g. Angular 6 and rxjs 6. Whatever, it's gone now.

**Comment by haverchuck** [comment]
@kwoxford - Thanks for letting us know it's resolved.  I'm going to continue to look into this, but I'm glad to hear that your immediate problem was resolved.

**Comment by baharev** [comment]
@mlabieniec I created an empty project from scratch, both on mobile hub, and locally with create react app. I used the latest version from everything involved (awsmobile, Amplify, react, etc). From the `package.json`:

```
  "dependencies": {
    "aws-amplify": "^1.0.2",
    "aws-amplify-react": "^1.0.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1"
  },
```

**My bundle size used to be 187KB, now it is 289KB** (both meant gzipped, optimized builds for deployment). I am only using authentication from Amplify. The `App` is what `create-react-app` creates. All I did was to add `export default withAuthenticator(App);` to App.js.

Storage is not imported or referenced anywhere in the app, but I see in the bundle that a large part of the bundle is concerned with S3 and multi-part uploads. The user file storage is disable on the backend (and always has been disabled).

It seems to me S3 access leaks into the bundle somehow, although nobody asked for it, partly explaining why the bundle size grew by 102KB or by 54%.

**Comment by baharev** [comment]
I think this issue should be reopened.

**Comment by mlabieniec** [comment]
@baharev if you use the HOC libraries (react and components in angular), those will include the entire library (for now) same as before. We are working on this, but to maintain backwards compatibility with the aws-amplify-react package it includes all modules. Here are my results working on a new project, (all of these achieve a 100 score with google lighthouse):
 
Vanilla JavaScript with the entire library
219 KB GZIP
First meaningful paint 130 ms
 
Vanilla JavaScript with only Auth and Analytics
​199 KB GZIP
First meaningful paint 150 ms
 
React withAuthenticator created using create-react-app with entire library
816 KB GZIP (includes React.js)
First meaningful paint 280 ms 
 
React withAuthenticator created using create-react-app with only Auth and Interactions
481 KB GZIP  (includes React.js)
First meaningful paint 240 ms

**Comment by baharev** [comment]
@mlabieniec OK, so you are aware of the problem, and you are working on it. 

I am glad to hear it, and sorry that I cannot help you with it.

**Comment by mlabieniec** [comment]
Thanks for the feedback, appreciated. Definitely open to PRs if you have suggestions on this as well 👍

**Comment by haverchuck** [comment]
@edgarelc Thanks for your input.  We've pushed a fix for this to the unstable branch, and it should become part of the stable release shortly.

**Comment by otbe** [comment]
Mh....I try to use `@aws-amplify/auth` to signUp/signIn users into my Cognito User Pool, but adding this lib as a dependency adds 379kb (uncompressed, ~110kb gziped) to my prod bundle. Code coverage before 

<img width="717" alt="bildschirmfoto 2018-07-28 um 00 22 08" src="https://user-images.githubusercontent.com/3391052/43348830-64385658-91fc-11e8-8002-35c15bcdf84b.png"> 
(not good) and after adding `@aws-amplify/auth`  

<img width="720" alt="bildschirmfoto 2018-07-28 um 00 24 55" src="https://user-images.githubusercontent.com/3391052/43348877-b10eb634-91fc-11e8-9531-6d916c566d63.png">
(even worse). 
I guess this is related to `aws-sdk`.
<img width="997" alt="bildschirmfoto 2018-07-28 um 00 15 33" src="https://user-images.githubusercontent.com/3391052/43348982-30ccdf22-91fd-11e8-85df-a32c528afa34.png">
 
Any hints on reducing the bundle size (maybe some webpack hacking or so?)?
Its a very nice and easy to use lib, but that (optimized, uglified) prod bundle size just kills my PWA :/

**Comment by AbdullahAdeeb** [comment]
@edgarelc @Ajji11 @kwoxford I had the same issue. fixed in v1.0.3
run: npm i aws-amplify-angular@1.0.3 -S

**Comment by semi-sentient** [comment]
OK, so bundle size is reduced dramatically using the modular approach, but events are no longer being sent. Am I missing something here (using v1.0.x)?

import aws_exports from './aws-exports';
// import Amplify, { Analytics } from 'aws-amplify';
import Analytics from '@aws-amplify/analytics';
import Amplify from '@aws-amplify/core';

Amplify.configure(aws_exports);
Analytics.record('page-view', {
    route: '/some/route'
});

**Comment by aldarund** [comment]
380kb just for auth seems excessive. Is there any plans to make it smaller?

**Comment by mlabieniec** [comment]
My lighthouse score for Auth+Analytics with gzip compression is around 199 KB and scores 100 on performance for PWA @aldarund @otbe 

![auth analytics-no-throttle-gz](https://user-images.githubusercontent.com/1417045/45272612-1b71b980-b463-11e8-985d-6d124c394ca2.png)

**Comment by mlabieniec** [comment]
@otbe thanks for the info, understood. This is definitely something we are continuing to work on, will keep this thread up-to-date as we make more progress

**Comment by ehorodyski** [comment]
I have to +1 the need for better documentation on tree-shaking this massive library. Especially when you already have AWS services created, and do not want to start a Mobile Hub project from scratch. I'm not a fan of the auto-naming scheme, and most of my services are created by other teams -- without our developers having access to do so.

**Comment by dimitarrusev** [comment]
@ehorodyski You can't. By opting to use modular imports, the `aws-amplify-angular` package is rendered useless. You have to write your own custom version. 

Obviously, they won't state this publicly because it's already advertised that the library has "first-class support for Angular" (whatever that means) which makes things even more confusing in addition to their half-baked documentation. Smh.

**Comment by roborourke** [comment]
Is it right just with the following lines my production bundle size is over 400kb? It's much higher than other analytics scripts I've looked at.

```
import Analytics from '@aws-amplify/analytics';
import Auth from '@aws-amplify/auth';
```

**Comment by afraser** [comment]
I'm including only `"@aws-amplify/auth": "^1.2.18",` and amplify is taking up an enormous chunk of my bundle:

<img width="257" alt="Screen Shot 2019-04-08 at 3 37 31 PM" src="https://user-images.githubusercontent.com/1179515/55751674-45e51e80-5a14-11e9-95ee-e9695f796236.png">

**Comment by danawoodman** [comment]
Same here, we added `@aws-amplify/auth` import and our bundle went from ~30kb to 130kb 😩

**Comment by johhansantana** [comment]
Following some of the suggestions here using `@aws-amplify/auth` instead of `aws-amplify` reduced our bundle where we use the login form by almost 90% I would say:

<img width="352" alt="Screen Shot 2019-09-27 at 1 31 02 PM" src="https://user-images.githubusercontent.com/9933887/65789295-172a4400-e12b-11e9-958d-dfa7443733bd.png">

vs

<img width="347" alt="Screen Shot 2019-09-27 at 1 27 34 PM" src="https://user-images.githubusercontent.com/9933887/65789159-bc90e800-e12a-11e9-977b-66ff3d779024.png">

and this is without importing any aws-amplify package

<img width="366" alt="Screen Shot 2019-09-27 at 1 27 07 PM" src="https://user-images.githubusercontent.com/9933887/65789187-c61a5000-e12a-11e9-9f7a-f7e8d22b17c7.png">

**Comment by j0b0sapi3n** [comment]
So just to confirm, instead of doing this which my app current does:
`import { Auth, API, Storage } from 'aws-amplify';`

I should do this:
`import Auth from 'aws-amplify/auth';`
`import API from 'aws-amplify/api';`
`import Storage from 'aws-amplify/storage';`

Or should I also be changing my package from `aws-amplify` to adding each individual package from `@aws-amplify`? Thanks for the help!

**Comment by mlabieniec** [comment]
@j0b0sapi3n you would want to do this:

```
// import the modules
import Amplify from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';
import API from '@aws-amplify/api';
import Storage from '@aws-amplify/storage';

// import the config file that's generated by the CLI
import AWSConfig from './aws-exports';

// configure amplify with it
Amplify.configure(AWSConfig);
```

See example here: 
https://github.com/mlabieniec/photo-translate/blob/master/src/main.ts#L7-L12

**Comment by waleedshkt** [comment]
Both aws-amplify and firebase sdk quicken and ease the web-app development. But they come at the expense of large bundle size. Same goes for Expo which allows rapid react-native app development.

**Comment by waleedshkt** [comment]
Both aws-amplify and firebase sdk quicken and ease the web-app development. But they come at the expense of large bundle size. Same goes for Expo which allows rapid react-native app development but adds many MBs of unwanted code

**Comment by srchulo** [comment]
I'm still seeing this issue with huge bundle sizes. My app takes a few seconds on initial load largely due to many AWS libraries that end up being included in my build that I don't think are actually needed. Would be great to have this reduced! I love the convenience of the amplify libraries, but now I'm trying to think about what parts I can rewrite so I can reduce my app size.

**Comment by betimer** [comment]
Same issue, and I can not fast debug online, cause it complain too large
![image](https://user-images.githubusercontent.com/8111748/93709171-745ea700-fb7f-11ea-8bb8-549f8fece858.png)

**Comment by vaskevich** [comment]
@betimer perhaps you can use [Lambda layers](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html).

**Comment by ZalgirisKaunas** [comment]
![image](https://user-images.githubusercontent.com/19693550/116694748-533d1f00-a9c8-11eb-81ba-a87a0cc0dccc.png)
 For some reason, my aws-sdk dependency is this heavy..
