### ISSUE TITLE
How do I set the chunck size for Storage.put?

### ISSUE THREAD

**Issue by baharev** [aws/aws-amplify#125]
`Storage.put` uses a default 5MB chunk size, and does a multipart upload if the file size exceeds the chunk size. I would like to do a simple put and not a multipart upload, but it is not clear to me whether setting the chunk size to 50MB or 100MB would help with that.

**In any case, how can I control the chunk size?**

I looked at 

https://github.com/aws/aws-amplify/blob/af6f351dbf5ba885c5d1ea3c12e170ba0b112668/packages/aws-amplify/src/Storage/Storage.ts#L150

and

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

which suggest that 

    Storage.put(key, object, { partSize: 1024 * 1024 * 50 })

might work, but it did not; I still got a multipart upload with 5MB chunk size. I was hoping, after reading the source code of `Storage`, that the option would go through to the underlying low-level API call, but it did not.

**Comment by baharev** [comment]
After spending a little bit more time reading the code I see why it did not go through. Is there any reason why not provide an escape hatch? In this case, it would be convenient to just pass through the additional parameters to the underlying low-level code.

**Comment by mlabieniec** [comment]
Tracking this in #61 for the multipart / resumable uploads feature in progress. Adding reference to our backlog to this issue as well for functionality.
