### ISSUE TITLE
Is there a live demo?

### ISSUE THREAD

**Issue by bootrino** [aws/aws-amplify#13]
It's a bit hard to understand the full picture without a live demo to load.

**Comment by undefobj** [comment]
@bootrino Hi - We're looking to put together some similar to the [React Native Starter](https://github.com/awslabs/aws-mobile-react-native-starter) and the [React Starter](https://github.com/awslabs/aws-mobile-react-sample). Are there any specific use cases or demos/examples that you'd like to see?

**Comment by AlexThomas90210** [comment]
If you guys did a TypeScript + Redux + ReactNative example I would be forever in debt :D I know its unlikely tho.

**Comment by jaxondu** [comment]
Would appreciate a demo in another frameworks, for example VueJS and Ionic. Or better still an official aws-amplify-vue package. I had the impression that Amplify is a React library. Luckily I pickup amplify again and realise the simplicity and usefulness of this library.

**Comment by mlabieniec** [comment]
@AlexThomas90210 @jaxondu thank you for the feedback! We are working on live examples and demos and will push them out either as starters or to the repos, stay tuned!

**Comment by bootrino** [comment]
Still no live demos anywhere to see what amplify looks like / works like without investing hours/days in building the demos.
