### ISSUE TITLE
Duplicate aws-sdk files in webpack

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#134]
I used this tool to look at my webpacks
https://github.com/webpack/webpack/issues/690

All of the references to aws-sdk files are ending up in the pack twice. A random example:
./node_modules/aws-amplify/node_modules/aws-sdk/lib/credentials/web_identity_credentials.js
./node_modules/amazon-cognito-identity-js/node_modules/aws-sdk/lib/credentials/web_identity_credentials.js

**Comment by jonsmirl** [comment]
This is interesting, they don't appear to be resolving to the same version....
I manually forced them to agree, my pack size shrank 60KB.
Choice one is amplify, don't know why it does not resolve to 2.179.0

jonsmirl@ubuntu-16:~/aosp/web3/web3$ yarn install --flat
yarn install v1.3.2
$ npm run npmcheckversion

> react-boilerplate@3.5.0 npmcheckversion /home/jonsmirl/aosp/web3/web3
> node ./internals/scripts/npmcheckversion.js

[1/5] Validating package.json...
[2/5] Resolving packages...
info Unable to find a suitable version for "aws-sdk", please choose one by typing one of the numbers below:
  1) "aws-sdk@^2.6.0, aws-sdk@^2.101.0" which resolved to "2.175.0"
  2) "aws-sdk@^2.179.0" which resolved to "2.179.0"
Answer?:

**Comment by mlabieniec** [comment]
@jonsmirl thanks for the feedback. We are working on consolidating this with the cognito js sdk team. I don't have a timeline yet but the goal is to get these types of issues resolved asap.

**Comment by mlabieniec** [comment]
This will be published in the next release to npm. The amazon-cognito-identity-js is now part of our packages and does not depend on the aws-sdk. The mobile analytics sdk is also removed so only the core package currently depends/uses the js sdk.
