### ISSUE TITLE
React Native - Error: Unable to resolve module ‘stream’

### ISSUE THREAD

**Issue by Jahans3** [aws/aws-amplify#153]
Reopening this issue, can the fix from aws-amplify v0.1.34 be added to aws-amplify-react-native please

> 
> There appears to be a node core module imported from this package via the aws-amplify package.
> 
> error: bundling failed: Error: Unable to resolve module `stream` from `/Users/joshua/Documents/side-projects/RoomShakeClient/node_modules/cipher-base/index.js`: Module does not exist in the module map
> Does anybody know a fix for this? I've downgraded a few versions but it doesn't seem to help

**Comment by nopedev** [comment]
```
yarn add aws-amplify-react-native@0.1.22
...
Couldn't find any versions for "aws-amplify-react-native" that matches "0.1.22"
```


How can I install 0.1.22 ?

**Comment by robmoorman** [comment]
Same over here, tested with multiple node version, RN versions

**Comment by robmoorman** [comment]
It requires node.js modules (e.g. stream). With latest versions of RN these aren't picked up by the packager.

**Comment by Jahans3** [comment]
Couldn't get this to work by installing from the git repo instead

@mlabieniec will this be published to npm soon? :-)

**Comment by WChoy** [comment]
Thanks.  Have been working on this for a day, too.
npm is available.

**Comment by WChoy** [comment]
Found the commit started the break, 7 days ago.
https://github.com/aws/aws-sdk-js/commit/0638060402931f572f9f75d77a12bd6c529b0424
It added the following to the working v2.178.0 branch:
"create-hash": "^1.1.3",
"create-hmac": "^1.1.6",
And used it in "aws-sdk/lib/browser_loader.js"  and "react-native-loader.js".

Background: create-hmac and create-hash use a hash-base module.   That does a 
"var Transform = require('stream').Transform".   That was defined in node.js core (NOT a standard JS function, see https://nodejs.org/api/stream.html#stream_new_stream_transform_options)

**Comment by mlabieniec** [comment]
All updates have been published. Is anyone still receiving this error? I just ran locally and is working for me. We are working with both sdk teams to work out the crypto issue and dependency issues.

```
react-native init myrntest
cd myrntest
awsmobile init xxxx-xxxx-xxxx-xxxx
npm install aws-amplify-react-native
react-native run-ios
```
boots up the app then added
```
import Amplify, {
  Authenticator
} from 'aws-amplify-react-native';
import settings from './aws-exports';
Amplify.configure(settings);
...
render() {
    return (
      <View style={styles.container}>
        <Authenticator />
      </View>
    );
  }
```

etc. Please let us know if you are still running into this issue with the latest.
"aws-amplify": "^0.1.x",
"aws-amplify-react-native": "^0.1.22"

**Comment by Jahans3** [comment]
Still seeing the error @mlabieniec

**Comment by mlabieniec** [comment]
@Jahans3 did you try deleting your node_modules and re-installing? An older version of aws-amplify being in your node_modules could also cause the problem

**Comment by Jahans3** [comment]
I did yeah, yarn cache clean too

**Comment by mlabieniec** [comment]
Can you give me your node version. Also, how is your project created? CRNA or react-native init? Are you including the aws-sdk in your app as well?

**Comment by Jahans3** [comment]
> Can you give me your node version

Sure, here's `react-native info` output:
```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
```

Project was created with react-native-cli (react-native init). Not including aws-sdk in the project

**Comment by mlabieniec** [comment]
Can you show me your package.json

**Comment by Jahans3** [comment]
{
  "name": "RoomShakeClient",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "ios": "react-native run-ios",
    "android": "react-native run-android",
    "test": "jest",
    "flow": "flow",
    "flow-stop": "flow stop"
  },
  "dependencies": {
    "eslint-plugin-react": "7.5.1",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-router-flux": "4.0.0-beta.27",
    "react-redux": "5.0.6",
    "redux": "3.7.2"
  },
  "devDependencies": {
    "babel-cli": "6.26.0",
    "babel-eslint": "8.2.1",
    "babel-jest": "22.0.4",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-flow": "6.23.0",
    "babel-preset-react-native": "4.0.0",
    "eslint": "4.15.0",
    "eslint-config-standard": "11.0.0-beta.0",
    "eslint-config-standard-react": "5.0.0",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-node": "5.2.1",
    "eslint-plugin-promise": "3.6.0",
    "eslint-plugin-standard": "3.0.1",
    "flow-bin": "0.59.0",
    "jest": "22.0.4",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by mlabieniec** [comment]
And just to be sure, you did:

```
react-native link amazon-cognito-identity-js
````

**Comment by mlabieniec** [comment]
can you check your node_modules/aws-amplify-react-native/package.json and verify the version is 0.1.22 and also similarly for aws-amplify 0.1.34

**Comment by Jahans3** [comment]
Yeah I linked the cognito identity package, got the correct version installed. I don't have aws-amplify installed

**Comment by elorzafe** [comment]
I have similar issues before, What files do you have under node_modules/aws-amplify-react-native ?

**Comment by mvantellingen** [comment]
Using NPM instead of yarn solved the issue for us. Not sure what the exact reason is but that might be something to look into.

**Comment by robmoorman** [comment]
I can reproduce @mvantellingen "solution". Removing and re-installing packages with npm does work. Yarn does not.

**Comment by mlabieniec** [comment]
The latest should function with yarn now. Please let us know if you are still seeing the issue and re-open if needed. The master branch currently is setup to use yarn/yarn workspaces for local dev and will be pushed with the next release.

**Comment by ggeoffrey** [comment]
Got this issue today with both npm and yarn. Dirty patched it with 
```
AWS.util.isNode = function(){return false;};
AWS.util.isBrowser = function(){return true;};
```
Because I have a guaranty my code will never run on Node.
This is obviously not clean at all but it worked, took 2 lines of code, and now I can move on.
I wouldn't call it a solution, but still hope it helps :)

**Comment by dev-reactnative** [comment]
@mvantellingen  Using npm instead of yarn is not working for me.

**Comment by waqaramjad** [comment]
Using npm instead of yarn is not working for me.
