### ISSUE TITLE
reactnative auth configuration 

### ISSUE THREAD

**Issue by natedog** [aws/aws-amplify#16]
Configuration method of AuthClass is referencing the config.analytics of the configuration object
it should be changed to  config.Auth.

`    configure(config) {
        logger.debug('configure Auth');
        let conf = config? config.Analytics || config : {};
`

Should be

` configure(config) {
        logger.debug('configure Auth');
        let conf = config? config.Auth || config : {};`

**Comment by richardzcode** [comment]
Thanks a lot @natedog ! Fixed.
