### ISSUE TITLE
Network Failure when sign up with Auth on Android Emulator

### ISSUE THREAD

**Issue by lichao0817** [aws/aws-amplify#163]
Hello Team Amplify,

I have problems with using Auth.signUp on Android. 
The Android Emulator I am running is: Nexus_5X
API Level: 23
"aws-amplify-react-native": "^0.1.23"

<img width="1151" alt="cognito" src="https://user-images.githubusercontent.com/4259219/35023275-8c9905dc-faff-11e7-9fd1-555df2d505d7.png">

I have no problem with iOS Emulator, but it does not work on Android.

**Comment by manueliglesias** [comment]
Hi @lichao0817 

Do you see the same behavior if you run your app with remote debugging disabled?

**Comment by lichao0817** [comment]
@manueliglesias Yes, I tried. There is no new user showing up on Cognito when remote debugging disabled.

**Comment by manueliglesias** [comment]
@lichao0817  can you share the relevant logs for android ?

e.g. `npx react-native log-android`

**Comment by lichao0817** [comment]
@manueliglesias Thanks a lot! I just found that this is not a bug of Amplify but rather a bug on the emulator. The emulator has a problem connecting to the internet.

To solve this, just wipe all the data on the emulator and restart it.
