### ISSUE TITLE
Password Input- Chrome Warnings

### ISSUE THREAD

**Issue by bbernays** [aws/aws-amplify#165]
Chrome (version 63.0.3239.132) is throwing the following warning with the default login screen:

```
[DOM]  Password field is not contained in a form: (More info: https://goo.gl/9p2vKq)
```

Amplify version 0.1.34

**Comment by manueliglesias** [comment]
Thank you for using the library and reporting this @bbernays !

This issue is in our backlog

**Comment by powerful23** [comment]
@bbernays we are closing this issue. Please feel free to reopen it if you still have this problem. Thanks!

**Comment by Abhishek2kr** [comment]
@powerful23  This is still returning the warning
for the following code
                <form className="myform" onSubmit={this.validateLogin()}>
                   <div className="myformgroup">
                       <label>Email</label>
                       <input type="text" placeholder="Email" id="email" required></input>
                    </div>
                    <div className="myformgroup">   
                       <label>Password</label>
                       <input type="password" placeholder="Password" id="password" required></input>
                   </div>
                   <div className="myformgroup">
                       <button type="submit" id="loginButton">Login</button>
                   </div>
                </form>
**_Error is_** 
**[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" placeholder=​"Password" id=​"password" required>**​

**Comment by Nenee948611390** [comment]
Hello, I also encountered the same problem, may I ask how to solve it finally?

**Comment by bogodars** [comment]
Have the same issue. Can someone suggest any help?

**Comment by plqin-xiaohao** [comment]
Have the same issue. Can someone suggest any help?

**Comment by JoaoSilvaCorreia** [comment]
Estou com o mesmo problema

**Comment by 13453197509** [comment]
type类型改成其他就没事了

**Comment by dorontal** [comment]
This issue absolutely still exists exactly the same way it was in January, 2018. Why was it closed?

Here is the warning, in today's version of AWS Authenticator and Chromium version 76.0.3809.100: 
  `[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq)`. 

Using NPM packages `aws-amplify` (version 1.2.4) and `aws-amplify-angular` (version 3.1.4).

**Comment by RD-Harry** [comment]
Hello, I also encountered the same problem, however when I use Firfox without any error message,
may I ask how to solve it finally?

**Comment by diksha-2020** [comment]
I am facing the same issue on chrome. Is there any solution on this?
