### ISSUE TITLE
CORS problems when developing

### ISSUE THREAD

**Issue by chessIthaca** [aws/aws-amplify#169]
Hi,

I am not sure it is an issue just something I struggle with to really understand. 
I am using the library to connect to Cognito based on an aws mobile backend. Authentication works wonderful.
When I use any other feature, whether it is lambda or storage I get cors errors from the browser.

I download the aws export to configure and as I said sign in works wonderfully. 

The code here creates the following web request (note changed the url to make it "safe"

 Storage.put('Hello', 'hello world');

Is there a recommended way to develop things with the mobile backend? I can't always upload and test it hosted in aws. That seems cumbersome.

Here is the header it creates for example for 

Request URL:https://iagramly-userfiles-mobilehub-5555.s3.amazonaws.com/public/Hello
  Request Method:OPTIONS
  Status Code:403 Forbidden
  Remote Address:52.216.224.104:443
  Referrer Policy:no-referrer-when-downgrade

Response Headers
   view source
  Content-Type:application/xml
  Date:Thu, 18 Jan 2018 21:05:10 GMT
  Server:AmazonS3
  Transfer-Encoding:chunked
  x-amz-id-2:KNx0jQUTn3KiPlIoSn1xhLwVdwstjZR8SVi779BwNeZu3th6TzNLsl03BMe64YIzkeeii0ABzuo=
  x-amz-request-id:8B01F0E44B34D800

Request Headers
  view source
  Accept:*/*
  Accept-Encoding:gzip, deflate, br
  Accept-Language:en-US,en;q=0.9
  Access-Control-Request-Headers:authorization,content-md5,content-type,x-amz-content-sha256,x-
  amz-date,x-amz-security-token,x-amz-user-agent
  Access-Control-Request-Method:PUT
  Connection:keep-alive
  DNT:1
  Host:iagramly-userfiles-mobilehub-ffff.s3.amazonaws.com
  Origin:http://localhost:3000
  User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
  Chrome/63.0.3239.132 Safari/537.36

**Comment by manueliglesias** [comment]
Hi @chessIthaca 

In order to be able to upload files to the userfiles S3 bucket created by AWS Mobile Hub from a web page, you need to configure CORS for your bucket, e.g.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
Let us know if this doesn't work for you.

**Comment by mbahar** [comment]
For me, updating the CORS configuration solves the problem.

**Comment by chessIthaca** [comment]
It took me a while to get it figured out. I had to turn off the cloudfront setting for the api portal and make the methods regional. For S3 the CORS setting works.

**Comment by alixeb** [comment]
@manueliglesias I am following this tutorial ==> `https://medium.com/@benawad/aws-appsync-tutorial-with-react-4e272a6f3527` and I got CORS issue when hitting graphql endpoint
```
Access to XMLHttpRequest at 'https://xxx-api.eu-west-1.amazonaws.com/graphql' from origin
'http://localhost:3000' has been blocked by CORS policy: Response to preflight request
doesn't pass access control check: Redirect is not allowed for a preflight request.
```

I added the CORS configuration you provided above to the S3 buckets and still I have the same issue.

I also get `Failed to fetch` when using AppSync Queries console (as the graphQL endpoint and the AppSync console are also on different domains.)

Any help would be much appreciated.

**Comment by alixeb** [comment]
@manueliglesias All good now! I saw #2157 and it is because of Brave Browser. Works fine in Chrome 🎉
