### ISSUE TITLE
withAuthenticator HOC doesn't allow signout 

### ISSUE THREAD

**Issue by vsrivatsan89** [aws/aws-amplify#174]
If I do withAuthenticator(App) and render the resulting component. then Auth.signOut() does not work. But if I do withAuthenticator(App,true)...then the Auth.signOut() works but it puts an ugly navbar type component. Is there a way to just wire my own button for signout instead of having the navbar

**Comment by vsrivatsan89** [comment]
Actually, I think I figured it out. The Auth.signOut() does work, it clears the credentials from localstorage but doesn't refresh React. A workaround was to just do a window.location = "/" after doing the Auth.signOut()

**Comment by vsrivatsan89** [comment]
Let me know if that is the wrong pattern to use.

**Comment by AlpacaGoesCrazy** [comment]
Oh well, i just noticed that component wrapped in `withAuthenticator()` is supplied with `onStateChange()` props. And it works perfectly like this:
```
Auth.signOut()
      .then(data => {
        return this.props.onStateChange('signedOut')
      })
      .catch(err => {/*handle error*/});
```
