### ISSUE TITLE
Allow SignUp with validation data

### ISSUE THREAD

**Issue by MatteCarra** [aws/aws-amplify#175]
Recently userAttributes have been added to signUp, but validationData is still missing:
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html#API_SignUp_RequestSyntax

My use case is to allow to verify that new web users are not robots through a captcha that is verified by a lambda.

**Comment by mlabieniec** [comment]
@MatteCarra validation data is coming with the next release

**Comment by nicolasheady** [comment]
Still no validation data possible with Amplify's Auth.signUp function.

**Comment by polmolea** [comment]
I just had some troubles with this and the docs are all over the place. The following should work with the latest version:
```javascript
Auth.signUp({
  username,
  password,
  validationData: [
    {
      Name: 'foo',
      Value: 'bar',
    },
  ],
});
```
