### ISSUE TITLE
What are the design considerations behind this aws-amplify library?

### ISSUE THREAD

**Issue by baharev** [aws/aws-amplify#178]
I keep running into the same issue: The service that I am trying to use is perfectly capable of doing what I need, and it is well documented how to use the feature that I need but `aws-amplify` wouldn't let me do that. If I used the `aws-sdk` directly, it would be a lot more painful to do it, but I would get what I want. Examples:

- `Storage.put`: It very carefully discards any option that it does not expect. I cannot control whether the upload will be a putObject or a multipart upload, see #125.
- `Storage.put`: I cannot pass precomputed MD5 checksums to it. It would be very useful in my use case.
- `Storage.put`: It only returns the key of the object, but very carefully discards the ETag for example which I would need.
- `Storage.list`: I haven't tried this one, but as far as I can tell, if there are more than 1000 keys, it will silently return 1000 keys, without a warning that there are more objects. If I am not mistaken, it will discard the `MaxKeys` options from the input, and the `IsTruncated` from the output. If so, this is a bug.

It seems to me that the amplify library is deliberately implemented this way.

**What are the design considerations behind this aws-amplify library?**

**Comment by mlabieniec** [comment]
@baharev there is some of this on the [wiki](https://github.com/aws/aws-amplify/wiki), here and we are working on populating this more soon.

**Comment by baharev** [comment]
@mlabieniec OK, let me put it in another way: 

Why is `Storage` systematically discarding any option that it is not expecting, although the underlying `aws-sdk` would understand just fine?

Why is it discarding useful information from the response that I would need?

Are these deliberate by design?

It is fine if they are, but I would rather figure that out sooner than later, and use the `aws-sdk` directly.

As it currently is, the `Storage` is not helping me, but it is an annoying middle men. I gave you 4 examples of that above.

**Comment by mlabieniec** [comment]
@baharev the initial features basically cover the "basic" options for usage when it comes to storage. The principles around Amplify are based around an opinionated approaches and declarative interfaces. We wanted to start basic and iterate based on customer feedback rather than adding to much of what we thought should be in there, or what is already present within the native JS SDK. Amplify will help when it comes to storage with automated credential management using amazon cognito and temporary credentials / permission level storage access. We are currently working on enhancing storage further around encryption and more upload/multi-part features. We would definitely appreciate and welcome your feedback around how we could improve this further as well. Thanks!

**Comment by baharev** [comment]
@mlabieniec In my use cases, the `aws-amplify` acts like a wall: (1) It stops me from passing options to the underlying `aws-sdk` by discarding all options it didn't expect, and (2) it discards valuable pieces from the response of the AWS service.  In [my first comment](https://github.com/aws/aws-amplify/issues/178#issue-290313313) I gave you 4 examples of this.

If I implemented the `aws-amplify` library, I would make sure that the caller can transparently pass *any* option to the `aws-sdk` library, and I would return literally everything that the service returns. I would not discard anything; neither options nor parts of the response. It is 120% OK if you don't want to write the `aws-amplify` library like this, but I would like to know where this project is headed, and switch to the `aws-sdk` if necessary.

I use `redux-saga` and, as a consequence, all API calls to AWS are already isolated from the rest of the code. I don't need an additional layer that tries to shield me from the `aws-sdk`.

In any case, please check the last point of my first comment (regarding `Storage.list`). If what I write is correct, it is bug.

**Comment by mlabieniec** [comment]
@baharev thanks, really appreciate the feedback. For the list command, currently we use the S3.listObjects command via the sdk, this only supports listing up to 1000 objects:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property

We are going to implement the v2 method which will allow returning a subset of objects:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property

we have discussed providing a way to simply pass parameters through to the lower level sdk, we are just working on the best way to implement this and what makes sense. Thanks again for the feedback and will keep you posted here on this.

**Comment by baharev** [comment]
@mlabieniec OK, I am delighted to hear that my feedback was actually helpful.

As for listing a bucket, it seems to me that it doesn't matter which version of `listObjects` you are using from the `aws-sdk`, the old version or the new one. You will have to either pass a marker (old version) or a continuation token (new version) if the response was truncated. It seems to me you can list the entire bucket with both versions in 1000 object chunks, and the caller has to deal with the pagination.

As far as I can tell, `Storage.list` (1) discards the marker or the continuation token from the parameters, and it also (2) discards the next marker and the next continuation token from the response too, making it impossible to implement pagination. This is the problem, and not the version of `listObject`. You could list the entire bucket with the old version of `listObjects` too.

Or do I seriously misunderstand something here?

**Comment by mlabieniec** [comment]
Closing in favor of suggested passthrough to the SDK, please let us know if you'd like to re-open!
https://aws.github.io/aws-amplify/media/quick_start.html#aws-services
