### ISSUE TITLE
Using cookies to store cognito tokens

### ISSUE THREAD

**Issue by pttse** [aws/aws-amplify#179]
As shown on the use case 26 of amazon-cognito-identity-js  ([https://github.com/aws/amazon-cognito-identity-js](https://github.com/aws/amazon-cognito-identity-js)), can Amplify have using cookies to store cognito tokens? 

<img width="974" alt="screenshot at jan 22 18-23-15" src="https://user-images.githubusercontent.com/2939262/35216119-7c56daf4-ffa1-11e7-84a4-71d17417baea.png">

We would like to set the cookies for Single Sign On to subdomain/different domains, however, after looking into this repository, we will have to define the cookie storage code either on the userData, userPool.

**Comment by yuntuowang** [comment]
Hi @pttse, though the amazon-cognito-identity-js repo has moved to under Amplify repo, the use case instructions didn't change. So you still need to pass it in the constructor map of CognitoUserPool and CognitoUser (when constructed directly).

**Comment by powerful23** [comment]
Closing the issue as this should have been fixed in the latest version
