### ISSUE TITLE
Updating mutable user attributes

### ISSUE THREAD

**Issue by ChrisButterworth** [aws/aws-amplify#18]
Is there a way to update a way to update user attributes using this library?

Checked the documentation but doesn't mention anything about updating user attributes.

**Comment by richardzcode** [comment]
We don't have this yet. In our backlog. We'll keep you posted.

**Comment by kbuechl** [comment]
Hey Chris, I just ran into this and found a workaround for now until this is updated.

`const updateAttributesExample = (attributeName, attributeValue) =>{
    let user = getCurrentUser(dispatch);

        user.getSession((err, session) => { 
            var disclaimerAttribute = [ 
                new CognitoUserAttribute({ 
                    Name: attributeName, 
                    Value: attributeValue
                }) 
            ]; 
 
            user.updateAttributes(disclaimerAttribute, function (err, result) { 
                if (err) { 
                  //handle the error
                } 
               //do something with the success if needed
            }); 
        });
}`

**Comment by kbuechl** [comment]
Chris, If you are looking for a workaround I was able to use something similar to this. 
``` 
import {
    CognitoUserAttribute
} from 'amazon-cognito-identity-js';

const updateAttributesExample = (attributeName, attributeValue) => {
    let user = getCurrentUser(dispatch);
    user.getSession((err, session) => {
        var disclaimerAttribute = [
            new CognitoUserAttribute({
                Name: attributeName,
                Value: attributeValue
            })
        ];

        user.updateAttributes(disclaimerAttribute, function (err, result) {
            if (err) {
                //handle the error
            }
            //do something with the success if needed
        });
    });
}
````

**Comment by asharafshahi** [comment]
Was this added recently?  I'm also trying to update user attributes from my mobile react-native app.  Thanks!

**Comment by mlabieniec** [comment]
@asharafshahi it's in PR right now and should be in the next release!

**Comment by asharafshahi** [comment]
If I'm using aws-amplify-react-native will the next release address this for me as well?

**Comment by asharafshahi** [comment]
Thanks Amplify devs and @mlabieniec for getting the new release out!  Looks like a lot of improvements.  Sorry in advance if this should be obvious to me, but I looked through the docs to see what the new way to update user attributes is and I couldn't find it.  A pointer would be much appreciated!  thx

**Comment by yuyokk** [comment]
@asharafshahi I think that's what you are looking for https://github.com/aws/aws-amplify/blob/master/docs/media/authentication_guide.md#user-attributes

**Comment by asharafshahi** [comment]
You are right, the docs definitely have a typo.  I tried the method as stated in the docs and it throws an error.  When I call Auth.currentAuthenticatedUser and pass the result in as the first argument all goes well.
