### ISSUE TITLE
TypeError: user.sendMFACode is not a function

### ISSUE THREAD

**Issue by vbudilov** [aws/aws-amplify#192]
aws-amplify, v0.1.36 (non-React version).  

While calling confirmSignIn:
```
        Auth.confirmSignIn(this.user, this.confirmationCode)
            .then(data => this.handleResponse(data))
            .catch(err => this.handleError(err));
```
I'm getting the following error:
`TypeError: user.sendMFACode is not a function`

I checked the user object and it doesn't have this function, so not sure where the disconnect is. The actual registration is successful. Here's the code that fails:
https://github.com/aws/aws-amplify/blob/fc8722ee79f5a691843901af3729be57dbadba0b/packages/aws-amplify/src/Auth/Auth.ts#L247

**Comment by richardzcode** [comment]
Hey @vbudilov just wanted to confirm. The user object in your call to Auth.confirmSignIn, was it from signIn method response? Also, need to make sure the challengeName was 'SMS_MFA'.

Something like this:

```
Auth.signIn(username, password)
  .then(user => {
    if (user.challengeName === 'SMS_MFA') {
      // somehow get the code, then
      Auth.confirmSignIn(user, code)
        .then(() => /* success */ )
        .catch(() => /* error */ )
    }
  });
```

Or keep user object to be used later:

```
signIn(username, password) {
  const that = this;
  Auth.signIn(username, password)
    .then(user => {
      if (user.challengeName === 'SMS_MFA') {
        that.user = user;
      }
    });
}

confirm(code) {
    Auth.confirmSignIn(this.user, code)
      .then(() => /* success */ )
      .catch(() => /* error */ )
}
```

**Comment by elorzafe** [comment]
Please feel free to reopen this issue in case you still have problems with this.

Thanks!

**Comment by asalia-marine** [comment]
Getting the same error with react-native. aws-amplify version 0.2.14
`TypeError: user.sendMFACode is not a function`

Somehow the CognitoUser object received in response of Auth.signIn(username,password) doesn't have this sendMFA function. It does contain `challengeName : "SMS_MFA"`

**Comment by grgaortiz** [comment]
@asalia-marine Were you able to move past this issue? Experiencing the same response even with `challengeName : "SMS_MFA"` when using Auth.confirmSignIn. Any suggestions?

**Comment by sheldonbarnes** [comment]
I am experiencing the same issue in Angular

**Comment by grgaortiz** [comment]
@elorzafe @richardzcode - Should we open a new issue or is there a way to re-open this specific one? Either way, any thought on the details above?

**Comment by sagenate24** [comment]
I am having this same issue. I am passing the user object returned by ```Auth.signIn()``` as the first parameter in ```Auth.confirmSignIn(user, "123456", "SMS_MFA")```. but yet that user object still does not have the sendMFACode function.

Error: `TypeError: user.sendMFACode is not a function`

Anyone still having issues with this?
`"@aws-amplify/auth": "^1.2.25",`

**Comment by webjestic** [comment]
I am. Same issue in Vue.

`TypeError: user.sendMFACode is not a function`

`    "aws-amplify": "^1.2.4",
    "aws-amplify-vue": "^0.3.3",`

**Comment by rahul-nath** [comment]
I'm having an issue with this. I am autoconfirming my user on sign up and immediately logging them in, with auto verification and MFA enabled. I save the user returned from the sign up in localstorage in case of page refresh and then retrieving it and passing it, along with the user provided code, to auth.confirmSignIn. Anyone find a solution for this one?

**Comment by rahul-nath** [comment]
my issue turned out to be that saving the session user in local storage does not work unless you stringify the json and unstringify it when you fetch it (I think). I kept seeing [Object object] stored as the value in application storage when I tried to cache the session User.

**Comment by minkasu-kuppusamy** [comment]
> Getting the same error with react-native. aws-amplify version 0.2.14
> `TypeError: user.sendMFACode is not a function`
> 
> Somehow the CognitoUser object received in response of Auth.signIn(username,password) doesn't have this sendMFA function. It does contain `challengeName : "SMS_MFA"`

Same issue here. Have. you resolved it ?

**Comment by EC-TBeall** [comment]
Has anyone found a resolution for this? Almost a year later and I am running into the same thing. My returned user object does not have the sendMFACode function as one of its attributes.

**Comment by joaomg** [comment]
Please ensure that your sending a CognitoUser type in the user parameter.

`Auth.confirmSignIn(user, confirmationCode)`

It's the user object returned by:

`Auth.signIn(username, password)`

**Comment by wgarzo1** [comment]
Hey in my case, i implement this method with stencilJs and Angular, for my this solution save my life jejej,
u need install amazon-cognito-identity-js, and import the `CognitoUser`
`import { CognitoUser } from 'amazon-cognito-identity-js';`,  this solution saved myself,  
```
  async otpSendCode( user:CognitoUser , code: any) {
    console.log('aqui en cognito service====>');
    const loggedUser = await Auth.confirmSignIn(
      user, // Return object from Auth.signIn()
      code, // Confirmation code,
    );
    console.log(loggedUser);
    return loggedUser

  }
  
```
