### ISSUE TITLE
How do I save Auth state in phone?

### ISSUE THREAD

**Issue by 7772** [aws/aws-amplify#193]
I make react native app using aws amplify and mobilehub(AWS Cognito, UserPool..etc..)
Also, I use redux, immutable !

I want to make user run my react native app after just once signedIn. For this, I think My app will need something about making persisted Auth.. But, I don't know what the best case is.
Considering that I use aws amplify and mobilehub, please recommend me How to persist User's Auth.

**Comment by mlabieniec** [comment]
@7772 we have this in our backlog. We are abstracting this portion into aws-amplify core Authentication module which react-native module will use. We plan on getting this pushed out in the next sprint.

**Comment by 7772** [comment]
Thank you for your answer.
