### ISSUE TITLE
ComputModPow of undefined

### ISSUE THREAD

**Issue by mrkirchner** [aws/aws-amplify#194]
Not sure what I am doing wrong, but i call Auth.signIn(username, password) and i always get the following error:

`Cannot read property 'computedModPow' of undefined`

I have even just done the withAuthenticator HOC method and i still get the same error.
 
Any help would be greatly appreciated.  

Running in IOS Simulator 
Without EXPO

Thanks

**Comment by mlabieniec** [comment]
@mrkirchner this method exists on the react native module provided by amazon-cognito-identity-js. So you need to be sure to run

    react-native link amazon-cognito-identity-js

As outlined [here](https://github.com/aws/aws-amplify/blob/master/media/quick_start.md#react-native-development). The expo sdk now includes this, so if you use `create-react-native-app` you won't need this step.

**Comment by mrkirchner** [comment]
Awesome thank you that link fixed it.  I swear i did react-native link before but maybe not.
