### ISSUE TITLE
Is { Storage } = TransferUtility ?

### ISSUE THREAD

**Issue by thisisjaiswal** [aws/aws-amplify#196]
Is { Storage } from 'aws-amplify-react-native' same as TransferUtility available in native SDKs ?
Does this use TransferUtility (or something similar) APIs under the hood for RN or is just an http api like [react-native-aws3](https://github.com/benjreinhart/react-native-aws3) ?

I had used TransferUtility in Android for video upload for my app and its very robust tool with lots of network issues handled out of the box.  and I'm trying to find RN alternative of my RN-iOS app. I used react-native-aws3 but its not that robust. so is { Storage } ready for mainstream or should I use RN wrapper for TransferUtility (like [react-native-s3)](https://github.com/mybigday/react-native-s3) ?

**Comment by mlabieniec** [comment]
Hi @thisisjaiswal, currently our S3 implementation is http/rest. We are currently working on implementing resumable and similar functionality to transfer utility as well. We should have this functionality in the coming weeks. Please let us know if you have any feedback around your requirements and what you'd definitely like to see!

**Comment by mlabieniec** [comment]
tracking this in #61
