### ISSUE TITLE
Iphone screen displaying white bar at top with custom Authenticator UI

### ISSUE THREAD

**Issue by jfrense** [aws/aws-amplify#197]
I noticed if I am trying to implement custom UI Authenticator, that there is a white bar that is present on the iphone screen. Is the authenticator not hiding itself completely? I have attached a screenshot and here is my code for reference:
<img width="455" alt="screen shot 2018-01-27 at 10 49 50 am" src="https://user-images.githubusercontent.com/6219866/35473532-dbba66bc-034f-11e8-9069-8494826a0240.png">

index.js 
----------
```
class App extends Component {


handleAuthStateChange(state) {
  if (state === 'signedIn') { 
    return ( // go To Entry point of app
      <ApolloProvider store={store} client={client}>
      <AppWithNavigationState />
      </ApolloProvider>
    )
  }
}
 
    render() {
        return (
         <Authenticator {...this.props} hideDefault={true} onStateChange={this.handleAuthStateChange}>
        <Login/>
        </Authenticator>

      );
    }

}
export default App = codePush(App);
```

Login.js
---------------
```
export default class Login extends Component {
    
    
    render() {
    
    
        return (<View style={styles.container}>

            <View style={styles.backgroundContainer}>
            <Image source={images.icons.LoginImage} style={styles.backgroundImage} />
            </View>
            <View style={styles.overlay}>
            <Button iconLeft light rounded style={styles.facebookLoginButton}>
            <Icon style={styles.facebookIcon} name='logo-facebook' />
            <Text style={styles.facebookButtonText}>Login with Facebook</Text>
            </Button>
            <Button rounded bordered light style={styles.loginLaterButton}
            onPress={() => alert('hi')}>
            <Text style={styles.buttonText}>Create Account</Text>
            </Button>


            </View>

            </View>
           
        );
      }
    }
```

**Comment by ldgarcia** [comment]
By default, the Authenticator component displays child elements inside a view that has `topPadding: 20`.

You need to pass a "custom style" to the Authenticator component:

````
import Amplify, { Components } from 'aws-amplify-react-native'
const { Authenticator, AmplifyTheme } = Components

const App = (props) => {
   return (
     <Authenticator
       theme={Object.assign(AmplifyTheme, styles)}
     >
     </Authenticator>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: 0,
  },
})
````

Use `Object.assign(AmplifyTheme, styles)` if you wish to keep using the default AmplifyTheme while you finish to develop your other screens.

**Comment by jfrense** [comment]
thanks this solved my issue!

**Comment by tncbbthositg** [comment]
This issue may be back.  Before I updated to  2.2.2, adding `paddingTop: 0` removed the white space.  Now, the space is back but I can't find the source of the spacing in the inspector.  If I set `marginTop: -20` the space goes away correctly.  If anybody else finds a less hacky fix, I'd love to hear it.  Thanks!!
