### ISSUE TITLE
dependency on mobile hub

### ISSUE THREAD

**Issue by ddddave** [aws/aws-amplify#202]
Hey Mobile Hub looks sweet, but I'm already using Serverless framework to build my app. I'm worried that combining the Mobile Hub with Serverless will create a mess. I just started testing the AWS Amplify Storage feature and got it to work with my manual setup by copying over the IAM policy that Mobile Hub created to the 'authenticated' IAM role on the identity pool that I already have set up.

some questions:
- Is using Amplify without Mobile Hub not recommended?
- Does the AWS Amplify Storage API expect the folder structure (private, protected, public, uploads) to be the same as what Mobile Hub sets up?
- Do the AWS Javascript SDK and AWS Amplify work together and if so is there any special setup I need to do?
- Should I be using the AWS JavaScript SDK for S3 tasks since I am not using Mobile Hub?

Thanks!

**Comment by nidsharm** [comment]
Hi @ddddave,

Thanks for trying out Amplify! To answer your questions:
1. Amplify can be used without Mobile Hub. AWS Mobile Hub helps customers set up AWS resources for their Apps, while Amplify is a Javascript library to make it easier to integrate calls to your resources in your App. 
2. Amplify Storage does expect the folder structure to be same as what Mobile Hub sets up. 
3. Amplify takes a dependency on AWS Javascript SDK and if making all your calls through Amplify, there is no additional setup required. 
4. You can still use Amplify for making calls to your AWS S3 bucket, there is no dependency on Mobile Hub for this. However, you will need to have the same folder structure as Mobile Hub to make your calls. 

Please do let us know if you have any further questions!
