### ISSUE TITLE
Invalid Signature Error on passing query string in path

### ISSUE THREAD

**Issue by vadiraja** [aws/aws-amplify#203]
I am trying to use Amplify API library in react native project to communicate with AWS API Gateway.
API Gateway is set up with AWS_IAM authentication. But I am getting Signature validation error if I pass query string as part of the 'Path' string. ex: "/items?id=23&userId=25". If I remove query string it works fine. 

Now the question is how do I pass parameter via Query String for GET requests?

**Comment by mlabieniec** [comment]
@vadiraja please see #127
