### ISSUE TITLE
API makes POST call to Cognito on every call to APIG

### ISSUE THREAD

**Issue by vadiraja** [aws/aws-amplify#204]
I am not sure if I am doing right but every call I make to API Gateway via Ampliy API package, first it makes POST call to Cognito (https://cognito-identity.us-east-1.amazonaws.com/) even though the current user is already signed-in and stored its keys in memory storage. Key are not expired but it make post call.

I don't mind the call but it adds ~500ms latency to API gateway call. It is somewhat affecting the user experience.

Can please somebody comment on the behavior or can I improve this aspect in any way?

Thanks in advance.

**Comment by powerful23** [comment]
@vadiraja thanks for your feedback. I tried API call on my machine after login and seems like everything goes fine. Could you provide more details about that so we can reproduce it?

**Comment by mlabieniec** [comment]
@vadiraja the normal behavior in amplify is to check if the credentials require refreshing i.e. they are expired and refresh the cognito credentials prior to the API call. How are you logged into your app via Federated login or username/pass? Also, are you on web/react or react-native?

**Comment by vadiraja** [comment]
Thanks for the reply.

It is a react-native mobile app. I am using Auth class to sign-in to Cognito. As of now, I have just enabled username/pass login. I have set up my project using Mobile Hub AWS console.

Does it need to check the expiration cognito credentials against server always? The POST call happens even API calls just after successful sign in scenarios. I would expect token refresh call happens only if token is expired.

**Comment by mbahar** [comment]
I see the same behavior with username/pass sign-in with Cognito with a web React JS app. https://cognito-identity.us-east-1.amazonaws.com is repeatedly requested before each call.

**Comment by mlabieniec** [comment]
This is fixed in the latest master and will be published in the next release to npm.

**Comment by mlabieniec** [comment]
@vadiraja can you verify this is working for you now on the latest?

**Comment by powerful23** [comment]
@vadiraja please reopen the issue if you still has this problem.

**Comment by ghingis** [comment]
I just run into this... before every request there is a cognito access token check, that gives back the User attributes:
![image](https://user-images.githubusercontent.com/3637899/49035827-32988b80-f1b6-11e8-8004-81a6d49b5777.png)
So from the 669 ms load time jumps up to 1017 ms

I'm using it with angular 7
```
 "@angular/core": "^7.0.0",
...
 "aws-amplify": "^1.1.10",


 "aws-amplify-angular": "^2.0.13",
```

What is special in my case, that I have a `graphql_headers` `Authorization` header override in my config (I need the custom claims to be in the id token).
But it seams this has nothing to do with this behaviour, same happened when I commented it.
