### ISSUE TITLE
Signing an API request

### ISSUE THREAD

**Issue by iamtekeste** [aws/aws-amplify#21]
Good job on releasing this package! 
I am interested in knowing how to sign API Gateway requests with Signature Version 4 using this package. I tried a couple of packages like [aws4](https://github.com/mhart/aws4) but they are made for react native mostly because React Native doesn't support the `crypto` module.

Thank you!

**Comment by undefobj** [comment]
Hi, the library will automatically sign the requests for you without any effort on your part. You just need to use the Auth and API modules. Check out the documentation and examples: https://github.com/aws/aws-amplify/blob/master/media/api_guide.md

**Comment by iamtekeste** [comment]
@undefobj Thanks for the quick reply! But it is not clear where/how I should pass `accessKey`, `secretKey` & `sessionToken`. I am using federated login with Facebook as the provider.

**Comment by iamtekeste** [comment]
This might me what I am looking for. https://aws.github.io/aws-amplify/packages/aws-amplify-react-native/docs/Signer.html

**Comment by undefobj** [comment]
Yes you can also use the signer directly if you choose. However for our feature list, would you like to be able to also pass in keys to the API module? Or would you rather have federation functionality with Facebook with the Auth modules and have those credentials automatically passed in when you use the API module?
