### ISSUE TITLE
S3Album component doesn't seem to work with private level storage

### ISSUE THREAD

**Issue by russelltaga** [aws/aws-amplify#211]
I'm using Amplify with Cognito with an identity pool and IAM auth. When using the S3Album component like so:

```
<S3Album level="private" path="test/" />
```
it appears that the component checks the right private user folder initially, but then ends up 404ing due to trying to display the images in the /public folder.

![screen shot 2018-01-31 at 8 40 20 am](https://user-images.githubusercontent.com/27798268/35635474-3ba088c0-0663-11e8-8f12-1b01121052ea.png)

**Comment by richardzcode** [comment]
released

**Comment by russelltaga** [comment]
@richardzcode Thank you!!
