### ISSUE TITLE
Impossible to sign in with MFA enabled - Error: Invalid phone number provided/Unable to send the message. User pool does not have SMS configuration to send messages.

### ISSUE THREAD

**Issue by BerndWessels** [aws/aws-amplify#214]
Hi

I've got a user pool with MFA enabled. I only want email verification for now.

But calling Auth.signIn gives me the following error:

`Error: Invalid phone number provided/Unable to send the message. User pool does not have SMS configuration to send messages.`

This basically makes it impossible to use MFA.

Is this a bug or is there some special configuration?

I read in some docs that users can choose if they want SMS or Email verification - but can't find anything about that in `aws-amplify`.

**Comment by richardzcode** [comment]
Hi @BerndWessels from error message looks like phone number is invalid.

Check this [doc](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html)

> Important
> 
> Phone numbers must follow these formatting rules: A phone number must start with a plus (+) sign, followed immediately by the country code. A phone number can only contain the + sign and digits. You must remove any other characters from a phone number, such as parentheses, spaces, or dashes (-) before submitting the value to the service. For example, a United States-based phone number must follow this format: +14325551212.

Choosing SMS or Email is by settings in AWS Console. In your Console, open service 'Cognito', then click 'Manage your User Pools', then choose the user pool. Then under 'General settings -> MFA and verifications' you should be able to find the setting.

**Comment by richardzcode** [comment]
In this section, only select Email but no Phone Number

#### Do you want to require verification of emails or phone numbers?
> 
> Verification requires users to retrieve a code from their email or phone to confirm ownership. Verification of a phone or email is necessary to automatically confirm users and enable recovery from forgotten passwords. Learn more about email and phone verification.
> Email           Phone Number

**Comment by elorzafe** [comment]
We update the docs mentioning phone number format. Please feel free to reopen this issue in case you still have problems with this.

Thanks!
