### ISSUE TITLE
How can I modify aws-amplify components?

### ISSUE THREAD

**Issue by 7772** [aws/aws-amplify#22]
I apply aws-amplify to my project but I want to modify signIn, signUp and other components of aws-amplify.

exactly, when I try to use aws-amplify, I didn't have a choice but to use this view. 

<img width="280" alt="amplify" src="https://user-images.githubusercontent.com/22615385/33227685-ef1b8244-d1eb-11e7-904f-527fc6be83e3.png">

**Comment by oluckyman** [comment]
I think the default components are for really basic use cases and provided as examples. If tweaking theme is not enough for you then you have to implement your own custom UI (https://github.com/aws/aws-amplify/blob/master/media/authentication_guide.md#5-write-your-own-auth-ui)

**Comment by 7772** [comment]
Thank you! 
I got hint due to your answer!
Do you know something examples about making my own custom UI for React Native App ? 
I'm React Native Starter...So everything is difficult.

**Comment by oluckyman** [comment]
I'm using only web-part currently. But I think the principle is the same. Take a look how react-native UI implemented and make your own basing on example

**Comment by lawcen** [comment]
hi @oluckyman, Do you have a web-part example of how to customize the Auth UI?

**Comment by oluckyman** [comment]
Hi @lawcen, I'm making my own UI components as suggested in the [docs](https://github.com/aws/aws-amplify/blob/master/media/authentication_guide.md#5-write-your-own-auth-ui). As I understood the only way you can customize provided UI is by tweaking `theme` prop

**Comment by mlabieniec** [comment]
You can create your own theme ui component and include it on the Authorizer [UI Theme Extension](https://github.com/aws/aws-amplify/blob/master/media/authentication_guide.md#ui-theme)

**Comment by honkskillet** [comment]
@mlabieniec @oluckyman  All the links here are broken.  Do you know where the docs/them extension info lives now?

**Comment by mlabieniec** [comment]
main docs site:
https://aws.github.io/aws-amplify/

Theme:
https://aws.github.io/aws-amplify/media/authentication_guide#customize-ui-theme
