### ISSUE TITLE
Error on Auth.signIn `util.crypto.lib.randomBytes` is not a function

### ISSUE THREAD

**Issue by yuyokk** [aws/aws-amplify#220]
Hi guys,

After upgrading to the latest version of `aws-amplify` I'm facing the following error on `Auth.signIn`

```
__WEBPACK_IMPORTED_MODULE_0_aws_sdk_global__.util.crypto.lib.randomBytes is not a function
```

I use a default `create-react-app` application with the following dependencies

```
"dependencies": {
    "aws-amplify": "^0.2.2",
    "aws-sdk": "^2.186.0",
    "classnames": "^2.2.5",
    "normalize.css": "^7.0.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.0"
  }
```

Please let me know if more info is required to help investigate the issue.

![image](https://user-images.githubusercontent.com/1225343/35690508-c1a13386-077e-11e8-9556-3a9da97e5a1d.png)

**Comment by yuyokk** [comment]
Removing `aws-sdk` from my dependencies fixes the issue but if I want to use some services that `aws-amplify` does not support yet e.g. Route53
Please advice if there are any workarounds for this.

**Comment by yuyokk** [comment]
Reverting `aws-sdk` to version `2.177.0` locally inside my app fixes the issue.

**Comment by tcscott** [comment]
Still having this problem with Amplify 2.2 and aws-sdk 2.1.177.0
