### ISSUE TITLE
CORS call works but library throws error

### ISSUE THREAD

**Issue by superandrew** [aws/aws-amplify#223]
using Amplify I am calling an API created using serverless framework.

     Amplify.configure(aws_exports);
        let apiName = 'dev-parameters';
        let path = '/devices';
        let myInit = { // OPTIONAL
          headers: {} // OPTIONAL
        }
        API.get(apiName, path, myInit).then(response => {
        // Add your code here
        debugger;
      });

Using Charles (a sniffer) I am able to see a OPTIONS call which returns the proper CORS header, and then a successful GET call which returns what is supposed to return via lambda function.

However in the browser I get this error:

<pre>
Failed to load https://myapiurl/dev/devices: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8101' is therefore not allowed access.
ion-dev.js?v=3.1.8:156 ERROR Error: Uncaught (in promise): Error: Network Error
Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError [as __zone_symbol__ON_PROPERTYerror] (xhr.js:87)
    at XMLHttpRequest.H (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4620)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
    at XMLHttpRequest.v (polyfills.js:2)
    at createError (createError.js:16)
    at XMLHttpRequest.handleError [as __zone_symbol__ON_PROPERTYerror] (xhr.js:87)
    at XMLHttpRequest.H (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4620)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
    at XMLHttpRequest.v (polyfills.js:2)
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4620)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
</pre>

So I never enter the response populated callback.

**Comment by superandrew** [comment]
I noticed something weird.

If I make a call to my api using OPTIONS, I get uppercase headers. This is the request made using Paw(like Postman, but for Mac)

<pre>
OPTIONS /dev/devices HTTP/1.1
Host: 0xv5lvx47f.execute-api.eu-west-1.amazonaws.com
Connection: close
User-Agent: Paw/3.1.5 (Macintosh; OS X/10.13.3) GCDHTTPRequest
</pre>

response:
<pre>
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 0
Date: Fri, 02 Feb 2018 14:14:33 GMT
x-amzn-RequestId: 64454962-0823-11e8-8d72-1dfde56a70fd
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent
Access-Control-Allow-Methods: OPTIONS,DELETE,POST,PUT,GET
Access-Control-Allow-Credentials: false
X-Cache: Miss from cloudfront
Via: 1.1 618e7837fdb70e63cc342aca20aeab81.cloudfront.net (CloudFront)
X-Amz-Cf-Id: wBHjKwCnwRakXaY_dxglO38kBpnOj45dUjZv26w-qg-nM3gX22rVuA==
Proxy-Connection: Close

</pre>

now the call made through Amplify:

request:

<pre>
:method: OPTIONS
:authority: 0xv5lvx47f.execute-api.eu-west-1.amazonaws.com
:scheme: https
:path: /dev/devices
access-control-request-method: GET
origin: http://localhost:8100
user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Mobile Safari/537.36
access-control-request-headers: authorization,x-amz-date,x-amz-security-token
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8

</pre>

response
<pre>
:status: 200
content-type: application/json
content-length: 0
date: Fri, 02 Feb 2018 14:14:57 GMT
x-amzn-requestid: 72ef40c8-0823-11e8-84c8-e3918e9f1c4b
access-control-allow-origin: *
access-control-allow-headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent
access-control-allow-methods: OPTIONS,DELETE,POST,PUT,GET
access-control-allow-credentials: false
x-cache: Miss from cloudfront
via: 1.1 2ab5bac3c4f4b14b2ce8671eb205d6c8.cloudfront.net (CloudFront)
x-amz-cf-id: lpzPO3yC4cAu4k0SW16XkMv4tb6wSmKO8EU7aIhtgtBaC7R0MaVkcA==
</pre>

It is way beyond my knowledge on why Amplify gets a lower case CORS response, but this might something that the browser doesn't recognize as a proper header. Isn't it?

**Comment by superandrew** [comment]
update: it seems that not watching the raw response both headers are read Uppercase (see images) not sure if it could make a difference for the browser.

![screen shot 2018-02-02 at 15 23 47](https://user-images.githubusercontent.com/71364/35737814-1ff15674-082d-11e8-8820-0d62ba85ba5b.jpg)
![screen shot 2018-02-02 at 15 23 39](https://user-images.githubusercontent.com/71364/35737815-20eb5962-082d-11e8-866a-015668ea7251.jpg)

**Comment by superandrew** [comment]
I can confirm that this could be a bug. In fact bypassing the browser security makes the call work. I want to highlight again that even in the failing case, after the OPTIONS call there is a GET which returns a working results, but the javascript layer fails.

<pre>open -a Google\ Chrome --args --disable-web-security --user-data-dir</pre>

The call works perfectly.

**Comment by mlabieniec** [comment]
@superandrew sometimes the "cors" errors can be a little misleading and sometimes means a configuration issue with the API itself. Did you create this API using Mobile Hub / Cloud Logic ? Or did you manually create the API in the console/cli with API Gateway?

If created manually, can you verify the CORs is setup within API Gateway and that the API is deployed to a stage?

https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html

If created with [awsmobile-cli](https://github.com/aws/awsmobile-cli) or Mobile Hub this would be configured automatically and uses express js routes within Lambda, have you considered using this (if you did not) instead to automate the configurations?

**Comment by superandrew** [comment]
thank you @mlabieniec I just realized that the Header should be provided also by the 200 GET response (which honestly I didn't know). In the end I made a classic 2006-like XMLHttpRequest and when I got the same result I realized it wasn't Amplify's fault. Sorry for that.

**Comment by superandrew** [comment]
Oh I forgot to mention: I created everything with serverless framework, and CORS enabled of course. But being the LAMBDA_PROXY way of doing things, I had to provide the Allow_origin header in my lambda function on the 200 response.
