### ISSUE TITLE
Authorization for Analytics fails with "No userpool"

### ISSUE THREAD

**Issue by floric** [aws/aws-amplify#229]
Hey,

I currently tried to upgrade from 0.1.x to 0.2.3 (also tried 2.0.0).
Unfortunately, the logging of metrics to Pinpoint doesn't work anymore. Somehow the initialization of Analytics fails already.
In "currentUserCredentials()" it rejects the "currentUser()" in Auth.ts promise with "No userPool". This will lead to "credentialsOK" in Analytics.ts to be false and so prevent Mobile Analytics and Pinpoint from getting initialized. But I'd like to collect metrics for unauthorized users of course and so I think I don't need a user pool for this.

Is this an expected behavior? There is no error output in the console.
I also double checked the configuration and it worked before the same in 0.1.x.

Thanks :)
Florian

**Comment by mlabieniec** [comment]
@floric are you using react native or web/js? If React Native, you need to update imports to import from 'aws-amplify' no long er 'aws-amplify-react-native' (this is only for HOCs and components now).

Also, if in an existing project you may need to delete your node_modules and `npm install`

**Comment by floric** [comment]
Hey, sorry for missing the information: "aws-amplify@0.2.3" using Yarn, also double checked this already (looking into the yarnlock and the node_modules folder)

I debugged the code as described above. Might be important as well, that in Auth in "essentialCredentials(credentials)", credentials is null and so credentials.accesskeyId will lead to an exception.

**Comment by mlabieniec** [comment]
We have seen some issues with yarn that we are looking into still, can you give npm install a try just to eliminate this possibility?

**Comment by floric** [comment]
Of course :) Tested using NPM 5.3.
But didn't change anything. I'll try to examine the bug and see if I can fix it.

**Comment by mlabieniec** [comment]
Are you including the aws-js-sdk in your project as well? If so, can you verify the version you have in node_modules

**Comment by floric** [comment]
It's not part of my package.json but 2.177.0 is included in Yarn as well as NPM. Should be enough, right?

**Comment by mlabieniec** [comment]
Yes that's right I just wanted to make sure that was the version since the later one has a breaking change with the cognito library.

**Comment by mlabieniec** [comment]
Did you create your backend through Mobile Hub or via the awsmobile-cli? Or did you manually setup your resources?

**Comment by floric** [comment]
At first I manually integrated aws-amplify based on the manual instructions and an existing project.
After the same problems using 0.2.0 as mentioned in this thread, I used awsmobile-cli to create a new Mobile Project. This used aws-amplify@0.1.36 which worked, but my custom events were not visible in Mobile Analytics so I tried to update to 0.2.x. The resources seem to work correctly as they are a standard project created with Mobile CLI using only analytics and I was able to see events and users in Pinpoint using 0.1.36 as well as the REST calls in Chrome.

**Comment by jacklinton** [comment]
I'm still having this "credentials.accesskeyId" being undefined problem. It started with APIs I created myself through the command line and now it continues with an imported cloud logic service created outside of Mobile Hub. I haven't successfully connected to any API. First I a warning about it in the console and then I directly tried to run Auth.essentialCredentials() and got an unhandled promise warning because credentials.accesskeyId undefined is not an object.

Amplify 0.2.6
React native is the ExpoSDK25.0.0 build and same version of expo.

**Comment by hsavit1** [comment]
Try checking for duplicate node_modules installations. check for node_modules in the library aws-amplify-react and if it's there, delete it
