### ISSUE TITLE
undefined is not a function (near ...window.addEventListener...)

### ISSUE THREAD

**Issue by depuleio** [aws/aws-amplify#230]
The error claims to be coming from within browser.js and whenever I comment out importing aws-amplify the error is gone and my app renders. 

<img width="371" alt="screen shot 2018-02-03 at 1 38 36 pm" src="https://user-images.githubusercontent.com/16300466/35771231-3ea7c4de-08f7-11e8-9325-c8d3929c50a7.png">

Browser.js
<img width="1280" alt="screen shot 2018-02-03 at 1 39 46 pm" src="https://user-images.githubusercontent.com/16300466/35771235-46ade3e8-08f7-11e8-9789-37ddc8d75492.png">

Here is my App.js
<img width="1280" alt="screen shot 2018-02-03 at 3 33 37 pm" src="https://user-images.githubusercontent.com/16300466/35771255-a2d68eea-08f7-11e8-81ca-ea99693ec0b2.png">
<img width="1280" alt="screen shot 2018-02-03 at 3 34 19 pm" src="https://user-images.githubusercontent.com/16300466/35771261-c26aa318-08f7-11e8-889d-d5febae6244d.png">

**Comment by mlabieniec** [comment]
@depuleio this would occur if you are using aws-amplify previous to 0.2.3, can you please delete node_modules and be sure you have aws-amplify: '^0.2.x' in your package.json

**Comment by depuleio** [comment]
@mlabieniec Still getting the error

**Comment by mlabieniec** [comment]
So just to be sure, did you follow the setup steps for react native?
https://github.com/aws/aws-amplify#react-native-development

```
$ npm install aws-amplify --save
$ npm install aws-amplify-react-native --save
$ react-native link amazon-cognito-identity-js  # this is needed if you are NOT using CRNA or Expo and used react-native init to create your project
```

**Comment by depuleio** [comment]
@mlabieniec Yes I did those things too, multiple times, but it did not work :/

**Comment by mlabieniec** [comment]
Did you use create-react-native-app to create your app or react-native init ?

Also, are you using yarn or npm

**Comment by depuleio** [comment]
I did react-native init, and I used yarn once to install react-native-navigation but then uninstalled it because I realized I did not want to use that library. I didn't know you needed to stick to yarn OR npm.

**Comment by mlabieniec** [comment]
Hm, are you sure you aren't including 'aws-amplify-react' ? I just ran:

```
$ create-react-native-app amplifyRnTest
$ cd amplifyRnTest && npm install
$ npm install aws-amplify --save
$ npm install aws-amplify-react-native --save
$ awsmobile init
$ awsmobile user-signin enable
$ awsmobile push
```

Then added to App.js:

```
import Amplify from 'aws-amplify';
import { withAuthenticator } from 'aws-amplify-react-native';
import aws from './aws-exports';
Amplify.configure(aws);
```

Could you give these steps a try and see if you have the same results? I will also try with react-native init.

**Comment by depuleio** [comment]
@mlabieniec I never used create-react-native-app before and it is saying "command not found". Do I need to install something prior? Also I double checked, I am definitely importing 'aws-amplify-react-native'; Thank you - Dan

**Comment by mlabieniec** [comment]
you might want to give that a try, unless you are using other native modules, it makes things a lot easier, you can get it with:

    npm install -g create-react-native-app

I also just ran through with `react-native init`. Perhaps your versions are just out of date? Here's what i did:

```
$ react-native init amplifyRnTest2
$ cd amplifyRnTest2 && npm install
$ npm install aws-amplify --save
$ npm install aws-amplify-react-native --save
$ cp ../amplifyRnTest/aws-exports.js ./ .    # just use my other aws-exports file

$ react-native link amazon-cognito-identity-js 
$ npm run ios
```

Did not see any issues here using npm v5.6.0, package.json deps:

```
"dependencies": {
    "aws-amplify": "^0.2.3",
    "aws-amplify-react-native": "^0.2.2",
    "react": "16.2.0",
    "react-native": "0.52.2"
  }
```

**Comment by depuleio** [comment]
how would i update aws-amplify to 0.2.3?

**Comment by mlabieniec** [comment]
`npm install aws-amplify@0.2.3 --save`

Similarly with aws-amplify-react-native.

Or you can just delete those entries from your package.json and run an `npm install`

**Comment by depuleio** [comment]
What's the difference between doing react-native run-ios and npm run ios?

**Comment by mlabieniec** [comment]
`npm run ios` is only available with `create-react-native-app` and will also run the packager

**Comment by depuleio** [comment]
Doing the following has worked. Thank you, I am very new to react-native as you can see. 

$ watchman watch-del-all && rm -rf node_modules/ && npm cache clean && npm install && npm start -- --reset-cache
