### ISSUE TITLE
API calls missing the response status

### ISSUE THREAD

**Issue by jsancho** [aws/aws-amplify#232]
I am integrating with API calls to APIG and it seems like the response status is missing.
The response object comes back as an empty object. 

I am invoking the call as in the official docs

```
API.post(apiName, path, myInit).then(response => {
    if(response) {
     this.setState({sucess:true})
    } else {
      this.setState({sucess:false})
    }
});
```
If the request success with a 2XX I can parse the response array just fine.
However, when the request results in an error, there is no response status to parse, e.g. 4xx, 5xx.
I can see in Chrome dev tools that the status codes are indeed present.

Any ideas?

using 
- aws-amplify: 0.2.3
- aws-amplify-react: 0.1.32

**Comment by yuyokk** [comment]
@jsancho 4xx, 5xx can be `catch`ed

```
API.post(apiName, path, myInit)
  .then(response => {
    this.setState({ sucess: true })
  })
  .catch(error => {
    this.setState({ sucess: false })
  });
```

but still the status code won't be available there :(

**Comment by mlabieniec** [comment]
@yuyokk this really depends on how your Lambda/API Gateway is setup. If you create an API Gateway as a Lambda proxy, then you would return the status code yourself. This is how the default setup is with [awsmobile-cli](https://github.com/aws/awsmobile-cli) and using the [aws-serverless-express](https://github.com/awslabs/aws-serverless-express) setup. 

Did you create the API Gateway / Lambda yourself in your setup, or use mobile hub / cli ?

There are many ways to accomplish this with API Gateway as well, you can see more on that here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/setup-http-integrations.html

**Comment by jsancho** [comment]
@mlabieniec 
We've created the API Gateway and Lambda ourselves (originally derived from a mobilehub project)
We are using the {proxy+} integration to handle the calls via aws-serverless-express in lambda.

This is the current config for the APIG Response Method
![api gateway](https://user-images.githubusercontent.com/1547884/35799648-4fb79fd4-0a5e-11e8-808e-056665309f89.png)

Does that mean that we should add mappings for all http codes as response mappings?

**Comment by BertR** [comment]
The return object from the API call contains only the "data" attribute from the http request.
(See line 198 in the RestClient file. https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/API/RestClient.ts#L197-L201)

I would prefer having access to the full response object (https://github.com/axios/axios#response-schema).

**Comment by mlabieniec** [comment]
@jsancho specifically for lambda proxy / api gateway:

Here is what your response should look like for lambda proxy in node.js:
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format

However, [aws-serverless-express](https://github.com/awslabs/aws-serverless-express) will forward your response for you, so you can provide the statusCode in your response object:
https://github.com/awslabs/aws-serverless-express/blob/master/index.js#L60

@BertR we will add returning the entire response as a feature-request thanks!

**Comment by jsancho** [comment]
@mlabieniec 
Thanks very much for the tips.
After appending .end() to all responses, the forwarding to APIG kicked in, and Amplify is now parsing the status codes.

Also, thanks for taking onboard the feature request for full responses!

top work 👍

**Comment by vkushnir-prismhr** [comment]
Any chance to get the response status with `API.graphql`?

**Comment by HardikShah-PFG** [comment]
I am facing this issue though it is fixed longed back. I have set response:true and calling error.response to get error detail, but getting undefined. Instead getting generic message 'Network Error' in error.message. please help.
![image](https://user-images.githubusercontent.com/65756215/83954287-8bde8200-a865-11ea-86b0-0133cb9bc78e.png)

**Comment by tnraddatz** [comment]
I'm having the same issue has HardikShah, not sure why this issue is close -- error.response is not working as advertised.
