### ISSUE TITLE
Unable to resolve module `./App.css`

### ISSUE THREAD

**Issue by depuleio** [aws/aws-amplify#241]
I am trying to add UI theme to my sign up page. For some reason react-native cannot find my css file. Any ideas? 

<img width="369" alt="screen shot 2018-02-06 at 2 11 31 pm" src="https://user-images.githubusercontent.com/16300466/35881448-ceaadb62-0b4e-11e8-851e-ae6a33206aea.png">
Here is App.js:
<img width="518" alt="screen shot 2018-02-06 at 2 11 41 pm" src="https://user-images.githubusercontent.com/16300466/35881449-ceb61e8c-0b4e-11e8-9e5c-cc8980aa08fb.png">
<img width="618" alt="screen shot 2018-02-06 at 2 11 59 pm" src="https://user-images.githubusercontent.com/16300466/35881450-cec07026-0b4e-11e8-9058-dbcf81c44225.png">

**Comment by mlabieniec** [comment]
@depuleio React Native doesn't support css. It has it's own `Style` syntax that is similar to CSS but is defined within your js files, see here:
https://facebook.github.io/react-native/docs/style.html

You can import this from another file, it would just be a .js or .jsx file, so something like

```
import Style from './AppStyles.js`
```
