### ISSUE TITLE
Unable to set up Storage in React Native while following the guide

### ISSUE THREAD

**Issue by finferflu** [aws/aws-amplify#242]
Hello,

I'm just getting started with AWS Amplify and Mobile Hub in general. I have followed the instructions provided in the documentation, and I have successfully installed AWS Amplify in my current React Native project. I am now attempting to test storage, and I have been following the [guide here](https://aws.github.io/aws-amplify/media/storage_guide.html): 

1. I have run `awsmobile user-files enable`
2. I have added `{ Storage }` to my import
3. I have changed the CORS policy of my S3 bucket (indicated in the awsmobile configuration) as follows

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
    <ExposeHeader>x-amz-request-id</ExposeHeader>
    <ExposeHeader>x-amz-id-2</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
4. I have added `Storage.get('example-image-1.png')` just below my AWS Amplify configuration.

In my console now I can see these errors:

```
"Cannot read property 'accessKeyId' of null"
```

And:
```
Possible Unhandled Promise Rejection (id: 0):
"No credentials"
```

Where do I specify the credentials in my code? What am I missing here?

Thank you very much for your time!

**Comment by mlabieniec** [comment]
@finferflu at the minimum you would need a IdentityPoolId and a region defined in your auth configuration. Did you setup your project with the [awsmobile-cli](https://github.com/aws/awsmobile-cli) ? If so are you importing the aws-exports.js file? The easiest way would be to use the cli:

```
$ npm install -g awsmobile-cli
$ cd /your-project
$ awsmobile init  #if you are using react, you can select all defaults otherwise select appropriate
$ awsmobile user-files enable
$ awsmobile push
```

Then within your code (App.js or similar):

```
import Amplify, { Storage } from 'aws-amplify';
import awsmobile from './aws-exports';
Amplify.configure(awsmobile);
```

The `configure` event is what is going to setup your credentials for you, which will be used by storage.

**Comment by finferflu** [comment]
Thanks for the quick reply.

Yes, I did use `awsmobile-cli`, and I am importing the `aws-exports.js` file as per the documentation. I have enabled analytics, hosting, user-files. My `aws-exports.js` looks like this (redacting sensitive info):

```
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': '***',
    'aws_cognito_region': 'eu-west-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': '***',
    'aws_content_delivery_bucket_region': 'eu-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': '***',
    'aws_mobile_analytics_app_id': '***',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '***',
    'aws_project_name': '***',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': '***',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': '***',
    'aws_user_files_s3_bucket_region': 'eu-west-1',
}
```

So I think I do have `IdentityPoolId` and region set correctly.

**Comment by powerful23** [comment]
@finferflu Thank you for you feedback. This issue have been fixed in pr #227 . We'll make a release in recent days. Or you can clone our repo and install aws-amplify/packages/aws-amplify in your local for now as a temporary solution.

**Comment by finferflu** [comment]
Thank you very much for letting me know. It’s good to know that it wasn’t just me going crazy!

**Comment by finferflu** [comment]
I can confirm that the error is gone in the current master branch. Please feel free to close this issue, unless you want to keep it open until the fix is released. 

Thanks again.

**Comment by pisacode** [comment]
Hi i have followed all the step without an error but now Storage.get() asks for a bucket key in params? I supposed automatic setup will do this by default?

**Comment by powerful23** [comment]
@pisacode Can you provide more details like how you call the ```Storage.get()``` method? Also could you turn on the debug mode by putting ```window.LOG_LEVEL = 'DEBUG'``` in you code.

**Comment by pisacode** [comment]
Hi, thanks for the fast response.

in app.js I put 

`import awsmobile from './aws-exports'
Amplify.configure(awsmobile);`

then 

`componentDidMount(){
        Storage.get('example-image-1.png')
        .then(result => console.log(result))
        .catch(err => console.log(err));
    }`

debug says 
`[DEBUG] 58:41.68 StorageClass - get example-image-1.png from public/example-image-1.png`


and the error is this
`Error: Missing required key 'Bucket' in params
    at ParamValidator.fail (aws-sdk-core-react-native.js:16699)
    at ParamValidator.validateStructure (aws-sdk-core-react-native.js:16710)
    at ParamValidator.validateMember (aws-sdk-core-react-native.js:16737)
    at ParamValidator.validate (aws-sdk-core-react-native.js:16683)
    at Request.VALIDATE_PARAMETERS (aws-sdk-core-react-native.js:11785)
    at Request.callListeners (aws-sdk-core-react-native.js:11528)
    at callNextListener (aws-sdk-core-react-native.js:11518)
    at aws-sdk-core-react-native.js:11745
    at finish (aws-sdk-core-react-native.js:10566)
    at getStaticCredentials (aws-sdk-core-react-native.js:10593)`

If there is anything i should post please let me know.

Many thanks

**Comment by pisacode** [comment]
Hi I just figured it out. At first I download the aws-exports file from mobile hub and placed it in the src folder but then I discovered that there was an automatically generated file on the root folder and changed the import location to that and now everything works fine. Sorry for the trouble. Have a nice day and thanks for the help.

**Comment by powerful23** [comment]
@pisacode Great! Please feel free to ask if you have any question.

**Comment by tncbbthositg** [comment]
Did this ever get released?  I'm having the same problem with aws-amplify `1.1.1`.

In my App.js, I'm doing this:
```import Amplify, { Storage, Logger, Analytics, I18n } from "aws-amplify";
import aws_exports from "./src/aws-exports";
Amplify.configure(aws_exports);```

When I try to put a file in the bucket, I get this:
```[DEBUG] 03:55.298 StorageClass - put images/avatars/84ebf52f-0a2c-493d-9d92-6fb9f109facd.jpg to public/images/avatars/84ebf52f-0a2c-493d-9d92-6fb9f109facd.jpg
YellowBox.js:80 Object {[WARN] 03:55.307 StorageClass - error uploading: Error: Missing credentials in config
    at credError ...```

I also have `user-files` configured:
```╰─╼ $ awsmobile user-files enable

user-files is already enabled
# to configure the feature
    $ awsmobile user-files configure```

I have the keys I'd expect to see in `aws-exports.js`.
```    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': '[our bucket]',
    'aws_user_files_s3_bucket_region': 'us-east-1',```

Thanks a lot for your help!
