### ISSUE TITLE
proper technique for exposing unprotected and protected pages

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#244]
There is a new aws blog entry with a good technique for doing this.
https://aws.amazon.com/blogs/networking-and-content-delivery/authorizationedge-how-to-use-lambdaedge-and-json-web-tokens-to-enhance-web-application-security/

This technique uses a JWT token returned from Cognito. Need to figure out how to get access to that token with amplify.

----

First problem I see with this technique is that it is using a token from User Pool, not Identity Pool. And that's going to be a mess with federated identities which the blog post skipped.

**Comment by adrianhall** [comment]
For user pools, you can use something like

```
async getAccessToken() {
    return (await Auth.currentSession()).getAccessToken().getJwtToken();
}
```

This is probably the more normal case you need.
