### ISSUE TITLE
AWS SDK use

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#25]
How are you bundling in the AWS SDK? I use several SDK calls that are not covered under amplify. So I need to include my own version of the SDK.  It would be very useful if I could go to https://sdk.amazonaws.com/builder/js/  and generate a single SDK containing the APIs I need and the ones  amplify needs. This should also reflect what amplify modules are in use, for example I am not using S3 support.

Maybe there could be a way to automate minified SDK generation.  amplify could select the modules it needs and then I could add the names of the modules I need. Then as part of the build process build a single SDK.

Don't default to the entire SDK, it is about 4MB. The small, customized one I use is 200KB.

**Comment by undefobj** [comment]
Hi John,

We only use a subset to try and keep the library size small for better experience with PWAs or slower networks. Can you let us know what specific use cases you're currently looking to address that aren't covered in Amplify? Also, if you were to include another Service outside of Amplify's category coverage how would you imagine that looking from a programming interface standpoint? Thanks!

**Comment by jonsmirl** [comment]
Top thing I need right now is the ability to call lambda. In my previous app it made direct calls into lambda; each function is totally locked down with per function roles and policies.  

Should I rework my code to use API-Gateway? I don't think there is anything in API-Gateway that I really need but maybe you can convince me otherwise. I would have to call into API-Gateway with AWS_IAM authentication since I rely on the Cognito ID to keep the users separate.  It is not a huge burden for me to use API Gateway, I can look into it tomorrow.

There is no need to cache my lambda results, they are generated on each call and it is rare that an identical call is repeated.

I also have to have Federated login support with Google/Facebook to a Cognito pool.

**Comment by jonsmirl** [comment]
I'm looking at app we have that uses API-Gateway. There is another integration problem with amplify, with API Gateway you generate SDKs. http://docs.aws.amazon.com/apigateway/latest/developerguide/genearte-javascript-sdk-of-an-api.html

The generated SDK is again duplicating  code in amplify and they are not unified with their handling of credentials. API Gateway uses these small library files:

    <script type="text/javascript" src="lib/axios/dist/axios.standalone.js"></script>
    <script type="text/javascript" src="lib/CryptoJS/rollups/hmac-sha256.js"></script>
    <script type="text/javascript" src="lib/CryptoJS/rollups/sha256.js"></script>
    <script type="text/javascript" src="lib/CryptoJS/components/hmac.js"></script>
    <script type="text/javascript" src="lib/CryptoJS/components/enc-base64.js"></script>
    <script type="text/javascript" src="lib/url-template/url-template.js"></script>
    <script type="text/javascript" src="lib/apiGatewayCore/sigV4Client.js"></script>
    <script type="text/javascript" src="lib/apiGatewayCore/apiGatewayClient.js"></script>
    <script type="text/javascript" src="lib/apiGatewayCore/simpleHttpClient.js"></script>
    <script type="text/javascript" src="lib/apiGatewayCore/utils.js"></script>

You've duplicated all of that in amplify.  One solution might be to adjust amplify to implement the same exposed API as this library does. Then I could simply use the apigClient.js file out of the generated SDK with amplify. 

So if I'm going to switch off from direct lambda use I need support for the apigClient.js file out of the generated API-Gateway SDK.

**Comment by jonsmirl** [comment]
The consensus from the developers I've talked to so far is that it would be better if amplify enabled the AWS.Lambda package. They suspect getting the API-Gateway SDK download supported in amplify may need significant coding effort in amplify (not our code). We also don't need the API Gateway features so it just slows us down and adds pointless expense.

**Comment by powerful23** [comment]
Closing the issue. Please re-open it if necessary.

**Comment by baharev** [comment]
@jonsmirl Please join the discussion at #122
