### ISSUE TITLE
Is there a way to integrate Amazon lex?

### ISSUE THREAD

**Issue by just4give** [aws/aws-amplify#250]
When I enabled Lex Bot in Mobile Hub project and issued awsmobile pull, I could see Lex bot details ( such as name, alias ) added to aws-export config file. But I don't know how to use those information to integrate Lex bot in react native project. Anyone has done this before? Can you please provide some guidance?

**Comment by mlabieniec** [comment]
@just4give Thanks for your question. we are working on integration with lex! Are there any specific features or requests you would like to see as part of amplify and react/react-native?

**Comment by just4give** [comment]
@mlabieniec that's a great news! Actually I like to integrate Lex with Ionic project.  Ionic team has created a great started project [here](https://github.com/ionic-team/starters/tree/master/ionic-angular/official/aws) to integrate AWS Mobile Hub with Ionic. I believe when awsmobile CLI will add integration with Lex through aws-amplify.js , I should be able to add that in Ionic similar to native React project. I don't have specific features in mind but both voice and test should work.

**Comment by mlabieniec** [comment]
@just4give thanks for the feedback, adding this issue to our backlog to track the functionality. Let us know if you think of anything else feature-wise.

**Comment by elorzafe** [comment]
Hi @just4give now amplify supports lex on Interactions category. 
https://aws.github.io/aws-amplify/media/interactions_guide

**Comment by hercax** [comment]
I know probably this is not the right place to ask but I have search everywhere with no luck, but how do you update an existing bot you created through the CLI? I've been updating it manually on the AWS console but not sure if I can just export it and replace any files on the backend folder.
