### ISSUE TITLE
Add functionality to change the current password for an authenticated user

### ISSUE THREAD

**Issue by yuyokk** [aws/aws-amplify#252]
Hi guys,

For our app we need a possibility to change the password for signed in users.

As I see there is available method on [cognito-identity-js](https://github.com/aws/amazon-cognito-identity-js/blob/6059c168270f8cf6b5d786e0b9dddd74fb06aa62/src/CognitoUser.js#L767-L783) to change the current password for an authenticated users but I cannot find according method on [Auth class](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L606)

Please let me know if you plan to implement this method in future releases.
Thanks

**Comment by elorzafe** [comment]
Hi @yuyokk 

You can change the user password. The flow is this:
- First  you need to call forgotPassword(username: string) this will send and MFA code to the user
- Then you can call 
forgotPasswordSubmit(
        username: string,
        code: string,
        password: string
)  
code is given by the user after receives the MFA code the same way is used on signin and signup

If you have any concerns please let me know
Thanks

**Comment by yuyokk** [comment]
@elorzafe thanks for explanation but we need slightly different flow where user inputs old password and new password/confirm password then clicks 'Change my password' and it gets changed without any confirmations etc. Let me talk to my team and see if we can reuse already existing change password flow within our app :)
