### ISSUE TITLE
Auth.currentUserInfo() not return E-mail address

### ISSUE THREAD

**Issue by kazyumaru** [aws/aws-amplify#254]
My Ionic 3 app cannot get E-mail from cognito.
I use Ionic AWS mobile hub starter.
AWS sent this JSON.
`{"UserAttributes":[{"Name":"sub","Value":"aad06r82-fe94-4402-840f-b2df2eee6f5a"},{"Name":"email","Value":"myemail@myemailaddress.jp"}],"Username":"kazyumaru"}`

And, account.ts file is like this.

```
Auth.currentUserInfo()
  .then(info => {
    this.userId = info.id;
    this.username = info.username;
    this.attributes = [];
    if (info['email']) { this.attributes.push({ name: 'email', value: info['email']}); }
    if (info['phone_number']) { this.attributes.push({ name: 'phone_number', value: info['phone_number']}); }
    this.refreshAvatar();
  });
```
info['email'] is null. However info.username is not null.

**Comment by 7772** [comment]
You try this

const userInfo = await Amplify.Auth.currentUserInfo();

**Comment by richardzcode** [comment]
Hey @kazyumaru currentUserInfo returns this:

```
{
  id: ...,
  username: ...,
  attribtues: {
    email: ...,
    email_verified: ...,
    phone_number: ...,
    phone_number_verified: ...
  }
```

You need to modify your code to:
```
if (info.attributes['email']) { ... }
if (info.attributes['phone_number'] { ... }
```

**Comment by kazyumaru** [comment]
How warm message!

>7772
Thank you. I try your suggestion code.

>richardzcode
Thank you. I try to modify.

**Comment by kazyumaru** [comment]
I tried to modify but nothing solved.
I did
`console.log(info)`
then
`{username: "kazyumaru", id: "ap-northeast-1:*******", email: undefined, phone_number: undefined, yubin: undefined}`
but aws sent this json.
`{"UserAttributes":[{"Name":"sub","Value":"aad06r82-fe94-4402-840f-b2df2eee6f5a"},{"Name":"email","Value":"myemail@myemailaddress.jp"}],"Username":"kazyumaru"}`

I attempted to check Auth.js, but it is hard for me to find the point.

**Comment by kazyumaru** [comment]
I could solved this issue.
the code in Auth.js I modified like this.
From
`email: attributes.email`
To
`email: attributes[1].Value`
