### ISSUE TITLE
Always On Auth example

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#26]
How can this work? In the onClick handler 'this' is not defined.

    const AlwaysOn = (props) => {
        return (
            <div>
                <div>I am always here to show current auth state: {this.props.authState}</div>
                <button onClick={() => this.props.onStateChange('signUp')}>Show Sign Up</button>
            </div>
        )
    }

**Comment by mikeparisstuff** [comment]
In stateless components you do not need to use "this" to reference the props. I believe if you change "this.props..." to "props..." it should work :)

**Comment by richardzcode** [comment]
Right! AlwaysOn is a function not component.

Thanks @jonsmirl and @mikeparisstuff !

**Comment by jonsmirl** [comment]
I copied this out of the readme. It needs to be fixed.

https://github.com/aws/aws-amplify/blob/master/media/authentication_guide.md
