### ISSUE TITLE
Building aws-amplify from a fresh checkout fails due

### ISSUE THREAD

**Issue by buggy** [aws/aws-amplify#261]
When attempting to build aws-amplify from a fresh checkout it fails.

```sh
node_modules/@types/lodash/index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! aws-amplify@0.1.36 build-with-test: `npm run clean && npm test && tsc && webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the aws-amplify@0.1.36 build-with-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rick/.npm/_logs/2018-02-11T11_52_25_116Z-debug.log
```

There's an issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23375 for it saying you need to use Typescript < 2.7.0

**Comment by mlabieniec** [comment]
@buggy it looks like the version you are building is very old:

    aws-amplify@0.1.36
    
the latest is 0.2.4. Also, for local build you would need to use yarn workspaces if you wanted to build everything, see here: https://github.com/aws/aws-amplify/wiki/Local-Development

Or if you just want to build the aws-amplify package, you would just need to be sure you are using the correct `tsc` version, which you could use `node_modules/.bin/tsc`

**Comment by mlabieniec** [comment]
@buggy saw your pr, thank you! will get that reviewed this week.

**Comment by buggy** [comment]
After updating this doesn't seem to be a problem now. I'll close the PR too.
