### ISSUE TITLE
API Delete method giving a 403 Error

### ISSUE THREAD

**Issue by kevaundray** [aws/aws-amplify#268]
I have used the post, put, and get method with the project. However, I keep getting an error when using the delete method.

I setup the project via the awsmobile cli, and so have the express app.

The signature for the delete method in express app is:

app.delete('/StockDynamoHistory/object/:SourceTime', function(req, res)

The method in my react-js app looks like so:

 API.del('StockDynamoHistoryCRUD', '/StockDynamoHistory/object/'+sortKey)

sortKey is the value of sortKey for the item I want to delete. The table is setup so the primaryKey is userId, and so the app gets it from the requestContext.

I get  403 in the console. Then a:

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.

**Comment by kevaundray** [comment]
I found the error at last.

My sortKey was a datetime : Which looked like so 2017-12-09T22:30.

The delete method requires us to pass the arguments as queryString Parameters in the url.

The ":" is not allowed, however even though I escaped it using encodeURIComponent(), encodeURI() and replace(':', '%3A') I was still getting the error.

I ended up replacing the colon for  dash and that worked fine.

Not sure why the replacing with %3A did not work.

To recreate problem:

- Hash Key was userId
- SortKey was DateTime generated from the html5 datetime field.

**Comment by nikhildinpure** [comment]
Hi Kevaundray, I am facing same issue.
I am trying to delete a file present in my repo. I am able to PUT ,POST, GET.

I am using following method (AngularJS)

reqObj is as per github api content documentation. 
b64CodedCredential are in format user:password .

$http.delete(dPath,reqObj,{headers: {'Authorization':'Basic '+ b64CodedCredential }}

response in console 
403 (Forbidden)
