### ISSUE TITLE
Cursor in the Auth Dialogs is wrong

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#27]
For example cursor over:
Confirm a Code   Sign In
Is I-beam when it should be pointing hand

Cursor over the button is arrow, should be pointing hand.

Cursor over:
Please Sign In / Sign Up

Should be pointing hand

**Comment by elorzafe** [comment]
The issue is fix on aws-amplify-react hoc. If you have any comments please let us know.

Thanks!
