### ISSUE TITLE
Unable to verify secret hash for client

### ISSUE THREAD

**Issue by ravindra4me** [aws/aws-amplify#277]
Unable to verify secret hash error while authenticating user.
***Response***
{"code":"NotAuthorizedException","name":"NotAuthorizedException","message":"Unab
le to verify secret hash for client 3xxxxxxx"}
***Code***
`var poolData = { UserPoolId : 'u***',
    ClientId : '3****'
};

var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
var userData = {
    Username : 'r****@gmail.com',
    Password : '*****',
    Pool : userPool
};
var cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);
cognitoUser.authenticateUser(authenticationDetails, {
    onSuccess: function (result) {
        console.log('access token + ' + result.getAccessToken().getJwtToken());
        /*Use the idToken for Logins Map when Federating User Pools with Cognito Identity or when passing through an Authorization Header to an API Gateway Authorizer*/
        console.log('idToken + ' + result.idToken.jwtToken);
    },

    onFailure: function(err) {
        alert(JSON.stringify(err));
    },
}); `

**Comment by itrestian** [comment]
This happens because you have the "Generate client secret" box checked for your client. Javascript apps, running on a client that might not have the ability to secure secrets shouldn't have that box enabled.

**Comment by ravindra4me** [comment]
I am generating this on node server not browser. Does node also  still have the same issue?

**Comment by itrestian** [comment]
The Javascript client only works without a client secret. We have an internal feature request to expose the client secret for node-use.

**Comment by ravindra4me** [comment]
Thanks!
