### ISSUE TITLE
Chaining onStateChange

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#28]
Again from the readme...

The internal implementation of onStateChange() does a lot of needed things. This replaces the internal onStateChange() with your own version. But you don't want to do that, you need to call both of them, your replacement and the internal version. 

    handleAuthStateChange(state) {
        if (state === 'signedIn') { /* GO TO Main Page */ }
    }
    
    render() {
        return (
            <Authenticator hideDefault={true} onStateChange={this.handleAuthStateChange}>
                <SignIn/>
                <SignUp/>
                <ConfirmSignUp/>
                <Greetings/>
                <AlwaysOn/>
            </Authenticator>
        )
    }

**Comment by richardzcode** [comment]
Hi @jonsmirl , There are two different `onStateChange` props. One is on the pieces like `SignIn`, `AlwaysOn` etc. Another is on 'Authenticator'. The example here is to set the one on `Authenticator`, does not replace the internal one.

Thanks,
Richard

**Comment by jonsmirl** [comment]
I figured out what confused me. I have debugger; several places in the code. When I hit those breakpoints background actions (like updating the state) can't happen. When I removed the debugger; calls it started working. I had thought that the state updates were synchronous and I see now they aren't.
