### ISSUE TITLE
Unclear in docs - how does one access tokens from Auth.signIn?

### ISSUE THREAD

**Issue by spencewine** [aws/aws-amplify#282]
example in docs: https://aws.github.io/aws-amplify/media/authentication_guide.html

example of my usage:
```
const user = await Auth.signIn(email, password);
....
```
`user` has a bunch of properties that are inaccessible including accessToken, refreshToken, and idToken.  In the docs, it's unclear how to get to these because the examples all log the result.

**Comment by powerful23** [comment]
@spencewine the idea of aws-amplify is to manage the auth flow automatically so we didn't expose these tokens to users. Can you tell us what you want to implement with these tokens? For now Amplify will refresh your cognito credentials automatically.

**Comment by spencewine** [comment]
@powerful23 We are implementing a checkout flow with a cart in a custom e-commerce site. The idea was to use the tokens to send down to our API to authenticate a user for account info (favorites, other personal info kept separate from Cognito) and cart endpoints. For unauthenticated users, we're just keeping the cart locally (in which this question doesn't apply).

**Comment by mlabieniec** [comment]
@spencewine We are working on our documentation, thanks for the feedback we realize it does need a lot of work and we are proactively trying update it. You can retrieve the tokens via the user session after being logged in:

    this.session = await Auth.currentSession();

This will return a `CognitoUserSession` which contains `accessToken`, `idToken`, and `refreshToken`
