### ISSUE TITLE
AuthState is initially 'SignIn' before changing to 'SignedIn' in custom Auth UI

### ISSUE THREAD

**Issue by jfrense** [aws/aws-amplify#285]
I am launching my app with a custom Auth UI:

```
index.js
--------
render() { 
        return (
          
          <ApolloProvider store={store} client={client}>
          <Authenticator hideDefault={true} onStateChange={this.handleAuthStateChange}
          theme={Object.assign(AmplifyTheme, styles)}>
          <AppWithNavigationState { ...this.props }/>
          </Authenticator>
          </ApolloProvider>

        )
    }
```

I then navigate to my splash.js file to decide if the user is logged in or not:

```
 async componentDidMount() {
      const { navigation, authData } = this.props;
      
  
      try {
        await new Promise(async (resolve, reject) => setTimeout(() => {
          if (!authData.session) {
            reject('No current session');
            return;
          }
  
          resolve();
        }, 3000));
      } catch (exception) {
        console.log('rejected', exception);
      }
  
      const loggedIn = authData.session && authData.session.isValid();
  
      console.log("MySession" + loggedIn)
  
      navigation.navigate(loggedIn ? 'AppStack' : 'LoggedOut');
  
    }

    render() {
          console.log(this.props)
        return(<View style={styles.container}>
          <Spinner color='#FFFFFF' />
          </View>);
      }
    
    }
```
^^ I noticed that the session is coming back null in authdata even if the authState is 'signedIn'. I also tried another approach where to decide if the user is signed in by the auth state but it seems that the authState is 'signIn' when it reaches my splash.js and by logging I can see that the render method is called a second time and this time authState is 'signedIn'. However, my componentDidMount method only gets called after the first render method (initial Mount). 

it seems that the Auth library takes some time to load the currentSession from local storage. Do you know of any strategy on how to wait for the Auth Data to completely finish loading from local storage and to gurantee that the Auth session is valid?

**Comment by powerful23** [comment]
@jfrense thanks for you feedback. Could you try ```Auth.currentUserInfo``` which will return an object if logged in? Or you can try ```Auth.currentSession``` to get the current user session from Cognito.

**Comment by jfrense** [comment]
@powerful23 thanks for the suggestions. I was able to accomplish the following by calling 

`Auth. getSyncedUser`
