### ISSUE TITLE
Typings not in NPM module

### ISSUE THREAD

**Issue by teddarling** [aws/aws-amplify#292]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Master branch of aws-amplify/packages/amazon-cognito-identity-js includes at least the following on CognitoUser:
associateSoftwareToken
verifySoftwareToken

for amazon-cognito-identity-js@2.0.0

At least those two functions are missing form npm module amazon-cognito-identity-js@2.0.0

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

first run
`yarn add amazon-cognito-identity-js`
or
`npm install --save amazon-cognito-identity-js`

then some example code (assumes a user pulled from local storage):

```
const poolData = {
    ClientId: cognitoConfig.clientId,
    UserPoolId: cognitoConfig.userPoolId
  } as ICognitoUserPoolData;

const userPool = new CognitoUserPool(poolData);

const user = userPool.getCurrentUser();

user.associateSoftwareToken({
              associateSecretCode: (secretCode) => {
                // Print
              },
              onFailure: (err) => {
                // Handle Error
              }
})

```
Trying to compile just the following (or IDE display errors) gives.

`Property 'associateSoftwareToken' does not exist on type 'CognitoUser'`

What is the expected behavior?

It compiles

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

I haven't tried previous versions. This is in MacOS 10.13.3 using Node 9.3.0

I can look at the code in node_modules//amazon-cognito-identity-js/index.d.ts
and see that several methods are missing

**Comment by mlabieniec** [comment]
@teddarling thank you. There have been some updates which include these. This has not been published to npm yet, it will be in the next release (we perform 1 - 2 week rolling releases of the npm packages). These will be published in the next Monday release.

**Comment by teddarling** [comment]
Great thanks for looking into it.

**Comment by hassankhan** [comment]
Hi there,

I've just downloaded `aws-amplify`, which installed `amazon-cognito-identity-js` at `v2.0.1`, but I don't seem to have the typings. Have the changes been released to NPM yet?
