### ISSUE TITLE
Response from RestClient only contains response.data (not response.headers, response.status, etc).

### ISSUE THREAD

**Issue by chapeljuice** [aws/aws-amplify#298]
Using API.get() like the following:

```
API.get(apiName, path, null)
    .then((response) => {
        resolve(response)
    },
    (err) => {
        resolve(err)
    })
```

....the response comes back with only the data, and it's not possible to access the headers, status, statusText, etc.

Being able to access the response headers is a key feature needed so we can access data such as total number of objects (`x-total-count`), etc.

**Comment by mlabieniec** [comment]
Hi @chapeljuice thanks, we have a feature request for this in this issue #232 

We are adding this to the next release.
