### ISSUE TITLE
Cannot read property 'CognitoIdentityServiceProvider' of undefined

### ISSUE THREAD

**Issue by jimmone** [aws/aws-amplify#301]
I am facing this error when trying to use amazon-cognito-identity SDK:
`Cannot read property 'CognitoIdentityServiceProvider' of undefined`

I downloaded the SDK trough the link in the readme and included it in the head -tag of my html file.
Because of this i cant seem to do anything with the SDK, for example creating a user pool results to this error: `app.js:5 Uncaught ReferenceError: AmazonCognitoIdentity is not defined`.

Looking at the readme i cant see anything else to be added inside the head tag except for this single amazon-cognito-identity.min.js file unless i want to use other than Cognito features.

UPDATE: Nevermind i just realized i wasn't using the actual sdk at all. Got it solved!

**Comment by annjawn** [comment]
@jimmone could you please share which lib you installed for this and how you used it? I am trying to figure this one out but the documentations aren't very helpful :(

**Comment by Cordazar** [comment]
@annjawn 

In terminal:
```bash
npm install aws-sdk --save
```

In code:
```javascript
import CognitoIdentityServiceProvider from 'aws-sdk/clients/cognitoidentityserviceprovider';
import CognitoIdentity from 'aws-sdk/clients/cognitoidentity';
```
