### ISSUE TITLE
Add example for `federatedSignIn`

### ISSUE THREAD

**Issue by kanteankit** [aws/aws-amplify#302]
Do you want to request a feature or report a bug?
Feature: Add example of 'federatedSignIn' to the doc

What is the current behavior?
No example available. Because of this, I can't figure out how to add Facebook login to my react-native app

By seeing the `federatedSignIn` function in the code, I am able to create this function
```
logInWithFacebook = async ()=> {
	  const { type, token,expires } = await Expo.Facebook.logInWithReadPermissionsAsync(FACEBOOK_APP_ID, {
	      behaviour: 'native',
	      permissions:['public_profile','email','user_friends']
	    });
	  if (type === 'success') {
	   
	   const user = await fetch(`https://graph.facebook.com/me?access_token=${token}`)
	   let userObj = await user.json()

	  Auth.federatedSignIn('facebook',{token:token,expires_at:expires},userObj)
	   	.then(result => {
	   		console.log(result)
			this.props.navigation.navigate('Home')
	   	})
	   	.catch(err =>{
	   		console.log(err
	    		
	    	}
	   	})



	  }else if (type==='cancel'){

	  }else{
	  	Alert.alert("Unable to login at this time.Please try later")
	  }
	}
```
Step1: The function fetches token from Facebook and the user object.
Step2:  I call `Auth.federatedSignIn` with the necessary parameters. In the response, I am receiving an object of `CognitoIdentityCredentials`.

**Now I don't know what to do with this object of `CognitoIdentityCredentials`**

Step3: In the success callback, I am directing the user to my homepage. 
Step4: Now, the question is how do I get the current authenticated user. The function `Auth.currentAuthenticatedUser` returns the message `not authenticated`. 

If there is an example for this, a lot of people will be able to implement Federated login without using any react native component

**Comment by mlabieniec** [comment]
Currently react-native does not support federation
https://aws.github.io/aws-amplify/media/authentication_guide.html#6-federated-identity

It is currently in this sprint to support in React Native.

**Comment by kanteankit** [comment]
@mlabieniec I understand that aws-amplify does not have a Federation supported component like `withAuthenticator` for react-native for now. But, the method `federatedSignIn` is still available for use.
Since there are examples of `signIn` and `signUp`, an example for `federatedSignIn` could also be provided so that developers need not wait for the component.

**Comment by mlabieniec** [comment]
`withAuthenticator` and `Authenticator` components are available on react native, only the social logins currently are not supported. Standard login works with these on both web and react native.

**Comment by rafaelgrilli92** [comment]
@mlabieniec his question is same as mine and it's not related to React Native itself.

I'm struggling a lot with AWS to simply have a facebook authentication on my RN app. The question was simple: How to use the method "federatedSignIn" to authenticate users but without a React Native component. On a simple javascript way.

I went through the library files, trying to find out how to use the method. But even passing the right parameters, it doesn't work.

I created a Mobile Hub and I've put all the configurations. When I use this method, instead of authenticating the user, they keep the status of "not authenticated".

**Comment by mlabieniec** [comment]
thanks @rafaelgrilli92, understood, federated login with RN is on our roadmap. We have a solution working with Expo SDK currently and are testing this sprint.

**Comment by rafaelgrilli92** [comment]
@mlabieniec I could get it done by using the aws-sdk instead of the aws-amplify. 

@kanteankit Install the **aws-sdk** package and, after you get the access token from facebook, try this approach below:
```
import AWS from "aws-sdk/dist/aws-sdk-react-native";


AWS.config.region = 'REGION';
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
	IdentityPoolId: 'YOUR_IDENTITY_POOL_ID',
	Logins: {
		'graph.facebook.com': authResponse.accessToken
	}
});

AWS.config.credentials.get(() => {
	// The user is authenticated
});
```

**Comment by kasterlod** [comment]
@rafaelgrilli92 @kanteankit 
I have the same problem and the code above not working. After this user have the access with credentials but after app reloading user is still 'not authenticated'. Any updates / ideas?

**Comment by rafaelgrilli92** [comment]
@kasterlod I wasted too much time trying to use AWS services and I just changed to Google Firebase. They have heaps of code examples and it is much much better and easier to implement.

**Comment by kasterlod** [comment]
Yep, you're right, but I want to give a chance for AWS :D. I have an idea how to solve this and will post my solution tomorrow :ok greetings!

**Comment by GerDner** [comment]
Got it working with:

```
    this.get('fb').login('email public_profile').then((authData) => {
      this.get('amplify.sdk.Auth').federatedSignIn('facebook', {
          token: authData.authResponse.accessToken,
          expires_at: authData.authResponse.expiresIn
        }, authData.authResponse.userID)
        .then(user => console.log(user))
        .catch(err => console.log(err));
      console.log(authData)
    });
```

note: i'm using EmberJs

**Comment by kanteankit** [comment]
@GerDner Are you getting a JWT Token or any kind of token while fetching the user? If not, then, how do you plan to make API requests after the user has logged-in?

**Comment by GerDner** [comment]
i'm getting a complete and valid `CognitoIdentityCredentials` object with all tokens.
`currentAuthenticatedUser` etc. is working as well.
The main problem for me was, that the structure for the second argument for `federatedSignIn ` was not as described in https://aws.github.io/aws-amplify/api/classes/authclass.html#federatedsignin

**Comment by rafaelgrilli92** [comment]
With Firebase you don't need to take care of anything about authentication. All social auth providers are included in the library and also after authenticated, you don't need to worry about tokens, auth, refresh tokens... firebase does it automatically and you can configure security rules in your database to use on your app very easily.

**Comment by rinick** [comment]
I'm able to loign with my google account, but on each different computer or different browser, I get a different identityId

**Comment by ZebGirouard** [comment]
@mlabieniec , any update on this?  Would love for React Native support, at least for Google and FB.  We have an enormous amount of S3 video traffic (like an upload every couple minutes, and an enormous amount of GETs), and we would love to standardize on Amazon.  Trying to get a mobile app now, but we're blocked...seems like you guys are close?

**Comment by shouvik44** [comment]
@mlabieniec Until Amplify can support social login, can you provide a best practice approach to using the standard aws-sdk for social login, while using Amplify for features supported in RN (email signup/signin, S3, API, etc.) A few ways have been proposed on this thread - which is the way that best positions us for the next version of Amplify?

**Comment by patw0929** [comment]
I've done a example of Amplify + Federated Identities with Google/Facebook on React Native.
It's not good enough, but it seems works.
https://github.com/patw0929/react-native-amplify-cognito-example

The authentication flow:
1. Get idToken from Google / accessToken from Facebook
2. Use Auth.federatedSignIn to retrieve identity id (from `CognitoIdentityCredentials`)
3. Use the identity id to get open id token
4. Now we can use the open id token to handle AWS services like API Gateway (make sure it has correct IAM role)

Hope it helps.

**Comment by jdeanwaite** [comment]
I have solved this as well using Expo and Amplify.

1. Set up Facebook login with Expo as per the instructions  [https://docs.expo.io/versions/latest/sdk/facebook](here).
2. Request Facebook login through expo.
3. Request user info from facebook graph api using token.
4. Authenticate Amplify using `federatedSignIn` function.

Here is an example gist. It is a short example, definitely not 100% complete but this will get you started really quickly: https://gist.github.com/jdeanwaite/fd6e2af51be6fd364b03caaba1fd0fb4

**Comment by mlabieniec** [comment]
We have a PR to address this we are planning publishing with the next release

https://github.com/aws/aws-amplify/pull/818

**Comment by ZebGirouard** [comment]
@patw0929 , thank you so much for that example.  I managed to get it to give me an Open ID token, and you're saying I can use this to authenticate for other AWS services.  Is it possible to save a user to a user pool this way, though?  I would like to save a user ID to cognito, so I can link that unique ID permanently to user information in my application.

**Comment by nindidooo** [comment]
hi, can someone please help me do a federatedSignin?

Here is my code:

    loginWithFacebook = async () => {
      const {
        type,
        token,
        expires
      } = await Expo.Facebook.logInWithReadPermissionsAsync("FACEBOOK_APP_ID", {
        permissions: ["public_profile", "email"]
      });
      if (type === "success") {
        // Get the user's information with the Facebook Graph api.
        const response = await fetch(
          `https://graph.facebook.com/me?access_token=${token}&fields=id,name,email`
        );
        // first_name,last_name`
        const user = await response.json();
        return {
          user,
          token,
          expires_at: expires
        };
      }
      return null;
    }

        // Use Expo to login with facebook and get user info.
        const { user, token, expires_at } = await this.loginWithFacebook();

        // Use the token to authenticated Amplify.
        await Auth.federatedSignIn('facebook', { token, expires_at }, user);

        // print auth user
        console.log('user:', Auth.currentAuthenticatedUser ());
.
Here is my result:

Promise {
         "_40": 0,
         "_55": null,
         "_65": 0,
         "_72": null,
       }

As you can see, there is no ability for my code to do  Auth.federatedSignIn with facebook at the moment. @powerful23
