### ISSUE TITLE
Update ConfirmSignUp

### ISSUE THREAD

**Issue by ldgarcia** [aws/aws-amplify#304]
Current code: 

````javascript
componentWillMount() {
  const username = this.props.authData;
  if (username && !this.state.username) {
    this.setState({
      username: username
    });
  }
}
````

Proposed changes: 

1) Remove `componentWillMount`

2) Add `componentWillReceiveProps`

````javascript
componentWillReceiveProps(nextProps) {
    const username = nextProps.authData;
    if (username && !this.state.username) {
        this.setState({
            username
        });
    }
}
````

Please see: https://github.com/aws/aws-amplify/blob/72159fb67735c0361e9e61903f4995ff0d95e828/packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.js#L82

**Comment by mlabieniec** [comment]
@powerful23 what do you think of this update?

**Comment by ldgarcia** [comment]
I proposed the change since `componentWillMount` is called only once when rendering `Authenticator`. However, when `authState` changes to `confirmSignUp` only `componentWillReceiveProps` will be triggered since the component is already mounted.

**Comment by powerful23** [comment]
@ldgarcia I think it's a good update. Thanks.
