### ISSUE TITLE
Custom domains in API RestClient -- service name

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#315]
The new code supporting custom domains does not quite do what I need. It is hardcoded to 'execute-api' and I want to change the service to 'lambda'

My Cloudfront configuration has two origins - S3 and lambda. This eliminate CORS. I don't use API Gateway simply because I don't need anything it offers.  Currently I have it stuck in the middle of my API calls where it adds $3.5/10K unnecessary expense and I'd like to remove it. Cloudfront is set to not cache the API calls, they are simply passed through.

I have the two origins cloudfront design working without issue. I'd like to use it with aws-amplify. And to do that I need to pass in 'lambda' as my service instead of 'execute-api' when the signature is calculated.

**Comment by mlabieniec** [comment]
Thanks @jonsmirl. Understood, I'll see if we can get this setup to be able to be passed as well. This initial update was specifically to use a custom domain with api gateway.

**Comment by jonsmirl** [comment]
Once you can pass in the service name you will be able to directly call any AWS API, not lambda specifically.  This is how the AWS SDK works internally. Other uses for this are making AWS IOT calls and Rekognition calls.  Here's a list of all of the domain endpoints that will be accessible.
https://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by mlabieniec** [comment]
@jonsmirl would you basically be looking for something like passing the service name in via the endpoint configuration i.e.:

```js
API.configure({
      'endpoints': [
        {
          'name': 'myCustomDomainAPI',
          'endpoint': 'https://api-dev.aws-amplify.com',
          'service': 'execute-api'
        }
      ]
    });
```

I think this makes sense, let me know if it solves for your use case.

**Comment by jonsmirl** [comment]
That would work, and if it defaults to 'execute-api' no one will even notice the change.

You can then make an array of endpoints and directly access the various services.

**Comment by mlabieniec** [comment]
Perfect! Thanks I'll get this in PR today.

**Comment by jonsmirl** [comment]
Many people don't realize AWS is all https calls inside its APIs. This URL will let you call any of your lamda functions
https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/yourFuncName/invocations
It is documented here:
https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html

You can make this work with a custom domain by setting up a Cloudfront origin pointing to https://lambda.us-east-1.amazonaws.com

This post explains more on how to setup Cloudfront...
https://forum.serverless.com/t/directly-proxying-lambda-via-cloudfront-without-api-gateway/3808
