### ISSUE TITLE
TypeError: user.getAttributeVerificationCode is not a function

### ISSUE THREAD

**Issue by jfrense** [aws/aws-amplify#322]
I am have a AWS Lambda pre-trigger that auto verifies users when they sign up. In my RN app I want to give the user the option to confirm their email and for that I use the following function:

```
handeResendEmailConfirmation() {
     Auth.verifyUserAttribute(this.props.screenProps.authData.username, 'email').then(data => {
      Alert.alert(
        'Verification Code Sent',
        'We sent the verification link to your email. Open the email and follow the link to confirm your account'
      )
    })
    .catch(err => {
      console.log(err);
      alert("Something Went wrong");
    });

  }

```
However I am getting the following error:

`TypeError: user.getAttributeVerificationCode is not a function
`

^^ looks like there is an error when the Auth.verifyUserAttributes is calling an internal function.

Also, I wanted to ask, would the verifyUserAttribute resend an email code/link to verify the email address? just wanted to make sure my logic is sound.

**Comment by richardzcode** [comment]
Hey @jfrense The first parameter of verifyUserAttribute is a CognitoUser object, not username string.

You may try this script
```
Auth.currentAuthenticatedUser()
    .then(user => Auth.verifyUserAttribute(user, 'email'))
    .then(data => {
      Alert.alert(
        'Verification Code Sent',
        'We sent the verification link to your email. Open the email and follow the link to confirm your account'
      )
    })
    .catch(err => {
      console.log(err);
      alert("Something Went wrong");
    });
```

Yes, Auth.verifyUserAttribute send code to email/phone_number depend on what attribute to verify. Then once got the code you may call `Auth.verifyUserAttributeSubmit(user, attr, code)` to submit the code.

The first parameter of Auth.verifyUserAttributeSubmit is also an user object.

Richard

**Comment by jfrense** [comment]
Thanks, was able to pass the user object by: this.props.screenProps.authData

**Comment by aibrahim3546** [comment]
> Hey @jfrense The first parameter of verifyUserAttribute is a CognitoUser object, not username string.
> 
> You may try this script
> 
> ```
> Auth.currentAuthenticatedUser()
>     .then(user => Auth.verifyUserAttribute(user, 'email'))
>     .then(data => {
>       Alert.alert(
>         'Verification Code Sent',
>         'We sent the verification link to your email. Open the email and follow the link to confirm your account'
>       )
>     })
>     .catch(err => {
>       console.log(err);
>       alert("Something Went wrong");
>     });
> ```
> 
> Yes, Auth.verifyUserAttribute send code to email/phone_number depend on what attribute to verify. Then once got the code you may call `Auth.verifyUserAttributeSubmit(user, attr, code)` to submit the code.
> 
> The first parameter of Auth.verifyUserAttributeSubmit is also an user object.
> 
> Richard

Hi @richardzcode , I have tried the way that you suggest, however I am hitting another error which is 

> invalid attribute name. Only phone_number and email can be verified aws

```
Auth.signIn(email, password).then((user) => {
  Auth.verifyUserAttribute(user, '+60123456789').then(() => {
    // should sent verification code here
  })
}).catch(err => {
  console.error(err)
})
```
