### ISSUE TITLE
credentials are not saved after login

### ISSUE THREAD

**Issue by fiddep** [aws/aws-amplify#323]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
After succesful login, when trying to call api gateway with API.post, Amplify throws error "No credentials"
Calling Auth.currentCredentials gives null as response.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**
create-react-app
install aws-amplify, aws-amplify-react
setup user pool & identity pool
wrap App.js in withAuthenticator
login and try calling api-gateway
`async componentDidMount() {
    await API.get(name, path, init);
  }`

**What is the expected behavior?**
Invocation of api-gateway, response either with result or error

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
aws-amplify: ^0.2.7,
aws-amplify-react: ^0.1.33,
react: ^16.2.0,
react-dom": ^16.2.0,
react-scripts: 1.1.1

OS: Windows10
Browser: Chrome Version 64.0.3282.168 (Official Build) (64-bit)

**Comment by powerful23** [comment]
@fiddep can you check if the ```aws_mandatory_sign_in``` is ```enable``` in your ```aws-exports.js```?

**Comment by powerful23** [comment]
@fiddep where did you configure the Auth piece? And also could you turn on debug mode to see more details. Put ```window.LOG_LEVEL = 'DEBUG';``` in your code.

**Comment by fiddep** [comment]
Very helpful tip with the debug! Turns out the mistake was made by myself forgetting to update the app-id for the identity pool.
Would probably be helpful if that error message could be returned or throw an error so you could get notified that the process was not completed successfully

The debug message that was logged
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L868

If you want I'd be happy to submit a PR for it

**Comment by mlabieniec** [comment]
@fiddep that'd be great if you would like to submit a PR for that please do, thank you!

**Comment by fiddep** [comment]
not reproducible as of 0.2.10
closing issue
