### ISSUE TITLE
Why is 'sub' excluded when constructing attributes object?

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-amplify#326]
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L735

`sub` is the user's uuid, which I would think is important to have access to. `username` sometimes matches `sub`, but not in all cases.

**Comment by mlabieniec** [comment]
@ffxsam this is the uuid of the authenticated user, according to the cognito docs it is not the same as the username. However, this was parsed out of the attributes originally because it's non-mutable and to make it easier to update user attributes we didn't include it so that you can send the same payload up to the update request as you get from info. 

However, we did add to the parser for updating to pull this value out anyway, so we can return it in the attributes if you think that is useful.

**Comment by ffxsam** [comment]
I would typically opt on the side of offering too much information back, and let the developer decide what they want or don't want.

In my case, I don't use usernames (people authenticate via email), so `username` and `sub` for me are the same. But I can see in some cases in a username-based system, `username` might be something like JoeCoder101, and you would need the `sub` uuid to pass to functions that call DB operations (e.g. fetch all records owned by this user ID).

**Comment by mlabieniec** [comment]
Thanks @ffxsam, that makes sense. We are moving towards a plugin based system, starting with Analytics category: https://github.com/aws/aws-amplify/pull/236

We plan to do the same thing and are working on this for Auth currently. At that point we will move this logic into the Cognito plugin. Also, for now, feel free to submit a PR for including that and i'll also add it to our backlog as well for an update to the current system to support this use case.

**Comment by ffxsam** [comment]
Thanks Michael! I'll try to submit a PR later this week. Also at some point I'll start working on a PR to add Lambda support to Amplify as it's something I'll need in the near future. Unless you guys beat me to it. 😉

**Comment by ffxsam** [comment]
Oh, and off-topic: I assume you have plans to add full MFA support to Amplify/Auth?

**Comment by mlabieniec** [comment]
@ffxsam thank you! Yes we do have functions on the roadmap as well, but absolutely would love to see what you think and collaborate of course :) 

For MFA, we actually are working on TOTP this sprint, it may make it into the next release but yes that is the plan!

**Comment by ffxsam** [comment]
Awesome news about TOTP! Ideally it would be great if it spit out a code we could just pass into a QR library.

**Comment by mlabieniec** [comment]
@ffxsam TOTP was launched so closing this issue for now, please let us know if you want to re-open it to track anything else.

**Comment by ffxsam** [comment]
Rad! Thanks @mlabieniec, I'll check it out next time I'm working on auth.
