### ISSUE TITLE
currentUserInfo() returning null - potential race condition

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-amplify#328]
I have a Vue app that's calling a function immediately upon page load which performs the following:

```js
const user = await Auth.currentUserInfo();
```

This is returning null. But if I call the same code a few seconds after the page is loaded, it returns a user.

Is there some kind of condition I need to wait for before calling `currentUserInfo`?

**Comment by richardzcode** [comment]
Hey @ffxsam it is because the first time Auth.currentUserInfo got called Auth did not have credentials yet. I'll make a fix to it. In the mean time you could get around it by something like this

```
Amplify.configure(aws_exports)
Amplify.Logger.LOG_LEVEL = 'DEBUG'

const logger = new Logger('main')

Auth.currentAuthenticatedUser()
    .then(user => Auth.currentUserInfo())
    .then(info => logger.debug(info))
    .catch(err => logger.debug(err))
```

Notice this line is to set log level to DEBUG so you'll have detailed logs in console.
```
Amplify.Logger.LOG_LEVEL = 'DEBUG'
```

Thanks!

**Comment by ffxsam** [comment]
Thanks @richardzcode! My fix was the following:

```js
  async getCurrentUserInfo({ commit }) {
    // This is returning null - why?
    // const user = await Auth.currentUserInfo();
    const user = await Auth.currentAuthenticatedUser();

    const attributes = await Auth.userAttributes(user);
    console.log(attributes);

    commit(types.AUTHENTICATE, {
      username: user.username,
      ...extractAttributes(attributes),
    });
  },
```

**Comment by richardzcode** [comment]
Same idea 👍
