### ISSUE TITLE
Progress status for Storage operations?

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-amplify#334]
Is it possible somehow to get transfer progress for `Storage` operations (put, get, etc)? This is a pretty important thing to have. Users of an app will want to see upload or download progress, especially for large files.

**Comment by ffxsam** [comment]
Perhaps Amplify could hook into this:

https://github.com/aws/aws-sdk-js/commit/084f676927b9cd3da337bd6d0d230680c138d73b

**Comment by mlabieniec** [comment]
Absolutely agree, this is in our backlog.

**Comment by ffxsam** [comment]
In the mean time, can you recommend how I can achieve this? I've been poring over documentation for hours. I don't see any way for the AWS JS SDK to allow me to see upload progress. I tried the `httpUploadProgress` event, but it just dumps out a progress update once, which isn't useful.

Is there some way to hook into the raw XHR for `s3.upload` so I can attach the XHR `progress` event handler?

**Comment by mlabieniec** [comment]
So what you could do is use the managed upload:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html

Then you can listen to the `httpUploadProgress` event:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#httpUploadProgress-event

We are going to be adding this to amplify, but in the interim you could access the S3 object directly as detailed in #335 and use the managed upload and progress.

**Comment by ffxsam** [comment]
I tried that. All that happens is, `httpUploadProgress` gets called once only, per part. So for example, if a user uploads a 2MB file, I get one event fire right away that tells me it's uploaded (or uploading) 100% of the file.. and that's it.

What I'm looking for is more along the lines of XHR's `onprogress` event which fires off a few times per second, giving an update on how many bytes have been uploaded. I know for sure this is possible with the S3 REST API (there's [a library for Meteor](https://github.com/CulturalMe/meteor-slingshot/) that does this). I just don't know if it's possible using the JS SDK.

**Comment by mlabieniec** [comment]
Hm ok thanks, let me see if we can add something like this to the API category when passing the service info, perhaps we can retrieve some sort of progress since that is interacting directly with the API.

**Comment by ffxsam** [comment]
Thanks! This would be extremely useful. Users will be angry if they upload a 10+ MB file and they can't see how it's progressing. 😉

**Comment by ffxsam** [comment]
Solved my issue BTW. I was testing the s3 upload from Node.js.. the progress check doesn't work right there. But in a web front-end environment, it works as expected.

**Comment by mlabieniec** [comment]
Oh nice thanks! I guess that perhaps makes sense, but I'll notify / raise the issue with the sdk team and see what the deal with that is. We don't really "officially" support node with Amplify yet, but i have a feeling this may use some local storage or browser specific stuff for the uploading/progress, I'm going to track this as part of #61 feature-request we have in our backlog. Thanks for the update.

**Comment by ffxsam** [comment]
No worries at all, Michael. Probably no need for Node support, and actually this has nothing to do with Amplify. I was just testing in Node to see how `s3.upload` operations could be tracked progress-wise. `httpUploadProgress` event works totally differently in the browser than it does on server-side.

**Comment by ffxsam** [comment]
_But_, having `Storage.put` and maybe `Storage.get` be able to communicate transfer progress seems like a necessity to me.

```js
Storage.put('somefile.zip', largeBinaryFile, {
  level: 'public',
  progress(progress, total) {
    // ...
  },
});
```

**Comment by mlabieniec** [comment]
Absolutely agree! Storage is really something that we are looking to enhance in the next couple sprints.

**Comment by vvusts** [comment]
What is status with progress? Is there any possibility to track it now?

**Comment by rygo6** [comment]
Any progress?
