### ISSUE TITLE
How to call AWS SDK methods after aws-amplify authentication?

### ISSUE THREAD

**Issue by ildar-icoosoft** [aws/aws-amplify#335]
If I call API methods after authentication then everything works fine. API methods are called with credentials. But what if I need to call AWS SDK methods? The AWS SDK methods will be called without credentials. For example:
```
Auth.signIn(username, password).then(...)
API.get(...) // API methods works fine. Methods are called with credentials

const iot = new AWS.Iot();
iot.describeEndpoint({}, (err, res) => {
    // I got error. Because iot.describeEndpoint is called without credentials
});
```
How to call AWS SDK methods with credentials from aws-amplify library?

**Comment by yuyokk** [comment]
@ildar-icoosoft here is an example of what I have with `aws.route53`

```js
Auth.currentCredentials()
  .then(credentials => {
    const route53 = new Route53({
      apiVersion: '2013-04-01',
      credentials: Auth.essentialCredentials(credentials)
    });

    route53.changeResourceRecordSets();
  })
```

basically I'm getting credentials from `Auth.currentCredentials()` and then pass them down to `Route53` constructor via `credentials` option ([`Auth.essentialCredentials()`](https://github.com/aws/aws-amplify/blob/f10a2c0a0c6ae82274b36d8d04939a7487ec27da/packages/aws-amplify/src/Auth/Auth.ts#L718-L726) returns needed tokens from `credentails` object)

Hope this helps.

**Comment by ildar-icoosoft** [comment]
@yuyokk thank you very much! It helped me a lot!
