### ISSUE TITLE
Documentation issue - readme.md for React web auth does not explain aws_exports import.

### ISSUE THREAD

**Issue by bizarosteve** [aws/aws-amplify#336]
Steps to reproduce (Following the Readme.md documentation for Web Development)
- Install aws-amplify
- Install aws-amplify-react
- run create-react-app
- update App.js as shown.  

...this fails to run with the message "Module not found: Can't resolve './aws-exports'"  ./src/App.js

Where should ./aws-exports.js come from?  Thanks.

**Comment by mlabieniec** [comment]
Hi @bizarosteve good call, the aws-exports is actually generated by [awsmobile-cli](https://github.com/aws/awsmobile-cli) with the `awsmobile init` command. We'll get the docs updated on the readme.
