### ISSUE TITLE
Any way to directly access the ad-hoc IAM access key ID & secret key?

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-amplify#337]
If I understand Cognito correctly, it basically creates an ad-hoc IAM user every time someone authenticates, and uses that IAM user to access AWS services.. is that right?

Is there any way to access these strings directly? I have a special case where I don't think the AWS JS SDK is going to work for me, and I need to call the S3 REST API directly, in which case I'll have to formulate an AWS authorization header.

**Comment by mlabieniec** [comment]
@ffxsam no, cognito does not create IAM users. Cognito is essentially 2 services: User Pools and Federated Identity. The users are part of user pools and are it's own service. The **permissions** for that user are governed by the IAM role associated with them or their group:
https://docs.aws.amazon.com/cognito/latest/developerguide/iam-roles.html

For the SDK directly, you can call it by just passing credentials:
See https://github.com/aws/aws-amplify/issues/335

For API, you can essentially call any AWS API via the API category and it will take care of signing the URL for you:
https://aws.github.io/aws-amplify/media/api_guide.html#manual-setup

**Comment by ffxsam** [comment]
BTW, this is related to #334 - as I may have to use S3 REST API directly to get fine-grained upload progress.

**Comment by ffxsam** [comment]
Ah.. I just tried `Auth.currentCredentials()`. I might've mis-worded it when I said it creates an ad-hoc IAM user, but you do indeed get a dynamically generated IAM key. I see an `accessKeyId` and `secretAccessKey` in the result of that function call.
