### ISSUE TITLE
Invalid password format message for valid passwords including spaces

### ISSUE THREAD

**Issue by bizarosteve** [aws/aws-amplify#345]
Current behavior:
- Configure a React web site with awsmobile/aws-amplify configuration as documented on aws-amplify readme + https://docs.aws.amazon.com/aws-mobile/latest/developerguide/web-add-user-sign-in.html
- Run the site with "npm start"
- On the "Sign In Account" page click the "Sign Up" option in the bottom left of the screen
- Add any user name (TestUser works) and "test TEST 01234!@#$%" (without the outer quotes) as a password.  
- Click the "Sign Up" button. The page prompts with an "Invalid password format" message.
- Remove the spaces from the password ("testTEST01234!@#$%") and click Sign Up - the warning message goes away.
- Checking the network tab after selecting the "Sign up" button shows two network request (first OPTION, then POST).  to https://cognito-idp.us-east-1.amazonaws.com/   The reply is 400 (Bad Request).    Headers include X-Amz-Target:AWSCognitoIdentityProviderService.SignUp and X-Amz-User-Agent:aws-amplify/0.1.x js

**Comment by UnleashedMind** [comment]
Hi @bizarosteve 

the following link points to a reference to the password policy. space is not allowed in the password.
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html
