### ISSUE TITLE
Phone number requires a plus sign (+) to validate on Sign Up Account page

### ISSUE THREAD

**Issue by bizarosteve** [aws/aws-amplify#347]
Current behavior:

- Configure a React web site with awsmobile/aws-amplify configuration as documented on aws-amplify readme + https://docs.aws.amazon.com/aws-mobile/latest/developerguide/web-add-user-sign-in.html
- Run the site with "npm start"
- On the "Sign In Account" page click the "Sign Up" option in the bottom left of the screen
- Add any valid user name (TestUser works) and password "aA2@aA2@".
- Type in a valid US phone number (703-555-1212) Response - "Invalid phone number format. Please use a phone number format of +12345678900"  (note this error has an invalid phone number format I will add that as a separate Issue)
- Change the phone number to this format - 17035551212.  Response - still gets an error
- Copy the same phone number from the warning (12345678900).  Response - still gets the same error
-  Copy the exact format including the plus sign (+12345678900) - the validation passes.

It shouldn't be necessary to include a plus sign in front of a phone number for validation - at least in the US this will cause a high drop percentage for enrollments - US residents do not know about E.164 formatting for phone numbers.

**Comment by UnleashedMind** [comment]
Thanks @bizarosteve 
This request has been added to our backlog

**Comment by ldgarcia** [comment]
@bizarosteve You can create your own `PhoneNumber` component and use [libphonenumber-js](https://github.com/catamphetamine/libphonenumber-js) to parse and format the phone number.

Example:

`utils/libphonenumber.js`:
````
import custom from 'libphonenumber-js/custom'
// Optional
import metadata from './metadata.min.json'

export const parse = (...args) => custom.parse(...args, metadata)
export const format = (...args) => custom.format(...args, metadata)
export const isValidNumber = (...args) => custom.isValidNumber(...args, metadata)
export const getNumberType = (...args) => custom.getNumberType(...args, metadata)

export class AsYouType extends custom.AsYouType {
  constructor(country) {
    super(country, metadata)
  }
}
````

````javascript
import { format, AsYouType, getNumberType } from '../../utils/libphonenumber'

export class PhoneNumber extends React.Component {

  state = {
    inputPhone: ''
  }
 
  handleChangeText = (text) => {
    const asYouType = new AsYouType('US')
    const inputPhone = asYouType.input(text)
    const country = asYouType.country
    const phone = asYouType.getNationalNumber()
    const formattedPhone = format(phone, country, 'E.164')
    const type = getNumberType(phone, country)

    // Your business logic here
    this.setState({ inputPhone })
  }

  render() {
           // Render your equivalent form component here (this is for React Native)
          <FormInput
              keyboardType="phone-pad"
              returnKeyType="done"
              onChangeText={this.handleChangeText}
              value={inputPhone}
          /> 
  }
}
````

**Comment by JustFly1984** [comment]
110kb to validate the phone number in production React app? I better make a lambda function and validate phone number with throttled thunk. Thanks for and idea. In other project I had user input phone validated with calls to Twillio. Now I can save some money, and ditch Twillio for next project.

**Comment by mlabieniec** [comment]
closing this in favor of using the recommended utility. Please feel free to re-open and let us know if you think we should build this in.
