### ISSUE TITLE
Is it possible aws-amplify to use Fetch API?

### ISSUE THREAD

**Issue by ildar-icoosoft** [aws/aws-amplify#348]
I want to call AWS API from service workers. There is no XMLHTTPRequet object in service workers. Only [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). Is it possible aws-amplify to send API requests with Fetch API?

I see you use Axios library. There is https://github.com/lifeomic/axios-fetch library to send requests via Fetch API

**Comment by mlabieniec** [comment]
hi @ildar-icoosoft glad to hear you are using service workers! Currently you may be able to use [importScripts](https://html.spec.whatwg.org/multipage/workers.html#dom-workerglobalscope-importscripts) to import the Signer.js file (from dist) and sign your URL with your credentials. You would need to retrieve your Cognito credentials from local storage, i'd recommend using something like [LocalForage](https://github.com/localForage/localForage) to do that. We are working on a pwa sample with Ionic right now that should be released soon with a service worker. Also, we will soon have first class support for service workers and pwa's within the Amplify library itself.

**Comment by ildar-icoosoft** [comment]
@mlabieniec Thank you! It works for me. I found out there is an [aws4](https://github.com/mhart/aws4) library  which signs requests like your Signer.js. Could you tell me please, which way to sign is better?

**Comment by mlabieniec** [comment]
@ildar-icoosoft basically the signer and this lib do similar things. We actively maintain our signer and are utilizing it for features we develop is really the main difference. You can also directly import and utilize the signer (it's exported).
