### ISSUE TITLE
Allow SignUp with custom attributes

### ISSUE THREAD

**Issue by oluckyman** [aws/aws-amplify#36]
Seems like it almost here: 
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L93-L106

Missing few lines to push rest attributes into `attributes` array and pass into `this.userPool.signUp` call.

My use case is to allow user to specify `name` attribute while signing up.
```
Auth.signUp(username, password, email, name)
```
Probably the signature should be changed: leave `username` and `password` params and provide all other attributes as third param:
```
Auth.signUp(username, password, { email, name })
```

**Comment by jeveloper** [comment]
Thumbs up for this too.

Cognito lib seems to have it all  
https://github.com/aws/amazon-cognito-identity-js

Curious if AWS is planning to have amplify as the replacement for cognito js lib 

Thanks

**Comment by homaily** [comment]
+1 for this request.


Probably this will be a breaking change.

@mlabieniec What do you think? Are you ok with adding a new method `Auth.signupWithAttributes`?

**Comment by mlabieniec** [comment]
Thanks for the feedback, attribute support is in our backlog and should be released after the next sprint, starting next week.

**Comment by mlabieniec** [comment]
We have signUp with custom attributes in PR right now and will be getting it merged soon so I'm closing this feel free to open if you feel you need to add anything further. We have more support for custom attributes in our backlog as well.

**Comment by MatteCarra** [comment]
I just saw the PR.
What about validation data? Why isn't it included?

**Comment by mlabieniec** [comment]
@MatteCarra what are you referring to for validation data exactly?
