### ISSUE TITLE
escape characters in URI

### ISSUE THREAD

**Issue by dfrkp** [aws/aws-amplify#361]
> Do you want to request a feature or report a bug?

**Bug**

> What is the current behavior?

Both of these approaches:
```
    const id = "eu-central-1:12354-12351-124512-124124";

    const apiName = "alpha";
    const path = `/users/${encodeURIComponent(id)}/info`;
   API.get(apiName, path);

    const apiName = "alpha";
    const path = `/users/${id}/permissions`;
   API.get(apiName, path);
```
yield the response:

`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

> What is the expected behavior?

I'd like to be able to pass a path with characters like a colon to API.get and don't worry about the escaping.
Alternatively I would like to understand why the approach with manual escaping is not working. :-)

> Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Tested with aws-amplify 0.2.7 and Chrome 64

Thanks

**Comment by ildar-icoosoft** [comment]
I have the same error. Please fix it. It worked in old autogenerated API Gateway SDK
