### ISSUE TITLE
Sign up multiple different accounts with the same email

### ISSUE THREAD

**Issue by ChrisChares** [aws/aws-amplify#369]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

I can sign up with the same email address multiple times.  Our Cognito pool uses email addresses as an alias that can be used to sign in.

```
        await Auth.signUp({
          username: UUID(),
          password,
          attributes: {
            email
          },
        });
```

I can call this as many times as I want successfully.  The last account to be created with a given email address gets the `email_verified: true` flag.  As soon as you create another account with the same email, the existing account with that email becomes `email_verified: false` and the new account becomes `email_verified: true`.  Accounts are created as `ENABLED` and stay that way even after another account "takes" their email. 

**What is the expected behavior?**

I would expect to receive an error trying to sign up an account with an email address that is already verified and attached to another account.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

React Native, Amplify v0.2.4.  We've seen this behavior on all platforms.  How is this supposed to be handled?

Thank you for your time.

**Comment by buggy** [comment]
This isn't an Amplify bug. It's the way your Cognito user pool is setup. If you use "username" login and "allow email logins" then Cognito allows multiple accounts to have the same email address. For the purpose of logging in it will point to only one of those accounts (the verified one).

You need to setup your user pool through Cognito Users Pools in the AWS console and select "Email address or phone number" when asked how you want your users to login. Once your pool is setup correctly you won't be allowed to register an account twice with the same email address.

- Do not select "Username" then "Also allow sign in with verified email address". This does what you're experiencing.
- Do not use AWS Mobile Hub as this sets up the pool using "Username" and does what you're experiencing.

**Comment by ChrisChares** [comment]
@buggy Thank you!  The guidelines for setting up our Cognito pool correctly were super helpful.

**Comment by mlabieniec** [comment]
re-opening this so we can add some of this info to our documentation. Thanks @buggy!

**Comment by bsdkurt** [comment]
Can the pre-signup trigger be used to prevent the new signup from being created when there's an existing account with a confirmed email?

**Comment by ChrisChares** [comment]
If you can't change your Cognito pool settings like us we've found a hacky workaround as well. You can  attempt a sign in with a randomized password to determine if a user account already exists.  This works because Cognito throws different errors for a (correct username, wrong password) combo than (non existent username, wrong password) combo.

```typescript
// Hacky test to check if a user exists in Cognito.  Look for a specific error to indicate the account already exists, but the password is wrong
const isUsernameInUse = async (username: string): Promise<boolean>  => {
  // We use a new UUID as a password to guarantee sign in fails
  try { 
    await Auth.signIn(username, UUID()); 
    return true;
  } 
  catch (error) {
    // Cognito throws a specific error when a username is in use but the password is wrong.
    if ( error.code === 'NotAuthorizedException' ) { return true; }
    else { return false }
  }
};
```

**Comment by bsdkurt** [comment]
@ChrisChares Nice work-around. One thing to point out is that with browser javascript using cognito user pools the user pool id and client id are not secret to the world and can be used to directly interact with cognito api's that don't require an authenticated user (e.g. userPool.signUp, cognitoUser.authenticateUser, cognitoUser.forgotPassword, cognitoUser.resendConfirmationCode, etc.). By putting the work-around in the SPA you are still exposed to a hacker calling userPool.signUp directly.

Note that you can use ValidationData on signUp and authenticate user to pass along Google's recaptcha g-recaptcha-response to the preSignUp and preAuthenticate triggers and have those triggers require the g-recaptcha-response validation data to exist and do the server side validation of it there. This is the approach we have taken as we are concerned about direct interaction with cognito unauthenticated apis and bot signup/auth attempts. As far as I can see there isn't a way to protect forgot password or resend confirmation code with recaptcha - these remain exposed to bots and/or directly using the exposed id's. I would love it if someone corrected me if I'm wrong or missing something.

**Comment by ChrisChares** [comment]
@bsdkurt Thanks that's a good point about sign up still being exposed to a malicious actor.  I'm also curious about best practices for protecting the other unauthenticated endpoints from bots.

Client side validation:
![Client Side Validation](https://i.redd.it/ldvkdq3cc02y.jpg)

**Comment by slackday** [comment]
It's not so smooth that recommended setup is MobileHub which allows setting for: 

• Users can use a username and optionally multiple alternatives to sign up and sign in.
• Also allow sign in with verified phone number

I tried to have username as `uuid()` like OP but `Auth.signIn` accepts only `username` and `password`.

**Comment by slackday** [comment]
Hi, any update on this? I feel like I am missing something critical in my app. I read another issue about using UUID as username. But how is this possible when you need username to login? It can't be expected enter 64 char username to login.

I would like to set username as UUID and also have users add email and phone_number attributes when signing up. Then to have users login with either email or phone_number + password. And have username only as a unique identifier.

Any input on this? I feel like I'm using Mobilehub totally wrong or my use case with phone_number as login is totally unique. :)

**Comment by 8vius** [comment]
@buggy I have it set up the way you indicate to do as to not allow duplicates, but it still allows duplicates. From what I've been reading what it doesn't allow is having 2 enabled accounts with the same email, when confirming it just moves the alias to the most recent confirmed account and this is done by design by the Cognito team. I keep seeing the sign in workaround everywhere, it seems like a rather silly issue that they haven't solved.

**Comment by Patryk-Szylin** [comment]
@buggy but how can I force unique email address and unique username, and allow users to login with either?

**Comment by Bulletninja** [comment]
I have the same question as @Patryk-Szylin 
We are supposed to trust these providers for auth, that's why we are able to delegate it to them. And the common identifier among them is an email. Shouldn't that be de default behavior? If we trust the providers we know it's basically the same person if the email matches.

**Comment by weaponsforge** [comment]
Thank you so much for the amplify tips and insights. @buggy 's solution worked best for me.

@bsdkurt  can I confirm if the Cognito user pool settings that you've mentioned apply for detecting & blocking the same email registration for Email/Password sign-up only?

> You need to setup your user pool through Cognito Users Pools in the AWS console and select "Email address or phone number" when asked how you want your users to login. Once your pool is setup correctly you won't be allowed to register an account twice with the same email address.
> 
> Do not select "Username" then "Also allow sign in with verified email address". This does what you're experiencing.
> Do not use AWS Mobile Hub as this sets up the pool using "Username" and does what you're experiencing.

I expect Google sign-in to be automatically rejected (or maybe synced to its existing Cognito user _previously registered using Email/Password with the same email (Gmail)_), instead I end up having (2) different Cognito accounts for the Email/Password and Google sign-in (and Facebook, too), even if they're all using the same email.

I'm wondering if this is still an [open issue](https://stackoverflow.com/questions/58811821/aws-cognito-adminlinkproviderforuser-user-pool-account-and-facebook)/[issue2](https://github.com/aws-amplify/amplify-js/issues/565) that cannot be resolved by the said Cognito user pool settings alone? Thanks.

**Comment by hakimio** [comment]
@weaponsforge you need to link users in your Cognito pre-signup hook:
```ts
        await this.cognitoClient.adminLinkProviderForUser({
            UserPoolId: process.env.USER_POOL_ID,
            SourceUser: {
                ProviderName: 'Google',
                ProviderAttributeName: 'Cognito_Subject',
                ProviderAttributeValue: event.userName.split('_')[1]
            },
            DestinationUser: {
                ProviderName: 'Cognito',
                ProviderAttributeValue: existingUser.Username
            }
        }).promise();
```

**Comment by weaponsforge** [comment]
> @weaponsforge you need to link users in your Cognito pre-signup hook:
> 
> ```ts
>         await this.cognitoClient.adminLinkProviderForUser({
>             UserPoolId: process.env.USER_POOL_ID,
>             SourceUser: {
>                 ProviderName: 'Google',
>                 ProviderAttributeName: 'Cognito_Subject',
>                 ProviderAttributeValue: event.userName.split('_')[1]
>             },
>             DestinationUser: {
>                 ProviderName: 'Cognito',
>                 ProviderAttributeValue: existingUser.Username
>             }
>         }).promise();
> ```

Thank you @hakimio, this solved the issue for me regarding Email/Password sign-up followed by a Google (or Facebook) sign-up which uses the same email.

**Comment by kewur** [comment]
> Do not select "Username" then "Also allow sign in with verified email address". This does what you're experiencing.

Selecting username without "Also allow sign in with verified email address" still allows multiple registrations with the same email.
