### ISSUE TITLE
Would like email (at least) to be retrieved from federated identity providers

### ISSUE THREAD

**Issue by ceich** [aws/aws-amplify#376]
Feature Request

Current behavior: when the user authenticates with Facebook, even though the requested scope includes email, the `/me` request made by `withFacebook` defaults the params, which returns only `name` and `id` fields. The resulting `user` object has only those attributes.

I would like to use federated logins to infer my user's identity, and need a stable user id. Lacking any imagination, I would like to use the user's email address. (The app supports all three federated providers, and choosing a different provider results in a different identity pool user id, whereas the email is the same in each provider.)

**Comment by ceich** [comment]
After further thinking I believe I need to use the Federated feature of User Pool itself, which seems to imply hosted login UI.

If this is true, aws-amplify would be out of the picture, at least as far as my needs go.

**Comment by powerful23** [comment]
Closing this issue.
