### ISSUE TITLE
Change Theme UI to allow a simple CSS stylesheet and a blank theme

### ISSUE THREAD

**Issue by Prefinem** [aws/aws-amplify#38]
With the theme setup as it is, it is difficult to extend the styling with css without writing a blank theme.

I have created a branch that provides a blank theme with the default CSS style sheet here https://github.com/aws/aws-amplify/compare/master...Prefinem:master as an example

**Comment by mlabieniec** [comment]
@Prefinem thanks for the feedback we are working on updating this to allow for styling with css, it is part of the backlog and should be released in the next couple sprints, thanks for the example branch.
