### ISSUE TITLE
Is it possible to send custom messages to pinpoint analytics?

### ISSUE THREAD

**Issue by ildar-icoosoft** [aws/aws-amplify#386]
I need to send error reports to pinpoint analytics. Is it possible to do it using aws-amplify HUB?

**Comment by mlabieniec** [comment]
@ildar-icoosoft sure you could do this, with Hub you can just dispatch events at any point and handle them appropriately: https://aws.github.io/aws-amplify/media/hub_guide.html

So if you handle events, with something like a try / catch you could just record the event, perhaps in an error handler class that retrieves all the errors with hub

```js
try {
 // something
} catch(e) {
 Hub.dispatch('error', { event: 'something', data: {} }, 'Error');
}
```

Then perhaps in your ErrorClass

```js
onHubCapsule(capsule) {
        const { channel, payload, source } = capsule;
        Analytics.record('SomeError', payload);
    }
```

**Comment by ildar-icoosoft** [comment]
Thank you very much!
