### ISSUE TITLE
Is it possible to add custom messages from Password Reset email flow

### ISSUE THREAD

**Issue by RameshRM** [aws/aws-amplify#387]
Hi, 
I am using `cognito pwd reset ` flow and Custom Message triggers from API Gateway ingress. I want to pass along the `http header` value to the Custom Message trigger. Can you point me how i can achieve that if thats a valid option. My basic request is to pass a HTTP Request Header from API Gateway and pass it along to the Custom Message trigger in Cognito Flow. 

Any Suggestions ?

**Comment by mlabieniec** [comment]
@yuntuowang any suggestions on this?

**Comment by yuntuowang** [comment]
Hi @RameshRM, I am not entirely we have this feature now. 
About custom message, Amazon Cognito invokes this trigger before sending an email or phone verification message or a multi-factor authentication (MFA) code, allowing you to customize the message dynamically. Static custom messages can be edited in the Message Customizations tab of the Amazon Cognito console.

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html
