### ISSUE TITLE
Using FederatedSignIn in with aws-amplify-react-native

### ISSUE THREAD

**Issue by marioskonstantinou** [aws/aws-amplify#39]
Hello. I couldn't find any examples with Federated Identities sign in using only the aws-amplify-react-native. Would it be possible to use FederatedSignIn of aws-amplify-react in a react-native mobile app? If yes, what would be the best way of doing this? If not what's the alternative? Thanks

**Comment by mlabieniec** [comment]
@marioskonstantinou Federated auth is currently in our backlog and should be available within the next couple releases, if not next release. 

Alternatively, the cognito js sdk provides a federated example (federated identities go on the "Logins" parameter): https://github.com/aws/amazon-cognito-identity-js, see use case #4, and docs here: http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-identity-federation.html.

Currently federated identities is in this sprint, so we are hoping to get this out within the next couple weeks!

**Comment by brickolicious** [comment]
Any updates on this functionality?

**Comment by bharat-tiwari** [comment]
when is federated identity likely to be introduced for aws-amplify-react-native?

**Comment by ASteinheiser** [comment]
Seems to be released, but I am experiencing token expiration issues with FB logins. The fb token has a long expire time, but for some reason, getting "Access Denied" on my API requests after a little while. Almost seems like the aws token is failing to refresh my fb access token.
