### ISSUE TITLE
Is it possible to get cognito user attributes in Lambda/cloud logic ?

### ISSUE THREAD

**Issue by daannijkamp** [aws/aws-amplify#390]
Do you want to request a feature or report a bug? 
**question**

Is it possible to get user attributes (like email) in a Lambda/cloud logic function. (with a Authenticated request).
I'm only getting the: "cognitoIdentityPoolId", "cognitoIdentityId", "accessKey", "cognitoAuthenticationType", "cognitoAuthenticationProvider", "user"

What is the expected behavior?
Get the user attributes in any form (jwt/idToken, user session) in the Lambda Event object

**Comment by mlabieniec** [comment]
@daannijkamp you won't receive the attributes via context, you would need to call the cognito api with the provided info to retrieve anything like that. You can retrieve it via the aws-sdk via the lambda function:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#getUser-property

**Comment by daannijkamp** [comment]
Do I need send the AccessToken from the Front-end to the backend manually (API HTTP header)? 
I’m clearly missing something :-(

**Comment by mlabieniec** [comment]
no you do not. The lambda function just needs permission to access that via it's IAM role
https://docs.aws.amazon.com/lambda/latest/dg/intro-permission-model.html

**Comment by daannijkamp** [comment]
I need an AccessToken (or Username) to get user attributes for a specific user with the CognitoIdentityServiceProvider. 
For example: ([aws-mobile-react-sample](https://github.com/awslabs/aws-mobile-react-sample)) I want to email the WebApp Authenticated user if they inserted a restaurant.
Is this possible with a default signed/authenticated  Amplify API get request?

**Comment by ldgarcia** [comment]
@daannijkamp, you need to grant permission to your Lambda through an IAM role:

Example using the Serverless Framework:

`serverless.yml`:
````yaml
  iamRoleStatements:
    - Action:
        - cognito-idp:AdminGetUser
      Resource: ${self:custom.extra.cognito.userPoolArn}
      Effect: Allow
````

`Lambda function`:
````javascript
 try {
    const user = await cognito.adminGetUser({
      UserPoolId: process.env.COGNITO_USER_POOL_ID,
      Username: userId,
    }).promise()
}
...
````

**Comment by willmtl** [comment]
Thank you I have been looking everywhere for this. Wish it was in context tho.

**Comment by powerful23** [comment]
Closing the issue.

**Comment by AlexThomas90210** [comment]
I have been looking around for a while, I feel the answers here didn't really answer the problem, which is getting the user's attributes or username who made the request. 

The example above only shows how to get a user's attributes if you already have their Username, but that won't be the case. Unless the client sends up that information 

```javascript
const AWS = require('aws-sdk');
// Note, make sure you have proper credentials, uncomment following code to set credentials if running file locally
// var myConfig = new AWS.Config({
//     credentials: {
//         accessKeyId: "XXXXXXXXXXXXX",
//         secretAccessKey: "XXXXXXXXXXXXXXXXXXXXXXX"
//     }
// });

// Set proper region
let cognitoClient = new AWS.CognitoIdentityServiceProvider({ region: 'eu-west-1' });


// Event object is the event passed to Lambda
async function getUserOfAuthenticatedUser(event) {
    // Get the unique ID given by cognito for this user, it is passed to lambda as part of a large string in event.requestContext.identity.cognitoAuthenticationProvider
    let userSub = event.requestContext.identity.cognitoAuthenticationProvider.split(':CognitoSignIn:')[1]
    let request = {
        UserPoolId: 'xxxxxxxxxx', // Set your cognito user pool id
        Filter: `sub = "${userSub}"`,
        Limit: 1
    }
    let users = await cognitoClient.listUsers(request).promise();
    console.log("got user:", users[0])
}


// Example with a dummy event object, change the 'YOURUSERSUB' part of the string for which ever user you want to test with
let event = {
    requestContext: {
        identity: {
            cognitoAuthenticationProvider: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:CognitoSignIn:YOURUSERSUB"
        }
    }
}
getUserOfAuthenticatedUser(event);
```

If you want to test this out quickly to see if it works for you, copy this file locally, insert your credentials, region & userpool ID, call a lambda function and console.log the event object, then paste that object instead of the dummy event I have and run the file locally with node <yourfilename> . Then the user who called the lambda function who's object you pasted into this file will be logged into the terminal

**Comment by daannijkamp** [comment]
Thanks @AlexThomas90210 😀!

**Comment by nelyo1** [comment]
i am currently working on getting a lambda  with RESTapi endpoint to return just the IdToken from cognito.
i see there are various node.js implementation on this git page,  but am very new to NODE code so making the lambda a Rest endpoint to respond with IdToken from cognito with GET method is unclear.

am looking for code help/solution on this issue.

Thank you

**Comment by daannijkamp** [comment]
@nelyo1 Are you using Amplify/Cognito JavaScript for the front-end?

**Comment by nelyo1** [comment]
@daannijkamp  
No am not using Amplify JavaScript.

I checked the website, couldn't find any sample code that could be used to return only an IdToken from cognito or any idp.

**Comment by daannijkamp** [comment]
@nelyo1 For an IdToken, a Cognito User needs to be authenticated/have a valid session.  (JavaScript SDK example: [Get the Current User](https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html#using-amazon-cognito-user-identity-pools-javascript-examples-get-user-from-local-storage)). 
IdToken is often used in the Front-End.
Maybe you can explain why you need a Lambda function to return an IdToken? Because of a custom authorizer?

**Comment by nelyo1** [comment]
@daannijkamp,

if i decide to go Amplify/Cognito route how easy will it be to implement a lambda that returns Only an IdToken in the header.

am open to any solution to resolve this issue as long it uses lambda and cognito.

and correct me if am wrong this amplify is pretty new, so it may have better support going forward.

thanks in advance

**Comment by daannijkamp** [comment]
Can you maybe describe what you have/want to make? 
A web app - API gateway - Lambda?
iOS/Android  app - API gateway - Lambda?

**Comment by nelyo1** [comment]
a web app --API gtwy - Lambda  path will be most ideal. --

the idea was to fetch the IdToken of an authenticated user (in cognito) with a web app (possibly using lambda or a container) .

....
console.log('idToken + ' + ret.idToken.jwtToken);
            callback(null, {
                statusCode: 200,
                body: JSON.stringify({
                }),
                headers: {
                    'Content-Type':'application/json',
                    'Authorization': ret.idToken.jwtToken,
                },
            });


the resulting Token returned in the header will be used to **monitor** other API endpoints (micro services)  that requires Token Authentication.

**Comment by stevemao** [comment]
@ldgarcia how do you get `userId` in your example?

**Comment by stevemao** [comment]
> no you do not. The lambda function just needs permission to access that via it's IAM role
> https://docs.aws.amazon.com/lambda/latest/dg/intro-permission-model.html

You are not answering the question. how to get `AccessToken` then?

**Comment by ldgarcia** [comment]
@stevemao 
In order to call `adminGetUser` you need to know the `username`. [I configured my pool](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-usernames) to use the email address as an alias, and the `username` to be created automatically. In this case the `username` is the same as the userId (`sub`).

My Lambda function receives the `sub` attribute in the payload:

````
{
   "triggerSource": "PostConfirmation_ConfirmSignUp",
   "request": {
      "userAttributes": {
         "sub": "cf2509d6-0c1c-476b-b8ec-c45858bdc045",
         "email_verified": "true",
         "cognito:user_status": "CONFIRMED",
         "cognito:email_alias": "john@doe.com",
         "name": "John",
         "phone_number_verified": "false",
         "phone_number": "+50688888888",
         "locale": "es-CR",
         "family_name": "Doe",
         "email": "john@doe.com"
      }
   }
}
````

````
const userId = event.request.userAttributes.sub
````

Can you post the event payload that you are receiving?

**Comment by stevemao** [comment]
I'm using Mobile Hub and it uses express when I generate a CRUD on my dynamoDB. Here's what I have for my `event` object:

```js
{
    ....
    "headers": {
      ...
    },
    "queryStringParameters": null,
    "pathParameters": null,
    "stageVariables": {
        "stage": "Development"
    },
    "requestContext": {
        ...,
        "identity": {
            "cognitoIdentityPoolId": "ap-southeast-2:XXXX",
            "accountId": "XXXXX",
            "cognitoIdentityId": "ap-southeast-2:XXXX",
            "caller": "XXXX:CognitoIdentityCredentials",
            "sourceIp": "XX.XX.XX.XX",
            "accessKey": "XXXXXXXXXX",
            "cognitoAuthenticationType": "authenticated",
            "cognitoAuthenticationProvider": "cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_XXXX,cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_XXXX:CognitoSignIn:XXXX",
            "userArn": "arn:aws:sts::XXXX:assumed-role/XXXX/CognitoIdentityCredentials",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
            "user": "XXXX:CognitoIdentityCredentials"
        },
        "apiId": "XXXX"
    },
    "body": "{\"title\":\"hello\",\"content\":\"world\"}",
    "isBase64Encoded": false
}
```

**Comment by vahdet** [comment]
@ldgarcia How about getting `"cognito:user_status"` as it contains a **colon(:)**?

    const userStatus = event.request.userAttributes.cognito:user_status

It should not be like that.

**Comment by ldgarcia** [comment]
@vahdet You shoud use square bracket notation: `const userStatus = event.request.userAttributes['cognito:user_status']`

**Comment by M-Younes** [comment]
Any reason why the `Created` value is not being sent?
e.g `event.request.userAttributes.Created` 
and if so any idea of how do I get the created date for the user?

**Comment by ashamalla** [comment]
Do you have an example of getting the user attributes (email) in swift (IOS) using list user.

I need to find retrieve a user email based on cognito userid?

thanks in advance

**Comment by daannijkamp** [comment]
@ashamalla “List Users” is for Cognito admin related purposes. 
You will probably need the “Get Current User” method http://aws.github.io/aws-sdk-ios/docs/reference//Classes/AWSCognitoIdentityUserPool.html#//api/name/currentUser

**Comment by daannijkamp** [comment]
Anything you store in cognito is accessible only to the user him/her self.
You will probably need to save for example “Seller-Buyer” relationships somewhere else (like DynamoDB).
If you need to get user attitudes from other users, you can make a backend api that uses the Cognito Admin parts.

**Comment by ashamalla** [comment]
Thanks I’ve succeeded in getting the user name however I can’t get the email. 
I’m using user.getdetails() !!! I’ve also set the attributes to be read (but not writing on cognito ) with no luck???

**Comment by ashamalla** [comment]
Here is My code.
if let username = pool.currentUser()?.username {
                print("Username Retrieved Successfully: \(username)") // prints the right username
               
                
         let  users = pool.getUser().getDetails()
                print(users)
                
                let  user = pool.getUser()
             
                
                user.getDetails().continueWith(block: { (task) -> Any? in
                    guard task.result != nil else {
                        
                        print(task.result) //Always Prints/Returns Nil
                        
                        return nil
                    }
//Never Reaches
                    let userAttributes = task.result?.userAttributes
                    userAttributes?.forEach({ (attribute) in
                        print("Name: " + attribute.name!)
                    })
                    DispatchQueue.main.async {
                       // self.setAttributeValues()
                    }
                    return nil
                })

**Comment by ToddHoff** [comment]
> I have been looking around for a while, I feel the answers here didn't really answer the problem, which is getting the user's attributes or username who made the request.

Is this lambda triggered through the API gateway? I don't see any of those parameters when I call lambda directly. I'm looking for a way to get the user when calling lambda directly. Having to pass it in the payload seems very insecure.

**Comment by daannijkamp** [comment]
@ToddHoff yes, the lambda function is triggered by API Gateway. The reason I got the parameters is because API Gateway has an Authorizer for Cognito (https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html).

**Comment by daannijkamp** [comment]
@ToddHoff can you describe how a user can directly call a lambda function? With the aws-sdk? Like https://aws-amplify.github.io/docs/js/authentication#working-with-aws-service-objects ?

**Comment by troygoode** [comment]
This is super frustrating. This is what I'm currently using to get access to a User Pool user in an authenticated REST API generated by Amplify CLI (based upon the code @AlexThomas90210 posted above):

```javascript
app.post('/my-api', async (req, res, next) => {
  try {
    const IDP_REGEX = /.*\/.*,(.*)\/(.*):CognitoSignIn:(.*)/
    const authProvider = req.apiGateway.event.requestContext.identity.cognitoAuthenticationProvider
    const [,, userPoolId, userSub] = authProvider.match(IDP_REGEX)

    const cognito = new aws.CognitoIdentityServiceProvider()
    const listUsersResponse = await cognito.listUsers({
      UserPoolId: userPoolId,
      Filter: `sub = "${userSub}"`,
      Limit: 1
    }).promise()
    const user = listUsersResponse.Users[0]

    // now I can actually do stuff...
    const myCustomAttribute = user.Attributes.find((a) => a.Name === 'custom:myCustomAttribute').Value
    res.json({})
  } catch (err) {
    console.error(err)
    next(err)
  }
})
```

It should really be much easier than this.

**Comment by ChristopherPeterson** [comment]
Can I ask a question? What is the harm in using the Cognito auth option in API Gateway, and passing the idToken up in the Amplify API.get/post headers?

This works, as I have tested it out in my app. 

And from my knowledge I don’t see a security risk. The JWT is secured via a hash from being tampered, and it is easily accessible to the end user from the JS code/console. 

Thanks!

**Comment by daannijkamp** [comment]
@ChristopherPeterson Do you [verify](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html) all JWT Tokens/id tokens in the backend? This is the only way you can trust any claims inside the ID token.

**Comment by ChristopherPeterson** [comment]
I could, but I would like to assume API Gateway should be doing this in order to authorize any request coming in. 

If that’s not true, then I wonder what the use is of API Gateway’s Cognito auth option.

**Comment by ChristopherPeterson** [comment]
In our Rails app I had to roll my own auth, so besides (1) asking Cognito if the token is valid it (2) checks the JWS. 

I would hope that API Gateway does (1), so I could always add (2) to a Lambda layer.

**Comment by RyanHow** [comment]
I have a question about extracing the cognito user sub using `req.apiGateway.event.requestContext.identity.cognitoAuthenticationProvider`

Where does this information come from, and is it verified or can it be spoofed? I'm concerned it is just passed through as some signed content from the calling user.

Can anyone point me in the right direction for some docs on understanding the authorization flow when using the IAM Authorizer?

Is there a best practice guide somewhere on this? I don't like to copy paste security related code unless I know what it's doing!

The other side effect is that every single call means another call to cognito to get the user details. It seems like it would be better practice to get it from the claims and lighten the load?

**Comment by janhesters** [comment]
@daannijkamp Do you happen to know how to get the user for a given request in AWS Amplify? (See https://github.com/aws-amplify/amplify-js/issues/3440 for full context). Thank you, if you do (or anyone else does).

**Comment by janhesters** [comment]
@troygoode Did you found a better way in the meantime?

**Comment by troygoode** [comment]
@janhesters The backend stuff for Amplify is so poorly baked that I had to abandon it. I still use `amplify-js` on the front-end only, but generate the backend via Serverless (https://serverless.com/). I've been very happy since switching a couple of months ago.

**Comment by janhesters** [comment]
@troygoode Thanks for answering so fast and letting me know. I agree, there is still a lot that's missing for Amplify. Would this be more easy using serverless?

**Comment by troygoode** [comment]
@janhesters Yes. It "just worked" with Serverless (if you use `amplify-js` on the frontend to properly pass the Cognito tokens over with the inbound request).

**Comment by janhesters** [comment]
@troygoode Thank you.

**Comment by ToddHoff** [comment]
> @daannijkamp Do you happen to know how to get the user for a given request in AWS Amplify? (See #3440 for full context). Thank you, if you do (or anyone else does).

I use amazon-cognito-identity-js directly instead of using Amplify. You can grab user data from the JWS tokens. I pass in the tokens with each request and verify in the lambda functions. If you use API gateway this information can be found in the context.

**Comment by janhesters** [comment]
@ToddHoff Thank you for your help. Could you please code up a quick example? I'm new to Lambda and serverless and don't really understand you answer.

**Comment by ToddHoff** [comment]
There is nothing quick about this stuff :-) I've spent weeks trying to
figure out how to make a real web app work end-to-end and I still don't
have confidence I have it right.

This is my biggest complaint about this stuff. There are no end to end code
examples that show how to build a bullet proof secure web app.

I tried to attach some files but google blocked them for security reasons.
Email me at toddhoffious@gmail.com and I'll try to help. My web client code
is all tangled up but the lambda code is reusable.

**Comment by zepelega** [comment]
> @stevemao
> In order to call `adminGetUser` you need to know the `username`. I configured my pool to use the email address as an alias, and the `username` to be created automatically. In this case the `username` is the same as the userId (`sub`).


Please, how do you configure the pool to create the username automatically as a sub? I can't fing anyware...

**Comment by stevemao** [comment]
@zepelega you should probably ping @ldgarcia

**Comment by zepelega** [comment]
> @zepelega you should probably ping @ldgarcia

True, I'm sorry man.

**Comment by zepelega** [comment]
@ldgarcia Please, can you tell me how do you configure the pool to create the username automatically as a sub? I can't fing anyware...

**Comment by lopezdp** [comment]
> There is nothing quick about this stuff :-) I've spent weeks trying to figure out how to make a real web app work end-to-end and I still don't have confidence I have it right. This is my biggest complaint about this stuff. There are no end to end code examples that show how to build a bullet proof secure web app. I tried to attach some files but google blocked them for security reasons. Email me at toddhoffious@gmail.com and I'll try to help. My web client code is all tangled up but the lambda code is reusable.
> […](#)

lol gotta put in the work man! you'll get it soon enough just dont quit

**Comment by lopezdp** [comment]
> @daannijkamp, you need to grant permission to your Lambda through an IAM role:
> 
> Example using the Serverless Framework:
> 
> `serverless.yml`:
> 
> ```yaml
>   iamRoleStatements:
>     - Action:
>         - cognito-idp:AdminGetUser
>       Resource: ${self:custom.extra.cognito.userPoolArn}
>       Effect: Allow
> ```
> 
> `Lambda function`:
> 
> ```js
> const AWS = require('aws-sdk')
> const cognito = new AWS.CognitoIdentityServiceProvider({apiVersion: '2016-04-18'})
> 
> ...
> 
>  try {
>     const user = await cognito.adminGetUser({
>       UserPoolId: process.env.COGNITO_USER_POOL_ID,
>       Username: userId,
>     }).promise()
> 
>   console.log(user.UserAttributes)
> }
> ...
> ```

@ldgarcia ldgarcia

My problem with this is that my service is deployed on CICD before my cognito service is deployed.

How do I give the `Resource` block in my `serverless.yml` file the correct permission without knowing the Cognito `arn` since my cognito service is deployed last?

Can I give it a permission based on the fact that the user is already authenticated once this service is running?

Thanks!!

**Comment by ivenxu** [comment]
> @daannijkamp, you need to grant permission to your Lambda through an IAM role:
> 
> Example using the Serverless Framework:
> 
> `serverless.yml`:
> 
> ```yaml
>   iamRoleStatements:
>     - Action:
>         - cognito-idp:AdminGetUser
>       Resource: ${self:custom.extra.cognito.userPoolArn}
>       Effect: Allow
> ```
> 
> `Lambda function`:
> 
> ```js
> const AWS = require('aws-sdk')
> const cognito = new AWS.CognitoIdentityServiceProvider({apiVersion: '2016-04-18'})
> 
> ...
> 
>  try {
>     const user = await cognito.adminGetUser({
>       UserPoolId: process.env.COGNITO_USER_POOL_ID,
>       Username: userId,
>     }).promise()
> 
>   console.log(user.UserAttributes)
> }
> ...
> ```

Do you have any sample which gets cognito user information in lambda function implemented by [amplify function](https://docs.amplify.aws/cli/function)?

**Comment by morgler** [comment]
Is there a less verbose way of accessing the Cognito user in a lambda? 

Initially I expected to find the Cognito user sub in the event or ENV passed to the Lambda, if everything (Cognito, API, Lambda) were created via Amplify CLI. It seems while the API Gateway and the Lambda certainly HAVE the information about the calling user, we still have to extract it tediously from the event and Cognito user pool (see @troygoode's code).

Is there any update or are there plans to simply provide the Cognito user (or at least their sub) to a lambda function protected by Cognito auth?

**Comment by theslyone** [comment]
@morgler checkout https://medium.com/@jan.hesters/how-to-access-the-user-in-lambda-functions-with-amplify-4f531dc6af51. Describes adding this functionality as an express middleware in your lambda function

**Comment by lopezdp** [comment]
> Thank you I have been looking everywhere for this. Wish it was in context tho.

Ive had it on SO for months now, here's a solution you can use to get both user attributes AND CUSTOM user attributes. Give it an UpVote if it works for ya!

https://stackoverflow.com/a/59973919/3879359
