### ISSUE TITLE
aws-amplify Storage does not support all s3 functions

### ISSUE THREAD

**Issue by ildar-icoosoft** [aws/aws-amplify#397]
aws-amplify supports only few s3 functions: put, get, remove, list. What about the other methods, for example [s3.getObjectTagging](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObjectTagging-property)

**Comment by mlabieniec** [comment]
@ildar-icoosoft you can interact with all the lower level sdk services once authenticated:
https://aws.github.io/aws-amplify/media/quick_start.html#aws-services
