### ISSUE TITLE
Documentation wrong Storage.md

### ISSUE THREAD

**Issue by elsenhuc** [aws/aws-amplify#40]
In storage.md the configuration indicates to specify identitypoolid within the Storage options. This does not work - one needs to specify this within AUTH - otherwise amplify throws an error. I guess just a bug in the docu .

**Comment by mlabieniec** [comment]
@elsenhuc thanks for the find, the [doc](https://github.com/aws/aws-amplify/blob/master/media/storage_guide.md) shows IdentityPoolId on Auth config, let us know if you see anything else.
