### ISSUE TITLE
Question: access token from federated login ?

### ISSUE THREAD

**Issue by vsrivatsan89** [aws/aws-amplify#402]
I notice that after a user logs in with a federated identity provider, setCredentialsFromFederation() sets the provider, token, user as part of the AWS.config (https://github.com/aws/aws-amplify/blob/36acdc9/packages/aws-amplify/src/Auth/Auth.ts#L725 ). How do I access the token returned from the identity provider, should I just get it from the local storage key 'federatedInfo'?

**Comment by buggy** [comment]
@vsrivatsan89 If I understand your question correctly then the [AppSync documentation](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-react.html) indicates you can use `Auth.currentCredentials()`. They use that to get credentials when AppSync authentication is set to IAM.

**Comment by vsrivatsan89** [comment]
Hey @buggy , If I understand correctly, `Auth.currentCredentials()` in turn just calls the `Auth.setCredentialsFromFederation()`. It doesn't give me access to the token. Am I mistaken?

**Comment by mlabieniec** [comment]
@vsrivatsan89 Auth.currentCredentials() will return you a [CognitoIdentityCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html) object. This will contain a [WebIdentityCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/WebIdentityCredentials.html) object which you can then retrieve the [Logins] from for your identity providers i.e. google/facebook etc.

So, for example, to retrieve a google token:

```js
async getCreds() {
    let credentials = await Auth.currentCredentials(),
         token = credentials.webIdentityCredentials.params.Logins['accounts.google.com'];
    
    console.log(token); // here is your token
}
```

**Comment by vsrivatsan89** [comment]
@mlabieniec Awesome! Also does this token get renewed automatically? They are short lived tokens correct? Does Aws-amplify do the refreshing of tokens underneath?

**Comment by mlabieniec** [comment]
@vsrivatsan89 the auto-refresh is in pr:
https://github.com/aws/aws-amplify/pull/191

Currently there is a bit of an issue on the facebook side, but we are working to get this pushed out asap.

**Comment by vsrivatsan89** [comment]
@mlabieniec In the mean time, I should just log my user out after the token expires?

**Comment by mlabieniec** [comment]
Yea if you follow that PR, you can basically request a new token similar to that, and Authenticate again, but something is up on the facebook login. Or yes, just require re-login.

**Comment by mlabieniec** [comment]
this enhancement has been released
