### ISSUE TITLE
Top suggestions for improving the documentation / examples

### ISSUE THREAD

**Issue by jfo8000** [aws/aws-amplify#411]
I have just finished getting this up and running, and I have had a mix of tearing my hair out and joy.  Here are my top things I wish the documentation was more clear on.

1. The difference between withAuthenticator and &lt;Authenticator&gt;

withAuthenticator(Component) detects if you are signed in in or not. If you are signed in, it shows your component.  If you're not signed in, it renders the <Authenticator> tag.  

The  &lt;Authenticator&gt; tag will always show all its children, regardless of sign in state, and its children decide whether to render or not. (See #3).    

TIP: if you are struggling with getting the right stuff passed into Authenticator from the withAuthenticator function, you can copy the code from withAuthenticator into your own project and then debug through it to get a better idea of how it all works.
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/src/Auth/index.jsx

2.  Best practice for using with a routed react application.

It would be good to have a sample app where some parts of your application are authenticated and some parts are not.  E.g. I've got an app where some pages need to be logged in, but most do not.  I also need my header and footer to show on every page, so I don't lose my branding when I pop into the Authenticator dialog.  The common code in every example of wrapping App with withAuthenticator(App) is incorrect for this situation as it would lock all the pages out and have no site branding.

3. How the children of  &lt;Authenticator&gt; work.

You can pass in a bunch of random tags into Authenticator and they seem to appear by magic.  The magic is the authState.  The AuthPieces (like SignIn, SignUp) listen to the authState and choose whether to render.

Amplify comes with prebuilt AuthPieces you can use, and  &lt;Authenticator&gt; has them all in it's 'default' list of children.  If you want to replace some or all of the children, you need to hideDefault so it doesn't render it's own.  Then you pass in your own set of auth pieces, that listen to authState and decide what to do. You can also just pass back in the tags you wanted to use out of Amplify, but just replace one.

These pieces can also be passed into the withAuthenticator as an array.

4. You can change the words on the built in dialogs (like 'Sign In' and 'Sign Up') by providing your own dictionary to the localization engine.  This is in addition to the error map.   

     import { I18n } from 'aws-amplify';
     
     const authScreenWords = {
          en: {
               'Sign Up': 'Create new account',
               'Sign Up Account': 'Create a new account'
          }
      };

      I18n.setLanguage('en');
      I18n.putVocabularies(authScreenWords);

5. Shout out to these projects
https://www.npmjs.com/package/aws-amplify-react-bootstrap
https://github.com/richardzcode/a-theme-react

**Comment by mlabieniec** [comment]
Thank you @jfo8000 for the excellent feedback and patience! We will get the docs updated with your suggestions.

**Comment by mlabieniec** [comment]
@jfo8000 can you let us know if our new docs and updates address your issues? Please feel free to reopen if you feel we should fix anything. Thanks!
