### ISSUE TITLE
how to use withFacebook() HOC?

### ISSUE THREAD

**Issue by Gribbs** [aws/aws-amplify#413]
The documentation is not very clear on how to use the withFacebook() HOC. Even after guessing how it might work, I can't see anything on the UI to allow a login via FaceBook. Here's my current App.js

```
import React, { Component } from 'react';
import Amplify from 'aws-amplify';
import { withAuthenticator, withFacebook } from 'aws-amplify-react';
import aws_exports from './aws-exports';
import logo from './logo.svg';
import './App.css';

Amplify.configure(aws_exports);

class App extends Component {
  render() {
    console.log(this.props)
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default withFacebook(withAuthenticator(App, { includeGreetings: true }), {facebook_app_id: '174036433240750'});

```

After this, the ui looks like it always did, there's no button anywhere on the signup form to allow login with FaceBook:

<img width="312" alt="screen shot 2018-03-07 at 5 39 15 pm" src="https://user-images.githubusercontent.com/4126269/37077312-828a6f26-222e-11e8-8f86-0e799cb4e13d.png">

 I'm totally guessing how to pass the FaceBook app id into the method. How do you pass the FaceBook app id into the withFacebook() HOC? What Component does that give you that you don't get otherwise?

To be clear I want to use withAuthenticator() AND withFacebook() HOC as I want to use the default signin, signup forms but want to support FaceBook Login as well. The documentation seems to suggest that adding withFacebook() will give you some kind of default component to work with.

**Comment by mlabieniec** [comment]
@Gribbs so if you would like to use the `<Authenticator />` component, you would just do something like (per [docs](https://aws.github.io/aws-amplify/media/authentication_guide.html#6-federated-identity)):

```js
import { Authenticator } from 'aws-amplify-react';
let federated = {
    'google_client_id': '...',
    'facebook_app_id': '...',
};
<Authenticator federated={federated} />
```

That will render based on the federated object you pass in the entire authenticator component.

If you only want to render a Facebook Signin button, you would then need to pass into your app just the 'facebook_app_id' into your main <App /> component, for example in index.js of a new react app:

```js
<App facebook_app_id="..." />
```

Then within App.js 

```js
import { withFacebook, FacebookButton } from 'aws-amplify-react';

// then in render()

render() {
   return (
      <div> <FacebookButton /> </div>
   );
}

// then export your app

export default withFacebook(App);
```

This would render ONLY a facebook signin button and allow you to customize your UI.

You could also use the [HOCs](https://aws.github.io/aws-amplify/media/authentication_guide.html#6-federated-identity) to customize as well.

**Comment by Gribbs** [comment]
I only wanted to use the HOC but there’s no examples for doing that. Thanks anyway. I wasnt aware of the FaceBook component so it’s been helpful

**Comment by Jun711** [comment]
Hi @Gribbs, just wonder if you could share a screenshot of the UI with FaceBook login button when u have it working. thanks.

**Comment by Gribbs** [comment]
for the benefit of anyone else coming across this issue., this got me working:

index.js:
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import { Authenticator } from 'aws-amplify-react';

ReactDOM.render(
  <Authenticator federated={{facebook_app_id:"174036433240750"}}>
    <App />
 </Authenticator>, document.getElementById('root'));
registerServiceWorker();
```

App.js:

```
import React, { Component } from 'react';
import Amplify from 'aws-amplify';
import { withAuthenticator, withFacebook} from 'aws-amplify-react';
import aws_exports from './aws-exports';
//import { Logger } from 'aws-amplify';
import logo from './logo.svg';
import './App.css';

window.LOG_LEVEL = 'DEBUG';

Amplify.configure(aws_exports);

class App extends Component {

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}
export default App;
```
After this
![screen shot 2018-03-12 at 12 29 31 pm](https://user-images.githubusercontent.com/4126269/37261496-0c9ad7e4-25f1-11e8-8723-cda0acbd11b1.png)
:
