### ISSUE TITLE
Cache.setItem expects a string value, not an object

### ISSUE THREAD

**Issue by rlmartin** [aws/aws-amplify#424]
Do you want to request a feature or report a bug? Bug

What is the current behavior?
When calling `Cache.setItem`, I believe the `value` argument (the second argument) must be a string. This is just a guess because when calling `Cache.getItem`, JSON.parse fails with an `object` error. Specifically, I believe this line needs to wrap the second argument with `JSON.stringify`: https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L721. I've tested this locally on an app that implements Facebook login and it resolves this issue.

I can submit a PR with a fix, but am having trouble running `npm run build` in the `aws-amplify` package. Any correct build instructions would be appreciated. 

What is the expected behavior?
To not get an error when pulling an object via `Cache.getItem`.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions? Latest aws-amplify (0.2.9) and aws-amplify-react-native (0.2.5).

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by buggy** [comment]
@rlmartin See https://github.com/aws/aws-amplify/wiki/Local-Development for instructions on how to build it locally. You need to be using yarn instead of npm.

**Comment by rlmartin** [comment]
Cool, thanks - I'll work on a PR.
