### ISSUE TITLE
Is it possible to use Authenticator for app with both authenticated and un-authenticated pages?

### ISSUE THREAD

**Issue by cdellinger** [aws/aws-amplify#427]
When using Authenticator in a react app, is it possible to utilize it in such a way that you can specify some pages as requiring authentication and other pages as not requiring it?  Ideally I was hoping to be able to wrap pages requiring authentication within my app.js inside the router.  If there is such a capability, is there an example of this being done somewhere?  All the examples I've found to date authenticate all pages.

**Comment by mwarger** [comment]
Yes, this is possible.  You can place the `<Authenticator>` component on any page and use it to authenticate.  Then, you can use the `onStateChange()` prop to set a variable when the user has signed in, and utilize that state throughout your app (or routes) to control access.  

When you app initiailizes, you can use `await Auth.currentAuthenticatedUser()` to see if there is an authenticated user and set your application state accordingly.

**Comment by mwarger** [comment]
@cdellinger - If it helps, I've written an article about this situation [here](https://medium.com/@mwarger/barebones-authentication-with-aws-amplify-a0961e5b91fb)

Perhaps it can help others that come across this issue.
