### ISSUE TITLE
Question: How to add pinpoint to existing react app?

### ISSUE THREAD

**Issue by genestd** [aws/aws-amplify#429]
I would like to configure Pinpoint analytics for an existing AWS React app.  First I set up a Pinpoint project in the AWS console.  Then I added the aws-amplify package with yarn.  Then I tried to add Amplify to my project with:
```
Amplify.configure(
    Analytics: {
    // OPTIONAL -  Amazon Pinpoint App ID
        appId: config.pinpointApp,
    // OPTIONAL -  Amazon service region
        region: config.pinpointRegion,
    },
    Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
        identityPoolId: config.identityPool,
    // REQUIRED - Amazon Cognito Region
        region: config.region,
    // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: config.userPool,
    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: config.appClient,
        cookieStorage: {
        // REQUIRED - Cookie domain (only required if cookieStorage is provided)
            domain: config.domain,
        // OPTIONAL - Cookie path
            path: '/',
        // OPTIONAL - Cookie expiration in days
            expires: 365,
        // OPTIONAL - Cookie secure flag
            secure: true
        }
    }
)
```
I'm not seeing any updates in the PinPoint analytics console.  Is it possible to add Amplify Analytics to an existing project that wasn't created in the AWS Mobile Hub?  If so, can you point me to an example of how to set it up?

**Comment by nidsharm** [comment]
Hi @genestd ,

Can you please share your code snippet of how you are using Amplify for Pinpoint Analytics? 
Also, it sometimes takes a few minutes before your metrics start showing up on Pinpoint console.

**Comment by genestd** [comment]
HI @nidsharm,

I did try to force the update and collect an event, but I didn't see any network activity in the console:
```
Analytics.updateEndpoint({
// OPTIONAL -  Amazon Pinpoint App ID
    appId: config.pinpointApp,
// OPTIONAL -  Amazon service region
    region: config.pinpointRegion,
})
Analytics.record('sign in')
```

However, I did not expect to need specific code for the user session analytics because the docs say: 

> After configuration, user session metrics are automatically collected and sent to Amazon Pinpoint

**Comment by nidsharm** [comment]
Can you add : window.LOG_LEVEL='DEBUG'; to the file where you configure Amplify ? This will show you the Amplify debug logs and should help you find where it might be erroring out.

**Comment by genestd** [comment]
That did give me some messages, but they aren't particularly helpful.  This one seems pertinent:
> AnalyticsClass - Do not have appId yet.

I am passing the appId in the config object (tried hard-coding it too).  

A more basic question: Is it even possible to just add Pinpoint analytics to a web app that was not created through the AWS mobile hub?

**Comment by powerful23** [comment]
@genestd we are sorry that the documentaion seems to be incorrect to configure the Amplify. I think you should configure the library by ```Amplify.configure({ Analytics: {}, Auth: {} })```. We will fix the doc later on. Thanks!

**Comment by Jun711** [comment]
Hi @genestd, when you set up a Pinpoint project in the Mobile Hub in AWS console, how did you point that project to your existing project?

**Comment by richardzcode** [comment]
@Jun711 

https://docs.aws.amazon.com/pinpoint/latest/apireference/rest-api-endpoints.html

> An endpoint uniquely identifies a mobile device, email address, or phone number that can receive a message. You can use this resource to create or update endpoints.

**Comment by genestd** [comment]
@Jun711 - I created a project in AWS Mobile Hub, and it automatically provisioned the Pinpoint project.  The Mobile Hub also provisioned a Cognito Identity Pool.  I set my existing Cognito User Pool as a provider for the Identity Pool so that when I log into my app, an identity is created in the new pool (which I assumed was connected to Pinpoint).  I also updated the Analytics properties in my Cognito User Pool to reference the Pinpoint project.

Even with these changes, I couldn't see any activity in Pinpoint.

**Comment by Jun711** [comment]
@richardzcode we have to programmatically collect that and update endpoint for each device to uniquely identify them?

@genestd Was it Cognito identity pool or use pool? I don't see analytics section under identity pool
What about your IAM role for analytics on your Cognito user pool?

**Comment by genestd** [comment]
My app uses a Cognito User Pool as an identity provider for a Cognito Identity Pool.  

My understanding was that the Mobile Hub back end resources are connected, so when Mobile Hub provisioned a Cognito Identity Pool, I replaced my existing Pool with the new one provisioned by Mobile Hub.  

>What about your IAM role for analytics on your Cognito user pool?

Well, I may have a problem here, but when I set up the analytics on the user pool, I entered a role name and clicked create role.  I did not do anything with the new role, but I assumed that was enough to let the user pool communicate to Pinpoint.

**Comment by Jun711** [comment]
@genestd What type of role ? what permission does it have? that matters, I think.

**Comment by genestd** [comment]
@Jun711 - it's a service role with permissions to write to Pinpoint and Mobile Analytics.

**Comment by Jun711** [comment]
btw, did you update your Amplify.configure arguments to `Amplify.configure({ Analytics: {}, Auth: {} })` mentioned by @powerful23

**Comment by genestd** [comment]
Yes, but it did not have any effect (no new network activity in the console, no additional messages).  I don't have the output in front of me anymore, but it didn't appear to have an effect.

**Comment by genestd** [comment]
Thanks all for your help here.  I made some progress and think I'm on the right track to get things set up.  I was missing a very basic step that is probably obvious to more experienced devs, but isn't explained anywhere in the context of my use case:

I needed to first install the awsmobile-cli tool and init a project in my existing React repo.  This set up the back end in AWS Mobile.  Then I could configure Amplify with the aws-exports.js file.  I still needed to do some configuration to map my existing Cognito User Pool to the new Mobile Hub Identity Pool, but at least now I seem to be getting user data and events in Pinpoint.  

I'm not sure it is possible to manually replicate the awsmobile-cli init process.  I don't think running the init in my project caused any issues; maybe the documentation could be clarified to explain that this is necessary for both new and existing projects.

**Comment by Jun711** [comment]
@genestd is it possible to do it without using awsmobile cli init?

**Comment by genestd** [comment]
@jun711 - I did not make any changes to the Cognito User Pool.  I updated the new Identity Pool using the console.  

Background: My previous configuration was a Cognito User Pool as an identity provider for an Identity Pool.  The identity pool has a customized auth role where I grant it permissions to access resources such as S3 buckets.

Step 1 - set up my existing Cognito User Pool as an identity Provider for the new Mobile Hub Identity Pool.
Step 2 - assign my existing customized auth role as the auth role for the new Identity Pool
Step 3 - update the trust relationship (in IAM) for the customized auth role to trust the new Identity Pool

I am getting some statistics now in Pinpoint, but I'm still not seeing Sign In or Sign Up statistics, so there's still some tweaking to do.

**Comment by Jun711** [comment]
Thanks @genestd 
I found this thread about integrating PinPoint with existing IdentityPool and currently trying with it. You can take a look
https://forums.aws.amazon.com/thread.jspa?messageID=835748&#835748

the setup of your app seems similar to mine. I am using a Cognito User Pool as an identity provider for an identity pool. The pool has a customized auth role that has permissions to some other resources.

1) 
It seems that we have to abandon the existing identity provider and switch over to the identity pool created by mobile hub when we create a new project? 

2) 
Did you do any configuration on your aws mobile hub project to link to your existing project?

**Comment by genestd** [comment]
@Jun711 - yes, I switched my configure to:
```
Amplify.configure(aws_exports)
```

I would also like to know if we can update the Mobile Hub backend to use the original Identity Pool.  There is an awsmobile-cli command to push the configuration from project to Hub, so maybe it is possible, but I couldn't figure it out yet.

**Comment by Jun711** [comment]
Thanks @genestd 
1) On mobile hub, there is integrate (backend features), did you try that? Not sure if it is used to connect with the original Identity Pool

2) Have you see this error before when you first configured Analytics?
No 'Access-Control-Allow-Origin' header is present on the requested resource
https://github.com/aws/aws-amplify/issues/448

**Comment by genestd** [comment]
@Jun711 - Yes, I got custom events with
```
Analytics.record('test event')
```

**Comment by Jun711** [comment]
@genestd I got it working by using manual setup but had to migrated over to the new identity pool which was not so ideal. Thanks for your help.

**Comment by mihaiblaga89** [comment]
Hey guys,

Whatever I do I can't get Cognito to push emails and phone numbers to Pinpoint. Any ideas? I tried setting the project up with awsmobile and amplify or creating everything manually, nothing works. I even gave the "Share analytics data with Pinpoint" role full permission to mobiletargeting and mobileanalytics but nothing... I get the push endpoints created but not email and mobile phone from the user that logs in.
