### ISSUE TITLE
Sharing state across multiple Authenticator instances

### ISSUE THREAD

**Issue by adamjv90** [aws/aws-amplify#43]
Attempting to share authentication state in a react native app between multiple Authenticator components that wrap only a selected few of my react-navigation tabs. Currently, I store both authState and authData in my redux store. Everything works fine until I attempt to log out. If I try simply nullifying authState and authData in my redux store the Authenticator component re logs my user back in when it is shown. If i try to first call Auth.logout I receive the warning ```[WARN] Hub - error dispatching auth event to noname``` and my user is re-logged in when the Authenticator component is shown.

**Comment by richardzcode** [comment]
The recommended way is to call `Auth.currentAuthenticatedUser` to get auth state. [issue 31](https://github.com/aws/aws-amplify/issues/31) had some discussion about this.

```
Auth.currentAuthenticatedUser()
    .then(user => console.log(user))
    .catch(err => console.log(err));
```

For the Hub error could you share the aws-amplify-react-native version you are using?

Thanks,
Richard

**Comment by adamjv90** [comment]
@richardzcode my comment here is relevant to this issue: https://github.com/aws/aws-amplify/issues/51#issuecomment-350796237
