### ISSUE TITLE
Can't retrieve user attributes

### ISSUE THREAD

**Issue by pabloow** [aws/aws-amplify#430]
Do you want to request a feature or report a bug? 
Bug

What is the current behavior?

`CognitoUserSession.idToken.payload`

This returns only the attributes specified during signup. However, if a user then adds an extra attribute (eg "name"), this won't show here (and I can't find it anywhere else)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

<img width="165" alt="screen shot 2018-03-11 at 3 53 03 am" src="https://user-images.githubusercontent.com/14921127/37251567-7b4021b6-24e0-11e8-9951-cd5e8e20ff8a.png">
<img width="103" alt="screen shot 2018-03-11 at 3 54 56 am" src="https://user-images.githubusercontent.com/14921127/37251568-7b5c78c0-24e0-11e8-8a46-2f97b96367a0.png">
After adding a "name" attribute on a user, it will show in the cognito console but I can't retrieve it with amplify.

What is the expected behavior?
Expect to be able to retrieve "name" attribute inside CognitoUserSession.idToken.payload

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Amplify 0.2.9

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by pabloow** [comment]
I realized that this problem is solved only if user logs out and then logs in again. (refreshing browser doesn't help)

**Comment by nidsharm** [comment]
@pabloow ,

Thank you for trying out Amplify and reporting this bug to us. I'm adding it to our backlog and will make the documentation updates for this.

**Comment by amisra24x7** [comment]
This bug seems to be still affecting. Has this bug been resolved?
