### ISSUE TITLE
initiateAuth and TS/Angular

### ISSUE THREAD

**Issue by Loghrenar** [aws/aws-amplify#436]
Hello everyone,

_Do you want to request a feature or report a bug?_

A potential feature/bug (don't really know how it is supposed to work)

_What is the current behavior?_

I'm currently working with cognito on a basic register/login/forgot password, ... project and for the confirm registration process i need to redirect the user to another site.

So i'm using **case 25** to authenticate the user without password, everything could go fine but i can't use **initiateAuth** method from **CognitoUser**. The method isn't present in the methods i can use it from the Class. 
Precising i'm using **Angular5** and **Typescript** so it throws an error when compiling and builing (prod for example)

Here is my method (initiateAuth is not recognizable but working): 

```
authenticatePasswordLess(username: string, callback: CognitoCallback) {
        const authenticationData = {
            Username: username,
            Password: "",
        };

        const authenticationDetails = new AuthenticationDetails(authenticationData);

        const userData = {
            Username: username,
            Pool: this.cognitoUtil.getUserPool(),
            Storage: new CookieStorage({ domain: this.domain, secure: false })
        };

        const cognitoUser = new CognitoUser(userData);
        cognitoUser.setAuthenticationFlowType("CUSTOM_AUTH");
        const self = this;
        cognitoUser.initiateAuth(authenticationDetails, {
            onSuccess: function (result) {
                AWS.config.credentials = self.cognitoUtil.buildCognitoCreds(result.getIdToken().getJwtToken());
                callback.cognitoCallback(null, result);
            },
            onFailure: function (err) {
                callback.cognitoCallback(err.message, null);
            },
        });
    } 
```

And here is how i import CognitoUser: 
`import { AuthenticationDetails, CognitoUser, CookieStorage } from 'amazon-cognito-identity-js';`

_What is the expected behavior?_

So, i expected to be allowed to use **initiateAuth** as method from the **CognitoUser** class in the **index.d.ts** file natively

``` 
public initiateAuth(authenticationDetails: AuthenticationDetails, 
callbacks: {
 onSuccess: (session: CognitoUserSession, userConfirmationNecessary?: boolean) => void,
 onFailure: (err: any) => void, 
newPasswordRequired?: (userAttributes: any, requiredAttributes: any) => void, 
mfaRequired?: (challengeName: any, challengeParameters: any) => void, 
customChallenge?: (challengeParameters: any) => void }): void; 
```
PS: When i add manually this method in the file mentionned, i can normally access the method and everything works (it's of course a wrong use)

_Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?_

This is my current version: 
`"amazon-cognito-identity-js": "^1.31.0",`

Thanks in advance.

**Comment by ninuxio** [comment]
+1

**Comment by mlabieniec** [comment]
@Loghrenar did you try this with amplify at all? Amplify simplifies this a lot by abstracting / automating a lot of this for you, you would end up doing something like:

```js
import Amplify, { Auth } from 'aws-amplify';
... // further somewhere in a provider
Auth.signIn({ 'username': '...', 'password': '...'});
```

We also have an angular module pending in the next couple sprints that will have first class support for angular via a provider / module. But for now the standard APIs work pretty well in angular. 

For direct cognito sdk issue: @yuntuowang what do you think of the above issue?

**Comment by yuntuowang** [comment]
Hi @Loghrenar, I am not entirely sure why you cannot use initiateAuth(). This method is recognizable and we have heard problem about following Use case 25. As @mlabieniec said, can you try with Amplify and see if it works. Thanks.

**Comment by Loghrenar** [comment]
Hello @mlabieniec and @yuntuowang,
Thank you for answering quickly, i will test with **amplify** asap and i'll update this thread.
Nice to hear that an angular module will be available 👍

**Comment by Loghrenar** [comment]
So i'm back after some few tests, it seems that there are no options for custom auth flow with **Auth.signin** like the one still in **amazon-cognito-identity-js**.
My question is, can you add the method **initiateAuth** (as declared below) in the **index.d.ts** file ? 

```
public initiateAuth(authenticationDetails: AuthenticationDetails, 
callbacks: {
 onSuccess: (session: CognitoUserSession, userConfirmationNecessary?: boolean) => void,
 onFailure: (err: any) => void, 
newPasswordRequired?: (userAttributes: any, requiredAttributes: any) => void, 
mfaRequired?: (challengeName: any, challengeParameters: any) => void, 
customChallenge?: (challengeParameters: any) => void }): void; 
```
Or should i open a **pr** for this ?

Thanks in advance.

**Comment by Loghrenar** [comment]
So, i tested aws-amplify and as the angular module is not present yet, a temporary solution is to update the path:

`import { AuthenticationDetails, CognitoUser, CookieStorage } from 'amazon-cognito-identity-js'; `
to 
`import { AuthenticationDetails, CognitoUser, CookieStorage } from 'aws-amplify/node_modules/amazon-cognito-identity-js/lib/'; `

As everything is working perfectly now, i can close this issue, thank you for your help 👍

**Comment by sonipriya10** [comment]
is there any working example of passwordless authentication?

**Comment by Loghrenar** [comment]
Hey @sonipriya10, 

Method: 
`authenticatePasswordLess(username: string, callback: CognitoCallback) {
        const authenticationData = {
            Username: username,
            Password: '',
        };
        const authenticationDetails = new AuthenticationDetails(authenticationData);

        const userData = {
            Username: username,
            Pool: this.cognitoUtil.getUserPool(),
            Storage: new CookieStorage({ domain: environment.domain, secure: false })
        };

        const cognitoUser = new CognitoUser(userData);
        cognitoUser.setAuthenticationFlowType('CUSTOM_AUTH');

        const self = this;
        cognitoUser.initiateAuth(authenticationDetails, {
            onSuccess: function (result) {
                AWS.config.credentials = self.cognitoUtil.buildCognitoCreds(result.getIdToken().getJwtToken());
                callback.cognitoCallback(null, result);
            },
            onFailure: function (err) {
                callback.cognitoCallback(err.message, null);
            },
        });
    }`

Use method in a service/component: 

`registerPasswordLess(email: string) {
        this.userService.authenticatePasswordLess(email, this);
    }

    cognitoCallback(message: string, result: any) {
        if (message != null) {
            this.isSpinnerActive = !this.isSpinnerActive;
            this.toastrService.error(message);
        } else {
            this.isSpinnerActive = !this.isSpinnerActive;
            window.location.href = localStorage.getItem('previousUrl');
        }
    }`

This is how i manage the passwordless authentication. Just note that this was done with cognito-identity-js and you should do this with amplify now (I need to refactor this one with amplify too).

And so this issue was a bit odd assuming now everything should be coded in the amplify style.

Just have a look on this: 
https://github.com/aws/aws-amplify

Regards, 
Logh

**Comment by michelmob** [comment]
I'm still confused about the correct implementation. The idea to use Amplify is to simplify the process, so I don't need to import aws cognito api. Am I correct ?

If yes, how is the correct implementation to check the user by email?


Thanks!

**Comment by buggy** [comment]
@Loghrenar #566 implements passwordless login for Amplify. It's probably best to close this one and focus development over there. Now I'm back from holiday I'll try to get the PR ready for merging again.
