### ISSUE TITLE
Pinpoint OPTIONS returning 415 (Unsupported Media Type)

### ISSUE THREAD

**Issue by ASteinheiser** [aws/aws-amplify#438]
For some reason, I started getting this error in the console, but all of my routes still work...
I've traced it back to the Amplify.configure(aws_exports) call. aws_exports is being generated from awsmobile-cli.

![screen shot 2018-03-12 at 5 58 10 pm](https://user-images.githubusercontent.com/9949512/37317210-ca2817ac-2620-11e8-9d91-82cdddcae442.png)

![screen shot 2018-03-12 at 6 00 34 pm](https://user-images.githubusercontent.com/9949512/37317217-d15a2394-2620-11e8-84ff-56b63572298b.png)

![screen shot 2018-03-12 at 6 07 37 pm](https://user-images.githubusercontent.com/9949512/37317220-d45dc064-2620-11e8-81f6-577f4772c1f7.png)

![screen shot 2018-03-12 at 6 11 03 pm](https://user-images.githubusercontent.com/9949512/37317232-f41db422-2620-11e8-84c8-21a2c7da56f8.png)

**Comment by teddarling** [comment]
I confirm the same issue here.

<img width="960" alt="screen shot 2018-03-13 at 12 04 01 pm" src="https://user-images.githubusercontent.com/3044359/37360732-abd3cbde-26b6-11e8-9ce4-f1d08897dc9c.png">

**Comment by bbernays** [comment]
I am seeing the same thing

**Comment by richardzcode** [comment]
It failed on CORS, then because of that got 'Unsupported Media Type'. Looks like the root cause is CORS setting. We are looking into it now.

**Comment by richardzcode** [comment]
The issue is fixed from the service side. @ASteinheiser @teddarling @bbernays could you try now?

**Comment by teddarling** [comment]
No more errors on my end.

**Comment by richardzcode** [comment]
Nice!
