### ISSUE TITLE
TypeError: Amplify.configure is not a function

### ISSUE THREAD

**Issue by PaulRBerg** [aws/aws-amplify#443]
The function doesn't seem to be available. Sample code:

```
const Amplify = require('aws-amplify')

Amplify.configure({
    foo: 'bar'
})
```

Steps to reproduce: create a fresh node project, and add the code from above in `index.js`. It will crash saying `TypeError: Amplify.configure is not a function`.

If I do `Amplify.default.configure` it works but this warning pops out:

```[WARN] 00:51.431 Cache - getItem failed! TypeError: Cannot read property 'getItem' of null```

**Comment by mnishizawa** [comment]
@PaulRBerg Did you resolve this issue?  I am having the same issue.

**Comment by PaulRBerg** [comment]
I have overlooked the fact that this is a frontend library, so it cannot (and should not) be used in node.

**Comment by yarax** [comment]
If someone is interested, there is still workaround to use it in Node. It should be: 
```
Amplify.default.configure(..)
```
and requires support of `fetch`, e.g 
```
global.fetch = require('node-fetch');
```

**Comment by samazadi** [comment]
Is it possible to use this with Lambda? I'm using node-fetch and Amplify.default.configure - it resolved my TypeError issue, but now I'm getting "window is not defined". Is Amplify just not meant to be used with Lambda?

**Comment by yarax** [comment]
We could do it, but only with some fixed old versions of amplify. It's an
ugly hack. I really hope that aws will introduce sdk methods to run queries
from lambdas

**Comment by duke7able** [comment]
has anyone found a solution for with lamda

**Comment by xenowits** [comment]
Any solutions to this one?

**Comment by chovyprognos** [comment]
I'm having issue with svelte-kit and `adapter-static` working
