### ISSUE TITLE
getMFAOptions always returning 'SMS' as preferred method

### ISSUE THREAD

**Issue by fg-daltonwallace** [aws/aws-amplify#447]
I recently implemented TOTP as an MFA option for our users.  When calling `setPreferredMFA` with 'TOTP' as the preferred `mfaMethod` the call returns successfully and the user is able to login using TOTP.  My issue is that when I call `getMFAOptions` it will always return 'SMS' as the preferred option even though I've selected 'TOTP' for the given cognitoUser.  Can you shed any light on this?  Thanks1

**Comment by itrestian** [comment]
The getMFAOptions exposes the old flag that was used when only SMS was available as an MFA method. You can use the getUserData method to retrieved the preferred MFA option.

https://github.com/aws/aws-amplify/commit/62f7f2e365a1b4b99e9ebdf55e30199121afa19b#diff-ad86cca172d534ffb68fffb455ef02e5

**Comment by powerful23** [comment]
Closing.

**Comment by gustavo-rios** [comment]
The getUserData method suggested here, I believe, is not exposed by the Amplify API, are there any plans to expand getMFAOptions to expose when an user has a preferred TOTP MFA setting?

**Comment by powerful23** [comment]
We created a new method for getting mfa type using getUserData in #1254 , will publish it in this week.
