### ISSUE TITLE
Federated logins using hosted UI?

### ISSUE THREAD

**Issue by jaxondu** [aws/aws-amplify#45]
Is there any plan for Amplify to support the federated logins using hosted UI as in [https://forums.aws.amazon.com/ann.jspa?annID=4869](https://forums.aws.amazon.com/ann.jspa?annID=4869)  (Amazon Cognito Launches General Availability of a Built-in Customizable User Experience for Sign-in, OAuth 2.0 Support, and Federation with Facebook, Login with Amazon, Google, and SAML providers for User Pools) ?

**Comment by jlederma** [comment]
this.

**Comment by roosi** [comment]
I am also looking for to use hosted UI for user pools.

**Comment by ceich** [comment]
+1

What options are there for me to work around this? I see that Amplify has subsumed the Cognito Identity library; is there a public interface I can use in that package?

**Comment by Gribbs** [comment]
+1
supporting a "Sign-in" with FaceBook button on the amplify forms but then having no way to add these signed in users to the user pool is very confusing

**Comment by ceich** [comment]
Isn't this closed as of 0.3.3 ?

**Comment by powerful23** [comment]
@ceich yes
