### ISSUE TITLE
ConsoleLogger should bind console.log

### ISSUE THREAD

**Issue by vipseixas** [aws/aws-amplify#451]
I was having a problem when running a Ionic app in a Android 6.0.1 tablet. Logging was raising a `TypeError: Illegal Invocation` exception. I changed the following lines to bind the `console.log` and `console.warn` functions to `console` and this solved the problem:

```typescript
let log = console.log.bind(console);
// if (type === 'ERROR' && console.error) { log = console.error; }
if (type === 'WARN' && console.warn) { log = console.warn.bind(console); }
```

**Comment by richardzcode** [comment]
Hey @vipseixas thanks for the report. This looks good to me. Do you want to make a pull request?
