### ISSUE TITLE
Authenticator with cognitoUserPool SignIn and Federated SignIn both at the same time!?

### ISSUE THREAD

**Issue by michaelcuneo** [aws/aws-amplify#452]
Do you want to request a feature or report a bug?
Feature?

What is the current behavior?
Adding federated to the standard Authenticator? Can you have both, login and federated... or just one or the other? adding federated={federated} to <Authenticator /> just continues to fail no matter what I do.

All I get it the standard SignIn...

**Comment by richardzcode** [comment]
Hey @michaelcuneo SignIn and Federated works together, they are not exclusive. Check out this guide: https://aws.github.io/aws-amplify/media/authentication_guide.html#6-federated-identity

Could you paste a snippet of your code so we can look together.

**Comment by michaelcuneo** [comment]
`mport React, { Component } from 'React'
import PropTypes from 'prop-types';

import config from 'config';
import AuthWrapper from './AuthWrapper';
import KoalaCall from './KoalaCall';

import Amplify, { Auth } from 'aws-amplify';
import { 
  Authenticator,
  Greetings,
  SignIn,
  ConfirmSignIn,
  RequireNewPassword,
  SignUp,
  ConfirmSignUp,
  ForgotPassword
} from 'aws-amplify-react';

export class LoginPage extends React.PureComponent { // eslint-disable-line react/prefer-stateless-function
  constructor(props) {
    super(props)
  };

  componentWillMount() {
    Amplify.configure({ Auth: config.amplifyAuth });
  }

  async handleAuthStateChange(state) {
    if (state === 'signedIn') { 
      console.log('We`re logged in, save state to User');
      let user = await Auth.currentAuthenticatedUser().then(console.log(user));
    }
  }

  render() {
    const federated = {
      google: '921567933214-naumeolsa1g0d9v1srcpno6l0p4hcnnh.apps.googleusercontent.com',
      facebook: '597560987251007',
    }

    const map = (message) => {
      if (/user.*not.*exist/i.test(message)) {
        return 'That user does not exist in our database, have you signed in? Go sign in so you can help us look for Koalas!';
      }
      if (/user.*already.*exist/i.test(message)) {
        return 'Thats user already exists in the database, have you forgotten your details?';
      }
      if (/validation.*password/i.test(message)) {
        return 'You`re going to have to make a better password than that, we`re secure around here, we`re hunting for Koalas!';
      }
      if (/invalid.*phone/i.test(message)) {
        'Invalid phone number format. Please use a phone number format of +12345678900';
      }
      if (/incorrect.*username.*password/i.test(message)) {
        return 'You`ve got your username right, but the password you entered was incorrect, check that you don`t have CAPSLOCK on and try again.';
      }
      if (/incorrect.*username/i.test(message)) {
        return 'That user does not exist, if you haven`t signed up, hit signup and you`ll be searching for Koala`s in no time.';
      }
      return message;
    };

    return (
      <AuthWrapper>
        <Authenticator federated={federated} errorMessage={map} hideDefault={false} theme={KoalaCall} onStateChange={this.handleAuthStateChange}>
          <Greetings />
          <SignIn />
          <ConfirmSignIn />
          <RequireNewPassword />
          <SignUp />
          <ConfirmSignUp />
          <ForgotPassword />
        </Authenticator>
      </AuthWrapper>
    );
  }
}

export default (LoginPage);`

**Comment by michaelcuneo** [comment]
```
import React, { Component } from 'React'
import PropTypes from 'prop-types';

import config from 'config';
import AuthWrapper from './AuthWrapper';
import KoalaCall from './KoalaCall';

import Amplify, { Auth } from 'aws-amplify';
import {
Authenticator,
Greetings,
SignIn,
ConfirmSignIn,
RequireNewPassword,
SignUp,
ConfirmSignUp,
ForgotPassword
} from 'aws-amplify-react';

export class LoginPage extends React.PureComponent { // eslint-disable-line react/prefer-stateless-function
constructor(props) {
super(props)
};

componentWillMount() {
Amplify.configure({ Auth: config.amplifyAuth });
}

async handleAuthStateChange(state) {
if (state === 'signedIn') {
console.log('We`re logged in, save state to User');
let user = await Auth.currentAuthenticatedUser().then(console.log(user));
}
}

render() {
const federated = {
google: '921567933214-naumeolsa1g0d9v1srcpno6l0p4hcnnh.apps.googleusercontent.com',
facebook: '597560987251007',
}

const map = (message) => {
  if (/user.*not.*exist/i.test(message)) {
    return 'That user does not exist in our database, have you signed in? Go sign in so you can help us look for Koalas!';
  }
  if (/user.*already.*exist/i.test(message)) {
    return 'Thats user already exists in the database, have you forgotten your details?';
  }
  if (/validation.*password/i.test(message)) {
    return 'You`re going to have to make a better password than that, we`re secure around here, we`re hunting for Koalas!';
  }
  if (/invalid.*phone/i.test(message)) {
    'Invalid phone number format. Please use a phone number format of +12345678900';
  }
  if (/incorrect.*username.*password/i.test(message)) {
    return 'You`ve got your username right, but the password you entered was incorrect, check that you don`t have CAPSLOCK on and try again.';
  }
  if (/incorrect.*username/i.test(message)) {
    return 'That user does not exist, if you haven`t signed up, hit signup and you`ll be searching for Koala`s in no time.';
  }
  return message;
};

return (
  <AuthWrapper>
    <Authenticator federated={federated} errorMessage={map} hideDefault={false} theme={KoalaCall} onStateChange={this.handleAuthStateChange}>
      <Greetings />
      <SignIn />
      <ConfirmSignIn />
      <RequireNewPassword />
      <SignUp />
      <ConfirmSignUp />
      <ForgotPassword />
    </Authenticator>
  </AuthWrapper>
);
}
}

export default (LoginPage);
```

**Comment by michaelcuneo** [comment]
It's nothing out of the ordinary... Just returning the Authenticator wrapper in a div. Supplied all the right props to the Authenticator... but it won't show federated, it also won't allow me to show any custom areas, I have to keep hideDefault={false} or nothing will display at all. I'm not wrapping it around <App /> because this app doesn't need this kind of functionality, it only needs one or two pages of the app authenticated.

**Comment by michaelcuneo** [comment]
I can sign in and out, and add users and get codes, forget password, the entire normal function of Authenticator... I can add errorMessages, themes, and I can set an onStateChange, ... but custom components within the Authenticator o.e. <Greetings /> <SignIn /> ... soon as I hit hideDefault it's meant to show up any custom ones I've made, and hide everything default right? Doesn't work... hideDefault={false} shows both, the default and my imported ones, and federated shows nothing.

**Comment by tyson-kubota** [comment]
@michaelcuneo I ran into this last week too. It turns out that `hideDefault` was broken until recently: https://github.com/aws/aws-amplify/issues/357

If you use the latest aws-amplify (0.2.11, which includes aws-amplify-react v0.1.36), it should be fixed: https://github.com/aws/aws-amplify/releases/tag/aws-amplify%400.2.11
