### ISSUE TITLE
currentUserCredentials returns undefined

### ISSUE THREAD

**Issue by nomadus** [aws/aws-amplify#453]
Auth.currentUserCredentials return undefined although currentSession, currentUserInfo and currentAuthenticatedUser return valid values. Should the above function return some credential information?

**Comment by richardzcode** [comment]
@nomadus current credentials can be get from Auth

```
Auth.currentUserCredentials()
    .then(() => console.log('current credentials', Auth.credentials))
    .catch(err => console.log('get current credentials error', err));
```

However I agree the method itself should resolve with credentials. So mark this as a bug.

**Comment by powerful23** [comment]
@nomadus This should have been fixed in aws-amplify@beta. Can you have a try on that version?

**Comment by powerful23** [comment]
Closing the issue as this should have been fixed in the latest version

**Comment by lusentis** [comment]
I confirm that this works correctly in `aws-amplify@^0.2.12` and `aws-amplify@0.3.0`.
Thanks!
