### ISSUE TITLE
amazon-cognito-identity-js 2.0.1 doesn't work with TypeScript - missing types?

### ISSUE THREAD

**Issue by MrIceman** [aws/aws-amplify#454]
**Do you want to request a feature or report a bug?**
bug
**What is the current behavior?**
We updated the SDK to 2.0.1 and we get an error after compiling and npm start:

> /node_modules/amazon-cognito-identity-js/index.d.ts
> (86,16): 'associateSoftwareToken', which lacks return-type annotation, implicitly has an 'any' return type.
> 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**
put "amazon-cognito-identity-js": "2.0.1" as dependency in your typescript project into package.jsn

**What is the expected behavior?**
to work

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
2.0.1 , Google Chrome and yes it worked in previous versions. 

**You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.**

```
amazon-cognito-identity-js": "2.0.1",

index.js:2177 /Users/.../node_modules/amazon-cognito-identity-js/index.d.ts
(86,16): 'associateSoftwareToken', which lacks return-type annotation, implicitly has an 'any' return type.
__stack_frame_overlay_proxy_console__ @ index.js:2177
handleErrors @ webpackHotDevClient.js:176
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:209
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2177 /Users/.../node_modules/amazon-cognito-identity-js/index.d.ts

(91,36): Parameter 'totpCode' implicitly has an 'any' type.
__stack_frame_overlay_proxy_console__ @ index.js:2177
handleErrors @ webpackHotDevClient.js:176
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:209
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2177 /Users/.../node_modules/amazon-cognito-identity-js/index.d.ts
(91,46): Parameter 'friendlyDeviceName' implicitly has an 'any' type.


```

**Comment by MrIceman** [comment]
I just saw that this is not fixed in 2.0.1 but it is in the current dev stage

**Comment by yuntuowang** [comment]
Hi @MrIceman, we already fixed this issue. It seemed v2.0.1 doesn't contain this change. We will fix this on NPM.

**Comment by richardzcode** [comment]
2.0.2 released
