### ISSUE TITLE
Documentation for Auth payloads, error codes

### ISSUE THREAD

**Issue by xdl** [aws/aws-amplify#455]
It would be useful to have a link in the readme to where the payloads for the Auth methods are documented, such as `challengeName` when signing in with MFA, `CodeDeliveryDetails` for resetting password, as well as the different exception codes for when passwords are reset (i.e. `InvalidParameterException` and `CodeMismatchException` - are these documented anywhere?

**Comment by xdl** [comment]
Thanks Yun, these are really coming in useful.

**Comment by gruckionvit** [comment]
The link doesn't contain meaningful information. Has it changed?
