### ISSUE TITLE
How to send Analytics events which contain uniquely identifiable user info when I am not using Cognito for user login mangement?

### ISSUE THREAD

**Issue by gauravko** [aws/aws-amplify#456]
Hi guys,

I am trying to implement the Mobile Hub setup for couple of my products, one of which is available for Android and one which is a React based web app. I have my own custom login setup at end up of which I assign to every user a uniquely identifiable id. 

For Android, I am using the Pinpoint SDK, which allows me to send custom events. There is also a provision in the [SDK](https://docs.aws.amazon.com/pinpoint/latest/developerguide/mobile-sdk-android-register.html ) to set a customer user identifier :  
> Assign user IDs to endpoints by doing either of the following:
> 
> Manage user sign-up and sign-in with Amazon Cognito user pools.
> Use the PinpointManager class to assign user IDs to endpoints.

Now if my understanding is correct, there is no Pinpoint library available right now for react-web. Which leads me to use Amplify Analytics for sending similar custom events which will hit Pinpoint. 
However, at no point in the documentation which I can find [here]( https://aws.github.io/aws-amplify/media/analytics_guide.html), are there any methods described to set some uniquely identifiable user properties before sending custom events. 

Am I understanding the use cases incorrect, or is this something under development ?

**Comment by powerful23** [comment]
@gauravko yes this feature is still in development. You can check this pr https://github.com/aws/aws-amplify/pull/437 which is to enable users to customize the userId and other attributes for pinpoint endpoint request.

**Comment by gauravko** [comment]
Hi @powerful23 , thanks for the quick reply and providing the commit. Looking forward to this getting merged. Do ping me if you need any 3rd party testing to be done. Cheers!

**Comment by mlabieniec** [comment]
#437 has been merged
