### ISSUE TITLE
release/version info is missing

### ISSUE THREAD

**Issue by uptimestar** [aws/aws-amplify#457]
I'm looking at what you recommend to use in web app, linked in your read me:
https://raw.githubusercontent.com/aws/aws-amplify/master/packages/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js

There is no version of release info in the file or url or on the git hub repo!
That is a bug.

For example this CDN offers version 2.0.1:
https://cdn.jsdelivr.net/npm/amazon-cognito-identity-js@2.0.1/dist/amazon-cognito-identity.min.js

But ... is 2.0.1 the latest? I'd like a bit of confidence on what I would be using. What is your release/tag process for us the users of your libs?

**Comment by elorzafe** [comment]
Hi @uptimestar, on every release we update github releases: https://github.com/aws/aws-amplify/releases 

currently amazon-cognito-identity-js is on version 2.0.2

**Comment by cekvenich** [comment]
So I have to look at your notes to know there was a release. But the regular way of looking at a file or the location of file or name of the file, one can't tell.

**Comment by mlabieniec** [comment]
@uptimestar github doesn't currently have support for creating releases with a mono repo. We tend to just follow the same way most do it for example [react](https://github.com/facebook/react). I imagine better support for package releases should be coming soon given the popularity of the mono repos. Until then please let us know what might help that we could do differently with the releases / changelog.

**Comment by cekvenich** [comment]
In the mean time, for the users, can you just put inside the .js file name the release version # like is common. You have license, etc. in there.
