### ISSUE TITLE
Leveraging Already Existing Identity Pool 

### ISSUE THREAD

**Issue by KylePalko** [aws/aws-amplify#46]
Hey all,

Love where the project is. The code is very clean (I've been digging through it this afternoon) and well documented. We've just started looking into Amplify and our team was curious as to whether it works with Identity Pools (not just User Pools). If so, can you point me in the right direction to get this working? I noticed in the documentation there is this example:

```
Amplify.configure({
    Auth: {
        identityPoolId: 'xx-xxxx-x:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        region: 'xx-xxxx-x'
    }
})
```

We already have an Identity Pool with our own authentication, and I'm of course able to get a hold of an Identity ID and Access Token. However, I'm not sure where to go from here (such as, what Object to instantiate and pass the ID/Token into). Any help would be appreciated, thanks!

**Comment by mlabieniec** [comment]
@KylePalko after configuring the component you can call signin or register methods to signin users, and listen for auth state changes within your app. See here for example code and info: https://aws.github.io/aws-amplify/media/authentication_guide.html

**Comment by KylePalko** [comment]
Hey @mlabieniec, just to confirm, does this sign-in API work with both Identity Pools and User Pools?

**Comment by mlabieniec** [comment]
@KylePalko  the authentication i.e. signIn, signUp, signOut etc.  works specifically with User Pools. I believe what you might be referring to is signup with MFA? That's when you would pass a auth code, which would be after signUp/signIn if you've enabled MFA with the confirmSignIn method and similarly with the confirmSignUp.
