### ISSUE TITLE
How to avoid double MFA on signup

### ISSUE THREAD

**Issue by ossareh** [aws/aws-amplify#461]
**Do you want to request a feature or report a bug?** Request a feature / additional documentation

**What is the current behavior?**

Using AuthClass you can call `signUp` which triggers an SMS to confirm the users phone number (in my case), followed by `CognitoUser.confirmRegistration` (see #449) with the MFA code. Now the user is in the CONFIRMED state which allows us to call `Auth.signIn()`; however this triggers a second MFA SMS.

**What is the expected behavior?**

While building a signup flow it is usual to want something like:
 * provide phone number and password as credentials
 * verify phone number && be logged in
 * fill out profile data / supply user attributes to cognito.

However, it appears, in it's current setup this isn't possible. https://github.com/aws/amazon-cognito-identity-js/issues/186 was a highly "+1'ed" issue prior to aws-amplify taking over the reins. One commenter, building for iOS, appeared to get this working https://github.com/aws/amazon-cognito-identity-js/issues/186#issuecomment-335690410 (however I think they may be using an admin API to do this?)

**Conclusion**

It would be great to either have some documentation that describes how to achieve the desired effect or a set of APIs made available which allow for this.

**Comment by richardzcode** [comment]
Hi @ossareh , there are couple of different things here, let me try to explain

1. Sign Up MFA. In Cognito settings, if selected SMS MFA then confirmation code is sent via SMS, otherwise email.
2. Sign In MFA. In Cognito settings, if selected require MFA then every time sign in requires a confirmation code, could be SMS or TOTP depending on selection.
3. Automatic Sign In after confirmed Sign Up. This is the feature we don't support now.

A short answer is to set MFA to 'optional' in Cognito settings. Let me know if this works for you.

**Comment by ossareh** [comment]
Hi @richardzcode, thanks for the response.

RE: 1 - yes, I have Sign Up MFA set to on because we want to verify the users phone number as part of the sign up flow, this also puts the user into a confirmed state - such that they can sign in. We're against using a Cognito trigger to automatically put the user into confirmed state because that would allow rogue users to "steal accounts".

RE: 2 - this is not clear to me. If we set MFA to Optional, then the user can decide - however we want it on unless the users device fingerprint changes. From what I can tell aws-amplify doesn't support passing a fingerprint along - am I missing something?

RE: 3 - Right, I came to understand that yesterday after logging the issue. Thanks for clearing that up. It is a pretty "normal" expectation for a registration flow - so I'm hoping to circle back around to this and tackle it by way of Cognito Triggers - however taking a look at aws-amplify it's clear you guys aren't setup for a Custom Auth flow - do you have any plans to support Custom Auth?

**Comment by nihp** [comment]
I have set MFA to optional. Because if this for some users MFA is disabled and for some users MFA is enabled while With.SignUp

How can I trigger or Enable MFA for this users from my code?
