### ISSUE TITLE
Clean EmberJS Project: Could not find module `aws-amplify`

### ISSUE THREAD

**Issue by GerDner** [aws/aws-amplify#462]
I want to report a Bug

I'm trying to import the module in a clean new emberjs app (created with ember-cli).

The module `aws-amplify` is not found, regardless how i include the module. 
I also tried to include the module via `app.import` in the `ember-cli-build.js` which is basically the brocfile.

Steps to reproduce:
Create a new ember-cli project, install `aws-amplify` with npm or yarn.
If you include the module with `import Amplify from 'aws-amplify';` you get an error.

```
loader.js:247 Uncaught Error: Could not find module `aws-amplify` imported from `myapp/amplify/service`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:407)
    at Class.resolveOther (index.js:110)
    at Class.superWrapper [as resolveOther] (ember-utils.js:420)
    at Class.resolve (resolver.js:133)
    at _resolve (container.js:871)
```

"aws-amplify": "^0.2.10"
"aws-sdk": "2.177.0
"ember": "3.0.0" and "ember": "2.18.0"
"node": "v8.1.4"

MacOS: 10.13.2

**Comment by mlabieniec** [comment]
@GerDner Ember has some trouble importing node_modules. you can put this in a service then access it through the service for abstraction:

First, in your broc file:

```js
// in ember-cli-build.js
app.import('node_modules/aws-amplify/dist/aws-amplify.min.js');
```

Then generate a service i.e. ember g service amplify. Within the service, if you are using `aws-exports.js`, make sure it's in the `app/` directory of your ember app:

```js
import Service from '@ember/service';
import awsmobile from '../aws-exports';
const Auth = window['aws-amplify'].Auth;
const Analytics = window['aws-amplify'].Analytics; 

Auth.configure(awsmobile);
Analytics.configure(awsmobile);

export default Service.extend({
	Auth: Auth
});
```

Then you can reference Auth or Anylytics (or anything else you configure) from your controllers, components etc. 

```js
// example component that does signIn

import Component from '@ember/component';
import { inject as service } from '@ember/service';

export default Component.extend({
	amplify:service(),
	username: null,
	password: null,
	message: null,
	error: null,
	actions: {
		signIn() {
			const auth = this.get('amplify').Auth;
		  	const username = this.get('username');
		  	const password = this.get('password');
		  	const that = this;

			auth.signIn(username, password)
				.then((result) => {
					that.set('error', null);
					that.set('message', result);
				})
				.catch((error) => {
					if (error.message) {
						that.set('error', error.message);
					} else {
						that.set('error', error);
					}
				});
		}
	}
});
```

**Comment by mlabieniec** [comment]
@GerDner Post here on setup with ember as well:
https://medium.com/@mlabieniec/adding-aws-amplify-to-an-ember-js-application-72683167c476

**Comment by officeguy** [comment]
fyi, the use of ember-cli-amplify was working for me in October, but testing again on a new project in December, all I can get is the symptom as described in this issue:
Could not find module `aws-amplify`

so, is this a related to some recent version changes in either ember-cli-amplify or in aws-amplify?

**Comment by officeguy** [comment]
thanks Michael, will do.

**Comment by GerDner** [comment]
i fixed it in alle of my projects by using ember-auto-import for all node_modules.

**Comment by officeguy** [comment]
thanks GerDner, could I ask for a code example demonstrating that idea? i.e which file are you editing with which text?
