### ISSUE TITLE
What configs / components are used to only show FederatedSignIn

### ISSUE THREAD

**Issue by shortjared** [aws/aws-amplify#464]
I am struggling trying to figure out how to show a form that ONLY allows federated SignIn and does not show the normal username / password signin.

Are there any examples or docs for this?

I got as far as this which will apply the hidesDefault (on beta) properly but I never get to actually see the FederatedSignIn itself.
```javascript
export default withAuthenticator(WithProvider, { 
  includeGreetings: true, 
}, [
  <FederatedButtons />,
  <FederatedSignIn />
]);
```

Any hints here?

Thanks!

**Comment by richardzcode** [comment]
Hey @shortjared here is an example of how to only show FederatedSignIn with `withAuthenticator` however there is a bug. I'll make a fix soon for that.

```
export default withAuthenticator(WithProvider, true, [<FederatedSignIn />]);
```

At this moment a workaround is to use `Authenticator` directly

```
const AuthWrapper = (props) => (
  <Authenticator hideDefault={true}>
    <FederatedSignIn federated={{facebook_app_id: '_replace_with_actual_facebook_app_id_'}} />
    <WithProvider />
  </Authenticator>
)

export default AuthWrapper;
```

Then in your `WithProvider.render` check `this.props.authState` to decide showing the component or not

**Comment by richardzcode** [comment]
Correction, this should work, I missed `federated` parameter

```
const federated = { facebook_app_id: '_replace_with_actual_facebook_app_id_' };
export default withAuthenticator(WithProvider, true, [<FederatedSignIn federated={federated} />]);
```

**Comment by shortjared** [comment]
Bingo. I had eventually got to the same conclusion with `beta` after reading the source. :+1: thank you much!
