### ISSUE TITLE
aws-amplify-react-native "Invalid undefined `width` of type `string` supplied...."

### ISSUE THREAD

**Issue by soroushnorouzi** [aws/aws-amplify#47]
When I `import Storage from 'aws-amplify-react-native'`, without doing anything else I get the below error in React Native (using version `react-native:0.39.2`)

<img src="https://user-images.githubusercontent.com/4604227/33745169-1092d9ae-db6a-11e7-8ba5-97f8635c2409.png" width=216 height=384/>

I'm not sure why this is happening, or why there aren't other records of a similar issue, but just by `import`ing I can cause this error!

**Comment by mlabieniec** [comment]
@soroushnorouzi are you still experiencing this issue? We are not able to reproduce so far, it looks like perhaps your react-native version is a bit outdated i'm using 0.50.3
