### ISSUE TITLE
Calls to fetch in aws-cognito-identity-js Client.js are failing when running in React Native 0.54.2.

### ISSUE THREAD

**Issue by smsenesac** [aws/aws-amplify#470]
Do you want to request a feature or report a bug?

bug

What is the current behavior?

When attempting to sign a user using aws-cognito-identity-js, the call to fetch in Client.js errors with 'unsupported BodyInit type'.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

The call to authenticateUser fails.

```
  logIn(email, password) {
    const userPool = this.getUserPool();

    const authenticationParams = {
      Username: email,
      Password: password
    };

    const authenticationDetails = new AuthenticationDetails(authenticationParams);

    const userParams = {
      Username: email,
      Pool: userPool
    };

    const user = new CognitoUser(userParams);

    return new Promise((resolve, reject) => {
      user.authenticateUser(authenticationDetails, {
        onSuccess: session => {
          const identityLogins = {};
          const identityLoginKey = session.getAccessToken().payload.iss.replace('https://', '');
          identityLogins[identityLoginKey] = session.getIdToken().getJwtToken();

          AWS.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: Config.COGNITO_IDENTITY_POOL_ID,
            Logins: identityLogins
          });

          AWS.config.credentials.clearCachedId();

          AWS.config.credentials.refresh(refreshError => {
            if (refreshError) {
              return reject(refreshError);
            }

            return resolve({
              userId: user.username,
              token: session.getIdToken().getJwtToken()
            });
          });
        },
        onFailure: error => reject(error)
      });
    });
  }
```

What is the expected behavior?

Call should complete successfully.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Broken:
React Native 0.54.2
aws-cognito-identity-js 2.0.1

Worked:
React Native 0.53.0
aws-cognito-identity-js 2.0.1

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by elorzafe** [comment]
Hi, there is a new version of amazon-cognito-identity-js 2.0.2

That should fix this issue.

**Comment by smsenesac** [comment]
Tried out 2.0.2 today but still seeing the same error.

**Comment by mlabieniec** [comment]
@smsenesac do you know where i.e. which line the error is thrown and via which method? Also, have you given aws-amplify a try to try and simplify this flow a bit? If you use that and react-native lib it would handle/automate this process for you. There is a good example here:
https://github.com/dabit3/react-native-auth-starter

Which only uses the core lib and the APIs (not the HOCs).

**Comment by smsenesac** [comment]
We tried using aws-amplify a few months ago before aci-js was pulled into the repo and it just didn't expose all the functionality that we needed. It looks like some of those things are now available via the amplify apis, but we are busy working to add features for beta and don't have the resources to see if switching back to amplify will allow us to maintain the functionality that we already have without introducing any new issues. For now, we're just going to stick with RN 0.53 since it's stable with aci-js 2.0.2 in our application. I just wanted to post a bug just in case others were having the same experience.

**Comment by smsenesac** [comment]
My understanding is that the BodyInit error is usually an indication that the request body was not stringified before calling fetch, but from looking at the code and inspecting the request body in the RN debugger, the request body seemed properly stringified to me. I noticed in the RN 0.54.2 release notes that changes were made to RN's fetch implementation. Maybe they have a defect? I didn't have the chance to debug into their fetch implementation to see what was going on at that level.

**Comment by smsenesac** [comment]
Figured this out. I had code in my startup logic to enable debugging of network requests:

`
if (__DEV__) {
  GLOBAL.XMLHttpRequest = GLOBAL.originalXMLHttpRequest || GLOBAL.XMLHttpRequest;
}
`

This apparently causes issues with newer versions of react following changes to the fetch implementation. The correct way to debug network requests in the simulator now is to enable request inspection in the react-native-debugger and remove the code above. See the following issue from the react-native-debugger project:

https://github.com/jhen0409/react-native-debugger/issues/209
