### ISSUE TITLE
Broken links on documentation

### ISSUE THREAD

**Issue by epicfaace** [aws/aws-amplify#472]
On https://aws.github.io/aws-amplify/media/api_guide, the following links are broken:

"Please refer to AWS Amplify Installation Guide for initial setup."

"For the complete API documentation for API module, visit our API Reference"

**Comment by elorzafe** [comment]
Thanks for pointing this out, we will fix this asap.

**Comment by mbahar** [comment]
This is fixed!

**Comment by yovetichg** [comment]
On https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/deployment-ecs-aspnetcore-ec2.html, the "Specify your AWS credentials" link is broken.
