### ISSUE TITLE
Signup with phone number: no SMS verification sent

### ISSUE THREAD

**Issue by aloukissas** [aws/aws-amplify#473]
My pool config is shown below. I signup a user using the JS library (or the CLI) with a phone number as username. The user remains in UNVERIFIED state and the SMS is never received. The correct IAM role is set up to be able to publish SMS using SNS.

As usual, the AWS guides aren't very helpful :/

<img width="1112" alt="screen shot 2018-03-18 at 7 37 24 pm" src="https://user-images.githubusercontent.com/12943502/37575368-044429c2-2ae4-11e8-930f-52f16214a1ae.png">

**Comment by slackday** [comment]
I had this problem. When I looked at SNS it had all messages as FAILED. Turned out I had to contact support to increase my SNS sending limit. It defaults to $1 if you havn't increased it.

**Comment by mlabieniec** [comment]
@aloukissas were you able to get an answer from support on this?

**Comment by powerful23** [comment]
Closing this issue. Feel free to reopen it.

**Comment by andrewheekin** [comment]
Having the same issue, despite increasing the SNS sending limit. @aloukissas any luck on your end?

**Comment by KOSSOKO** [comment]
@andrewheekin i'm having the same issue, did you find a solution ?

**Comment by AakashPat** [comment]
I am facing this exact same issue. I have gone through the process of raising a Service Quota Increase request for SNS and getting it raised. I have also changed my spending limit from SNS Console to the granted quota (30$ in my case).

I am able to send SMS messages programatically through the aws-sdk for other communication with the user. But the SMS verification code that gets sent upon registration using phone number is never delivered. Even resending the code multiple times over has not helped. And this issue is also not isolated. We have tried it with multiple (10+) mobile number and none are receiving any messages at all.

**Comment by raghavendra-hashtaglearn** [comment]
I have been facing the same issue. I requested for a service quota increase in the ap-south-1 (Mumbai region) as my user pools were setup in ap-south-1 region. 
I reached out to tech support at AWS with the same problem. They informed me that Mumbai region Cognito utilizes SNS from Singapore region (ap-southeast-1) to send the messages. They have suggested that I increase the limit in the ap-southeast-1 region for this problem to be solved. I just submitted the request. Will keep you guys posted if the issue gets resolved.

**Comment by santhedan** [comment]
Any update on the issue? I am also facing this isssue. I am able to send SMS via console but on signup it is not sending any SMS message.

**Comment by rs3603** [comment]
You can try changing the region of the user pool to ap-southeast-1. Then you can submit for service limit increase request for that pool in Singapore region. Everything worked after I moved to this region.

**Comment by santhedan** [comment]
My UP is already in production and in Mumbai region so I can not move it now. I have submitted the request to increase limit for Singapore region. Let us see when it gets done. Till that time all my production users are going to get stuck at signup!

**Comment by lucasmends** [comment]
@santhedan I found at https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html that Amazon Cognito Region for Asia Pacific (Mumbai) ap-south-1 actually uses SMS from ap-southeast-1. I am actually experience similar issue and I think that it could be your problem.

**Comment by lifehetu** [comment]
I am stuck here! I am using Cognito Multi-factor authentication. The MFA verification SMS delivered just fine before the Spend limit crossed. Then I requested to increase the spend limit and subsequently updated the SNS configuration accordingly.

Even after all this done the verification SMS is still not delivering.

The AWS team is denying any help. Asking me to go for a paid customer support.

If you have found a way out of this mess, request you to please post your solution here.

With this much uncertainty and lack of support/documentation, I am not sure if should use it in my production environment at all. Please help!

Thanks,
Puneet

**Comment by lifehetu** [comment]
My User pools are in Mumbai reason. Also, I created a User Pool in the Singapore region only to see the SMS messages not delivering for that region also.
