### ISSUE TITLE
Create a session using the JWTs from the hosted sign in

### ISSUE THREAD

**Issue by NRaf** [aws/aws-amplify#480]
I'm building an Angular 5 application and would like to use `aws-amplify` since it's recommended over `amazon-cognito-identity-js`.

Given that there doesn't seem to be any pre-built components for Angular in the same way there is for React, I'd prefer to use the Hosted UI rather than handling sign up / sign up / change password, etc within my application.

When I sign in with Angular 5, I get an identity token and a refresh token. Is there any way to pass these to AWS Amplify to create a session?

**Comment by elorzafe** [comment]
In the next sprint we will have available components for angular. I will let you know when we publish those.

**Comment by mlabieniec** [comment]
@NRaf Angular components have been launched, see 
https://aws.github.io/aws-amplify/media/angular_guide
