### ISSUE TITLE
Ionic + aws amplify + push notifications

### ISSUE THREAD

**Issue by lucaslc-sp** [aws/aws-amplify#482]
Hello,

Is possible to use aws-amplify for push notifications with Ionic ? If not yet, there's any workaround ? 

Because I need to send push notifications for some users separating by a cognito field. So, I think that 
to use the Pinpoint is a good solution.

**Comment by mbahar** [comment]
@lucaslc-sp Ionic is not supported for the moment, but this tutorial shows how to use Pinpoint with Ionic:

https://aws.amazon.com/blogs/mobile/push-notifications-with-ionic-and-amazon-pinpoint/

**Comment by lucaslc-sp** [comment]
Ok, no problem. In this tutorial is used direct push notification. There's any way to send by a campaign or only direct push notification ? 

Because I need to send notification to many users ! Any suggestion?

**Comment by mbahar** [comment]
@lucaslc-sp for that, you need to register your target devices to Pinpoint:
https://docs.aws.amazon.com/pinpoint/latest/developerguide/mobile-sdk-android-register.html

You can do it with AWS JS SDK which is [bundled](https://aws.github.io/aws-amplify/media/quick_start#working-with-aws-service-interface-objects) with Amplify as well. Here is how is it done;
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#updateEndpoint-property

For React Native, above process is done under the hood by AWS Amplify, for Ionic you can try to handle it manually.

**Comment by lucaslc-sp** [comment]
Thank you so much @mbahar . I'll try !!!
