### ISSUE TITLE
Auth.signIn always NotAuthorizedException

### ISSUE THREAD

**Issue by jeprojects** [aws/aws-amplify#485]
Do you want to request a feature or report a bug?

BUG

What is the current behavior?

Using a custom User Pool with the settings:

> How do you want your end users to sign in?
> - Email address or phone number
> - Allow email addresses

Using this to login always give a NotAuthorizedException:

`const login = await Auth.signIn(email, password)`

What is the expected behavior?

It should login

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Amplify Version 0.2.11
React Native
First time using

**Comment by elorzafe** [comment]
Hi @jeprojects 

Where are you calling Amplify.configure? Are you using awsmobile-cli or you create it on Cognito console?

**Comment by jeprojects** [comment]
@elorzafe Originally created it in Mobile Hub, but that didn't allow me to use "Email address or phone number", so I deleted the User Pool and created it again. Then attached it to the existing Identity pool created by Mobile Hub.

I modified the aws-exports & aws-config files with the new user pool config.

Amplify.configure is called when the react native applicate is run.

I can use Auth.signUp to create accounts.

**Comment by mlabieniec** [comment]
@jeprojects can you check the App clients section of your user pool for the one you have attached to your Federated Identity? Make sure these match in identities you should see/have added user pool AND client ID. The client ID in user pools should NOT have "App client secret" also if they are matching. Let me know if this helps.

**Comment by jeprojects** [comment]
@mlabieniec Double checked all that. Still not working

I can signup from the React Native application, but can not login.

The account is created correctly in the user pool, and I can login to it from the console in appsync, so everything is fine there.

Are you sure the React Native Amplify library allows signin using a different User Pool and not the standard one Mobile Hub creates for your?

For example I am doing:

**How do you want your end users to sign in?**

[x] Email address or phone number - Users can use an email address or phone number as their "username" to sign up and sign in.

**Comment by jeprojects** [comment]
@mlabieniec I just updated the Amplify Library to the latest version released 4 days ago: v0.2.11 and it is working!

**Comment by powerful23** [comment]
Closing the issue.
