### ISSUE TITLE
🐛 Unable to Dismiss Numeric Keyboard: React Native

### ISSUE THREAD

**Issue by treyhakanson** [aws/aws-amplify#491]
With no keyboard dismissal on outside touch built into the core UI, situations like this arise, where the user is unable to dismiss the numeric keyboard without tapping into another input and hitting "Return":

<img style="height:300px;width:100%;display:block;background-size:contain;background-position:center;" src="https://user-images.githubusercontent.com/15150871/37726153-15b71a56-2d0b-11e8-98ed-8ec2e03a8be2.png" />

A simple solution to this is outlined [here](https://stackoverflow.com/questions/29685421/react-native-hide-keyboard). It boils down to wrapping the UI in a `TouchableWithoutFeedback` with the prop `onPress={Keyboard.dismiss}`. For example, the `showComponent` functions used by the components in ` aws-amplify/packages/aws-amplify-react-native/src/Auth` could use this component to wrap the returned `View`. Styles from the Theme would still apply as desired.

If there is a way to implement this without overwriting all the UI components, I apologize for this issue. But, at the moment I see no such solution.

**Comment by powerful23** [comment]
Closing as this is fixed in #530
