### ISSUE TITLE
Authentication Guide has broken links from broken jekyll script

### ISSUE THREAD

**Issue by dobon** [aws/aws-amplify#492]
Hi maintainers,

I see that in this commit: https://github.com/aws/aws-amplify/commit/2cb627724f019152a6df7a5fe500b98bbb8934fe#diff-29333497a683e4a2baba578d517b2078

Authentication guide was edited to dynamically change the URL's based on environment... regrettably, this is broken and results in broken links on github at the moment.

Cheers.

**Comment by mbahar** [comment]
@dobon Thanks for letting us know. All the links on the page are working fine now.
