### ISSUE TITLE
Code links in API docs point to a fork of the aws-amplify repo, not to the original

### ISSUE THREAD

**Issue by tyson-kubota** [aws/aws-amplify#496]
**Bug/Question:**

The API methods documented on https://aws.github.io/aws-amplify/api/ (e.g. https://aws.github.io/aws-amplify/api/classes/authclass.html#constructor) contain links to their corresponding source code, e.g. `Defined in Auth/Auth.ts:55`. However, clicking on these links goes to the `mbahar/aws-amplify` fork of the repo, instead of the `aws/aws-amplify` original (e.g. https://github.com/mbahar/aws-amplify/blob/2164c5f/packages/aws-amplify/src/Auth/Auth.ts#L55 instead of https://github.com/aws/aws-amplify/blob/2164c5f/packages/aws-amplify/src/Auth/Auth.ts#L55 ).

Did a wrong setting get included when generating these docs? Perhaps something from @mbahar 's local machine?

Example link on page:
<img width="784" alt="screen shot 2018-03-21 at 5 53 26 pm" src="https://user-images.githubusercontent.com/317573/37745206-cccdacb2-2d30-11e8-98b0-fd0c616e8625.png">

**What is the current behavior?**

The links to source code in the Amplify API docs point to the `mbahar/aws-amplify` fork rather than the original `aws/aws-amplify` repo.

**What is the expected behavior?**

I'd expect all links in the docs to point to the original `aws/aws-amplify` repo.

**Comment by mbahar** [comment]
@tyson-kubota  Thanks for letting us know. This is for `typedoc` automatically creates the links based on the forked repo. We will fix that.
