### ISSUE TITLE
adminLinkProviderForUser -> AliasExistsException and Internal Server Error.

### ISSUE THREAD

**Issue by kasperbe** [aws/aws-amplify#497]
I am in the process of migrating from a homemade user solution to cognito.
I'd like to migrate all of my users, I don't have too many so I chose doing by batch.

My strategy:
Do an import batch with the cognito console, uploading a CSV file.
Run a script that connects the users to the federation (Facebook).

I got to the connection step where things are derailed.
For simplification purposes I have a single user in my pool

I run: `adminLinkProviderForUser` for this user given params: 
```
     "DestinationUser": {
            "ProviderAttributeValue": user.username,
            "ProviderName": "Cognito"
     },
     "SourceUser": {
            "ProviderAttributeName": "Cognito_Subject",
            "ProviderAttributeValue": user.facebookId, 
            "ProviderName": "Facebook"
     },
     "UserPoolId":  poolId
```

This gives an error: `AliasExistsException`.

I found this highly confusing as there's only this single user in the entire pool. If i delete the user, obviously I get a User not found exception. 

If I try to log in using this user anyway I now get an Internal Server Error when redirected back from the facebook login page.

Additional info:

I created the user in the pool using the cognito interface, so he has status: 
```
User Status | Enabled / FORCE_CHANGE_PASSWORD
```
I don't expect this to be an issue...

**Comment by powerful23** [comment]
@kasperbe thanks for your feedback! The Cognito team is tracking the issue now.

**Comment by elorzafe** [comment]
Hi @yuntuowang what do you think?

**Comment by kasperbe** [comment]
@elorzafe Sorry, I didn't actually comment back on this issue, but I fixed this, as this was somehow an issue with my user pool. I deleted it and recreated it, and it worked. It had something to do with validation of properties in the pool. I removed all validation and all was good
