### ISSUE TITLE
Missing authenticator in react-native

### ISSUE THREAD

**Issue by digitaledge** [aws/aws-amplify#50]
It looks like Authenticator is not exported with the react-native module.

To reproduce:
import { Authenticator } from 'aws-amplify-react-native'; 

= Authenticator does not exist...

**Comment by mlabieniec** [comment]
@digitaledge did you link the libraries for react-native? See here:
https://github.com/aws/aws-amplify/blob/master/media/quick_start.md#react-native-development

**Comment by digitaledge** [comment]
Yes, i did.. auth is even working when using the HOC.
Just the Authenticator to custom the auth screens does not import.

**Comment by digitaledge** [comment]
I just had a deeper look in to your code and figured out that the export statement for the Authentificator is missing in aws-amplify-react-native/src/index.js.

Right now it can be imported like this:

import { Components } from 'aws-amplify-react-native';
const { Authenticator } = Components;

I will create some pull request this afternoon.
