### ISSUE TITLE
Auth.currentCredentials() always returning a promise when using .then

### ISSUE THREAD

**Issue by DocCaliban** [aws/aws-amplify#507]
In React map aws-amplify session data to props using redux connect.

My problem is that even when I use a .then I always get a promise returned, the result looks like so:

    Promise {<resolved>: CognitoUserSession}
      __proto__: Promise
      [[PromiseStatus]]:"resolved"
      [[PromiseValue]]:CognitoUserSession

And the code is as follows.

    import LoginForm from './LoginForm';
    import {Auth} from 'aws-amplify';

    const session = Auth.currentSession().then((res) => { return res });

I tried resolving with JSON.stringify, Promise.resolve(), etc...  and I always get just the promise back.

Also tried double .then thinking it might be a promise wrapped in a promise, but that is not the case either.  this happens with all call to the following Methods: 

- currentAuthenticatedUser
- currentCredentials
- currentSession
- currentUserCredentials
- currentUserInfo
- currentUserPoolUser

**Comment by powerful23** [comment]
@DocCaliban can you try ```Auth.currentSession().then(res => console.log(res));``` or ```const res = await Auth.currentSession();```. The way you are using will only return a promise to you.

**Comment by DocCaliban** [comment]
I tried using await, but still always get a promise.  

When I log the result, i do actually get the CognitoUserSession, but it's not very helpful in the console, and my session constant still returns a promise.

**Comment by richardzcode** [comment]
Hey @DocCaliban , Most of the Auth methods are async, returns a promise. So by assigning you will always get a promise. `.then` of a promise also returns a promise, that makes promise chain-able.

The logics with resolved value need to be implemented inside `.then` callback. Like this:

```
Auth.currentSession()
  .then(session => {
    // Do something with session.
  })
  .catch(err => console.log('error happened', err));
```

`await` keywords makes it possible to 'block' and wait until promise resolve. Then your calling method has to be async. Also don't forget to catch the exception.

```
async myFunc() {
  try {
    const session = Auth.currentSession();
    // Do something with session.
  } catch (err) {
    console.log('error happened', err)
  }
}
```

**Comment by mlabieniec** [comment]
@DocCaliban please feel free to reopen if you still have an issue here.
