### ISSUE TITLE
federated user has different IdentityId on different browser

### ISSUE THREAD

**Issue by rinick** [aws/aws-amplify#509]
using latest version of amplify js code in browser
google login, `Auth.federatedSignIn(...)`  then use private storage : `Storage.vault.put(..)`

I login with same google account on 2 different browsers. they don't shared same storage.
and when I console.log the users, their IdentityId are different. 

I then tried different computers, different browsers,  all create new IdentityId.

**Comment by powerful23** [comment]
@rinick Hi I tried in Chrome and Firefox and seems working for me. Can you give us more details like which browser?

**Comment by rinick** [comment]
when I send same user in Auth.federatedSignIn("google",response, user)
these are the results I got in differenet browsers
https://gist.github.com/rinick/0b206647adae2baf5dfb656b2c4e19c9

response is a map of {"access_token":xxxxx} which I got from google, which are 2 different value 
the user is same google userId string

**Comment by powerful23** [comment]
Did you call thie method like:
 ```
Auth.federatedSignIn("google", {
    token: your_access_token, 
    expires_at: the time when the token expires
}, user); ```

And also could you try the beta version by ```npm install aws-amplify@beta``` and open the debug mode to see if the credentials are loaded correctly?

**Comment by rinick** [comment]
when I use `token`, federatedSignIn failed.  seems it has to be `access_token`

**Comment by powerful23** [comment]
Or can you try the HOC component we provided? Also you can have a check about this [implementation](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/src/Auth/Provider/withGoogle.jsx)

**Comment by rinick** [comment]
yes, using that input finally fixed my issue

user paramter is supposed to be ` {email: profile.getEmail(), name: profile.getName() }`
and response parameter is supposed to be ` { token: id_token, expires_at }`

this is not mentioned in the doc at all, and this page even says it needs access token
https://docs.aws.amazon.com/cognito/latest/developerguide/google.html

**Comment by powerful23** [comment]
@rinick you may need to check this [doc](https://aws.github.io/aws-amplify/) which is the official one for AWS Amplify. And also we will improve the doc based on this issue, thanks!

**Comment by rinick** [comment]
@powerful23  yes, I've been using the doc, and this part really need more information
https://aws.github.io/aws-amplify/api/classes/authclass.html#federatedsignin

**Comment by mlabieniec** [comment]
docs updated, please let us know if you think it needs more clarification!
