### ISSUE TITLE
Federated identities put into my user pool (React Native)

### ISSUE THREAD

**Issue by Soren-Knudsen** [aws/aws-amplify#513]
I'm in the progress of building a React Native app and want to utilize Cognito for handling my users.

**Problem:**
When a user registers themselves via e.g. Facebook/Google in the app, I also want their information to be put in my User Pool.

**What I'm after:**
The flow I'm wishing for (which I haven't been able to find documentation for):
1. I utilize the Facebook SDK in the app and gets their Facebook token.
2. The token is sent off to Cognito which auth the user and puts them into the user pool.
3. An access token is sent back.

**Question:**
It that possible? And if so how?

**Comment by mlabieniec** [comment]
@Soren-Knudsen, currently our federation support is in React with HOCs and is done with Cognito Federated Identities. We are in the process of building similar native modules for React Native. We are hoping to complete this next sprint which will allow you to do this. It requires native modules in React Native.

**Comment by ganap** [comment]
Any update on the ETA for federated login HOC for React Native?
