### ISSUE TITLE
Refreshing the session without having a CognitoUser Object

### ISSUE THREAD

**Issue by tomshabtay** [aws/aws-amplify#514]
Do you want to request a feature or report a bug?
Request a feature

Hi, we are using Cognito in our Angular web app and I have a question about refreshing the token.
To refresh the token we are using refreshSession() from the CognitoUser Object like this:

```
    user.refreshSession(refreshToken,
      (err, session) => {

        refreshCallback(err, session);
      });
```

the problem is that when I close the browser I cant save the CognitoUser Object (only strings in cookies files).
is there another recommended way to refresh the token using only the username, password and refresh token?

**Comment by mlabieniec** [comment]
@tomshabtay if you use aws-amplify the session/s will be automatically refreshed for you. You can also retrieve current user with Auth.currentAuthenticatedUser().

For refreshing with the cognito SDK, there is a PR #499 that outlines refreshing the token, but with the sdk i do believe you would need to retrieve the current user first. If you are currently using the Cognito SDK, you should be able to include amplify as well and at least use these methods to retrieve your user and/or deal with your session. See [here](https://aws.github.io/aws-amplify/media/authentication_guide) for more details.
