### ISSUE TITLE
AmplifyConfig not applying headers set in APIOptions

### ISSUE THREAD

**Issue by jflayhart** [aws/aws-amplify#515]
I am using latest Amplify version for react and even following documentation and sifting through the API docs, the supplied headers are NOT applied to the request when set within [APIOptions](https://aws.github.io/aws-amplify/api/interfaces/apioptions.html#headers).

For example, my AWSConfig looks like this:
```
Auth: {...},
// APIOptions
API: {
    // THIS IS NOT IN REQUEST HEADERS!
    headers: {
      'x-api-key': string,
    },
    endpoints: [{
      name: string,
      endpoint: url,
    }],
    credentials: {
      accessKeyId: string,
      secretAccessKey: string,
      sessionToken: string,
    },
},
```

For me, the ONLY way for the headers to be applied is to set it per request, which to me seems unnecessary and verbose:
```
// THIS WORKS!
const options = { headers: { 'x-api-key': string }}
API.get(appName, path, options)
```

I would expect the headers in the main [APIOptions](https://aws.github.io/aws-amplify/api/interfaces/apioptions.html#headers) config object (as part of Amplify.configure()) will be applied to EVERY request. But they are never applied.

Here's some debug info:
<img width="1438" alt="amplify-debug" src="https://user-images.githubusercontent.com/6808172/37876940-6e90e8bc-3019-11e8-85c7-f4b7d8106d38.png">

**Comment by mlabieniec** [comment]
@jflayhart API configuration doesn't support sending the APIOptions i.e. headers. This is passed to the method directly i.e. API.get() configuration takes [manual or auto config from aws-exports](https://aws.github.io/aws-amplify/media/api_guide).

**Comment by jflayhart** [comment]
Then the API docs for [APIOptions](https://aws.github.io/aws-amplify/api/interfaces/apioptions.html) ([and here's the code](https://github.com/mbahar/aws-amplify/blob/2164c5f/packages/aws-amplify/src/API/types/index.ts#L63)), which are part of the [AmplifyConfig](https://aws.github.io/aws-amplify/api/interfaces/amplifyconfig.html#api), need to change because that is very misleading. 

It would be extremely helpful for this to become a feature. Most APIs (i.e. axios, [which Amplify uses](https://github.com/mbahar/aws-amplify/blob/2164c5ff903d0e68f52874507a42d10e93ea4753/packages/aws-amplify/src/API/RestClient.ts#L19)) allow setting default headers and extending/overwriting them. It's not that great to have to configure headers, etc for EVERY request. I'm already sensing a refactor-nightmare in my codebase ;)

Thanks for the quick reply!

**Comment by elorzafe** [comment]
It was published aws-amplify@unstable with custom_header support during configure. I will close this issue for now. Please feel free to reopen if you have any issues with this.

**Comment by souuu** [comment]
We still don't have this on the stable version ?
