### ISSUE TITLE
What's the difference between aws-amplify and the Node.js SDK?

### ISSUE THREAD

**Issue by satiewaltz** [aws/aws-amplify#516]
Hello! Sorry if this question is a no-brainer. But after reading the documentation and website I didn't really get the purpose of this library. 

What's the difference between this library and using the Node.js SDK? What are the main goals aws-amplify is trying to achieve? Is it supposed to offer a cleaner API to interact with commonly used AWS services? Again sorry and thanks!

**Comment by lunaroyster** [comment]
Disclaimer: I'm new to this too.

Reading the [aws-amplify introduction](https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-aws-amplify-a-declarative-javascript-library-for-cloud-development-with-mobile-or-web-applications/), one word used is declarative.

>Declarative programming is when you write your code in such a way that it describes what you want to do, and not how you want to do it.

Aws-amplify seems to abstract away features provided by aws-sdk. Looking at cognito for instance, The [amplify version](https://aws.github.io/aws-amplify/media/authentication_guide) seems to be much simpler to use than the [aws-sdk](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html) one. 

I'd like some confirmation on this.

**Comment by mlabieniec** [comment]
Thanks @lunaroyster, the wiki also has an overview of the inception: 
https://github.com/aws/aws-amplify/wiki

**Comment by mbahar** [comment]
@satiewaltz, in addition to previous comments,
- AWS Amplify is 'client-first' with support for modern JavaScript workflows and React Native.
- Comes with ready-to-use implementations that you can be up and running in minutes. (Auth, Storage ...)

**Comment by satiewaltz** [comment]
Hi everyone,

Thank you for your explanations! I now have a better understanding of the purpose behind aws-amplify, why it exists, and how it differs from the Node.js SDK. The wiki hits home about what are the motivations behind the library. Like how it aims to enhance development experience through a declarative API design, reduction in boilerplate code, and simplifying various methods the SDK provides. Again, thank you for the pointers and information. 

Closing this issue! 🎉
