### ISSUE TITLE
[amazon-cognito-identity-js] "es" dir missing in NPM package.

### ISSUE THREAD

**Issue by simonbuchan** [aws/aws-amplify#517]
See [unpkg.com's listing](https://unpkg.com/amazon-cognito-identity-js@2.0.2/) - although the directory exists in source (a bad practice, but I won't get into it here), the published package does not include it.

This is potentially an issue for bundlers, as the package.json lists `es/index.js` as the `module` entrypoint - either they will error or not be able to do as good tree-shaking.

To be frank, I have no idea why it's missing from the bundle - the directory existed when it was packaged, `.npmignore` is empty and the package.json doesn't have a `files` entry: [which is what is listed here](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) as the reasons it might be missing. Is there something funky in the packaging workflow that could be deleting it before `npm pack/publish`?

**Comment by dfrkp** [comment]
Note: For what it's worth, the folder is only missing starting v2.0.2

**Comment by simlu** [comment]
This breaks our tests. Would love to see this fixed.

**Comment by powerful23** [comment]
@simonbuchan sorry about that. We will publish a new version to fix it.

**Comment by powerful23** [comment]
Closing as this should have been fixed in the latest version of Cognito.
