### ISSUE TITLE
SNS push notification 

### ISSUE THREAD

**Issue by cosmosof** [aws/aws-amplify#52]
is this service linked to the library? I can't find it here

**Comment by mlabieniec** [comment]
@cosmosof SNS is not currently part of the library. Amazon Pinpoint is currently included for [Analytics](https://github.com/aws/aws-amplify/blob/master/media/analytics_guide.md) and we are working towards supporting push notifications with Pinpoint as well.

**Comment by cosmosof** [comment]
Pinpoint sns awesome. But I like to able to send single device notification, which will be core feature of the app.

**Comment by mlabieniec** [comment]
Pinpoint currently now supports direct device messaging with device token. The new Push notification support for react native supports this as well. Please re-open if you feel appropriate.
