### ISSUE TITLE
Authentication documentation error

### ISSUE THREAD

**Issue by funkfinger** [aws/aws-amplify#520]
The signup section of [https://aws.github.io/aws-amplify/media/authentication_guide#working-with-user-attributes](https://aws.github.io/aws-amplify/media/authentication_guide#working-with-user-attributes) has attributes that **look** like standard attributes, but are not. I believe according to [this](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#cognito-user-pools-standard-attributes)

```
first_name
last_name
nick_name
```

should be

```
given_name
family_name
nickname
```

Possibly fixed:

```
Auth.signUp({
    'username': 'jdoe',
    'password': 'mysecurerandompassword#123',
    'attributes': {
        'email': 'me@domain.com',
        'phone_number': '+12128601234', // E.164 number convention
        'given_name': 'Jane',
        'family_name': 'Doe',
        'nickname': 'Jane'
    }
});
```

**Comment by funkfinger** [comment]
I assume that the [aws.github.io]( https://aws.github.io/aws-amplify/media/authentication_guide#working-with-user-attributes) site is getting generated from [the markdown file in the repo](https://github.com/aws/aws-amplify/blob/master/docs/media/authentication_guide.md)? If so, should I fix?

**Comment by powerful23** [comment]
@funkfinger yes you can do that with a pull request. Thanks!

**Comment by mbahar** [comment]
Thanks @funkfinger, your correction has been approved.
