### ISSUE TITLE
Unable to run awsmobile init and error on s2-choose-strategy.js:104

### ISSUE THREAD

**Issue by ykbryan** [aws/aws-amplify#521]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
I am unable to do `awsmobile init` at the project folder. 
![awsmobile-init-failed](https://user-images.githubusercontent.com/1001146/37885558-8063b91e-30e8-11e8-83f0-69f689f8e6da.png)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
Able to init the awsmobilejs within the project folder.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Version of Amplify and other dependencies:
```
"aws-amplify": "^0.2.9",
"aws-amplify-react-native": "^0.2.5",
"expo": "^25.0.0",
"native-base": "^2.3.10",
"react": "16.2.0",
"react-native": "0.52.0"
```
OS: Mac OS X, Sierra. 

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by elorzafe** [comment]
Also which node version are you using?  I think that should be the problem. I am using 8.9.3

**Comment by ykbryan** [comment]
I’m using node version 6.11.0, npm version 4.6.1 on the iterm2

**Comment by Samuel-Chan** [comment]
I has the same issue before upgrading node version (was using v7.2.1)
It works fine after upgrading to the newest version

**Comment by ykbryan** [comment]
Probably? If so, this needs to be documented in the README.md

**Comment by mlabieniec** [comment]
@mbahar can we add to the docs the node requirements for cli
