### ISSUE TITLE
Loading an expired federated user's token from cache leave the authenticator stuck in an invalid state

### ISSUE THREAD

**Issue by Brulogaz** [aws/aws-amplify#524]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Tested with google:  If the cache provide the user with an expired token he will be stuck in an invalid state preventing the signout method from working.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

Log in with google, wait for the token to expire, reload the page. You get an expired token which won't refresh or go away without clearing your browser cache.

What is the expected behavior?

The cache should not return an expired token if it has no means to refresh it. 

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
0.2.12. I don't think it worked in previous versions.

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by Brulogaz** [comment]
The token refresh fail because googleAuth.currentUser.get() return null while trying to refresh the token.  

I assume it is impossible to refresh an expired token when loading back the app without prompting the user or a refresh token.  The currentuser is always loaded from cache, even while the app is running, which makes it a bit harder to distinguish if the refresh was caused by the app reloading.

I think simply clearing the cache when token refresh fail should be enough to fix this.

**Comment by powerful23** [comment]
@Brulogaz Good catch! We didn't catch this error in the ```signOut``` method. I have created a pr to fix this issue. As you suggested, the idea is to clear out the cache so that users will be logged out on reloading the page once they cannot get the federation credentials from cognito. You can also catch this case when you call ```Auths.currentCredentials()``` and handle this case on your need.

**Comment by powerful23** [comment]
Closing the issue as it should have been fixed in the latest version.
