### ISSUE TITLE
[Help Wanted] First react native app fails with federatedinfo error 

### ISSUE THREAD

**Issue by TheRealRed7** [aws/aws-amplify#535]
Creating my first React Native app which can connect to AWS services with Amplify and I am running into problems with authentication.

On **npm start** the app builds to 100% but then throws the following errors:

**09:43:03: Finished building JavaScript bundle in 98737ms
09:43:11: Get item: key is federatedInfo with options undefined
09:43:11: Get item: key is federatedInfo with options undefined
09:43:11: Get item: key is federatedInfo with options undefined
09:43:11: Get item: key is federatedInfo with options undefined**

These are the steps I followed:

**create-react-native-app RNTuesday**
**cd RNTuesday**
**mkdir src**
**awsmobile configure** (put in credentials)
**awsmobile init** (entered app details)
**npm install --save aws-amplify**

then added the following to my app.js:

**import Amplify from 'aws-amplify';
import aws_exports from './src/aws-exports';
Amplify.configure(aws_exports);**

Logged into AWS Mobile Hub. Selected project and added React app.
I then linked the app to the hub using: **awsmobile init 15c482e2-2c3c-11e8-8692-sometext3**

CLI responded : "Successfully linked AWS Mobile Hub project: happ1-datetime!" 

However when I run npm start it throws the federatedinfo errors above.

I have attached redacted app.js and aws-export files. Please take a look if you have time.

Thanks,

![aws-export](https://user-images.githubusercontent.com/36988589/37964100-3cc693cc-31b8-11e8-89bf-674936d20534.PNG)
![app](https://user-images.githubusercontent.com/36988589/37964102-3cdf18e8-31b8-11e8-92cf-72ca11f1654e.PNG)

**Comment by powerful23** [comment]
@TheRealRed7 These messages are not errors. You need to import ```withAuthenticator``` from ```aws-amplify-react-native``` and you also need to link the cognito library. Please check this [doc](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/react-native-add-user-sign-in.html)

**Comment by TheRealRed7** [comment]
Thank you for the input. I followed your advice and the doc as suggested. 

The app still outputs the federatedInfo messages but I am going to close this question and create a new one as I realise now that my question is unclear. 

Thanks again.
