### ISSUE TITLE
400 after adding custom attribute

### ISSUE THREAD

**Issue by jkettmann** [aws/aws-amplify#536]
I created a user pool and realized after some while that I needed a new custom attribute. So I added the new attribute to my existing user pool. Now I get a `400` status code when I try to set the new attribute on some user

```
Auth.updateUserAttributes(user, { 'custom:myNewAttribute': 12345 });
```

When I create a new user pool and add the custom attribute before adding any users everything works as expected.

Does this mean, that I need to decide upfront on all potential custom attributes? What do I do when I need to edit an existing production user pool?

**Comment by powerful23** [comment]
@jkettmann You can also add this attribute first in the user pool console and then that call should work

**Comment by Jun711** [comment]
Should custom attribute keys have prefix **custom:** when I signUp or updateUserAttribute using Amplify? 
I got this error: `A client attempted to write unauthorized attribute` when I tried to signUp a mutable custom attribute. 

```
Auth.signUp({
      username: email,
      password: pwd,
      attributes: {
        nickname, 'created_date' : currentDate
      }
    });
```

**Comment by mlabieniec** [comment]
@mbahar can we add a note about this in the docs related to Auth / Custom Attributes
