### ISSUE TITLE
Aws_Amplify "No Credentials" Error

### ISSUE THREAD

**Issue by MohammedShabeeb** [aws/aws-amplify#537]
I am using AWS amplify to connect with Mobile Hub back end. On connecting with S3/API i am getting a error back "No Credentials".

I already set "Enable Un Authenticated Access" in the Federated Identity pool. Please let me know whether AWS Amplify is supporting "Un Authenticated Access"? or Is there any alternative to acheive this behaviour. I also would like to integrate with Lex too.

**Comment by mbahar** [comment]
@MohammedShabeeb First-class Lex support is on the roadmap. 

Until then, you can use 'AWS Service Interface Objects' as documented here;

https://aws.github.io/aws-amplify/media/quick_start#working-with-aws-service-interface-objects
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/LexRuntime.html

**Comment by MohammedShabeeb** [comment]
Thank you for the Information.
But what about the Anonymous user access to Cognito. Currently 'No Credentials' Error is throwing back while connecting with API. In Federated Identity Pool Anonymous access is enabled.

**Comment by MohammedShabeeb** [comment]
Got the answer, it was a mistake from my side. My Un Authenticated roles trust policy was not correct. When i added trust policy to access the Cognito for un authenticated users the error is not coming

**Comment by elorzafe** [comment]
Hi @MohammedShabeeb amplify now support Amazon Lex on Interactions category. Take a look!
https://aws.github.io/aws-amplify/media/interactions_guide
