### ISSUE TITLE
Login using Identity Provider i.e Google

### ISSUE THREAD

**Issue by engharb** [aws/aws-amplify#542]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
I still using aws/amazon-cognito-identity-js.
I want to login in my Mobile App to Cognito Pool using i.e my google credentials. When I logged in successfully using my google account I call the following code
```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      'IdentityPoolId': aws_cognito_identity_pool_id,
      'Logins': {
        'accounts.google.com': result.idToken
      }
    });

alert(AWS.config.credentials);
```

the result:  IdentifierId is null.

Question:
How can I authenticate my current google account to AWS-Cognito-Pool?

Thanks

**Comment by powerful23** [comment]
@engharb you need to load your credentials after construct it by ```AWS.config.credentials.getPromise()```. Please check the details [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html#getPromise-property)

**Comment by engharb** [comment]
@powerful23 thank you very much. But I still facing problems. Here I will type the parts of signing-in using the google account and please correct me if there is error.

```
//# login.ts

loginWithGoogle() {

      this.googleplus.login({})
          .then(
              res => {
                  console.log(res);
                  alert("success");
                  alert(JSON.stringify(res));
                  this.user.loginAwsGoogle(res.idToken, res.displayName);
              }
          ).catch(
              err =>
              {
                  console.error(err);
                  alert("fail");
                  alert(JSON.stringify(err));
              }
      );
  }
```
then
```
//# user.ts
loginAwsGoogle(idToken, username) {
    this.cognito.makeGoogleCredentials(idToken, username);
  }
```
then
```
//# aws.cognito.ts
getUserPool() {

    return new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool({
            "UserPoolId": aws_user_pools_id,
            "ClientId": aws_user_pools_web_client_id
    });
  }

makeUser(username) {
    return new AWSCognito.CognitoIdentityServiceProvider.CognitoUser({
      'Username': username,
      'Pool': this.getUserPool()
    });
  }


makeGoogleCredentials(idToken, username) {

    AWSCognito.config.credentials.getPromise().then(
        data => {

          AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: aws_cognito_identity_pool_id,
            Logins: {
              'accounts.google.com': idToken
            }
          });

          alert("Data Correct");
          const user = this.makeUser(username);

            alert(JSON.stringify(data));
            alert(JSON.stringify(user.pool.client));

        },
        error => {
          alert("Data Error");
          alert(JSON.stringify(error));

        }
    ).catch(
        err => {
          alert("Catch Error");
          alert(JSON.stringify(err));

        }
    );
```

I do not know why I got ```config->credentials->expired:true``` is expired????

Do you have a complete example or idea, let me know about your inspiration.  

regard.

**Comment by powerful23** [comment]
@engharb There are two "pool" in Cognito: User pool and Identity pool. From the code you provided I think you are actually using Google OpenId to get a federated identity from the Identity Pool. If you want to login in that way, you can either use [aws-amplify](https://aws.github.io/aws-amplify/media/authentication_guide#comment-3829447888) or write your own code. You can have look at this [implementation](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L1121) which may give you some help.

**Comment by engharb** [comment]
@powerful23 
I appreciate yours, thanks a lot. But i still wondered why AWS Cognito login stuff is difficult as it is. They explain binding the Cog. Pool with Social Providers as it is a piece of cake, while it is not. And I have seen videos and docs for other Clouds i.e ionic one, the authentication issue especially with FB, google ... is very easy in few lines and calling a function like: FacebookAuthDetails which takes care about adding the user to cloud user pool. If you still have in mind an example that helps in saving my time regarding Cognito User Pool and Identifier it would be very appreciated and helpful.

regards,

**Comment by powerful23** [comment]
@engharb yeah it's a bit trivial to figure all the things out. That's why we are developing AWS Amplify as well as Awsmobile CLI to make life much easier for developers. Currently we are working on to integrate the Cognito hosted UI into our library and give users detailed documentation about how to setup with those stuff and that won't be too far. Thanks for your feedback!

**Comment by engharb** [comment]
@powerful23 Thanks a lot for details. But I have another Idea and I do not know if it works. I tried to get the IdentityId of unauthenticated Facebook on AWS-External-provider and then call ```getCredentialsForIdentity()```. Unfortunately it gives me error as e is not a function.
```
let params = {
                    IdentityId: AWSCognito.config.credentials.cognito.config.credentials.params.IdentityId,
                    Logins: {
                        'graph.facebook.com': accessToken
                    }

                };

AWSCognito.config.credentials.getCredentialsForIdentity(params, function(err, data) {
                    if (err) {
                        alert(JSON.stringify(err));
                    } // an error occurred
                    else {
                        alert(JSON.stringify(data));
                    }           // successful response
                });

```

Do you have any Idea if that does work or not?

regards,

**Comment by powerful23** [comment]
@engharb I am not sure as I didn't try this way to get the credentials. But can you make sure ```AWSCognito.config.credentials``` is an instance of ```CognitoIdentityCredentials```?

**Comment by engharb** [comment]
@powerful23 I would expect when I call
```
AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: aws_cognito_identity_pool_id,
            Logins: {
              'facebook provider identity':accessToken
            }
          });
```
to get a sessionKey contains the three different key, id/access/refreshTokenkey, but unfortunately I do not.
Some references mentioned that but I do not know how they get these three keys.

**Comment by engharb** [comment]
@powerful23 I also tried 
```
makeGoogleCredentials(idToken, username) {

AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: aws_cognito_identity_pool_id,
            Logins: {
              'accounts.google.com': idToken
            }
          });

    AWSCognito.config.credentials.getPromise().then(
        data => {
          alert("Data Correct");
          const user = this.makeUser(username);

            alert(JSON.stringify(data));
            alert(JSON.stringify(user.pool.client));

        },
        error => {
          alert("Data Error");
          alert(JSON.stringify(error));

        }
    ).catch(
        err => {
          alert("Catch Error");
          alert(JSON.stringify(err));

        }
    );
```

the result contains the identityId with expired:true ????!

**Comment by engharb** [comment]
@powerful23 thank you. I am waiting for your updates soon. But I still have a question what if I do not what to use Cognito Hosted UI feature.?

**Comment by engharb** [comment]
@itrestian @powerful23 
after getting sessionToken, secretAccessKey and accessKeyId. Is it possible to authenticateUser with these keys instead of 'username and password'? 

if yes, How?


regards.

**Comment by engharb** [comment]
@powerful23 
bug

I want to integrate/install Aws-Amplify and use hosted UI in my Ionic mobile project. Project src/Assest contains the following files:
amazon-cognito-identity.min.js, aws-sdk.js ...

I have run ```$ npm install aws-amplify --save```. And when I start run ```$ ionic cordova run android``` I got the following exception:
```
typescript: node_modules/aws-amplify/lib/Analytics/types/Analytics.d.ts, line: 19 
            In ambient enum declarations member initializer must be constant expression. 

      L18:  export declare enum SessionState {
      L19:      START = "START",
      L20:      STOP = "STOP",
```

The goal is:
to use AWS-Amplify for authenticating user in login-process (using cognito-user-pool or federated-identifier).
Do i need to install aws-amplify completely? 
and Is there a complete example?

regards,

**Comment by powerful23** [comment]
@engharb you can check this [sample](https://github.com/ionic-team/starters/tree/master/ionic-angular/official/aws). For that error we will make a fix on that, thanks.

**Comment by dhumeniuk** [comment]
@powerful23, you mention adding support for Cognito Hosted UI. Is there a issue tracking this feature? I would be interested in being able to use this.

**Comment by powerful23** [comment]
@dhumeniuk It has been merged in master branch but not published yet. We are going to publish a beta version this week.

**Comment by engharb** [comment]
@powerful23 thanks a lot for your help and responses. I am eagerly looking for the coming feature utilizing hosted UI (especially in social login). and regarding to the sample that you announce I have successfully configured and implemented the complete login process for our Mobile App and Web App using aws-cognito-sdk.js . 

Now I am thinking weather to use ```aws-cognito-sdk.js``` directly or use ```aws/amplify```. 
In case of ```amplify``` (as upper layer depends on cognito-sdk.js) I found it easier than using directly the functions in ```aws-cognito-sdk.js``` and much less code.

Do you advance me to use ```aws/amplify``` or keep working directly with ```aws-cognito-sdk.js``` for authentication process?

regards,

**Comment by engharb** [comment]
@powerful23 I am sorry for asking you frequently. I am able to use 
```
Auth.federatedSignIn(
            'facebook',
            {
                token: authResult.accessToken,
                expires_at:authResult.expiresIn
            },
            {
                email:data.email,
                name:data.id
            }
        );
```
The result consists of accessKeyId, sessionToken .... The Question : 
Is it possible to use this sessionKey or token by using pre-defined function in order to get (idToken, accessToken, refreshToken) and automatically assign/store those values in the session?

I think such a function is needed to be implemented or workaround?

regards,

**Comment by Birowsky** [comment]
@powerful23 Hey there, thanx for actively helping out. In Cordova apps, we cannot use the Cognito hosted UI for Google auth. What is the recommended approach for auth with Google?

I went [this route ](https://stackoverflow.com/a/51050200/592641)with no success.
What do you recommend?

**Comment by powerful23** [comment]
@Birowsky if you only want to get a valid AWS credential from Cognito Federated Identity Pool, then `Auth.federatedSignIn` would be enough for you to retrieve one once you provide the token from Google. Check this: https://aws.github.io/aws-amplify/media/authentication_guide#enabling-federated-identities and also this: https://docs.aws.amazon.com/cognito/latest/developerguide/google.html#JavaScript

**Comment by Birowsky** [comment]
@powerful23 ah, no, I need to end up with a session from a user pool, not identity pool. Any input there?

**Comment by yuntuowang** [comment]
Hi @Birowsky, we haven't supported this feature yet. It is on our roadmap. Thanks!

**Comment by Birowsky** [comment]
@yuntuowang oh dear.. just spent a day on it :} Good to know it's being considered. Where do I track progress on it? Any vague estimation?

**Comment by yuntuowang** [comment]
It is hard to comment on the delivery time at this point. Once this feature is released, I will post on this issue!  TOKEN and AUTHORIZATION endpoints are for cognito flows.

**Comment by Birowsky** [comment]
For anyone interested, I logged the [Google auth in Cordova issue here](https://github.com/aws/aws-amplify/issues/1126). Let's hope for results as soon as possible. Have a good one!

**Comment by engharb** [comment]
@yuntuowang I hope that I will be confirmed about the coming features. Is there a way to decode and verify the Identity-Pool sessionToken using i.e PHP-SDK? I solved that for user-pool JWT but not for Identity-pool sessionToken!.

**Comment by MadhavVarshney** [comment]
Hi @powerful23 , Hope you are doing good, Can you please help to implement the same using `aws-cognito-sdk.js` for my ionic.
ps: I am a beginner
