### ISSUE TITLE
Feature request: user's created time and last updated time.

### ISSUE THREAD

**Issue by Jun711** [aws/aws-amplify#549]
Do you want to request a feature or report a bug?
To get user's createdTime and lastUpdatedTime.

What is the current behavior?
 user's createdTime and lastUpdatedTime aren't exposed via any method. 
I have tried with the following 2 methods (with my required attributes being name and email): 
with userAttributes, I can get sub, email_verified, name, email
with currentUserInfo, I can get id, username and a list of attributes(email_verified, name, email)

What is the expected behavior?
expect to get it via currentUserInfo

Which versions of Amplify, and which browser / OS are affected by this issue? 
aws-amplify 0.2.14

**Comment by powerful23** [comment]
@Jun711 No you can't. You can only check this info in the Cognito console -> users and groups

**Comment by Jun711** [comment]
@powerful23 so, at the moment, if I want to access createdTime and lastUpdatedTime, I have to use [aws-sdk CognitoIdentity](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#describeIdentity-property), right? 
Thanks

**Comment by yuntuowang** [comment]
Hi @Jun711, it is not available by using cognito-identity package directly either. You can only check this info by logging to cognito console and check the "Users and groups" tab to see the "createdTime and lastUpdatedTime" info of every user.

**Comment by powerful23** [comment]
@Jun711 Yeah I think you can try that.

**Comment by powerful23** [comment]
@Jun711 But it seems like that's only for the Cognito identity not Cognito user.

**Comment by yuntuowang** [comment]
Hi @powerful23, are you talking about amazon-cognito-identity-js which is under Amplify, or aws cognito identity service sdk?

**Comment by powerful23** [comment]
@yuntuowang I mean the aws-sdk CognitoIdentity is only for the identities in the Cognito identity pool right?

**Comment by yuntuowang** [comment]
@powerful23, yes.

**Comment by Jun711** [comment]
@yuntuowang @powerful23, in that case, is there no way to retrieve createdTime and lastUpdatedTime?

**Comment by yuntuowang** [comment]
Hi @Jun711, for Cognito User Pool service, we don't currently support retrieving createdTime and lastUpdatedTime in JS SDK. But we can mark this as a feature request!

**Comment by Jun711** [comment]
thanks @yuntuowang and @powerful23. Hope that it would be supported soon. 
 I guess, for now, I have to use a custom attribute to save createdTime.

**Comment by yuntuowang** [comment]
Hi @Jun711, sure, that is a good work around solution!
