### ISSUE TITLE
Questions / need clarification - Which sdk should I use for Cognito? 

### ISSUE THREAD

**Issue by Jun711** [aws/aws-amplify#551]
Thank you for providing amplify. 
However, I would like some clarification if it is possible. There are amplify, amazon-cognito-identity-js, aws-sdk (CognitoIdentityServiceProvider) and maybe other sdks that support cognito that I am not aware of. It would be great if someone could clarify these for me. 

1) Will amplify cover all amazon-cognito-identity-js functions in the near future? 
Is there a timeline?

2) Amplify seems to have quite a few modules now: Auth, API, PubSub, Storage etc
What is the direction? 

3) Is there documentation for amazon-cognito-identity-js? like the one for [amplify](https://aws.github.io/aws-amplify/api/globals.html#cognitouserattribute)?
For example, I saw on amazon-cognito-identity-js that on v1.0.0 that the following function is supported but there is no example or documentation for the method? 
Search users in your pool using user attributes

4) What about [AWS.CognitoIdentityServiceProvider](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#createUserPool-property) from aws-sdk plugin? Should I use this and amplify together to get all the functions that I want?  For example, [listUsersInGroup](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#listUsersInGroup-property)
It seems to be the first sdk that supports all the functions available with cognito. 

5) Which sdk should I use in my Angular web app to support Cognito? 
Amplify has been great as it supports quite a few services that I am using.  

Thank you!

**Comment by Jun711** [comment]
Hi @yuntuowang, maybe you know the answer to 1 and 3? Thanks

**Comment by Jun711** [comment]
Thanks @yuntuowang.
yea, i was aware of that. The README states that v1.0.0 supports `Search users in your pool using user attributes` function there is no example or documentation for the method.
in the README, there are only use cases, there isn't a doc similar to amplify where I can see all the methods available. Is that right?
Thanks

**Comment by yuntuowang** [comment]
Hi @Jun711, yes, in the README.md, there are all the use cases with the code snippet showing how you code.

**Comment by Jun711** [comment]
Thanks @yuntuowang 
 If it is ok, could you please share the method name for this `Search users in your pool using user attributes` function? I think I must have missed it.
There are 
Use case 8. Update user attributes for an authenticated user.
Use case 5. Retrieve user attributes for an authenticated user.
There doesn't seem to have `Search users in your pool using user attributes` or something similar.

**Comment by yuntuowang** [comment]
Hi @Jun711, we have "Search users in your pool using user attributes" feature for Cognito User Pool service. You can do this on Cognito console or low level SDKs with developer credentials. 

We don't support this on this JS SDK.

**Comment by Jun711** [comment]
@yuntuowang I see. thanks.
