### ISSUE TITLE
Cannot find type definition file for 'paho-mqtt'. 

### ISSUE THREAD

**Issue by ashishsoni** [aws/aws-amplify#552]
typescript: node_modules/aws-amplify/lib/PubSub/Providers/MqttOverWSProvider.d.ts, line: 1 
            Cannot find type definition file for 'paho-mqtt'. 

       L1:  import { Client } from 'paho-mqtt';
       L2:  import * as Observable from 'zen-observable';

[packagejson.txt](https://github.com/aws/aws-amplify/files/1861205/packagejson.txt)

**Comment by Jun711** [comment]
You need to install these for type definitions
npm i –save-dev @types/zen-observable
npm i –save-dev @types/paho-mqtt

**Comment by ashishsoni** [comment]
for which module, i ran the command as you provided but same error


[13:29:55]  typescript: node_modules/aws-amplify/lib/PubSub/Providers/MqttOverWSProvider.d.ts, line: 1 
            Cannot find type definition file for 'paho-mqtt'. 

       L1:  import { Client } from 'paho-mqtt';
       L2:  import * as Observable from 'zen-observable';

[13:29:55]  typescript: node_modules/aws-amplify/lib/PubSub/Providers/MqttOverWSProvider.d.ts, line: 2 
            Cannot find type definition file for 'zen-observable'. 

       L1:  import { Client } from 'paho-mqtt';
       L2:  import * as Observable from 'zen-observable';
       L3:  import { AbstractPubSubProvider } from './PubSubProvider';

[13:29:55]  typescript: node_modules/aws-amplify/lib/PubSub/Providers/PubSubProvider.d.ts, line: 1 
            Cannot find type definition file for 'zen-observable'. 

       L1:  import * as Observable from 'zen-observable';
       L2:  import { PubSubProvider, ProvidertOptions } from '../types';

[13:29:55]  typescript: node_modules/aws-amplify/lib/PubSub/PubSub.d.ts, line: 1 
            Cannot find type definition file for 'zen-observable'. 

       L1:  import * as Observable from 'zen-observable';
       L2:  import { PubSubProvider, PubSubOptions, ProvidertOptions } from './types';

[13:29:55]  typescript: node_modules/aws-amplify/lib/PubSub/types/Provider.d.ts, line: 1 
            Cannot find type definition file for 'zen-observable'. 

       L1:  import * as Observable from 'zen-observable';
       L2:  import { ProvidertOptions } from './PubSub';

**Comment by Jun711** [comment]
You need to install these for type definitions
`npm i –save-dev @types/zen-observable`
`npm i –save-dev @types/paho-mqtt`

my previous comment had formatting issue.

**Comment by richardzcode** [comment]
@ashishsoni I believe with @Jun711 updated commands the issue should be fixed. Please reopen this issue if problem remains.

**Comment by amiram** [comment]
@Jun711 @richardzcode Adding types of packages is the responsibility of the package developer, not the consumer, otherwise any package consumer will find himself adding many types for packages he doesn't know about, and he doesn't know when to update or delete them in case their usage was changed by the package developer. Those two definitions should be included by aws-amplify in the `dependencies` section.
More info: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by mwarger** [comment]
I'm seeing this behavior again on the latest version of aws-amplify - can this issue be investigated once more?

**Comment by mwarger** [comment]
@richardzcode @powerful23 I just wanted to bump this in case it being closed reduces visibility.  I think this should be re-opened.  The recent changes to the library have taken out the type definitions by apparently removing the third-party dependency and dropping the file in the `src/vendor` folder.  Please let me know if I can help provide any additional information.

**Comment by powerful23** [comment]
@mwarger thanks for the feedback, investigating.

**Comment by mwarger** [comment]
@powerful23 can this be re-opened?

**Comment by haverchuck** [comment]
@mwarger -  I'm continuing this discussion on #1836 .

**Comment by powerful23** [comment]
@mwarger this issue should have been fixed by #1821

**Comment by kylekirkby** [comment]
I'm still getting this issue - any ideas people?

**Comment by powerful23** [comment]
@kylekirkby are you using the latest version?
