### ISSUE TITLE
API doesn't work with local (or non-AWS) endpoints

### ISSUE THREAD

**Issue by epicfaace** [aws/aws-amplify#560]
I'm running an AWS API locally (through Chalice) but can't get it to work with AWS Amplify.

In my config, I have:
```
  API: {
    endpoints: [
      {
        name: "ENDPOINT",
        endpoint: "http://localhost:8001/"
      }
    ]
  }
```
And my code calls this function:
```
        API.get("CFF_DEV", "/forms", {}).then(e => {
            console.log("got", e);
        });
```

Here's the error I'm getting:
```
Unhandled promise rejection 
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
Stack trace:
fromObject@http://localhost:8000/scripts/dist/vendor.bundle.js:148017:9
from@http://localhost:8000/scripts/dist/vendor.bundle.js:147843:10
Buffer@http://localhost:8000/scripts/dist/vendor.bundle.js:147819:10
update@http://localhost:8000/scripts/dist/vendor.bundle.js:32550:41
encrypt@http://localhost:8000/scripts/dist/vendor.bundle.js:20357:12
get_signing_key@http://localhost:8000/scripts/dist/vendor.bundle.js:20491:75
sign@http://localhost:8000/scripts/dist/vendor.bundle.js:20563:23
./node_modules/aws-amplify/lib/API/RestClient.js/RestClient.prototype._signed@http://localhost:8000/scripts/dist/vendor.bundle.js:16785:29
./node_modules/aws-amplify/lib/API/RestClient.js/RestClient.prototype.ajax/</</<@http://localhost:8000/scripts/dist/vendor.bundle.js:16710:63
run@http://localhost:8000/scripts/dist/vendor.bundle.js:40858:22
notify/<@http://localhost:8000/scripts/dist/vendor.bundle.js:40871:30
flush@http://localhost:8000/scripts/dist/vendor.bundle.js:36692:9
```

This only happens when the endpoint is set to localhost:8001. If I set it to an actual AWS published API, (*.execute-api.us-east-1.amazonaws.com.amazonaws.com), everything works fine.

**Comment by powerful23** [comment]
@epicfaace could you try set endpoint to ```http://localhost:8001``` so the endpoint joins the path correctly

**Comment by epicfaace** [comment]
I tried:
```
  API: {
    endpoints: [
      {
        name: "ENDPOINT",
        endpoint: "http://localhost:8001/"
      }
    ]
  }
```

and it gives me the same issue. When I use an actual AWS endpoint instead, however, it works fine.

**Comment by powerful23** [comment]
@epicfaace could turn on the debug mode and search for ```Signed Request``` to check the params used by ```axios```?

**Comment by epicfaace** [comment]
@powerful23 is this what you need?

![image](https://user-images.githubusercontent.com/1689183/38147796-cf082820-3421-11e8-87d5-ae9016904c7f.png)

**Comment by powerful23** [comment]
@epicfaace I tried on my machine and seems working for me. Can you make sure you are using the latest version of amplify and also re-install all the node modules?

**Comment by epicfaace** [comment]
Yes, by reinstalling all the node modules it works now. Thanks!
