### ISSUE TITLE
[Question] completeNewPassword/changePassword different?

### ISSUE THREAD

**Issue by tuanluu-agilityio** [aws/aws-amplify#572]
Hi guys,

I wonder what is different between two methods `completeNewPassword` and `changePassword` in `aws-amplify`. Because when I custom UI change password for first time login, I have using method `changePassword` but it have error: `Local storage is missing an ID Token, Please authenticate`
https://github.com/aws/aws-amplify/blob/0124c02cdccfbea5064c1b81cc403fe3b68c6383/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1132

Look like when we not login success, we can't get `idTokenKey` as above?

On my opinion:
`completeNewPassword`: using when we login the first time to app
`changePassword`: using when we signed in to app, so we can get `idTokenKey`

Please help me more clear here.
Thanks

**Comment by powerful23** [comment]
@tuanluu-agilityio from my understanding:
```completeNewPassoword``` is when the admin assigned an account to the user and then the user logged into the app in the first time.
```changePassword``` is used for the current user to change his password which can only be used when the user logged in.

**Comment by richardzcode** [comment]
@tuanluu-agilityio please feel free to reopen this issue if needed.
