### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by timroesner** [aws/aws-amplify#574]
I noticed that error handling in the signUp and other functions can be a little confusing for new users and wanted to suggest a change, that makes it more descriptive.

This is specifically for the Amazon Cognito Identity SDK for JavaScript.

Currently:
```js
if (err) {
    alert(err);
    return;
}
```

which results in the alert `[Object object]`

Proposed:
```js
if (err) {
    alert(err.message);
    return;
}
```
which results in an alert like `User already exists`

If you agree give this a thumbs up or let me know in the comments. Happy to do a PR for this as well.

**Comment by mbahar** [comment]
Hey @timroesner, thanks for the feedback. Go for it!

**Comment by powerful23** [comment]
Closing as the pr has been merged. Thanks for the contributing!
