### ISSUE TITLE
New federation support and Cognito user pools

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#58]
Have you considered making Cognito user pools into a federated service like Google and Facebook? Cognito supports AWS generated UIs now. If you do that there is no need for the user dialogs in the react app any more.

Please don't use the Cognito self-hosted UI that also supports Google/Facebook. That UI makes the federated users in the User Pool, not the Federation Pool.  Doing it that way causes a Google login from the User Pool UI and a mobile login via the Federation Pool to end up with two different Cognito IDs. 

If you use the Cognito User Pool UI just for Cognito users and leave the current amplify Google/Facebook login code alone, everything is fine for mobile integration (ie app generated via Mobile Hub).

Here's a demo login page I made using the AWS User Pools hosted UI:
https://digispeaker.auth.us-east-1.amazoncognito.com/login?client_id=71hfsop6tn8sr85kqg088emdkr&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fredirect.html&response_type=token&scope=openid%20profile%20email&state=cjanc9fdf0000325kmnz959zq

**Comment by flieks** [comment]
ok but can aws-amplify enable embedded UI for cognito FB/google ?
I don't want the hosted UI because it's 1 more click for the user and an exit from our domain.

**Comment by mlabieniec** [comment]
Thank you for the feedback @jonsmirl we recently pushed out support for federation via custom ui with Amazon Cognito Federated Identities; this is currently only supported in React and Google/Facebook, further support is coming. The docs are [here](https://github.com/aws/aws-amplify/blob/master/media/authentication_guide.md#6-federated-identity).

**Comment by brianfoody** [comment]
@mlabieniec docs link is broken. Where can I find out how to use this?

**Comment by mlabieniec** [comment]
@brianfoody all docs are now on github.io site: 
https://aws.github.io/aws-amplify/media/authentication_guide.html#6-federated-identity
