### ISSUE TITLE
Null response and no current user session from `Auth.federatedSignIn`

### ISSUE THREAD

**Issue by vonkanehoffen** [aws/aws-amplify#580]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**

When calling `Auth.federatedSignIn` as shown [here](https://aws.github.io/aws-amplify/media/authentication_guide#enabling-federated-identities), supplying `id_token`etc. from `ga.signIn`, I receive `null` from it's returned Promise, instead of user credentials.

After the call completes, I can see `aws-amplify-cachefederatedInfo` in local storage, containing Google account info, but `Auth.currentSession` returns `No current user`

Normal user pool sign-in works fine and both `identityPoolID` and `userPoolId` are set with Amplify.configure at init, as described [here](https://aws.github.io/aws-amplify/media/authentication_guide#manual-setup).

**Debug reports** 

`AuthClass - refresh credentials error: Error: Missing required key 'IdentityPoolId' in params
    at ParamValidator.fail`

I tried setting it with the capital "I" too....

**What is the expected behavior?**

I'd expect user credentials to be returned like they are in the response from `Auth.signIn`. I'd also expect `Auth.currentSession` to return these credentials.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

`aws-amplify@0.2.11` Chrome 65.0.3325.181, MacOS 10.12.6

Don't know if this worked with previous version or not.

**Comment by powerful23** [comment]
@vonkanehoffen can you try aws-amplify@0.2.14 and also for now ```Auth.currentSession()``` only works with users logged with Cognito. You can get current credentials by ```Auth.currentCredentials()```

**Comment by vonkanehoffen** [comment]
Ah didn't know about the difference between `currentSession` and `currentCredentials`. Thanks! Still looks broken though. I set up a demo of the issue here:
https://codesandbox.io/s/48kwy1v7z4

Think something to do with Google's iFrame and the way CodeSandbox catches errors stops them reporting fully, so I put the code in a repo here too:
https://github.com/vonkanehoffen/amplify-test

Run that locally and you'll see errors in console:
Different one with the latest version : `AuthClass - Failed to load credentials: CognitoIdentityCredentials` but still fails when the JWT is definitely being passed.... Any ideas? :-)

Thanks!

**Comment by richardzcode** [comment]
Hey @vonkanehoffen sorry for the late reply. I've just tested with your test app. The issue is simply configure attribute is `identityPoolId` instead of `identityPoolID`

**Comment by vonkanehoffen** [comment]
Ah no way! So it is! Thanks very much @richardzcode . Confirmed + this works fine now. Sorry - should have noticed that :-D
