### ISSUE TITLE
Python Backend?

### ISSUE THREAD

**Issue by guanzo** [aws/aws-amplify#584]
The docs only show examples with a javascript backend, seen here: https://aws.github.io/aws-amplify/media/install_n_config

Is it possible to use this library with a python backend? If I only need authentication, do I have to use a backend?

**Comment by defionscode** [comment]
You can/should use Auth entirely client-side, so the backend itself shouldnt really matter

**Comment by mlabieniec** [comment]
@guanzo you can use whatever backend i.e. lambda runtime etc. you like. Within Amplify we have an [API](https://aws.github.io/aws-amplify/media/api_guide) category which will allow you to call API gateway, or even lambda directly via invoke API. The lambda can be running either Java, Python,  JavaScript, GO, or any other runtime lambda is supporting.

**Comment by eugeniogalioto** [comment]
Hi, in case you need a simple backend configuration I wrote a medium article about a Flask integration (the same concept can be applied to all the other frameworks): https://medium.com/@eu.galioto/the-simplest-server-configuration-for-your-aws-amplify-cognito-app-a074c01c743d

I hope you find it useful
