### ISSUE TITLE
API.get() Cannot access event.queryStringParameters when using Amplify and Serverless

### ISSUE THREAD

**Issue by causingchaos2** [aws/aws-amplify#597]
I believe i'm having issues with API.get() . How do you access queryStringParameter?, if I remove the extra JSON argument in the call to API.get it works perfect! I'm just trying to figure out if this is indeed a problem with AWS amplify and how i'm sending the JSON parameter. Thank you in advance if you can push me in the correct direction.

My client side code (aws-amplify 0.2.11 ):
return API.get('trips','/days', {'queryStringParameters': {'param1': "99b60260-363c-11e8-b7ca-250a890d0675"}})

My API side code ( using serverless-webpack v 1.6.0, aws sdk v 2.202.0 ) :
serverless.yml file :

listDays:
        handler: listDays.main
        events:
          - http:
              path: days
              method: get
              cors: true
              authorizer: aws_iam

API-javascript listDays.js code trying to access the event, the event.queryStringParameter.param1 just causes an error because it's null:

```
export async function main(event,context,callback) {

    const params = {
        TableName: "DAYS",

        KeyConditionExpression: "tripId = :tripId",
        ExpressionAttributeValues: {
            ":tripId": event.queryStringParameters.param1
        }
    }

  //console.log(data.tripId)
    try {
        //result will return an array of trips
        const result = await dynamoDbLib.call("query", params)
        callback(null, success(result.Items))
    } catch (e) {
        callback(null, failure({status: false}))
    }
}
```

**Comment by causingchaos2** [comment]
Tried this:


@roosi @ephopper when you pass query string parameters, you need to pass them as part of the initargument object with the queryStringParameters object on the API request. This is because the rest api setup with the cli is a lambda proxy integration:let items = await API.get('sampleCloudApi', '/items', {   'queryStringParameters': {     'test': '1'   } }); You can then access them within Lambda on the event["queryStringParameters"]['...']
--

**Comment by mlabieniec** [comment]
to access the query string params on the lambda function when using the awsmobile-cli and express stack. you need to use the express middleware, see example here:
https://github.com/awslabs/aws-serverless-express/blob/master/example/app.js#L6

**Comment by jarrettj** [comment]
Hi,

Good day.

The link does not work.

Regards.
