### ISSUE TITLE
Please improve the README

### ISSUE THREAD

**Issue by zhulika** [aws/aws-amplify#599]
Thank you for producing all of this but please would you improve the README so that someone coming to it for the first time has some chance of getting things up and running without having to absorb your entire SDK when starting up?

This comment, for example, is not helpful when the user is unaware of what her "client id" is, therefore does not know what to put in the field:

![aws_ids](https://user-images.githubusercontent.com/4997470/38350475-54f99e02-38a3-11e8-9d2a-4f047ed42632.png)

I understand that ``ClientID`` is a simple concept that would be obvious to someone who has spent a couple of weeks working with AWS, but I hope that you can see that telling me that a field called ``ClientID`` should be set to my "client id" is not helpful. I could deduce that from its name. :)

Please would you tell me where I get this value from in the vastness that is AWS?

Many thanks

**Comment by mlabieniec** [comment]
@zhulika the client id comes from your Amazon Cognito User Pool:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html

You can create / automate the create of all this with the [awsmobile-cli](https://github.com/aws/awsmobile-cli), you will need to just make sure you have you access keys for interacting with AWS (see instructions on the awsmobile-cli for setup/installation):

```bash
$ npm install -g awsmobile-cli
$ cd into-your-project
$ awsmobile init
```

The init command will ask you some questions including your source code directory for your project. You can accept all the defaults if you don't plan on publishing anything to, for example Amazon S3 for static hosting etc. This will also download a file called `aws-exports.js` to chosen source code directory. This file is autogenerated for you and contains all these values you are pointing out here for you. However you need to enable user-signin to get that user pool setup, to do this you just run:

```bash
$ awsmobile user-signin enable
```

Then update your AWS backend:

```bash
$ awsmobile push
```

After that you will have an updated `aws-exports.js` file which includes these client values for you. You can then use them within [Amplify](https://github.com/aws/aws-amplify) to configure your user pool. From there it depends on what framework / library you are using with your application. You can also use the amazon-cognito-identity-js sdk directly like you are pointing out here and just use the values within the `aws-exports.js` file for those parameters, however, amplify does automate and simplify a lot of this for you on the front end, see [Quick Start](https://aws.github.io/aws-amplify/media/quick_start). We will work on adding some better docs and pointers for these things in that particular readme, thanks for the feedback.

**Comment by zhulika** [comment]
@mlabieniec Thank you very much for your detailed and very helpful description. I know what to read, now :)
