### ISSUE TITLE
Does the JWT Token refresh also updates the service-specific objects, such as S3?

### ISSUE THREAD

**Issue by vbudilov** [aws/aws-amplify#6]
Hi all, great product!

With the current workflow (non-awsamplify), once a user signs in and I retrieve the access tokens for him, I can then create service-specific objects such as S3 and DDB. After an hour I would need to re-generate the objects since the tokens have expired and everything needs to be refreshed. Does aws-amplify take care of re-instantiating the service-specific objects or do the devs need to take care of this themselves? 

Thanks,
Vladimir Budilov

**Comment by richardzcode** [comment]
Thank you Vladimir! Yes the idea is aws-amplify takes care of service-specific objects. Developer access S3 or DDB through aws-amplify, don't need to hold those service-specific object directly.

Thanks,
Richard

**Comment by vbudilov** [comment]
Great! So when the JWT tokens are refreshed, the service-specific objects are also recreated, correct?

**Comment by richardzcode** [comment]
@vbudilov Yes you are right.
