### ISSUE TITLE
How to confirm user's updated email?

### ISSUE THREAD

**Issue by hszeto** [aws/aws-amplify#601]
Is there a way to send a confirmation email when user changes the email? Just like when user signup.

For example,

```
Auth.updateUserAttributes(user, {email:"blahBlah@example.com"})
.then(res=>console.log( res ))
.catch(err=>console.log( err ));
```

will update user's email on Cognito...

 However, should a confirmation email be sent to "blahBlah@example.com" before updating the record?

**Comment by powerful235** [comment]
@hszeto hi can you check this doc [Verifying When Users Change Their Email or Phone Number](https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html)
