### ISSUE TITLE
How to immediately disable user?

### ISSUE THREAD

**Issue by vithmel** [aws/aws-amplify#606]
I wrote yesterday in the comments:
https://aws.github.io/aws-amplify/media/api_guide
---
Hi, I have some problems with Api Gateway and Auth in my React Native App. I configure Cognito user pool, and Api Gateway manually. I can sign up, sign in, sign out. In Api Gateway I use Authorization: AWS_IAM and api was deployed.
Api Gateway trigger Lambda function, everything works fine, then I manually delete user from Cognito user pool, but nothing happen - everything continues to work, I still can make requests and the api returns a response. I thought that there should be an authorization error but everything works as before. How to immediately block a user?

I can also upload files to s3 within an hour after disabling or deleting the user. Most likely, there is a token caching, while each request should be validated with the Cognito.
----

If the user is logged in, and at this moment try to disable/delete him, the effect will occur about an hour.

Imagine that the application allows you to store information on S3. If a user's  smartphone, or  laptop was stolen, he will call the support service and say: "My laptop / smartphone, was stolen please disable my account, I have confidential information there, my username is johnDoe@site.com." Someone from the support service goes to Cognito finds johnDoe@site.com and presses the Disable button. But the effect will be in about an hour.
This means that for an hour the data will be available to the attacker. It seems to me that this is not entirely correct. If Cognito caches tokens, then when the user is disabled or removed, the cache should be updated immediately, and not after a while.

**Comment by richardzcode** [comment]
If I understand correctly, this is a feature request for Cognito backend to sign out all devices when disable / delete a user. Cognito SDK has a method `globalSignOut` however that is meant for the user to trigger, not admin.

**Comment by vithmel** [comment]
Yes, you are right, it must be on the server side. If Cognito caches tokens, then at the moment when the user is disabled or deleted, it is necessary to update the cache, otherwise there are security problems.

**Comment by yuntuowang** [comment]
Hi @vithmel, I will create this feature request on your behalf.

**Comment by svzi** [comment]
@yuntuowang Could you please share the link of the feature request? I'm interested in that topic as well.

**Comment by dilanthaH** [comment]
@yuntuowang Hello, do you know the status of this feature request? Thanks.

**Comment by vithmel** [comment]
Now I think this is not bug. This is how JSON Web Tokens(JWT) works.

**Comment by ldgarcia** [comment]
Hi, I am interested in this feature request. Any news?

**Comment by Jun711** [comment]
@vithmel 
have you tried admin-user-global-sign-out? I tried but it doesn't seem to make users' sessions invalid.

I have tried these Auth Class functions after running admin-user-global-sign-out command:
currentCredentials, currentSession, currentAuthenticatedUser, currentUserCredentials, userSession and essentialCredentials
They return result for current user or session without any error.

**Comment by yepes** [comment]
I'm also interested on this. @yuntuowang can you share the FR?

**Comment by nihp** [comment]
I have disabled an user account, but still the data was set for the user.

I am using aws-amplify-react-native. After disabling the user there is no immediate response for this action from cognito pool.

I need to manually reload the app. After reload I am force the user to Auth.signOut. Still the data is set for that user and he is in the app with signedIn state. 

Then I will manually restart the app which clears the data after the force logout.

Question:

Any solution to know the user state immediately?
Any solution to clear the user data?
