### ISSUE TITLE
Storage file structure and S3 lifecycle transitions

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-amplify#611]
Just a quick note—a flaw, maybe—on Storage:

I realized due to the directory structure `(public|private)/<userId>/...`, it's impossible to have an S3 lifecycle transition rule use a prefix. Typically I might set a prefix like `files/original/`, but this isn't possible with Amplify. If prefixes supported wildcards, we could do something like `private/*/original/`, but that's not possible.

This isn't necessarily a bug, just something I wanted to bring up as a caveat. And this is a good example of why I pick and choose which parts of Amplify I use. Auth is great, but I'll likely never use Storage due to limitations like this one.

**Comment by mlabieniec** [comment]
@ffxsam thanks for the feedback, we are working on making those prefixes configurable (this sprint). If the prefixes were configurable would this solve for this particular use case? Also can you provide some more details in regards to what you might want to see there. @powerful23 fyi

**Comment by ffxsam** [comment]
Yes, it would definitely solve this use case!

One of my issues with Amplify so far is that it boxes us in too much by removing customizability. Allowing us to specify our own key prefix would be really helpful.
