### ISSUE TITLE
Redirect to url after clicking email verification link

### ISSUE THREAD

**Issue by guanzo** [aws/aws-amplify#612]
When the user clicks on the email verification link, they're taken to a confirmation page, located at

https://APP.auth.us-east-2.amazoncognito.com/confirmUser?client_id=CLIENT_ID&user_name=USERNAME&confirmation_code=CODE

I'd like the ability to specify a URL that the confirmation page will redirect to, thereby auto logging in the user. This will make the signup flow more streamlined. Perhaps there could be an extra parameter for the redirect url. 

https://APP.auth.us-east-2.amazoncognito.com/confirmUser?client_id=CLIENT_ID&user_name=USERNAME&confirmation_code=CODE&redirect=URL

The way it works now is that after clicking the link, the user has to go back to my app and log in again, which is awkward.

**Comment by nidsharm** [comment]
Hi @guanzo ,

You can go to Cognito User Pool console for your pool, then on the left pane click on App Client Settings under App Integration. There is an option to set your Callback URL there. 
We don't currently support specifying the Cognito settings on awsmobile-cli. I'm adding this to our backlog. 
Let us know if you face any issues adding your url.

**Comment by guanzo** [comment]
@nidsharm That callback URL seems to be for cognito's hosted UI. I'm using my own UI.

**Comment by yuntuowang** [comment]
Hi @guanzo, yes, I understand your situation. It is a good point to add a parameter: https://APP.auth.us-east-2.amazoncognito.com/confirmUser?client_id=CLIENT_ID&user_name=USERNAME&confirmation_code=CODE&redirect=URL

I will mark this as a feature request. Thanks!

**Comment by ChandruNextbrain** [comment]
Hi @yuntuowang ,

Is that feature is implemented. Please respond asap. Thanks.

**Comment by yuntuowang** [comment]
Hi @ChandruNextbrain, this feature is not released yet. Thanks

**Comment by lxmaran** [comment]
Hello @yuntuowang ,
When do you expect to release this feature?

**Comment by yuntuowang** [comment]
Hi @lxmaran, at this point, we cannot comment on the release time.

**Comment by Chitrarekha** [comment]
Hi @guanzo @yuntuowang  how to generate codeParameter values

I have the below link 
https://emailtestingapi.auth.us-east-1.amazoncognito.com/confirmUser?client_id=u2njid8d4asctb6pj1htcahq3&user_name=chitra&confirmation_code=undefined

conformation code is undefined 
any help?

**Comment by Chitrarekha** [comment]
can anyone help me regarding how to customise the url link for email verification ?

**Comment by Deliforce** [comment]
That is auto generate by AWS. You can't customize as of now.

**Comment by Chitrarekha** [comment]
Hi @Deliforce  , is there any option to how to achieve email verification ? i have to verify email and phoneno both. CustomMessage_SignUp triggerSource is not sending mail to verify, could you please help me .

**Comment by Deliforce** [comment]
In Cognito, After creating user pool go to MFA & Verification section. There you have option to set Email & Phone number verification.

**Comment by huihe** [comment]
Hi @yuntuowang, is there any update about redirect after confirmUser?

**Comment by guanzo** [comment]
I managed to implement the redirect myself with the help of this SO post: https://stackoverflow.com/questions/47159568/how-to-redirect-after-confirm-amazon-cognito-using-confirmation-url

In Cognito's "Message Customizations" tab, under the option "Do you want to customize your email verification messages?", select "Code".

Create a cognito trigger for "Custom message". Here's my lamba code:

```
exports.handler = (event, context, callback) => {
    // Identify why was this function invoked
    if(event.triggerSource === "CustomMessage_SignUp") {
        // Ensure that your message contains event.request.codeParameter. This is the placeholder for code that will be sent
        const { codeParameter } = event.request
        const { userName, region } = event
        const { clientId } = event.callerContext
        const { email } = event.request.userAttributes
        const url = 'https://example.com/api/confirmSignup'
        const link = `<a href="${url}?code=${codeParameter}&username=${userName}&clientId=${clientId}&region=${region}&email=${email}" target="_blank">here</a>`
        event.response.emailSubject = "Your verification link"; // event.request.codeParameter
        event.response.emailMessage = `Thank you for signing up. Click ${link} to verify your email.`;
    }

    // Return to Amazon Cognito
    callback(null, event);
};
```
More information about what kind of data is available to the function:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html?shortFooter=true

The link directs the user to a server that you control. The server then sends a POST request to the Cognito API endpoint which verifies the users email. Check the SO post for what that request looks like.

Since you now control the request, redirect the user wherever you like.

Hopefully AWS implements this feature soon, because this is an annoying workaround for such a simple feature.

**Comment by bmoquist** [comment]
Hi @yuntuowang - is there any update on this? This is a basic feature for so many applications and significantly improves the user experience. Furthermore, it has been a feature request from your customers for a long time (the above SO article is from Nov. 2017).

**Comment by bmoquist** [comment]
@guanzo - Your solution worked brilliantly! 

Create the Lambda function above. Then, in the Cognito User Pool UI, set the Message Customization trigger to that function under the Triggers section and set the verification type to code in Message Customizations section.

Here is the second half needed on the server (Node here) using the AWS SDK for everyone's reference:

```js 
'use strict';
var AWS = require('aws-sdk');
AWS.config.setPromisesDependency(require('bluebird'));
var CognitoIdentityServiceProvider = new AWS.CognitoIdentityServiceProvider({ apiVersion: '2016-04-19', region: process.env.COGNITO_AWS_REGION });

exports.verifyEmailAddress = function(req, res, next) {

  const confirmationCode = req.query.code
  const username = req.query.username
  const clientId = req.query.clientId
  const region = req.query.region
  const email = req.query.email

  let params = {
    ClientId: clientId,
    ConfirmationCode: confirmationCode,
    Username: username
  }

  var confirmSignUp = CognitoIdentityServiceProvider.confirmSignUp(params).promise()

  confirmSignUp.then(
    (data) => {
      let redirectUrl = process.env.POST_REGISTRATION_VERIFICATION_REDIRECT_URL
      res.redirect(redirectUrl);
    }
  ).catch(
    (error) => {
      next(error)
    }
  )
}
```

**Comment by holtc** [comment]
Why was this closed? As far as I can tell, it still has not been implemented

**Comment by cliffordh** [comment]
Does this solution require the user to login again? I would prefer that once the user creates their account, clicks the email link, that they are "signed in" and can then use the app. To require them to enter their credentials again seems like a bad UX.

**Comment by cliffordh** [comment]
@bmoquist In your second half example, is your code a Lambda? If so, what trigger is it associated with?

**Comment by bmoquist** [comment]
No, the code is an API controller in Node Express. The Lambda function written by guanzo sends an email with the API url. The user clicks on the link in the email and is redirected to the API (my code above). The server conducts verification on behalf of the user and redirects the user to a new url. You could apply the same logic of my code using Lambda as the API.

Yes, the user will be required to login again - it would be a better UX experience if they didn't need to.

**Comment by cliffordh** [comment]
This Lambda snippet (found on SO) auto confirms the user:

```
exports.handler = (event, context, callback) => {
    event.response.autoConfirmUser = true;
    //https://stackoverflow.com/questions/47361948/how-to-confirm-user-in-cognito-user-pools-without-verifying-email-or-phone
    //event.response.autoVerifyEmail = true;  // this is NOT needed if e-mail is not in attributeList
    //event.response.autoVerifyPhone = true;  // this is NOT needed if phone # is not in attributeList
    context.done(null, event);
};
```
Could we combine these two approaches, auto-confirm the user which lets them use the app without requiring a new login, but then also trigger email verification?

**Comment by bush** [comment]
Has there been any movement on this?  It looks like cognito really needs the extra redirect parameter ... I really think this should be re-opened.  If its not going to be reopened it would be nice to confirm there is an actual feature request in the backlog.

**Comment by justinbrush702** [comment]
Whether you add a redirect parameter to the `AmazonCognitoIdentity.CognitoUserPool` or **just let us add a custom url in the Cognito user pool UI**, this feature should be added ASAP!

**Comment by elorzafe** [comment]
@bush @justinbrush702 there is a RFC on [this issue](https://github.com/aws-amplify/amplify-cli/issues/766), we are discussing auth enhancements there.

**Comment by bush** [comment]
@elorzafe thanks for the update!  Appreciate the feedback.

**Comment by RamyaChinnadurai** [comment]
Is this feature implemented? Please, someone, give a reply.

**Comment by akalana** [comment]
I am also face this issue ?Is there  any updates?

**Comment by BrentLoft1** [comment]
Timeline for when this feature will be implemented?

**Comment by joshmello** [comment]
Please add this as a priority of possible really kind of annoying doing workarounds

**Comment by davmrs** [comment]
Yes, we need the same feature. I think it's a must for this product.

**Comment by olivierto** [comment]
it's so annoying to use workaround with lambda for this... 
+1

**Comment by uncle-scooter** [comment]
There should be little to no lock-in for delivery of codes. If I was able to have more control of the delivery mechanisms then we wouldn't have to be writing our own work-arounds. 

Would be much better if Cognito/Amplify let us drop in our own delivery method and modifications and not just stuck to SES and SNS without access to the params.

**Comment by DanielWFrancis** [comment]
this should be extremely simple, curious to know what the holdup is for a redirect param?

**Comment by MarcelBlockchain** [comment]
thanks for posting the snippets!

**Comment by marcinkaczor** [comment]
We also need the same feature.

**Comment by kelvinliang-seekers** [comment]
We need this features as well lol

**Comment by jacobjoy24** [comment]
**I have written a complete guide for the re-direct functionality,**

https://medium.com/@jacobjoyseba/redirect-user-using-amazon-cognito-confirmation-url-d8ccb11bac75

**Comment by spkenn5** [comment]
The solution provided in the link is no longer working.

**Comment by davekiss** [comment]
Here's a bit cleaner version of the confirm step for anyone using Lambda proxy integration instead / HTTP APIs instead of the API Gateway. Make sure your lambda has permission to confirm users in Cognito.

```
const AWS = require("aws-sdk");
const cognito = new AWS.CognitoIdentityServiceProvider();
const REDIRECT_URL = process.env.POST_REGISTRATION_VERIFICATION_REDIRECT_URL;

exports.handler = async event => {
  const { code, username, clientId } = event.queryStringParameters;

  const params = {
    ClientId: clientId,
    ConfirmationCode: code,
    Username: username
  };

  try {
    await cognito.confirmSignUp(params).promise();
    return {
      statusCode: 301,
      headers: {
        Location: REDIRECT_URL
      }
    };
  } catch (error) {
    return { statusCode: 400, body: error.message };
  }
};
```

**Comment by lebnic** [comment]
Cognito should at least update the doc / interface... The link simply "does not work out of the box..." contrary to what is "advertised" :

<img width="1183" alt="Capture d’écran, le 2020-04-10 à 16 29 11" src="https://user-images.githubusercontent.com/6682795/79021036-7fc99300-7b48-11ea-802d-33e1fdb64413.png">

**Comment by DanielWFrancis** [comment]
Adding to the long list of people who want to see this. Seems exceptionally simple to implement.

**Comment by stevelizcano** [comment]
This is extremely frustrating and makes working with amplify/cognito a negative experience.

**Comment by SilverLinings89** [comment]
This functionality as a UI element in the AWS console would be very helpful. A simple URL to redirect to if the confirmation was successful would be exactly what people in most usecases want I guess. Weird that such a core functionality would require quirky workarounds as have been mentioned above - this is after all a situation something like half of all registered users should go through (I guess 50% code, 50% link)

**Comment by beevekmgr** [comment]
Can some one help me with these.. I have been stuck in this work around .....

**Comment by asterikx** [comment]
From what I understand we need to do two things

1. Customize the confirmation link sent to the user (to point to sth. we have control of to redirect the user after confirmation)
2. Call the Cognito API to confirm the user (based on the information in the confirmation link) and redirect the user to where we want to

For the first step, we need to create a [Custom Message Lambda Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html?shortFooter=true) since Cognito's static message customization does not allow us to encode redirect information in the generated confirmation link.

For the second step, the suggested solution uses a custom API endpoint with a Lambda to call the Cognito API (to confirm the user) and returns an HTTP 302 to redirect the user based on the redirect information encoded in the confirmation link.

I wonder why no one handles confirmation and redirection on the client-side?

I case of a SPA (e.g. React), I could have the following route for confirmation: `/confirm?username=${username}&code=${code}`

React Router v6
```
<Routes>
  <Route path="/confirm" element={<Confirm />} />
</Routes>
```
The `Confirm` component parses the search parameters, confirms the user using the Amplify's [confirmSingUp method](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js#confirm-sign-up) (calling the Cognito API under the hood), and, on success, replaces the current location with the previous location (or a default one).
```
import { useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Auth } from 'aws-amplify'; // pre-configured with clienId

export function Confirm() {
  const navigate = useNavigate();
  const location = useLocation();
  const search = new URLSearchParams(location.search);

  const username = search.get('username') || '';
  const code = search.get('code') || '';

useEffect(() => {
    const confirmUser = async () => {
      try {
        await Auth.confirmSignUp(username, code);

        const prevPath = (location.state as { from: string }).from || '/home';
        navigate(prevPath, { replace: true });
      } catch (err) {
        // handle error
      }
    };
    confirmUser();
  }, [username, code]);
```

I haven't tested this solution yet, but I think it should work ...

I believe it is more flexible than using a custom API route/lambda with a fixed redirect URL. It can redirect the user to the previous location (which is useful for when confirmation must not happen immediately after sign up) and simplifies error handling on the client (expired links etc.).

I'm wondering if there are (major) drawbacks of such an implementation compared to a server-side solution? At the end of the day, both Lambda and Amplify make calls to the Cognito API, while Amplify adds useful methods for these calls.

**Comment by harleyguru** [comment]
@asterikx I think it's impossible to do this on FE as the users would get the verification email through email (not in-app).
That's the reason why we should expose the endpoint for verification on server side.

**Comment by asterikx** [comment]
I have it working now, using only FE. However, as the link in the verification email will open a new tab in the user's default browser (possibly on another device), redirection based on (in-memory) FE state will not work indeed.

**Comment by ramanaditya** [comment]
It is better to have the authentication process working in the backend, due to following reasons
- If a user wants to authenticate from another device
- And for the simple frontend where they do not care about preserving step
- We won't be able to customize it if we are not dealing with just the signup process, like if we want to store the info on a different database.

I have done this through the backend referring the links posted above, but this should not be the actual solution, for a single process we have to make multiple requests. This should one of the feature updates if the team is planning upon.

This should be more like the federated login where the tab automatically gets closed upon authentication.

Looking forward to seeing the update ASAP.

**Comment by dedsinon** [comment]
@yuntuowang Hi, may I ask if the redirection from the confirmation link has already been solved?

**Comment by dedsinon** [comment]
> Can some one help me with these.. I have been stuck in this work around .....

Have you found a solution on this?

**Comment by SumindaD** [comment]
Why this issue is being closed? it's a much needed feature.

**Comment by theothertaxman** [comment]
Hi! September '20 and still waiting for an easy way to redirect users back to my site after clicking on the email validation link. 

I will use the lambda workaround, but still it would be nice if you could push this feature in your backlog 🥰

**Comment by colinbowen** [comment]
This should not be closed.

**Comment by Xychun** [comment]
Still nothing? Need this feature, please open and add!
+1

**Comment by beevekmgr** [comment]
Sorry but I think i solved somehow

**Comment by sverraest** [comment]
What's the latest on this? It doesn't seem possible out of the box still?

**Comment by NoControl712** [comment]
Just adding my 2 cents. This feature would be awesome. Please add.

**Comment by yaquawa** [comment]
I know how to redirect to a URL after confirmation, but how to login the user automatically??

**Comment by sverraest** [comment]
> I know how to redirect to a URL after confirmation, but how to login the user automatically??

Step 1: Stop using Cognito and Amplify unfortunately.

**Comment by IvanCaceres** [comment]
Why does clicking the  email verification link just lead the user to a constant loading spinner/indicator?

Why won't it redirect back to my amplify site?

**Comment by beevekmgr** [comment]
Are you still stuck at this?

**Comment by karray3000** [comment]
Any update on this? I can do with the Lambda workaround, but I also want to log the user in directly after verifying their email and there doesn't seem to be a simple way (if any) of doing so with Amplify...

**Comment by JosephUrciuoli** [comment]
+1 - I'm not sure why this closed.

**Comment by narciso-dev** [comment]
+1

**Comment by sammartinez** [comment]
@narciso-dev / @JosephUrciuoli,

Just want to get some clarity here. We support this feature in our latest UI Components, please review the documentation [here](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react). Are you looking for this at the API level? 

Please let us know

**Comment by narciso-dev** [comment]
@sammartinez 
I see, but in some cases we are not using the hosted UI nor the UI components library. 
As mentioned above, some of us wants to know if the feature of adding a redirect URL at the URL the user gets in the verification email is still considered.

It would be helpful in my case because I wants the user to click on a link and being redirected to my website after he verifies the account.
Maybe can be also considered to have a setting for our endpoint with the params added automatically (in the email the user will see www.domain.com/api/verifyAccount?params) and then have a method in the Auth API to let us customly verify it how we wants. This will avoid to pass through the default URL and avoid in some cases lambda triggers.

Thanks!

**Comment by sammartinez** [comment]
Thanks for this feedback. Here is what we currently have and support for this use case within Amplify:

In our latest [UI Components](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react), we handle the auto signing in once a user confirms their sign up on your application. This is strictly with the UI Components on the client side. 

As for the redirect URL, we recommend using our [Cognito Lambda Triggers](https://docs.amplify.aws/cli/usage/lambda-triggers#cognito-lambda-triggers) in order to accomplish this. We have a section on [Email Verification Link with Redirect](https://docs.amplify.aws/cli/usage/lambda-triggers#email-verification-link-with-redirect) under this documentation you can follow for setup. 

As for feature requests for the Hosted UI, Amplify JS acts as a proxy to the Amazon Cognito service, and we do not control the Hosted UI feature. That being stated, we can raise a feature request internally to Cognito but it may be best to ask them for a feature request via the [Amazon Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).

**Comment by clehnert** [comment]
+1

This is such a simple request. All we want is a simple redirect url when using the verification link. It's one label and one text box in the AWS Console (and obviously a little more). It could redirect automatically. It could show a button that says "Continue" or maybe "Go Home" or maybe "We Care About and Listen to our Customers."

I'm already ignoring the fact that I can't log somebody in before verification (standard UX - "feel free to look around but you gotta verify before you can post"). Now this. Why does AWS Cognito continue to push me back to using Firebase for authentication?

+1

**Comment by anil1712** [comment]
I am also wondering that it's such a simple standard process in any IDP, don't know AWS is not implementing this request.

**Comment by voigtito** [comment]
Still waitting

![meme](https://user-images.githubusercontent.com/55980259/121579974-a01e0780-ca02-11eb-958a-509a0e2fa3c5.jpg)

**Comment by andreasanta** [comment]
I think it's unacceptable that such a simple feature has been around for four years in the backlog and users still have to implement at least two lambdas to perform custom redirect. Feels like the 90s when I was programming in Java Servlets. This definitely does not ampify anything, if you compare it to Firebase.

**Comment by sverraest** [comment]
Paging @mlabieniec to consider re-opening this, it's really a shame this ticket is closed, the fact it still receives so many comments is a sign.

**Comment by jonnyn** [comment]
Still waiting!!!

**Comment by CarlJoven** [comment]
UP!

**Comment by giomarino** [comment]
Still here...

**Comment by purbanow** [comment]
+1

**Comment by kangleon-karl** [comment]
+1

**Comment by sverraest** [comment]
@sammartinez Any feedback from the Amplify team, it's becoming a bit embarrassing.

**Comment by anil1712** [comment]
@TheRedshift how was your meeting with AWS team regarding this issue?

**Comment by sverraest** [comment]
@sammartinez Can we at least re-open this, it's clearly an issue / missing basic functionality that is causing a lot of concern for a lot of developers. Why leave it closed (and completely ignore it)?

**Comment by Seanmclem** [comment]
> @sammartinez Can we at least re-open this, it's clearly an issue / missing basic functionality that is causing a lot of concern for a lot of developers. Why leave it closed (and completely ignore it)?

I literally just spoke with the new product manager for AWS Amplify on the phone for a half an hour yesterday, almost entirely about this exact issue. I referenced it directly and she was able to look it up. We'll see if they do anything about it.￼

**Comment by sammartinez** [comment]
> Thanks for this feedback. Here is what we currently have and support for this use case within Amplify:
> 
> In our latest [UI Components](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react), we handle the auto signing in once a user confirms their sign up on your application. This is strictly with the UI Components on the client side.
> 
> As for the redirect URL, we recommend using our [Cognito Lambda Triggers](https://docs.amplify.aws/cli/usage/lambda-triggers#cognito-lambda-triggers) in order to accomplish this. We have a section on [Email Verification Link with Redirect](https://docs.amplify.aws/cli/usage/lambda-triggers#email-verification-link-with-redirect) under this documentation you can follow for setup.
> 
> As for feature requests for the Hosted UI, Amplify JS acts as a proxy to the Amazon Cognito service, and we do not control the Hosted UI feature. That being stated, we can raise a feature request internally to Cognito but it may be best to ask them for a feature request via the [Amazon Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).

Hello folks, please see the above comment that I posted on March of this year. This is what we currently support and our recommendations. Since we do not have control over the Hosted UI experience as this is owned by the Amazon Cognito team, we still recommend to open a feature request via the [Amazon Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).

**Comment by BernhardSmuts** [comment]
I really want to buy into amplify, been trying to use it for 1.5 years now, but it feels like it's been forgotten about and it would almost be easier to just custom code everything. 
Mocking not working most of the time.
Auth is a nightmare and not easy to use unless you jump through the exact hoops they want you to (ie: THIS 2 YEAR OLD ISSUE).
Docs cover 0.1% of the details needed to implement anything.

It seemed like such a promising framework to get my teeth stuck into but just keeps disappointing me.

**Comment by Talhafayyaz11** [comment]
still waiting!!

**Comment by Sultandi** [comment]
_**waiting too...........**_

**Comment by CristopherVidalMachado** [comment]
Still no updates;

**Comment by sverraest** [comment]
At this point I'm convinced Half Life 3 will be released before this feature is implemented.

**Comment by Israelhrs** [comment]
Still waiting..

**Comment by abdallahshaban557** [comment]
Hello everyone, we have internal conversations started on supporting this feature. We will provide an update when this feature is available!

**Comment by rchristiemtt** [comment]
@abdallahshaban557 if you are starting conversations about supporting this feature, can this issue remain open until then

**Comment by sverraest** [comment]
@abdallahshaban557 that's a great first step on such a widely requested and anticipated feature. Echo'ing @rchristiemtt comments to re-open this issue as a lot of people are tracking this.

**Comment by abdallahshaban557** [comment]
Hi @rchristiemtt and @sverraest  - the reason this is closed because we have another issue we are using to track this ask https://github.com/aws-amplify/amplify-js/issues/9006.

**Comment by Seanmclem** [comment]
> Hi @rchristiemtt and @sverraest  - the reason this is closed because we have another issue we are using to track this ask https://github.com/aws-amplify/amplify-js/issues/9006.

Amplify is still a thing? I figured it was abandonware based on the dozen issues like this.

**Comment by Harsh4999** [comment]
Waiting ++.....

**Comment by KundaiClayton** [comment]
Any updates on this?

**Comment by ledgerdevelop** [comment]
Amplify Team : Please this in high demand and the UX without it is terrible. The workarounds are also not dev friendly at all. It's been over 4 years now since this has been requested. Come on.

**Comment by Wigglor** [comment]
Any updates on this? Do we still need to use lambda triggers?

**Comment by gh-samadkhan** [comment]
Hi , any update on this issue it's 2023 October. Do I still need to use lambda triggers for redirecting my users after clicking on verification link or is there any option to add it from Dashboard. I can see re-direct URL but that's for cognito hosted UI

**Comment by ViniciusgCaetano** [comment]
January, 2024.

**Comment by asyschikov** [comment]
How is internal conversation going?

**Comment by GonzaloPardoVillalibre** [comment]
Well... +1 here...

**Comment by imduchy** [comment]
7 years later, still waiting... 💤

**Comment by cliffordh** [comment]
> 7 years later, still waiting... 💤

gonna take a wild guess that the owner of this issue @sammartinez is no longer working on this project... he hasn't had a commit in over a year.

**Comment by imduchy** [comment]
> > 7 years later, still waiting... 💤
> 
> gonna take a wild guess that the owner of this issue [@sammartinez](https://github.com/sammartinez) is no longer working on this project... he hasn't had a commit in over a year.

I believe this is a limitation on the Amazon Cognito side, not the library itself.
