### ISSUE TITLE
Auth.setPreferredMFA(user, 'TOTP') requires phone number verification?

### ISSUE THREAD

**Issue by guanzo** [aws/aws-amplify#618]
I'm trying to setup MFA with TOTP. Everything works, including `Auth.verifyTotpToken`. However, when I try to set the preferred MFA with `Auth.setPreferredMFA(user, 'TOTP')`, I get an `InvalidParameterException`, with the message, `User does not have a phone_number set to turn on SMS MFA`. The phone number shouldn't matter, it's wholly unrelated to TOTP authentication.

Since `Auth.setPreferredMFA` calls `user.setUserMfaPreference`, i tried replacing the default value for the sms option with null, and the error went away.

So instead of this 
`user.setUserMfaPreference(smsMfaSettings, totpMfaSettings, ...)`,
i called this 
`user.setUserMfaPreference(null, totpMfaSettings, ...)` 
and the error was gone. Not sure if that's helpful or not.

I also noticed some specific language in the Cognito dashboard which may be related. On the "MFA and verifications" page, the top paragraph contains 

> Phone numbers must be verified if MFA is enabled.

Does that mean, that no matter which MFA option you choose (SMS or TOTP), the user's phone number must be verified?

So to reiterate, does Cognito TOTP authentication require a verified phone number? And if not, what could be causing the error message?

**EDIT**: Solved by referencing use case 29, https://github.com/aws/aws-amplify/tree/master/packages/amazon-cognito-identity-js . I had to pass `null` for the SMS parameter.

**Comment by tomquisel** [comment]
@guanzo Can you reopen this? I hit the same issue. I think this should be fixed in the Amplify Auth library as well.

**Comment by guanzo** [comment]
@tomquisel Sure thing. I'd like to see this fixed in aws-amplify as well.

**Comment by filipjelic** [comment]
Is this still a thing? I was just activating MFA for a specific user, and it still requires that the user has to have a phone number....
