### ISSUE TITLE
User Information Analytics

### ISSUE THREAD

**Issue by bbernays** [aws/aws-amplify#62]
Is there anyway to tie the Cognito user id to the Pinpoint endpoint via the Analytics module? I am looking for a way to be able to track individual usage rather than just session usage.

(I have already enabled Cognito to share data with Pinpoint by creating the IAM role)

**Comment by mlabieniec** [comment]
@bbernays you can use attributes to reference a user ID, these will then be viewable in Pinpoint->Events
