### ISSUE TITLE
API.get() not adding security credentials

### ISSUE THREAD

**Issue by ajmontero** [aws/aws-amplify#622]
Do you want to request a feature or report a bug? bug

What is the current behavior?

I am using Auth to include authentication in my React(web) app using 
`import Amplify, { Auth } from 'aws-amplify';
import aws_exports from './aws-exports';
import { withAuthenticator } from 'aws-amplify-react';
Amplify.configure(aws_exports);
...

export default withAuthenticator(DashApp);`

In a sub container I am trying to make an API call:

`
      import { API, Auth } from 'aws-amplify';
...
      
let apiName = 'transcript';
      let path = '/transcript';
      let myInit = { // OPTIONAL
        headers: {} //OPTIONAL
      }
      API.get(apiName, path, myInit).then(response =>{
        props.transcripts = response.transcripts;
      });
`
Which results in an error {"message":"Missing Authentication Token"}.
Using the Network tab of debug tools I am seeing that in fact the security token is not included. I am able to do this with my React Native app and it is working perfectly.

I have also tried adding the header explicitly like so:
`
let session = Auth.currentSession().then(function(result){
      
      let apiName = 'transcript';
      let path = '/transcript';
      let myInit = { // OPTIONAL
        headers: {
          'Authorization': result.idToken.jwtToken
        }
      }
      API.get(apiName, path, myInit).then(response =>{
        props.transcripts = response.transcripts;
      });

    });
`
Which still does not include the header. Am I missing a critical step somewhere?

These are the headers that I see in my request btw:
`
:authority: [removed].execute-api.us-west-2.amazonaws.com
:method: OPTIONS
:path: /Development/transcript
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
access-control-request-headers: authorization
access-control-request-method: GET
cache-control: no-cache
origin: http://localhost:3000
pragma: no-cache
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
`

What is the expected behavior?
API.Get will automatically include the credentials of the user to the Get request.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
 "aws-amplify": "^0.2.14",
 "aws-amplify-react": "^0.1.38",

**Comment by nidsharm** [comment]
Hi @ajmontero ,

Can you please check if you have CORS enabled on API Gateway?

**Comment by nidsharm** [comment]
@ajmontero , CORS is used to add additional HTTP headers to let user agent get permission to access resources from a different domain than the website. It is designed specifically for a script from a foreign domain, running in the browser, sending a request to your server that includes your authorization cookies. 

In a native app, there won't be any foreign scripts that are able to make a request to your server using your cookies.
