### ISSUE TITLE
Running on device(ios), undefined is not a function (...window.addEventListener )

### ISSUE THREAD

**Issue by 7772** [aws/aws-amplify#638]
#### My environment..

  "dependencies": {
    "amazon-cognito-identity-js": "^2.0.3",
    "aws-amplify": "^0.1.36",
    "aws-amplify-react-native": "^0.2.7",
    "aws-sdk": "^2.224.1",
    "immutable": "^3.8.2",
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.0",
}

import Amplify, { API } from 'aws-amplify';
import aws_exports from '../../aws-exports';

Amplify.configure(aws_exports);

#### Problem
I could run my project ios simulator !

But I can't run on device..

![error](https://user-images.githubusercontent.com/22615385/38661911-73b20440-3e6d-11e8-93ec-f1ec46422ab6.jpeg)

I checked the issue #230 but didn't work.

What should i do to fix this error?

**Comment by nidsharm** [comment]
Hi @7772,

Can you try running the app with the latest version of Amplify?

**Comment by richardzcode** [comment]
It is a side effect of Polyfills.ts. The latest version of Amplify should have fixed the issue.

@7772 could you run `npm install aws-amplify@latest` and see if problem persists?

Thanks,
Richard

**Comment by 7772** [comment]
@nidsharm @richardzcode 

I solved this error after $ npm install aws-amplify@latest

Thanks a lot Friends!
