### ISSUE TITLE
New polyfill to fix PubSub for SSR breaks checks for SSR.

### ISSUE THREAD

**Issue by cgarvis** [aws/aws-amplify#640]
**Versions**:
aws-amplify@0.2.15
next.js@5.0.1

**What is the current behavior?**
When using the latest amplify code with polyfill, it doesn't polyfill the `window` object fully so it breaks other SSR checks liked here: https://github.com/zeit/next.js/blob/085b2f806afd4d16e6f4754cce62e88d7bd47518/lib/router/router.js#L45-L50 which in `getUrl` is looking to the `href` on `location` which hasn't been polyfilled.

**What is the expected behavior?**
Set `location` to empty object.

**Comment by nidsharm** [comment]
Hi @cgarvis,

Thank you for reporting this bug. We will fix it soon.

**Comment by michaelmerrill** [comment]
Also experiencing this issue with the latest versions of amplify and next.

`"aws-amplify": "0.3.3",`
`"aws-amplify-react": "0.1.43",`
`"next": "5.1.0",`
