### ISSUE TITLE
implementation help (solved) RNAWSCognito.xcodeproj manually linked

### ISSUE THREAD

**Issue by cosmosof** [aws/aws-amplify#65]
User able to signup and pool has the credentials. but I got this error when I try sign-in, not sure what's going on there,  anyone came across it?

`undefined is not an object (evaluating 'RNAWSCognito.computeModPow)
`
```
...
import Amplify, { withAuthenticator } from 'aws-amplify-react-native';
import aws_exports from './awsmobilejs/#current-backend-info/aws-exports';
Amplify.configure(aws_exports);

class App extends Component<{}> {
 ......
}
export default withAuthenticator(App);
```

  ```
"dependencies": {
    "aws-amplify": "^0.1.0",
    "aws-amplify-react-native": "^0.1.8",
    "react": "16.0.0",
    "react-native": "0.51.0"
  },
```

**Comment by cosmosof** [comment]
sadly this RNAWSCognito.xcodeproj had to manually linked. (IOS)

**Comment by mlabieniec** [comment]
@cosmosof sorry for the confusion, yes per the docs [here](https://github.com/aws/aws-amplify/blob/master/media/quick_start.md#react-native-development), the Amazon Cognito JS SDK 
currently requires a native bridge for mathematical performance not available in the JavaScript runtime.

**Comment by jatazoulja** [comment]
Please Note that this also happens in Android. same scenario as above... can someone point me where I can manually link android and iOS?

Cheers

**Comment by jatazoulja** [comment]
Please Note that this also happens in Android. same scenario as above... can someone point me where I can manually link android and iOS?

Cheers

**Comment by BenjaminWatts** [comment]
Hey - i am having the same problem in Android. Getting the ` #171
TypeError: Cannot read property 'computeModPow' of undefined` error, though it seems to work fine on ios. 

Is there a fix for this bug?

**Comment by mlabieniec** [comment]
@jatazoulja @BenjaminWatts see [here](https://aws.github.io/aws-amplify/media/quick_start#install-aws-amplify) (click on react native)

**Comment by NeverFearTheasHere** [comment]
All of the links to the docs in this issue thread seem to be out of date and I can't see anything in the current AWS amplify docs (https://aws-amplify.github.io/docs/js/react) about needing to link native libraries in order to get authentication working on react-native.

In case anyone else runs into this same problem and finds this issue - I found that I had to run: `react-native link amazon-cognito-identity-js` to fix this error.

**Comment by duytq94** [comment]
I don't know why command link just effect on Android, iOS does nothing.
Then I have to link manually, so for people stuck issue like me:
1. Find RNAWSCognito.xcodeproj in node_modules folder and add to Libraries
![screen shot 2019-02-26 at 9 30 04 pm](https://user-images.githubusercontent.com/24253421/53420113-bd835f00-3a0d-11e9-96d5-953b7eaa2b5c.png)
2. Click on your main project file (the one that represents the .xcodeproj) select Build Phases and drag the static library from the Products folder inside the Library you are importing to Link Binary With Libraries
![screen shot 2019-02-26 at 9 31 13 pm](https://user-images.githubusercontent.com/24253421/53420188-e0ae0e80-3a0d-11e9-8731-9fe9b5c82eeb.png)
Done.
