### ISSUE TITLE
API use case

### ISSUE THREAD

**Issue by guanzo** [aws/aws-amplify#658]
Is the API module only used for making requests to AWS endpoints? 

I'm running my own server and would like to secure my REST endpoints by verifying the cognito users JWT. Does the API module automatically add the JWT, specifically the ID Token, to the request headers? Or do I need to manually add the JWT to my requests?

**Comment by elorzafe** [comment]
Hi @guanzo you can make request to any endpoint not necessarily only AWS ones. Amplify library sign the request using the credentials from cognito.

**Comment by manueliglesias** [comment]
@guanzo 

As @elorzafe  mentioned,  you can use the API module to do requests to any REST (now even GraphQL) endpoint. In your case, you can  include your JWT in a header, e.g. from https://aws.github.io/aws-amplify/media/api_guide#post

```javascript
let apiName = 'MyApiName'; // replace this with your api name.
let path = '/path'; //replace this with the path you have configured on your API
let myInit = {
    body: {}, // replace this with attributes you need
    headers: {
        'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
    }
}

API.post(apiName, path, myInit).then(response => {
    // Add your code here
}).catch(error => {
    console.log(error.response)
});
```
