### ISSUE TITLE
Custom Auth UI not visible

### ISSUE THREAD

**Issue by roosi** [aws/aws-amplify#66]
I have following component and it gives me black screen.

```
class AppWithAuth extends Component {
  render () {
    return (
      <Authenticator hideDefault>
        <SignIn />
        <SignUp />
        <ConfirmSignUp />
      </Authenticator>
    )
  }
}
```

```
  "dependencies": {
    "aws-amplify": "^0.1.0",
    "aws-amplify-react": "^0.1.23",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.0.17"
  }
```

Am I missing something? If I remove hideDefault prop I will see two signIn forms.

**Comment by digitaledge** [comment]
The problem is with your render methods that do not handle the current authstate.

As example in AppWithAuth:
`render() {
            const { authState, authData } = this.state;
            const signedIn = (authState === 'signedIn');

            if (signedIn) {
                return (
                    <Comp
                        {...this.props}
                        authState={authState}
                        authData={authData}
                        onStateChange={this.handleAuthStateChange}
                    />
                )
            }

            return (
                <Authenticator {...this.props} hideDefault={true} onStateChange={this.handleAuthStateChange} theme={theme}>
                    <SignInScreen />
                    <SignUpScreen />
                    <ConfirmSignUpScreen />
                    <ForgotPasswordScreen />
                </Authenticator>
                )
        }`

and in the SignInScreen component:

` render() {
        const { authState } = this.props;
 
        if (!['signIn', 'signedOut', 'signedUp'].includes(authState)) {
            return null;
        }
       return(.....)
`

**Comment by oluckyman** [comment]
aws `<SignIn>` component hides himself if `<Authenticator hideDefault>` is set. So you have to use your `<SignIn>` implementation which manages its visibility itself:
```
render() {
    if (!['signIn', 'signedOut', 'signedUp'].includes(authState)) { return null; }
}
```

**Comment by roosi** [comment]
Makes sense, I was hoping to reuse some components as is.
