### ISSUE TITLE
withOAuth missing from dist in aws-amplify-react

### ISSUE THREAD

**Issue by tunecrew** [aws/aws-amplify#677]
In aws-amplify-react master branch, withOAuth is present in the src dir but not in the dist dir, although it is referred to in the dist/index file exports.

To use withOAuth I had to clone the repo and manually rebuild the package

**Comment by richardzcode** [comment]
@tunecrew thank you for reporting this! It was an issue in our build process. We'll correct that very soon.

**Comment by richardzcode** [comment]
made a new build, withOAuth is now present in dist dir.
