### ISSUE TITLE
NotAuthorizedException: Token is not from a supported provider of this identity pool when using Google as Identity Provider

### ISSUE THREAD

**Issue by kyeljmd** [aws/aws-amplify#681]
Do you want to request a feature or report a bug?

What is the current behavior?
Upon calling federatedSignIn using Google it returns a

"NotAuthorizedException: Token is not from a supported provider of this identity pool when using Google as Identity Provider"

I'm using a 3rd party library namely angular5-social-login for logging in social providers such as google. I believe I have configured this as expected in both cognito, and federated entities. 

Here's my sample code

```

this.socialAuthService.signIn(socialPlatformProvider).then(
      (userData) => {
        console.log(socialPlatform+" sign in data : " , userData);
        // Now sign-in with userData
        let user = {
          email:userData.email,
          name: userData.name
        }
        Auth.federatedSignIn(
          // Initiate federated sign-in with Google identity provider 
          'google',
          { 
              // the JWT token
              token: userData.idToken,
              expires_at: null
          },
          // a user object
          user
      ).then(a => {
          // ...
          console.log(a)
      });

```
Here's the configuration I did

https://imgur.com/a/5ZodDC7

and on the federated entities

https://imgur.com/a/ttfo2

Where both ahve the same google client id 

I believe I have already configured as necessary in both user pool, and federated entities. However I am still encountering the same issue
.
What is the expected behavior?
Return a valid success response when calling Auth.federatedSignIn

**Comment by richardzcode** [comment]
@kyeljmd from error message it does look like a configuration problem. Could try to follow instructions here: https://aws.github.io/aws-amplify/media/authentication_guide#enabling-federated-identities

It uses gapi directly, may eliminate possible causes from integrating plugin.

**Comment by kyeljmd** [comment]
@richardzcode I'm working with typescript, and I needed to use a wrapper for the gapi, and I ended up using this one.

I was able to retrieve the id token, and expires at, however after passing it to Auth.federatedSignIn I still receive the error for this one.

**Comment by kyeljmd** [comment]
I was able to fixed the issue thanks to the gapi libray. I'm workingw with typescript, and angular5 so I ended up using a wrapper for the gapi libray(ng-gapi)

**Comment by dinamic** [comment]
@kyeljmd please don't be one of those people who creates a question in StackOverflow and then says "I fixed it" without contributing the solution.

**Comment by ttawan** [comment]
Happe to me too.

**Comment by oliverandersencox** [comment]
this should not be closed, or at least some sort of guidance offered. I am trying to authenticate via facebook. It works fine on desktop, however in Ionic on the IOS device I always get this error. I am using the Facebook sign in method directly from the FB API and so I know the returned access token is correct

**Comment by uchar** [comment]
> I was able to fixed the issue thanks to the gapi libray. I'm workingw with typescript, and angular5 so I ended up using a wrapper for the gapi libray(ng-gapi)

@dinamic How did you fix it ?

**Comment by oliverandersencox** [comment]
@uchar if this helps I managed to get Facebook login working by using the Facebook Ionic plugin which deals with the OAuth process and returns the token, much like the Ionic Google Auth plugin.

`public async loginWithFacebook(): Promise<any> {

    const res = await this.amplify.auth().federatedSignIn();
    return;
    const permissions = ['public_profile', 'email'];

    try {
      const response: FacebookLoginResponse = await this.facebook.login(permissions);
      const { accessToken, expiresIn } = response.authResponse;
      const date = new Date();
      const expires_at = expiresIn * 1000 + date.getTime();
      const userFbData = await this.facebook.api('/me?fields=first_name,last_name,email', permissions);
      console.log(userFbData);
      const user = {
        id: response.authResponse.userID,
        firstName: userFbData.first_name,
        lastName: userFbData.last_name,
        email: userFbData.email,
        picture: `https://graph.facebook.com/v3.3/${response.authResponse.userID}/picture?height=250&width=250`
      };

      const federatedUser: FederatedUser = {
        name: user.firstName + ' ' + user.lastName,
        email: user.email
      };
      try {
        const fed: FederatedResponse = { token: accessToken, expires_at };
        const res = await this.amplify.auth().federatedSignIn('facebook', fed, federatedUser);
        console.log('FACEBOOK SIGN IN: CONFIRMED');
        this.$socialAuthData.next(user);
        this.$authenticated.next(true);


        const doesExist = await this.user.doesUserExist(user.id);
        console.log('DOES FACEBOOK USER EXISTS: ' + doesExist);

        if (!doesExist) {
          this.nav.navigateForward('create-user');
        }
      } catch (err) {
        console.log('FEDERATION ERROR');
        console.log(err.message);
      }
    } catch (err) {
      console.error(err);
    }
  }`

However this federated login doesn't create a new cognito user and uses federated cognito identify pools and so you cannot call the API as it uses Cognito uses to auth against.

Unless anyone knows how to successfully do this to create a cognito user in the user pool?
