### ISSUE TITLE
[Question] How to invoke lambda without using API Gateway and access the params? 

### ISSUE THREAD

**Issue by Jun711** [aws/aws-amplify#690]
What is the current behavior?
I got 403 error when calling API.get(). Did I miss some steps? 
err message is
Unable to determine service/operation name to be authorized

I configured Amplify based on the following example. Does yourFuncName have to be an arn? 
https://aws.github.io/aws-amplify/media/api_guide
```
 API: {
        endpoints: [
            {
                name: "MyCustomLambdaApi",
                endpoint: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/yourFuncName/invocations",
                service: "lambda",
                region: "us-east-1"
            }
        ]
    }
```

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
0.2.14

**Comment by mlabieniec** [comment]
403 is a permissions (forbidden) error. Are you sure you credentials/role has invoke permissions? If you are using cognito you will need to make sure either your auth or unauth role has lambda invoke permissions. https://docs.aws.amazon.com/lambda/latest/dg/intro-permission-model.html

**Comment by Jun711** [comment]
right, I figured out that it is the credential error. The unauth role didn't have lambda invoke permission. 
Thanks.

**Comment by Jun711** [comment]
@mlabieniec I realized post worked after I added lambda invoke permission but API.get still gets 403 error.

**Comment by rqton** [comment]
Hello ! I have the same issue as @Jun711. I also have granted my cognito role to all lambda invoking.

Here is my Amplify configuration : 
```
  API: {
    endpoints: [
      {
        name: 'MyLambda',
        endpoint: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/MyLambda/invocations",
        service: "lambda",
        region: "eu-west-1"
      }
    ]
  }
```

And the api call in JS : 
```
    const apiName = 'MyLambda';
    const path = '';
    const myInit = {};
    API.get(apiName, path, myInit).then(response => {
      console.log(response);
    }).catch(error => {
      console.log(error);
    });
```

Did someone found any solution ?
Thanks in advance.

**Comment by MattiaCostamagna** [comment]
Same problem here. My code is exactly like @rqton mentioned in his post.
I'm making a post request, and in my cast the lambda function needs to be called by unauthenticated users, so I created a IAM role with the following conditions:
`"Condition": {
        "StringEquals": {
          "cognito-identity.amazonaws.com:aud": "eu-west-1_xxxxxxxxx"
        },
        "StringLike": {
          "cognito-identity.amazonaws.com:amr": "unauthenticated"
        }
      }`, an then a policy that allows to invoke the lambda function. 

When I'm calling it from amplify I just get a 403 error code. What am I doing wrong? Is there something I need to do beside this?
