### ISSUE TITLE
Add Authorization header to GraphQL operations

### ISSUE THREAD

**Issue by hassankhan** [aws/aws-amplify#696]
Feature Request

What is the current behavior?

Currently if a user uses a GraphQL endpoint, `aws-amplify` does not seem to apply any headers that would usually be on a request made from `API.post()`.

What is the expected behavior?

It would be nice to be able to specify that the GraphQL endpoint is also `AWS_IAM` authorized.

---

Amplify v0.3.0

**Comment by honkskillet** [comment]
Yes.  I second this.  Working with AWS Amplify and AppSync using IAM auth.  The context identity object in AppSync is from Congito Identities (not User Pool) and does not have any user information.  I would love to just be able to pass the authenticated user's JWT as a header.
