### ISSUE TITLE
Simplifying the endpoints configuration

### ISSUE THREAD

**Issue by hassankhan** [aws/aws-amplify#697]
Feature request

What is the current behavior?

Currently the configuration for the `API` object somewhat awkwardly requires defining two extra properties aside from `endpoints`.

```
API: {
  graphql_endpoint: '',
  graphql_headers: () => {},
  endpoints: [
    {
      name: "MyAPIGatewayAPI",
      endpoint: "https://1234567890-abcdefgh.amazonaws.com"
    },
    {
      name: "MyCustomCloudFrontApi",
      endpoint: "https://api.my-custom-cloudfront-domain.com",

    },
    {
      name: "MyCustomLambdaApi",
      endpoint: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/yourFuncName/invocations",
      service: "lambda",
      region: "us-east-1"
    }
  ]
}
```

What is the expected behavior?

I would like to propose adding three new properties to an endpoint:
`type`, `authorization` and `headers`.

The authorization would(should?) allow for Cognito Federated Identities using `AWS_IAM` as well as Cognito User Pools (via User Pool ID?).
The header function would change to include the entire request object so as to allow signing via `Signer.sign()`.

The Typescript blurb below should help:

```

type UserPoolId = string;
export interface Endpoint {
  name: string;
  type?: 'graphql' | 'rest';
  authorization?: 'AWS_IAM' | UserPoolId;
  headers(req): {} | Promise<{}>
  endpoint: string;
  service: string;
  region: string;
}

const endpoints: Endpoint[] = [
  {
    name: "MyAPIGatewayGraphQLAPI",
	type: "graphql",
	authorization: 'AWS_IAM',
	headers: async () => {}
    endpoint: "https://1234567890-abcdefgh.amazonaws.com/graphql"
  },
  {
    name: "MyAPIGatewayAPI",
	type: "rest", // can be omitted
	authorization: 'AWS_IAM',
    endpoint: "https://1234567890-abcdefgh.amazonaws.com"
  },
  {
    name: "MyCustomCloudFrontApi",
	type: "rest", // can be omitted
	headers: async () => {}
    endpoint: "https://api.my-custom-cloudfront-domain.com",
  },
  {
    name: "MyCustomLambdaApi",
    endpoint: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/yourFuncName/invocations",
    service: "lambda",
    region: "us-east-1"
  }
];
```

**Comment by elorzafe** [comment]
Hi @hassankhan thanks for your feedback!

I have some questions to understand better your requirements.

- Why do you need have multiple graphql endpoints? 
- Why do you need to configure AWS_IAM or UserPool on your api? Your app should have an IdentityPool that gives aws credentials that have IAM roles. The UserPool is related to your IdentityPool and Amplify handles your credentials for you 😄 

Looking forward to your response.
Thanks!

**Comment by hassankhan** [comment]
> Why do you need have multiple graphql endpoints?

I personally do not, but if Amplify supports multiple REST/regular APIs, then why not multiple GraphQL APIs? It seems like an arbitrary limitation.

> Why do you need to configure AWS_IAM or UserPool on your api?

I have some API Gateway APIs that use a Cognito User Pool authorizer (not `AWS_IAM`), and I would like Amplify to support that use-case, if possible.

Thanks for the reply, @elorzafe, hope that clarifies things 😃

**Comment by elorzafe** [comment]
It was published aws-amplify@unstable with custom_header support during configure. I will close this issue for now. Please feel free to reopen if you have any issues with this.

**Comment by bingtimren** [comment]
Why do you need have multiple graphql endpoints?

I would add a use case and upvote the multiple graphql endpoint feature. It's common that some api is secured by IAM or cognito user pool authentication while other api is open. Currently AppSync does not support multiple authentications (that's another feature request to AppSync) so one work around would be to use multiple endpoint with different authentication methods.

**Comment by blazestudios23** [comment]
So is there a way currently to have multiple GraphQL endpoints in the config? I have a case where we need three. These are many use cases where this may be needed as well. For example if you are using external GraphQL endpoints and want to be able to directly hit the third party providers, and have your own end point as well. 

I have three massive data stores that we want to manage, they are not interconnected in any way, but the app will have a page for managing each one individually. Rather than have 400 queries and 12,000 mutations, it just much easier to deal with as three different APIs. 

If there were a way to have "graphql/datasubset" inside the of the graphQL implementation, that would be more ideal, but from what I can tell there is no way to do this.
