### ISSUE TITLE
App UI Customization

### ISSUE THREAD

**Issue by lpezet** [aws/aws-amplify#7]
I've made changes to the UI of the web client but I don't see any changes when loading up the sign in/up page.

Does aws-amplify support the App UI Customization made for app client in user pool?

NB: I'm using aws-amplify-react

**Comment by richardzcode** [comment]
Hey @lpezet what kind of customization did you mean? Amplify UI is theme based. You may provide your own 'theme' to <Authenticator /> for appearance changes.

Or, if you'd like to write your own form etc., this guide may help: https://github.com/aws/aws-amplify/blob/master/media/authentication_guide.md#5-write-your-own-auth-ui

**Comment by robsonkades** [comment]
@richardzcode links off

**Comment by cdaringe** [comment]
@robsonkades, did you locate it?

**Comment by cdaringe** [comment]
https://aws.github.io/aws-amplify/media/authentication_guide#customize-ui-theme

**Comment by markotitel** [comment]
Those pages are now gone. Any other resource available?
