### ISSUE TITLE
[Help Wanted]  How to validate password in Javascript code before sending it to AWS Amplify

### ISSUE THREAD

**Issue by vahdet** [aws/aws-amplify#709]
I want my web front-end to validate the password before calling an `Auth.signup(...)` method, so that I can verify that the password that the user types is satisfying the __AWS Cognito User Pool__'s  policy.

Is there a way for __generating a password-checker__ derived from AWS Cognito User Pool Policy (i.e. require number, require special chaarcter etc.) for Javascript?

**Comment by manueliglesias** [comment]
Hi @vahdet 

Currently there is no way, that I know of, to do what you want. It is a very interesting use case that I'll make sure to share with the team!

This would require knowing in your front-end the current password policy, and verify according to it.

If this is a problem you would like to tackle yourself, you could start by looking at the Amazon Cognito API reference, specifically the [DescribeUserPool](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DescribeUserPool.html) operation. It gives you access to the Password policy for your user pool. maybe you could call this operation at build time, save the policy as a json that you can include in your front-end code and verify at runtime.

```javascript
{
      // ...
      "Policies": { 
         "PasswordPolicy": { 
            "MinimumLength": number,
            "RequireLowercase": boolean,
            "RequireNumbers": boolean,
            "RequireSymbols": boolean,
            "RequireUppercase": boolean
         }
      },
      // ...
}
```
