### ISSUE TITLE
federated logins are not getting persisted in browser

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#71]
Using a browser and the demo React app...
login with user pool
close tab/visit site again
your session is properly restored
this works as expected

login in with google
close tab/visit site again
session is not restored
I see session data for Google stored in the browser local storage
it is just not being used to restore the session

same happens with facebook.

aws-amplify from 12/14

**Comment by jonsmirl** [comment]
A related issue with persistent federated logins is that they should stop working if permission for the app is revoked at FB/G.

**Comment by jonsmirl** [comment]
I have examined other solutions for this problem that work like this...

1) Browser authenticated to G/FB, gets code instead of token
2) Send code to server
3) Server uses code to get id token, refresh token (remember these)
4) Server generates a session cookie (JWT token) and credentials, sends to browser
5) browser uses credentials to access API
6) Server remembers this session cookie
7) server refreshes with FB/G to keep long term tokens from expiring

Later browser sessions
1) browser sends session cookie
2) server checks to see if session cookie still valid
2) Server checks to see if id token, refresh token still valid (ie app deleted at FB/G)
3) If ok, send credentials

Logout just deletes the session cookie. You can also set them on the server to expire after a week of non-use.

Some side effects: this tracks the devices accessing the account. You can perform global log out by deleting all of the session cookies at the server.

If someone logs in at a public terminal and does not log out. 
1) The login dialog should have a 'remember me' checkbox. If not remembered cookie not saved.
if they mistakenly remember on a public terminal..
1) they can see that the log in is still valid since session cookie still at server
2) they can then delete that cookie at the server
3) alternatively if they delete the app at FB/G the cookie will stop working
4) backup plan is server deleting session after a week of non-use

**Comment by jonsmirl** [comment]
When the app loads, the FB code gets the login status and does nothing with it.
withFacebook.jsx
            fb.getLoginStatus(response => logger.debug(response));

The Google code does not appear to be getting the initial status.

**Comment by mlabieniec** [comment]
This should be fixed in the latest 0.1.30 that is now published, let us know if you still are running into issues here. We are working on furthering federated support.
