### ISSUE TITLE
Custom analytics events not recorded in react native app

### ISSUE THREAD

**Issue by hrkeni** [aws/aws-amplify#712]
I was trying to use Pinpoint for analytics. I configured the project using `awsmobile-cli`.
I followed setup instructions as per: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/react-native-add-analytics.html

My session start events do get recorded but my custom events do not. What am I missing here?
Even tried `Analytics.enable()` after calling `Amplify.configure()` but that doesn't seem to help.

**Comment by powerful23** [comment]
@hrkeni can you open the debug mode to see more details when sending the event? ```window.LOG_LEVEL = 'DEBUG'```
