### ISSUE TITLE
Re-Surfacing Issue #336

### ISSUE THREAD

**Issue by Integralist** [aws/aws-amplify#719]
Issue #336 was closed when the README was updated to include information on how to source `./aws-exports`. But was later removed, see my comment in that PR [here](https://github.com/aws/aws-amplify/pull/339#issuecomment-383892338).

I'm still getting the error that was reported in issue #336.

If I look at [awsmobile-cli](https://github.com/aws/awsmobile-cli) I see there is no such file existing there:

![screen shot 2018-04-24 at 12 20 20 pm](https://user-images.githubusercontent.com/180050/39184059-fd948be2-47b9-11e8-94bd-9e4305d77226.png) 

Below is what I've been setting up (FYI I'm new to modern client-side development)...

```bash
# npx comes with npm 5.2+
npx create-react-app foobar

# start up the local webserver to run this app
cd foobar && npm start

# install amplify (required for dealing with aws via js)
npm install --save aws-amplify

# optional extras for react
npm install --save aws-amplify-react

# tried installing globally (npm install -g awsmobile-cli), but that didn't help
npm install --save awsmobile-cli
```

Then within the application `App.js` I'm trying to add the following, with the last line causing the compiler to error:

```js
import Amplify from 'aws-amplify';
import { withAuthenticator } from 'aws-amplify-react';
import aws_exports from './aws-exports';
```

The error being:

```
Module not found: Can't resolve './aws-exports' in '/Users/integralist/code/aws/js-app-example/foobar/src'
```

I've also tried using `find . -name '*aws-exports.js'` to locate the file, but no results.

**Comment by richardzcode** [comment]
Hi @Integralist Here is the quick start guide: https://aws.github.io/aws-amplify/media/quick_start

The [Automatic Setup](https://aws.github.io/aws-amplify/media/quick_start#automatic-setup) section has steps to setup with awsmobile-cli. `aws-exports.js` file will be generated by CLI.

Thanks,
Richard
