### ISSUE TITLE
Add service_info to API Config (want to use custom domain at endpoint)

### ISSUE THREAD

**Issue by 70-10** [aws/aws-amplify#72]
Hi.
I can't English.   I use Google Translate.
I'm sorry if I do not understand the sentences I wrote...

I want to be able to set serice_info as below ↓

```js
Amplify.configure({
  Auth: {
    identityPoolId: "ap-northeast-1:********-****-****-****-************",
    region: "ap-northeast-1",
    userPoolId: "ap-northeast-1_*********",
    userPoolWebClientId: "**************************"
  },
  API: {
    endpoints: [
      {
        name: "API",
        endpoint: "https://custom-domain.com",
        service_info: {
          service: "execute-api",
          region: "ap-northeast-1"
        }
      }
    ]
  }
}
```

I could not resolve the service_info and it caused an error when I made the endpoint of the API a custom domain.

`parse_service_info` is expecting `/([^\.]+)\.(?:([^\.]*)\.)?amazonaws\.com$/`.
`service_info.region` and `service_info.serivce` are always null when you are in a custom domain.
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Common/Signer.ts#L104

`parse_service_info` doesn't execute when `service_info` exists.
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Common/Signer.ts#L249

But always execute `parse_service_info`, because RestClient does not setting service_info.
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/API/RestClient.ts#L165

I think it will solve it, if you can pass the service_info set in config to the third argument when `Signer.sign` calls.

**Comment by mlabieniec** [comment]
Added support for service_info and customer domains in PR #321
