### ISSUE TITLE
Push Notification on background

### ISSUE THREAD

**Issue by tlofano** [aws/aws-amplify#722]
Do you want to request a feature or report a bug?
Question: Currently, is the onNotification event supported on background?
If the answer is yes. I'm having problems with this, is there any other requirement that the documentation doesn't say?
If the answer is no, I'm submitting a Feature Request.

What is the current behavior?
onNotification is only triggered when the app is in the foreground

What is the expected behavior?
onNotification trigger when the app is in background

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
I'm developing for Android.
aws-amplify-react-native: 0.2.9
aws-amplify: 0.2.15
react-native: 0.54.4

I follow this implementation:
https://aws.github.io/aws-amplify/media/push_notifications_setup.html

**Comment by tlofano** [comment]
@powerful23 thanks for quick response. I'll close the issue because I found and fix my problem. Again, thanks. My implementatios was say the documentation: 

```
PushNotification.configure(aws_exports);

PushNotification.onRegister((token) => {
     console.log('in app registration', token);
});

PushNotification.onNotification((notification) => {
      this.somethingToDo();
});
```

This works well, even on background.

**Comment by iuliuvisovan** [comment]
What was the problem in your case?
