### ISSUE TITLE
 Warning when configuring Amplify with only GraphQL credentials - Error: Missing required key 'IdentityPoolId'

### ISSUE THREAD

**Issue by dabit3** [aws/aws-amplify#726]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Warning is thrown when using AWS Amplify with only the API GraphQL category.

Configuration looks like this:

```
const config =  {
  "aws_appsync_graphqlEndpoint": "https://xxx.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "xxx"
}

import config from './AppSync'
import Amplify from 'aws-amplify'

Amplify.configure(config)
```

Actual functionality is fine as far as data fetching is concerned, it all still works just throws an error:

__WARN] 44:09.976 API - ensure credentials error: Error: Missing required key 'IdentityPoolId' in params at ParamValidator.fail__

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

1. Create new React project
2. Install aws-amplify
3. Configure AWS AMplify with only API GraphQL credentials.
4. Run a query 

What is the expected behavior?
No warnings

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
__"version": "0.3.3"__

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by elorzafe** [comment]
Hi @dabit3 thanks for your feedback. We will add this on our backlog.

**Comment by jordanranz** [comment]
Warning is thrown at this line:
https://github.com/aws/aws-amplify/blob/180a996345e878b51badb34031ab1e69bc480e2c/packages/aws-amplify/src/API/API.ts#

GraphQL queries hit this block of code to make a 'post' request:
https://github.com/aws/aws-amplify/blame/180a996345e878b51badb34031ab1e69bc480e2c/packages/aws-amplify/src/API/API.ts#L399

The post function seems to check credentials from Auth even though Auth configuration is not required for to use of GraphQL. I will look into a fix to change the credential check for GraphQL queries.
