### ISSUE TITLE
Using Amplify Auth to connect to IOT device shadows?

### ISSUE THREAD

**Issue by janpoltan** [aws/aws-amplify#728]
Is there an example on how to use the auth and access the device shadows?
Is the PubSUB api similar to the IOT device shadows?

**Comment by manueliglesias** [comment]
Hi @janpoltan 

Yes, you can use the PubSub category to establish a connection to AWS IoT and [subscribe](https://aws.github.io/aws-amplify/media/pub_sub_guide#subscribe-to-multiple-topics) to the appropriate [device shadow topics](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html)

The Amplify [documentation for PubSub](https://aws.github.io/aws-amplify/media/pub_sub_guide#aws-iot) can show you how to configure it

**Comment by joshuasa-synapse** [comment]
Would be great to have a wrapper API that manages things -- I couldn't find that either.

The shadow updates are available through ordinary MQTT topics, and Amazon documents them here:  https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html

Since I haven't found anything in Amplify, I'm planning to handle all the interactions myself, but haven't started yet.

**Comment by develpr** [comment]
I agree, it would be SUPER handy to have the actual device shadow exposed in more of an API, instead of having to implement / watch for updates ourselves!

**Comment by jskrt** [comment]
Any updates on this?

**Comment by roeemz** [comment]
This should definitely turn into a feature, Amplify shadow integration should be easier than having to manually implement this using MQTT messages.

**Comment by jamesthesken** [comment]
Would using the PubSub API still give you the benefits that the device shadows offer? 

I am trying to understand how this might work in an offline scenario. e.g if I wanted to view the most recent device shadow wouldn't I have to "wait" for the shadow to publish?

Thank you for any help @manueliglesias

**Comment by atyshka** [comment]
+1 on this. Would like to see more of the functionality from the js sdk such as shadows make its way into amplify.
