### ISSUE TITLE
Bug in completeNewPassword in Auth class

### ISSUE THREAD

**Issue by atlas5d-emily** [aws/aws-amplify#732]
Bug

**Context:** I am not using the amplify-react HOC components, but rather explicitly calling Auth functions in the frontend of my react app. My user pool requires TOTP mfa (no SMS). 

**Bug:** An error is thrown when a user changes his password (completeNewPasswordChallenge). 

**Steps taken:**
1. My code calls ```Auth.completeNewPassword```
2. The Auth class calls ```AuthClass.prototype.completeNewPassword``` with callback parameters onSuccess, onFailure and mfaRequired. 
3. The auth method calls ```CognitoUser.prototype.completeNewPasswordChallenge```, which makes a request to ```'RespondToAuthChallenge'```.
4. The callback method inside```'RespondToAuthChallenge'```  calls an internal method ```_this5.authenticateUserInternal(dataAuthenticate, authenticationHelper, callback);```
5. The first parameter in ```CognitoUser.prototype.authenticateUserInternal(dataAuthenticate, authenticationHelper, callback);``` has the value```dataAuthenticate.ChallengeName = 'MFA_SETUP'```. 
5. As a result of the above condition ```dataAuthenticate.ChallengeName = 'MFA_SETUP'```, the function then tries to call ```callback.mfaSetup```, which is NOT an option in the callback for ```AuthClass.prototype.completeNewPassword```. This auth function only supports onSuccess, onFailure and mfaRequired. This causes an error to be thrown and does not allow the user to move to the next challenge. 
**Note:** The user's password was successfully changed, despite the error.

**Fix:** When I change the method inside ```CognitoUser.prototype.authenticateUserInternal``` to 
```
if (challengeName === 'MFA_SETUP') {
      this.Session = dataAuthenticate.Session;
      return callback.mfaRequired(challengeName, challengeParameters);
    }
```
it all works correctly

It does not work in multiple (including the latest) versions of Amplify.

**Comment by powerful23** [comment]
@atlas5d-emily thanks for pointing out!
