### ISSUE TITLE
Can't use a custom endpoint for cognito

### ISSUE THREAD

**Issue by dguayrobotiq** [aws/aws-amplify#744]
Do you want to request a feature or report a bug?

Bug

What is the current behavior?

1. Create CognitoUserPool with my config

```
const userPool = new AmazonCognitoIdentity.CognitoUserPool({
    UserPoolId: myUserPoolId
    ClientId: myClientId
    endpoint: 'https://cognito.myorganization.com');
})
```

where `https://cognito.myorganization.com` is a subdomain of my organization.

2. Add a CNAME record in my DNS to that alias to cognito url

CNAME name: `cognito.myorganization.com`
Alias to: `cognito-idp.us-east-1.amazonaws.com.`

3. When using the user pool to login, I get this error:

`OPTIONS https://cognito.myorganization.com/ net::ERR_CERT_COMMON_NAME_INVALID`

What is the expected behavior?

`https://cognito.myorganization.com` should redirect to `https://cognito-idp.us-east-1.amazonaws.com` 

We tried multiple configuration for this to work but no dice. Am I missing something obvious? I'm using `amazon-cognito-identity-js 1.20.0`.

**Comment by manueliglesias** [comment]
Hi @dguayrobotiq 

The `ERR_CERT_COMMON_NAME_INVALID` message points to a problem with your SSL cert. You can start there by, for example, verifying that you can issue a https request to your endpoint.

`curl -v -s https://your.endpoint.example.com`

**Comment by dguayrobotiq** [comment]
@manueliglesias I've tried running the command and it is working. I think the problem is we need to add cognito to our DNS wildcard on AWS but we're not sure how to do that.

**Comment by mlabieniec** [comment]
Closing this for now. Please let us know if you find any issues related to the library and need to re-open.
