### ISSUE TITLE
Facebook access token not mapped correctly in federated signin

### ISSUE THREAD

**Issue by shb7919** [aws/aws-amplify#75]
In aws-amplify-react package, the src/Auth/Provider/withFacebook.jsx doesn't correctly map the facebook access token when doing a federatedSignIn. It tries to map the accessToken directly from the root of the response, instead of getting it from the authResponse property of the response object.

I.e: (line 42 currently)
`const { accessToken } = response;`

should have been:

`const { accessToken } = response.authResponse;`

**Comment by mlabieniec** [comment]
Fixed in #74 now published to latest release 0.1.30
