### ISSUE TITLE
After signing in, user is always taken to screen that prompts for MFA code, even if mfa-configuration is OFF

### ISSUE THREAD

**Issue by SagarMhatre** [aws/aws-amplify#751]
Do you want to request a feature or report a bug? bug

What is the current behavior?
Even if MFA is disabled, after Sign In , MFA code is asked

What is the expected behavior?
When setting in mobile-hub-project.yml (created by awsmobile cli) is mfa-configuration: OFF,
User should be taken to the greetings page after successful login

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
aws-amplify@0.3.3
previous version of aws-amplify - not tried

Temporary Work around that I used -
The node_modules\aws-amplify-angular\src\components\authenticator\sign-in.component.ts 
has logic that always takes you to the node_modules\aws-amplify-angular\src\components\authenticator\confirm-sign-in.component.ts
where you are asked for MFA Code after successful sign in (does not check if MFA is required or not)
Code change in sign-in.component.ts:
	.then(() => {this.amplifyService.setAuthState({ state: 'confirmSignIn', user: user }); 	//previous
	.then(() => {this.amplifyService.setAuthState({ state: 'signedIn', user: user }); 		//changed
After making changes to the code in sign-in.component.ts,need to run 
	\node_modules\aws-amplify-angular>npm run build

**Comment by elorzafe** [comment]
On the next amplify-angular release this will be solved

**Comment by crsepulv** [comment]
when will be availbale this fix? how can I use it before the release?
