### ISSUE TITLE
MFA failing with missing Session parameter

### ISSUE THREAD

**Issue by Integralist** [aws/aws-amplify#758]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

Using the [AWS provided sample application](https://github.com/aws-samples/aws-mobile-react-sample/tree/master/client/src) with Amplify version 0.3.3 I'm trying to log into the application, but when I'm redirected to `/main` I see the error:

```
{code: "InvalidParameterException", name: "InvalidParameterException", message: "Missing required parameter Session"}
``` 

If I then refresh the `/main` page I'm not able to access it and I'm sent back to the `/login` endpoint.

Specifically the call request flow is:

1. `Auth.signIn`
2. `Auth.confirmSignIn`

## What is the expected behavior?

That I'm sent to `/main` and that I'm able to refresh the page and have the application remember I'm logged in (for however long).

## Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

I'm using Amplify `0.3.3`. I had to update the Amplify version from what the sample app used because of a separate error related to user registering, where I couldn't register a new user because of a standard (required) attribute `name` not being provided. Seems I was able to fix that issue by updating the Amplify version and utilising the newer API call where an object could be passed as a param to `Auth.signUp`.

## You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

...

**Comment by elorzafe** [comment]
Hi @Integralist did you use awsmobile-cli to create your backend resources?

I just tried on MacOS Sierra on Firefox and Google Chrome, on both MFA works ok. 

I can confirm the problem with reloading the page. (redirects to the login screen)

**Comment by Integralist** [comment]
Hi @elorzafe, no I manually set-up cognito via console and connect manually using `Amplify.configure` (I don't use aws_export file that awsmobile-cli would have produced)

**Comment by Integralist** [comment]
This is the code that's executing...

```js
Auth.confirmSignIn(this.state.cognitoUser, this.state.code).then(data => {
    console.log('>>> confirm sign-in complete: ', data);
}).catch (err => console.log('confirm sign-in failed!', err))
```

The `catch` isn't triggered. The `data` returned from the API call _is_ an error object 🤦‍♂️ 

This is what I see in the console logs...

**First, an OPTIONS request is made**

```
Fetch finished loading: OPTIONS "https://cognito-idp.us-east-1.amazonaws.com/".
request @ Client.js:46
sendMFACode @ CognitoUser.js:765
(anonymous) @ Auth.js:569
./node_modules/aws-amplify/lib/Auth/Auth.js.AuthClass.confirmSignIn @ Auth.js:568
(anonymous) @ Login.jsx:94
Promise.then (async)
(anonymous) @ Login.jsx:91
Promise.then (async)
(anonymous) @ Login.jsx:88
Promise.then (async)
(anonymous) @ Login.jsx:85
Promise.then (async)
(anonymous) @ Login.jsx:82
Promise.then (async)
(anonymous) @ Login.jsx:79
Promise.then (async)
_callee2$ @ Login.jsx:76
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.(anonymous function) @ runtime.js:117
step @ Login.jsx:19
(anonymous) @ Login.jsx:19
(anonymous) @ Login.jsx:19
(anonymous) @ bundle.js:182497
Button._this.handleClick @ Button.js:70
boundFunc @ ReactErrorUtils.js:63
./node_modules/react-dom/lib/ReactErrorUtils.js.ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:69
executeDispatch @ EventPluginUtils.js:83
executeDispatchesInOrder @ EventPluginUtils.js:106
executeDispatchesAndRelease @ EventPluginHub.js:41
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:52
forEachAccumulated @ forEachAccumulated.js:22
processEventQueue @ EventPluginHub.js:252
runEventQueueInBatch @ ReactEventEmitterMixin.js:15
handleTopLevel @ ReactEventEmitterMixin.js:25
handleTopLevelImpl @ ReactEventListener.js:70
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145
18:33:49.434 
```

**Followed by a `[DEBUG]` log**, that indicates a failure to sign in...

```
[DEBUG] 33:49.436 AuthClass - confirm signIn failure:
code: "InvalidParameterException"
message: "Missing required parameter Session"
name: "InvalidParameterException"
```

**This is the final console log**, which is the returned data from the API and is effectively the same as the debug message...

```
{code: "InvalidParameterException", name: "InvalidParameterException", message: "Missing required parameter Session"}
```

**Comment by Integralist** [comment]
I've read through some old GitHub issues, back before Amplify was a wrapper around the now defunct cognito JS library (well, Amplify is now a facade in front of that old cognito js lib), and people suggested that some calls like `sendMFACode` needed to be made _on the cognito user object_ otherwise it would fail.

Now Amplify wraps this old cognito js library (and I can see it indeed makes a call to `sendMFACode` in the debug logs) it would suggest that Amplify would (or _should_) be intelligently handling that scenario. 

But that doesn't appear to be the case 🤔

**Comment by kalzoo** [comment]
I ran into this same issue in development (repeatedly signing in and out) - MFA worked for two cycles, and then afterwards, each call to `Auth.confirmSignIn` would fail with this message, `Missing required parameter Session`. Debug calls to `Auth.currentSession()` were showing that authentication was succeeding even without MFA, but the object returned by `Auth.signIn` had a null value for the key `Session`. Not sure if that is intended behavior I haven't seen documented - AFAICT AWS temporary roles live on after logout, but tokens aren't supposed to.

Clearing the domain cookies was an instant fix - SMS MFA verification came back.
