### ISSUE TITLE
The doc of Amazon S3 Bucket CORS Policy still renders wrong

### ISSUE THREAD

**Issue by baharev** [aws/aws-amplify#76]
I have tried to fixed this with the already merged pull request #53 but Amazon S3 Bucket CORS Policy still renders wrong at:

https://aws.github.io/aws-amplify/media/storage_guide.html#amazon-s3-bucket-cors-policy

However, it renders OK at:

https://github.com/aws/aws-amplify/blob/master/media/storage_guide.md#amazon-s3-bucket-cors-policy

How is the former page updated?

It either has not been updated yet, or it wasn't the superfluous space that caused the problem. In any case, please check.

**Comment by mlabieniec** [comment]
@baharev we are working on updating the .io docs, currently they reside on the gh_pages branch but we are looking into a better way to build/deliver them, thanks for the comments/feedback and catching these.
