### ISSUE TITLE
aws-amplify-react: There is no screen for unconfirmed account to enter confirmation code when they re-open the login UI

### ISSUE THREAD

**Issue by pmbanugo** [aws/aws-amplify#767]
Do you want to request a feature or report a bug?
Feature 

What is the current behavior?
I'm using the `withAuthenticator(App)` and the app uses UI from aws-amplify. When an unconfirmed user returns to sign in it tells them the account needs confirmation but there is no link/page to enter the code. The confirmation page only shows immediately after signup but if a user revisits the page they can't navigate to a confirmation screen

What is the expected behavior?
If an account is not confirmed, show a link to navigate to a confirmation screen

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
 I'm using version 0.3.3 and aws-amplify-react 0.1.43

**Comment by elorzafe** [comment]
Hi @pmbanugo Thanks for your feedback. We will add this to our backlog.

**Comment by jdeanwaite** [comment]
If you need a quick solution, when you go to the Sign Up screen, there is a button that says "Confirm a code". I believe that is the link you are referring to, however you are right that it does not display on the sign in page once an unconfirmed user tries to sign in.

**Comment by pmbanugo** [comment]
I see that now. I initially didn't see it and I've got some unconfirmed account because they're unable to find that link and instinct didn't direct them there. 

I am proposing this flow:

1. User tries to login with an unconfirmed account.

2. Show the confirmation screen alongside the error message "Account not confirmed". 

3. User can paste in the code or click the "Resend Code" button to resend it. 

What do you think?

**Comment by ablbol** [comment]
Hi
I am not using withAuthenticator(App).  I am using my own UI with React Native.  I was wondering how to resend activation code.  Can you point me in the right direction.  
I have the following 2 cases :

case 1:
- user signs up and is expected to enter activation code (sent by email) but the user never receives the code.

case 2:
- user signs up and is expected to enter activation code (sent by email).  User did not enter activation code but rather came back after a while and tried to sign in.  The user will receive "UserNotConfirmedException", so I need a way to resend activation code to the user to ask the user to activate account.

I would appreciate it if someone can tell me how to resend the activation code.
Thanks

**Comment by powerful23** [comment]
@ablbol 
for case 1: You need to confirm you have chosen email as the verification method in your Cognito user pool console.

for case 2: You can use `Auth.resendSignUp()` to resend the code. https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L261

**Comment by pmbanugo** [comment]
Hi @powerful23 with that PR I can upgrade the npm package and have it working with `aws-amplify-react` ?

**Comment by powerful23** [comment]
@pmbanugo yes it should work for you now.
