### ISSUE TITLE
Getting refreshed Id Token with aws-amplify-react

### ISSUE THREAD

**Issue by RedHatter** [aws/aws-amplify#779]
I have a react app using aws-amplify-react for authentication. I use `props.authData.signInUserSession.idToken.jwtToken` from a child of `Authenticator` to authenticate with my backend. I would expect that when amplify refreshes the token amplify-react would pass it down through the props and everything would stay in sync. That is not what happens. The token expires and no new token is passed down to the children. What is the supported way of passing the token once it is refreshed?

I saw #42 but would expect `authData.signInUserSession.idToken.jwtToken` to be equivalent to `Auth.currentSession().idToken.jwtToken` and being a react prop to be passed automatically once it changes.

Auth.jsx

    import React, { Component } from 'react'
    import Amplify from 'aws-amplify'
    import {
      Authenticator, Greetings,
      SignIn as AmplifySignIn,
      SignUp as AmplifySignUp,
      ConfirmSignUp as AmplifyConfirmSignUp
    } from 'aws-amplify-react'

    import App from './App.jsx'
    import SignIn from './SignIn.jsx'

    Amplify.configure({
      Auth: {
        region: 'us-west-2',
        userPoolId: 'us-west-2_*****,
        userPoolWebClientId: ******'
      }
    })

    class Auth extends Component {
      render() {
        return (
          <Authenticator hide={ [ AmplifySignIn, AmplifySignUp, AmplifyConfirmSignUp, Greetings ] }>
            <SignIn />
            <App />
          </Authenticator>
        )
      }
    }

    export default Auth

App.jsx (simplified)

    import React, { Component } from 'react'
    import Dashboard from './Dashboard.jsx'

    class App extends Component {
      render () {
        if (this.props.authState != 'signedIn')
          return null

        return <Dashboard authorization={ this.props.authData.signInUserSession.idToken.jwtToken } />
      }
    }

    export default App

**Comment by powerful23** [comment]
@RedHatter hi I would recommend you using `Auth.currentSession` to get those tokens because when this method is called, amplify will check whether the session expired or not and then update it automatically. If you directly using the session from the object you would need to refresh it by yourself.

**Comment by powerful23** [comment]
Please feel free to reopen if necessary.

**Comment by mghazanfar** [comment]
It does not refresh the idToken itself. I tried it but token remains the same after an hour and it expires after an hour too.

**Comment by sebastienfi** [comment]
Anyone with a clear answer to that?
