### ISSUE TITLE
Re-entry into async functions causes uncaught exceptions

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#78]
My user pool does not use guest Credentials, the new support for guest CognitoIdentityCredentials broke my use case.

I error out here, since the calling code is not expecting the 'no current user' return.

         AuthClass.prototype.currentSession = function () { 
             if (!this.userPool) {
                 return Promise.reject('No userPool');
             }
             var user = this.userPool.getCurrentUser();
             if (!user) {
                 return Promise.reject('No current user');

Higher up in configure, pickupCredentials() is not expecting an error.

        if (userPoolId) {
            this.userPool = new CognitoUserPool({
                UserPoolId: userPoolId,
                ClientId: userPoolWebClientId
            });
            this.pickupCredentials();

**Comment by jonsmirl** [comment]
Adding an unauthenticated role to my identity pool did not fix this. 
I am using manual setup and the configure call is failing.

    Amplify.configure({
      Auth: {
        identityPoolId: 'us-east-1:.... /
        region: 'us-east-1', 
        userPoolId: 'us-east-1_....', 
        userPoolWebClientId: '71hfs....', 
      },
    });

I'll try again with a configuration file from Mobile Hub

**Comment by jonsmirl** [comment]
This problem appears to be timing related. When I make changes to try and pin it down it goes away.  Here's screen shot of the call stack.

![screenshot from 2017-12-17 19-35-23](https://user-images.githubusercontent.com/14943/34085623-8bd3b288-e361-11e7-8cb2-bf0eebe4767a.png)

It may not be a regression, instead changes in my app may have altered the timing of how the code runs.

**Comment by mlabieniec** [comment]
Hi Jon, it's possible that your code is trying to use the auth module before it's signed in, or established a session, which in fact should be handled though. Are you using the react library and Authenticator or using just plain JS for this?

**Comment by mlabieniec** [comment]
@jonsmirl I am able to reproduce in Angular with the latest. Looking into it more now.

**Comment by mlabieniec** [comment]
@jonsmirl it seems like this occurs when using `await` syntax on Auth.currentSession(). It's not actually failing, but the promise is getting rejected (as it should), but if you use the await syntax this will just produce an error, which technically it should (since there is no session). Are you expecting more to receive some sort of empty object or `undefined` for session? If you use standard promise syntax it works as expected i.e.

    Auth.currentSession()
        .then(data => console.log('this will have a session if available') )
        .catch(err => console.log('this will fire if no session')

How ever if you use an async function

    let session = Auth.currentSession();

This will throw an error

    ERROR Error: Uncaught (in promise): No current user

**Comment by jonsmirl** [comment]
I think this is the source of my troubles, I tried to put a Greeting into the page header.
I am only using the higher level React components.

    class Header extends React.Component { // eslint-disable-line react/prefer-stateless-function
      render() {
        return (
          <div>
          Hello
            <Authenticator hideDefault={true}>
              <Greetings />
            </Authenticator>

Here is my startup...

    Amplify.configure({
      Auth: {
        identityPoolId: 'us-east-1:...',
        region: 'us-east-1',
        userPoolId: 'us-east-1_C...',
        userPoolWebClientId: '71...
      },
    });

    // Create redux store with history
    const initialState = {};
    const history = createHistory();
    const store = configureStore(initialState, history);
    const MOUNT_NODE = document.getElementById('app');

    const render = (messages) => {
      ReactDOM.render(
        <Provider store={store}>
          <LanguageProvider messages={messages}>
            <ConnectedRouter history={history}>
              <App />
            </ConnectedRouter>
          </LanguageProvider>
        </Provider>,
        MOUNT_NODE
      );
    };
































































































































',
      },
    });

    // Create redux store with history
    const initialState = {};
    const history = createHistory();
    const store = configureStore(initialState, history);
    const MOUNT_NODE = document.getElementById('app');

    const render = (messages) => {
      ReactDOM.render(
        <Provider store={store}>
          <LanguageProvider messages={messages}>
            <ConnectedRouter history={history}>
              <App />
            </ConnectedRouter>
          </LanguageProvider>
        </Provider>,
        MOUNT_NODE
      );
    };

**Comment by jonsmirl** [comment]
I can hit this with nothing but the Amplify.configure() call in my app and using the remote debugger.  The remote debugger is altering the timing which causes the problem to occur. If I use the in-browser debugger I don't hit it.

I also logged into my Cognito user pool so that I have a current user, I still hit this problem when using the remote debugger.

**Comment by mlabieniec** [comment]
@jonsmirl there was a fix that went out for this yesterday and was published to npm v0.1.22 (or latest master) should address this let me know if you still run into it.

**Comment by jonsmirl** [comment]
Still there

jonsmirl@ubuntu-16:~/aosp/web3/web3$ yarn add aws-amplify-react aws-amplify | grep aws
├─ aws-amplify-react@0.1.23
├─ aws-amplify@0.1.22
├─ aws-sdk-mobile-analytics@0.9.2
├─ aws-sdk@2.171.0

![image](https://user-images.githubusercontent.com/14943/34171818-cd5ada94-e4bd-11e7-9366-9707a4bf02bb.png)

I rebuilt the Webpack DLL for sure

jonsmirl@ubuntu-16:~/aosp/web3/web3$ npm run build:dll

> react-boilerplate@3.5.0 build:dll /home/jonsmirl/aosp/web3/web3
> node ./internals/scripts/dependencies.js

Building the Webpack DLL...
Hash: 0093d8d89b46be85332e
Version: webpack 3.5.5
Time: 5830ms
                      Asset     Size  Chunks                    Chunk Names
reactBoilerplateDeps.dll.js  6.78 MB       0  [emitted]  [big]  reactBoilerplateDeps
chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 5.67 MB [entry] [rendered]
jonsmirl@ubuntu-16:~/aosp/web3/web3$ yarn start
yarn run v1.3.2
$ cross-env NODE_ENV=development node server
Server started ! ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://192.168.1.183:3000
-----------------------------------
Press CTRL-C to stop
    
webpack built cebf1a8d7c1c2e6f4143 in 3148ms
webpack building...
webpack built 1ad3f17112d016bf02e3 in 180ms
webpack building...
webpack built 7ef5c27c57d2c229087a in 83ms
webpack building...
webpack built e10a3d31a0f0e326cd74 in 91ms
webpack building...
webpack built c3f30841fadb4e8072db in 132ms

**Comment by jonsmirl** [comment]
If I delete the files in, node_modules/aws-amplify/dist$ rm *, then the source maps correctly.

![screenshot from 2017-12-17 19-35-23](https://user-images.githubusercontent.com/14943/34172427-07b1f78e-e4c0-11e7-9de0-dbf7faef690c.png)\

This is similar error in another place

![screenshot from 2017-12-17 19-35-23](https://user-images.githubusercontent.com/14943/34172494-3c20234c-e4c0-11e7-9c02-68d2124b9c32.png)

**Comment by jonsmirl** [comment]
If I tell my IDE not to stop on uncaught exceptions, well then the errors go away.  But there shouldn't be uncaught exceptions.  Other people maybe not be noticing this because they don't have this turned on in their debugger.

**Comment by mlabieniec** [comment]
Hi @jonsmirl yes, so this does make sense, as in my comment above, the promise rejection is occurring "correctly" since you are trying to get an authenticated user and/or session when there is none, to prevent your uncaught exception you would surround it with a try/catch:

    try { 
        this.session = await Auth.currentSession()
    catch(e) { console.log('no session') }

Again this only occurs when using await syntax [see comment above](#issuecomment-352300940).

**Comment by jonsmirl** [comment]
I pushed my basic demo app out to git hub.
https://github.com/jonsmirl/web3
yarn install, yarn start
Open browser and debugger, turn on pause on uncaught exception.
Click the Login tab, click the Home tab, click the login tab
You should hit the exception.

The only interesting code is in:
https://github.com/jonsmirl/web3/blob/master/app/app.js
https://github.com/jonsmirl/web3/blob/master/app/containers/LoginPage/index.js

**Comment by jonsmirl** [comment]
I asked a friend who is a Javascript expert, he did not look at the code but had experienced similar issues. His suspicion is that since async things like currentUserPoolUser() are getting called from the render() function the calls are being re-entered (from another need to render) before the async part of the first call finishes. When they get re-entered, the promise from the first entry gets lost which is what causes the 'uncaught exception' errors. He says this is why he uses things like Redux to keep the async activities independent of the rendering.

**Comment by mlabieniec** [comment]
Newer version should be more accommodating to the exceptions, for now if you use async await it will throw an exception on rejection so you need to surround it with a try catch, or use then.catch similarly. We have more exception handling stories in our backlog and we'll track this one as part of that as well

**Comment by tuanluu-agilityio** [comment]
I  saw on `Auth` have `user` object when `signedIn`:
```
try {
     const { accessToken, idToken, refreshToken } = Auth.user.signInUserSession
     const { jwtToken } = accessToken
     console.warn('this.session: ', jwtToken)
} catch (e) { console.log('no session') }
```
Look like docs missing update or I'm missing things here?
```
Retrieve Current Session
Auth.currentSession() returns a CognitoUserSession object which contains JWT accessToken, idToken, and refreshToken.
```
Refer: https://aws.github.io/aws-amplify/media/authentication_guide#using-withauthenticator-hoc
