### ISSUE TITLE
awsmobile appsync configure takes the wrong region

### ISSUE THREAD

**Issue by lucfranken** [aws/aws-amplify#789]
**_Do you want to request a feature or report a bug?_**
BUG

**_What is the current behavior?_**
Command tries to setup appsync in a wrong region which does not support appsync at all. It raises the error:

> This service may not be available in the `us-west-1' region.

But the requested region was: us-west-2

**_Reproduction_**

```
$ awsmobile appsync configure

? Please specify the auth type:  AMAZON_COGNITO_USER_POOLS
? user pool id:  us-west-2_xxxxxxxxx
? region:  us-west-2
? default action:  ALLOW

$ awsmobile push

checking the backend contents
   generating backend project content
   done
backend build artifacts are saved at: 
/Users/xxxxxx/awsmobilejs/.awsmobile/backend-build

preparing for backend project update: xxxx
done
⠧ creating appsync: create graphql api...create graphal API err diy
{ UnknownEndpoint: Inaccessible host: `appsync.us-west-1.amazonaws.com'. This service may not be available in the `us-west-1' region.
    at Request.ENOTFOUND_ERROR (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/event_listeners.js:456:46)
```

**_What is the expected behavior?_**
Install and configure appsync in the selected region. According to: 
https://docs.aws.amazon.com/general/latest/gr/rande.html
It's not even available there.

It might be connected to this setting in aws-exports.js but I am not sure on that:

> 'aws_project_region': 'us-west-1',

**_Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?_**

> "aws-amplify": "^0.3.3",

**Comment by UnleashedMind** [comment]
Hi @lucfranken 
Thanks for the feedbacks, the cli configuration part for the appsync is probably a little misleading. 
The prompts for `user pool id`, `region`, `default action` only happen after you have selected AMAZON_COGNITO_USER_POOLS as the auth type. And you are setting the information of the **user pool** that's going to be used to access the appsync api. 

If you want to change the region that you are working at with the awsmobile-cli, execute `awsmobile configure aws`. There you can change the region to point to a region that the appsync feature is available.

**Comment by lucfranken** [comment]
@UnleashedMind thanks! Correct that was the issue. Did not expect that because the region for incognito is already mentioned in the user pool id. I did not expect duplicate data entry to be needed so I inferred that would be the region for appsync!

**Comment by nielsgl** [comment]
@UnleashedMind I have a similar issue.

In a new project I'm using auth type `AWS_IAM`, and `awsmobile configure aws` is set to region `us-west-2`. When I enable and push `cloud-api` everything gets deployed to `us-west-2` as expected, then enabling `database` it also works and creates a database in `us-west-2`.

However, when I enable and push _appsync_ next, it does create the AppSync app in `us-west-2`, but it creates the tables in `us-east-1`, which is correct because in the `dataSources.json` file it sets the `awsRegion` and `Region` to `us-east-1`,

```json
{
    "dataSources": [
        {
            "name": "AppSyncCommentTable",
            "description": null,
            "type": "AMAZON_DYNAMODB",
            "serviceRoleArn": "{managed-by-awsmobile-cli}",
            "dynamodbConfig": {
                "tableName": "AppSyncCommentTable-{suffix}",
                "awsRegion": "us-east-1",
                "useCallerCredentials": false
            }
        },
        {
            "name": "AppSyncEventTable",
            "description": null,
            "type": "AMAZON_DYNAMODB",
            "serviceRoleArn": "{managed-by-awsmobile-cli}",
            "dynamodbConfig": {
                "tableName": "AppSyncEventTable-{suffix}",
                "awsRegion": "us-east-1",
                "useCallerCredentials": false
            }
        }
    ],
    "tables": [
        {
            ...,
            "Region": "us-east-1"
        },
        {
            "AttributeDefinitions": [
                {
                    "AttributeName": "id",
                    "AttributeType": "S"
                }
            ],
            "TableName": "AppSyncEventTable-{suffix}",
            "KeySchema": [
                {
                    "AttributeName": "id",
                    "KeyType": "HASH"
                }
            ],
            "ProvisionedThroughput": {
                "ReadCapacityUnits": 5,
                "WriteCapacityUnits": 5
            },
            "Region": "us-east-1"
        }
    ]
}
```

Any ideas why this is happening?

**Comment by flashfabrixx** [comment]
@nielsgl Happens to me as well. 

The workaround of overwriting the regions in the `dataSources.json` doesn't feel like a valid solution for the future.
