### ISSUE TITLE
OpenID - No current user session from `Auth.federatedSignIn`

### ISSUE THREAD

**Issue by iAmUndefined** [aws/aws-amplify#793]
This issue is related to #580 - but is for OpenID.

`Auth.currentCredentials()` (mentioned as a solution for #580) works well for Google. But it doesn't work for OpenID. Is this a bug? If not, can you please let me know what works for OpenID?

In my tests, `Auth.currentSession()` works for Cognito User Pool and `Auth.currentCredentials()` works for Google - but neither works for OpenID. 

BTW, `Auth.federatedSignIn` works well and logs in the user. Local storage gets `Identity ID` from AWS so that part works well for OpenID. But both `Auth.currentCredentials()` and `Auth.currentSession()` return null. Please advise, thanks!

**Comment by powerful23** [comment]
I think `Auth.currentCredentials()` should return you a credential but `Auth.currentSession()` won't return a session for you cause that method is just for Cognito. Basically the `Auth.federatedSignIn()` will just use the jwt token to fetch a valid credentials from federated identity pool so you need to manage the session by yourself. `Auth.federatedSignIn()` will also return the credentials for you.

**Comment by iAmUndefined** [comment]
Thanks for the reply!

> so you need to manage the session by yourself

Understood, didn't realize this.

**Comment by kanteankit** [comment]
@powerful23  
Could you describe how to use the credentials returned by `Auth.federatedSignIn` to manage a session myself?

**Comment by powerful23** [comment]
@kanteankit since Amplify will automatically refresh the jwt token from Facebook or Google, or you can also provide a refresh handler yourself, the user will always have a credentials to use your AWS resources. So if you don't want the user stayed logged in forever, you need to develop your own logic to sign the user out.

**Comment by simoazzo** [comment]
@kanteankit and others, have you managed how you can get the id token once you call `Auth.federatedSignIn` please? Thanks
