### ISSUE TITLE
Amazon-cognito-identity-js Security concern

### ISSUE THREAD

**Issue by Makulis** [aws/aws-amplify#794]
The  region, userPoolId and clientId are visible on the browser when using the Amazon Cognito Identity SDK for JavaScript (amazon-cognito-identity-js). 
With this information anyone can download the JSON Web Key (JWK) for your user pool from https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json.
This means that the person can then decode the ID token and the access token issued by the sdk.

My question is, would it be possible for an attacker to use the JSON Web Key (JWK) for your user pool to create a valid ID token and access token? 

I’m using the ID token and the access token for authenticated web API calls.

**Comment by MeixnerTobias** [comment]
Hi Makulis,

true, token can be decoded by anyone but an attacker won't be able to generate a token with the public keys.
Cognito is using RS256 with private keys to sign the token which are not publicly available in the jwks.json.
An attacker can still decode the token and guess the signing algorithm plus sending a token to your endpoint, so it is up to you to properly verify tokens in your backend/API.

Make sure you follow the recommendations here like verifying claims, kid, etc.:
https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-identity-user-pools-using-id-and-access-tokens-in-web-api

**Comment by Makulis** [comment]
Hi Tobias,

Thank you for the prompt response. I will follow the recommendations. I will mark the issue as closed. I just have one more question.

Wouldn't it increase security if Amazon made the JSON Web Key (JWK) for the user pool only accessible via the AWS console?

Regards
Lincoln
