### ISSUE TITLE
propTypes warnings on sign in and sign up pages

### ISSUE THREAD

**Issue by oluckyman** [aws/aws-amplify#8]
When wrapping `App` inside `Authenticator` component:
```
export default props => (
  <Authenticator
    amplifyConfig={amplifyConfig}
  >
    <App {...props} />
  </Authenticator>
);

```
I am getting that warning on sign in page:
![image](https://user-images.githubusercontent.com/642673/33035106-4e05e634-ce2a-11e7-852a-080d145c5501.png)

This on on sign up page:
![image](https://user-images.githubusercontent.com/642673/33035186-89cafbbe-ce2a-11e7-8575-274f3efec313.png)

**Comment by richardzcode** [comment]
Hey @oluckyman in our local env we don't see the warning. I'm guessing it is the way we remove prop behaves differently in different dev setup. I've made a patch to remove the props properly. Could you get the latest library to have a try?

Thanks,
Richard

**Comment by oluckyman** [comment]
Tried the latest version (aws-amplify-react@0.1.4) and it was not work at all:
![image](https://user-images.githubusercontent.com/642673/33072904-80ef8e64-cec1-11e7-9d1b-a0ad0d585d0c.png)

Then updated aws-amplify@0.1.3 as well. It works, but there is a warning again this time on `<a>` node:
![image](https://user-images.githubusercontent.com/642673/33073063-f121ff0a-cec1-11e7-8ada-b4beb01b8d62.png)

**Comment by richardzcode** [comment]
Yes it requires aws-amplify@0.1.3. The second one was missed. Now fixed.

Thanks,
Richard

**Comment by oluckyman** [comment]
Thanks 👍
