### ISSUE TITLE
Assignment to boolean attributes

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#80]
My React IDE is complaining about assignments to boolean attributes. It doesn't want this:

&lt;Authenticator hideDefault={true}&gt;

Instead it wants:

&lt;Authenticator hideDefault&gt;

Then if the attribute is missing it is considered to be false.
If my memory serves me, this is part of the base XML language spec.

**Comment by mlabieniec** [comment]
Hi @jonsmirl thanks again for the feedback. React uses [JSX](https://facebook.github.io/jsx/) definition not based on xml but an "xml-like" extension for EcmaScript. Details at the link above and at the [React Docs](https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored) in particular with booleans etc. The hideDefault={true} is standard for jsx but we can look into supporting without as well.
