### ISSUE TITLE
Enabling TOTP using Amplify FAILS when the user does not have a cellphone number in the profile

### ISSUE THREAD

**Issue by Makulis** [aws/aws-amplify#806]
When using Amplify to enable TOTP for a user, the operation will fail if the user does not have a cellphone number set. The issue is in Line 444 in packages/aws-amplify/lib/Auth/Auth.js.

user.setUserMfaPreference(smsMfaSettings, totpMfaSettings, function (err, result) Should pass "null" for the smsMfaSettings i.e. it should be  user.setUserMfaPreference(null, totpMfaSettings, function (err, result) if mfaMethod == 'TOTP'.

Passing  var smsMfaSettings = {
            PreferredMfa: false,
            Enabled: false
        } seems to cause the library to check for a valid cellphone number first. This then causes the function to fail since there is no cellphone number in the user's profile. TOTP ends up not being activated at all.

There are cases where you want to enable TOTP for a user even if they don’t have a registered cellphone number.

A workaround for this issue is to use the amazon-cognito-identity-js directly and pass "null" for smsMfaSettings. However, it would be great if you can use Amplify without having to sometimes call functions from the amazon-cognito-identity-js directly.

**Comment by guanzo** [comment]
Same issue here #618
