### ISSUE TITLE
Documentation amplify angular: wrong const name imported

### ISSUE THREAD

**Issue by 39ro** [aws/aws-amplify#807]
Amplify Angular documentation: https://aws.github.io/aws-amplify/media/angular_guide

- Import the configuration file and load it in your main.ts, which is the entry point of your Angular application.

```
import Amplify from 'aws-amplify';
import awsmobile from './aws-exports';
Amplify.configure(aws_exports);
```

shall be

```
import Amplify from 'aws-amplify';
import awsmobile from './aws-exports';
Amplify.configure(awsmobile);
```

**Comment by mbahar** [comment]
Thanks @39ro!  I've submitted the PR for the update.
