### ISSUE TITLE
Cognito Sync's data within Amplify?

### ISSUE THREAD

**Issue by jeremyputeaux** [aws/aws-amplify#808]
I have not seen anything about this, so I think this is a feature request.

**Is this possible tu access Cognito Sync's data with Amplify?**

**Comment by yuntuowang** [comment]
Hi @jeremyputeaux, I will mark this as a feature request on your behalf. Thanks.

**Comment by mlabieniec** [comment]
@jeremyputeaux it is generally recommended to utilize AWS AppSync in place of Amazon Cognito Sync. Currently AWS Amplify supports AWS AppSync. We don't directly support Cognito Sync, however you could drill down to the JS SDK / Cognito SDK and use it (see readme here): https://github.com/aws/aws-amplify/tree/master/packages/amazon-cognito-identity-js

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoSync.html

You can access the SDK directly with your Auth session via Amplify, see example here:
https://aws.github.io/aws-amplify/media/quick_start#working-with-aws-service-interface-objects
