### ISSUE TITLE
Persisting Auth

### ISSUE THREAD

**Issue by ckorhonen** [aws/aws-amplify#812]
I'm exploring Amplify for a React Native project and wondering how I would go about persisting a user session if I'm not using the HOC's?

My code is more or less identical to the documentation:

```
import { Auth } from 'aws-amplify';

Auth.signUp({
        username,
        password,
        attributes: {
            email,          // optional
            phone_number,   // optional - E.164 number convention
            // other custom attributes
        },
        validationData: []  //optional
    })
    .then(data => console.log(data))
    .catch(err => console.log(err));
```

Upon submission, I see the user is created, but nothing is being persisted anywhere. Is there something I'm missing?

![screenshot 2018-05-09 16 11 46_preview](https://user-images.githubusercontent.com/39121/39837240-e297bd3c-53a3-11e8-9f37-30f5421625f0.png)

When I use `withAuthenticator` everything works as I would expect, I see entries added to my AsyncStorage and when I reload the app the session persists, however, I have some requirements for additional customization to the screen flow and behaviors which don't quite fit when I go this route.

**Comment by powerful23** [comment]
@ckorhonen you can use `Auth.currentAuthenticatedUser()` to check whether the user is logged in or not and then determine switch the app state to signed in. The library will store user info into AsyncStorage and keep it until `Auth.signOut()` called.

**Comment by powerful23** [comment]
@ckorhonen There is no authenticated user with just signing up. You need to go back to sign in after a user signed up.

**Comment by Larsrdev** [comment]
@powerful23 I also have problems with persisting auth. After I call 'signIn' on my following code, i get the folowing error back 'not authenticated' - but the User is logged in and able to make requests and gets correct responses from aws. After reload the page (without cookie delete), the user is logged out (my 'isLoggedIn' calls Auth.currentAuthenticatedUser() - and rejects too - not authenticated).

In amplify@2.0.9 it works (with Auth.currentSession() ) flawlessly.

```
constructor() {
        Amplify.configure({
            Auth: {
                identityPoolId: process.env.REACT_APP_AWS_IDENTITY_POOL_ID,
                region: process.env.REACT_APP_AWS_REGION,
                userPoolId: process.env.REACT_APP_AWS_USER_POOL_ID,
                userPoolWebClientId: process.env.REACT_APP_AWS_APP_CLIENT_ID,
                mandatorySignIn: true,
                cookieStorage: {
                    domain: process.env.REACT_APP_AWS_DOMAIN,
                    path: '/',
                    expires: 365,
                    secure: true
                }
            }
        });
    }

    signIn(email: string, password: string): Promise<AuthEntity> {
            Auth.signIn(email, password)
                .then(user => {
                    Auth.currentAuthenticatedUser().then((session) => {
                        console.log(session);
                    }).catch((error) => {
                        console.log(error);
                    });
                    console.log(user);
                }).catch(error => {
                console.log(error);
        });
    }
```

**Comment by powerful23** [comment]
@Larsrdev can you try `Auth.currentUserPoolUser()` to check if the current user is stored in your cookie?

**Comment by AlexGoranov** [comment]
I am running into this issue without having Cookie Storage in my config file.

The config looks like this:
`
const awsmobile = {
  aws_project_region: ****,
  aws_cognito_region: ****,
  aws_user_pools_id: ****,
  aws_user_pools_web_client_id: ****
};

export default config;
`
My code looks like this:

`
const signedInUser = await Auth
      .signIn(username, password);

const authUser = await Auth.currentAuthenticatedUser(); // throws error not authenticated
`

**Comment by Guttz** [comment]
I had this error simply because I had some additional logic inside onAuthUIStateChange( ... ) before setting the user state.
