### ISSUE TITLE
Authenticator and withAuthenticator behave inconsistently

### ISSUE THREAD

**Issue by slawek-mazur** [aws/aws-amplify#819]
Bug

Wrapped component is visible when wrapped with `<Authenticator/>`  and it's hidden when wrapped with `withAuthenticator()`

**secret** is visible
```
class Secret extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <Authenticator>
        <span>secret</span>
      </Authenticator>
    )
  }
}
export default Secret;
```
**secret** is not visible
```
class Secret extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <span>secret</span>
    )
  }
}
export default withAuthenticator(Secret);
```

```
"dependencies": {
    "aws-amplify": "^0.3.3",
    "aws-amplify-react": "^0.1.43",
    "lodash": "^4.17.10",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-scripts": "1.1.4"
  }
```
`Firefox Quantum 59.0.2`

**Comment by powerful23** [comment]
@slawek-mazur yes it's designed to act like that. If you are using `Authenticator`, you need to develop your own logic to determine which components are hidden if not logged in.

**Comment by slawek-mazur** [comment]
true. i just took a closer look at docs and it's there [Example: Show your App Only After User Sign-in](https://aws.github.io/aws-amplify/media/authentication_guide.html#example-show-your-app-only-after-user-sign-in)
@powerful23 thanks.
