### ISSUE TITLE
Can we get a better React demo?

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-amplify#83]
Preferably one with:

1) Start from create-react-app, user react-router to create the pages. Check this base code in so that the later code can be diffed against it.
2) Unprotected home page
3) Login button that displays page with login dialog
4) After successful login a protected page becomes accessible. Login button turns into Logout.
5) On logout the protected UI disappears.
6) Persistent logins for User Pool, Google, FB. ie if I start the app with a persistent login I go directly into the protected UI with Logout button enabled.
7) Show proper technique for exposing unprotected and protected pages via Cloudfront under single domain using Cognito based authorization.
8) Show how to add a protected API into the same, single domain.
9) Show how to create an admin (or privileged user)
10) Show how to do proper security logging.

Using AWS is like walking into Home Depot and saying "I want to build a house". It can be done, but a huge amount of knowledge is required to finish the job.  Example frameworks make this task much easier.

**Comment by mlabieniec** [comment]
@jonsmirl have you checked out the [react-sample](https://github.com/awslabs/aws-mobile-react-sample) app? This has mostly been migrated to use Amplify at this point. Let me know if this has the features you are looking for, either way we should probably move this over to there.

**Comment by jatazoulja** [comment]
specially for react and please add social integration for federated authentication?

**Comment by mlabieniec** [comment]
@jatazoulja I've added this to our backlog

**Comment by richardzcode** [comment]
Federated auth is already part of our implementation. Please have a look at: [Authentication Guide](https://aws.github.io/aws-amplify/media/authentication_guide), section "Federated Identities (Social Sign-in)"

Also, maybe this [step by step sample](https://github.com/richardzcode/Journal-AWS-Amplify-Tutorial) can help in some way for other requests.

**Comment by haverchuck** [comment]
@jonsmirl  @jatazoulja   - We have updated our react-sample with an authentication component.  Hope that helps!   
[](https://github.com/aws-samples/aws-mobile-react-sample)

**Comment by johncade** [comment]
👍
