### ISSUE TITLE
Cache documentation should encourage maintaining own instance

### ISSUE THREAD

**Issue by jfo8000** [aws/aws-amplify#830]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
Documentation says to use the Cache.setItem and Cache.getItem, which I gleefully did but my stuff got all cleared out because I didn't have my own keyPrefix.  So in the end I had to create my own Cache instance and configure it. 

https://aws.github.io/aws-amplify/media/cache_guide#configuration

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
@jfo8000 the items will be cleaned if the Amplify cache hits the upper limit which is configurable. Also you can set higher priority for critical items.

**Comment by powerful23** [comment]
Closing the issue.
