### ISSUE TITLE
New version breaks with timezone error

### ISSUE THREAD

**Issue by Funkmyster** [aws/aws-amplify#84]
```
TypeError: Cannot read property '1' of null

C:/myapp/node_modules/aws-amplify/lib/Common/ClientDevice/browser.js:62
  59 | exports.dimension = dimension;
  60 | function browserTimezone() {
  61 |     var tzMatch = /.+\(([A-Z]+)\)/.exec(new Date().toString());
> 62 |     return tzMatch[1] || "";
  63 | }
  64 | function browserType(userAgent) {
  65 |     var operaMatch = /.+(Opera[\s[A-Z]*|OPR[\sA-Z]*)\/([0-9\.]+).*/i.exec(userAgent);
```

I'm using Chrome on Windows 10

**Comment by mlabieniec** [comment]
@Funkmyster when/where in your app are you seeing this exception occur? Also, just fyi we don't edit the .js files directly since these are generated by typescript (and overwritten on publish/build). Are you using the master branch or the npm version?

**Comment by Funkmyster** [comment]
I'm using the npm version.
```
>npm list aws-amplify
`-- aws-amplify@0.1.22
```

And it breaks as soon as I import Amplify with:
```
import Amplify from 'aws-amplify';
```

**Comment by Funkmyster** [comment]
I'm also getting that errors on my Firefox and Edge Browser.

I get this in my Firefox, Chrome, Edge, and node cli consoles:
```
new Date().toString()
"Tue Dec 19 2017 12:39:14 GMT-0600 (Central Standard Time)"
```

Which is different than the format on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString#Examples

**Comment by jsancho** [comment]
I have the same exact error.
This takes place during application initialisation on Chrome/Firefox/Edge on Windows.
It works fine with Chrome on Mac OS. I'll try to investigate with a few more browser/OS combinations.

![amplify](https://user-images.githubusercontent.com/1547884/34260593-684e8964-e65e-11e7-90be-89967f081f57.png)

**Comment by jsancho** [comment]
@mlabieniec I think I have found the problem

I've commented the line that breaks execution on Windows 10
https://github.com/aws/aws-amplify/commit/29f91c97a791e156b79048f7bdf8822445270081#diff-29ba1411b375128c1ee9349ffdf97d1d

**Comment by d0ruk** [comment]
Same here. aws-sdk: v2.173.0 | aws-amplify: v0.1.22

```
 var tzMatch = /.+\(([A-Z]+)\)/.exec(new Date().toString()); // undefined
...
 return tzMatch[1] || ""; // TypeError
```

Maybe (new Date()).[getTimezoneOffset()](https://devdocs.io/javascript/global_objects/date/gettimezoneoffset) might be future-proof ?

What's the proposed work around?

**Comment by EthanRBrown** [comment]
This issue is also present in v0.1.21.  I had to revert to v0.1.20 to avoid it.
