### ISSUE TITLE
No current user after login via Hosted UI

### ISSUE THREAD

**Issue by MiroslavPetrik** [aws/aws-amplify#841]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
After successful request to /oauth2/token with grant_type authorization code, the amplify fails with error No current user.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
Steps:
1. configure oauth in Amplify.configure
2. click link or navigate to "https://DOMAIN.auth.us-west-2.amazoncognito.com/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2response&response_type=code&client_id=CLIENT_ID&scope=openid+profile+email+phone&identity_provider=Google"
2.1. log in with google account
3. you are redirected to the specified redirect uri
4. Amplify parses the url to get the code which in turn is used in request to /oauth2/token
5. success on the request, but error in the login flow with message "No current user"

What is the expected behavior?
I should be logged in. There should be no error. currentSession should return info about logged in user...

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
amplify: 0.3.3
browser: chromium 66.0.3359.139

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.
https://pastebin.com/bcUvfvcS

**Comment by erothmayer** [comment]
I'm working with Miroslav, and think I found the source of the issue.

The auto-magic parsing occurs in the amazon-cognito-auth-js library, which requires using localStorage for the authenticated user info (https://github.com/aws/amazon-cognito-auth-js/blob/master/src/StorageHelper.js#L83)

Amplify adds an option to use cookies for storage, and even tacitly encourages it in the documentation (https://aws.github.io/aws-amplify/media/authentication_guide) however if you enable this option Amplify is not able to find the user credentials parsed out by the library above in cases where it handles an authorization_code callback.

Given the pervasiveness of localStorage it seems like Amplify could potentially just ditch the cookie storage option entirely. If that's not possible, it would be good to at least note in the documentation that using the option will disable some functionality like automatic handling of oauth flows.

**Comment by powerful23** [comment]
#812

**Comment by markw351** [comment]
The problem with 'ditching the cookie storage option' is that the local storage approach does not handle Auth across a single domain, eg, *.example.com, which cookie storage did support. Now that cookie storage is broken, my app is not working with either option.

**Comment by buggy** [comment]
Local storage also doesn't work with Safari if you're transitioning from outside an iframe to inside an iframe which Shopify embedded apps need to do. I managed to get around that one by using cookie storage.

**Comment by buggy** [comment]
@MarkAtwood I'm not sure why cookie storage is broken for you. I'm currently running a fork of 0.4.2-unstable with my passwordless authentication PR and it's fine. It has been fine all week when I was using 0.4.1 with the same PR.

**Comment by Hugodby** [comment]
I have the same issue. Setting 'cookieStorage' in the config break the authentication methods. No cookies are saved but the tokens are still written in the localstorage. If I remove the cookieStorage option, authentication methods work again. I would like to use the cookie storage. Below my configuration : 
```
Auth: {
    region: '*******',
    identityPoolId: '************************',
    userPoolId: ''************************',
    userPoolWebClientId: ''************************',
    mandatorySignIn: false,
    cookieStorage: {
      domain: '.cloud9.*****.amazonaws.com',
    },
    oauth: {
      domain: '************************.auth.******.amazoncognito.com',
      scope : ['phone', 'email', 'profile', 'openid','aws.cognito.signin.user.admin'], 
      redirectSignIn : window.location.protocol + '//' + window.location.host + '/auth', 
      redirectSignOut : window.location.protocol + '//' + window.location.host  + '/auth',
      responseType: 'code'
    }
  },
```

**Comment by erothmayer** [comment]
Note that this is currently still broken for some users as the amazon-cognito-auth-js library is vending an old version of the code to some dependency systems.

This PR would fix it: https://github.com/aws/amazon-cognito-auth-js/pull/141
And I've opened these issues to try to get attention on getting it merged:
https://github.com/aws/amazon-cognito-auth-js/issues/144
https://github.com/aws/aws-amplify/issues/1187

**Comment by erothmayer** [comment]
This issue is further extended by a typo in the original fix. Once both the issue above and this PR are merged, this issue should be resolved: https://github.com/aws/aws-amplify/pull/1194
