### ISSUE TITLE
term and condition

### ISSUE THREAD

**Issue by supun19** [aws/aws-amplify#844]
I am going to integrate term and condition for signup page.  can you guide me. is there any component inside that i can use

**Comment by mlabieniec** [comment]
@supun19 it really depends on the framework you are using. Amplify supports react, react native, angular and vanilla js. If you are vanilla js you would simply just enable / disable a button by id/class, if using built in components you could do similar, here's a fiddle for example: http://jsfiddle.net/T6hvz/

**Comment by supun19** [comment]
thank you
