### ISSUE TITLE
amazon-cognito-identity-js dependency browserify-crypto is still at 3.0.0

### ISSUE THREAD

**Issue by poidl** [aws/aws-amplify#848]
Do you want to request a feature or report a bug?

Bug

What is the current behavior?

UnhandledPromiseRejectionWarning: ReferenceError: crypto is not defined

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

I'm using  amazon-cognito-identity-js 2.0.5. Recently there was a commit that upgraded browserify-crypto to 3.12.0, but that didn't seem to end up in the 2.0.5 release of amazon-cognito-identity-js.

**Comment by abador** [comment]
It seems I have the same issue. Dod you manage to fix it?

**Comment by poidl** [comment]
Reverting to 2.0.2 worked for me. Not sure though if this is save. I just
use it to lock down my homepage Dev environment, so I don't care.

**Comment by mlabieniec** [comment]
we have rolled back the use of crypto 3 due to issues with other modules (stream). We are looking into replacing this module with another crypto library or investigating the next upgrade.
