### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by joebernard** [aws/aws-amplify#856]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

Error after adding `aws-amplify` to a new project and running `react-native run-ios`:
```
error: bundling failed: Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:693:18)
    at Object.readSync (/opt/projects/awsAmplifyTest/node_modules/graceful-fs/polyfills.js:138:28)
    at tryReadSync (fs.js:557:20)
    at Object.fs.readFileSync (fs.js:600:19)
    at Module._readSourceCode (/opt/projects/awsAmplifyTest/node_modules/metro/src/node-haste/Module.js:194:29)
    at Module._getCacheProps (/opt/projects/awsAmplifyTest/node_modules/metro/src/node-haste/Module.js:386:29)
    at Module._readFromTransformCache (/opt/projects/awsAmplifyTest/node_modules/metro/src/node-haste/Module.js:347:29)
    at Module.readCached (/opt/projects/awsAmplifyTest/node_modules/metro/src/node-haste/Module.js:334:19)
    at /opt/projects/awsAmplifyTest/node_modules/metro/src/node-haste/Module.js:315:29
    at Generator.next (<anonymous>)
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**

```
react-native init awsAmplifyTest
cd awsAmplifyTest
npm install --save aws-amplify
npm install --save aws-amplify-react-native
react-native link amazon-cognito-identity-js
awsmobile init
```
add `import Amplify from "aws-amplify";` to `index.js`.

`react-native run-ios`

**What is the expected behavior?**

The project runs without error.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

"aws-amplify": "^0.4.0",
"aws-amplify-react-native": "^0.2.11",
"react": "16.3.1",
"react-native": "0.55.4"

node 8.11.2

*edited to add `link` and `awsmobile init` steps

**Comment by joebernard** [comment]
I will add that the newly created project runs without error. It is only once I add `aws-amplify` that this issue surfaces.

**Comment by joebernard** [comment]
![screenshot 2018-05-17 19 40 27](https://user-images.githubusercontent.com/1540653/40208903-371c5f5e-5a0a-11e8-9f9f-354449b849ec.png)

**Comment by joebernard** [comment]
If I delete the `import` in index.js the app will build and run successfully. 

Also tried:
```
watchman watch-del-all
rm -rf node_modules && npm install
rm -rf /tmp/metro-bundler-cache-*
rm -rf /tmp/haste-map-react-native-packager-*
```

and restarted the machine. Reproducible repo [here](https://github.com/joebernard/awsAmplify856).

**Comment by mlabieniec** [comment]
@joebernard when using react-native and NOT Expo, you need to link the `amazon-cognito-identity-js` native module, see [here](react-native link amazon-cognito-identity-js) for details.

```js
$ react-native init myReactNativeApp
$ cd myReactNativeApp
$ npm install --save aws-amplify
$ npm install --save aws-amplify-react-native
$ react-native link amazon-cognito-identity-js
```

**Comment by joebernard** [comment]
Hi @mlabieniec . I forgot to add this step to my bug report. I did complete the `link` and still have the same issue.

```
react-native link amazon-cognito-identity-js
Scanning folders for symlinks in /opt/projects/awsAmplifyTest/node_modules (63ms)
rnpm-install info Platform 'ios' module amazon-cognito-identity-js is already linked 
rnpm-install info Platform 'android' module amazon-cognito-identity-js is already linked
```

**Comment by joebernard** [comment]
I attempted a brand new installation under my `~/` home directory using the same steps. Same issue.

Then I tried a `create-react-native-app` installation and installed the aws packages. This seems to get around the problem and it compiles correctly. The issue is within `react-native init` or I am calling it incorrectly somehow.

**Comment by joebernard** [comment]
I'm not able to solve this. I created a new project and migrated my code to move on.
