### ISSUE TITLE
Facebook federated login not working

### ISSUE THREAD

**Issue by rohitspujari** [aws/aws-amplify#86]
When I login via facebook, the cognito identity pool doesn't recognize this login as a facebook login. It may be due to the fact that graph.facebook.com field in the login section is undefined. 
![image](https://user-images.githubusercontent.com/6819305/34161277-ce46a9ec-e495-11e7-9a61-cd01a6115a3b.png)

Any idea on how to fix this?

**Comment by mlabieniec** [comment]
This should be fixed in the latest published release 0.1.30 let us know if you are still running into issues there.
