### ISSUE TITLE
How to use Amplify in Symfony4

### ISSUE THREAD

**Issue by engharb** [aws/aws-amplify#860]
Hello,

I'm using Symfony4 as framework and I have installed aws-amplify. How can I use 'aws-amplify' in JS file within Symfony4?

regards,

**Comment by mlabieniec** [comment]
@engharb amplify is a client-side javascript library. You would need to either use a framework (angular,react etc). Or include the amplify.min.js file in your html file. You can then reference the library via window['aws-amplify'], you can see a fiddle here: https://jsfiddle.net/0gmqtq7g/226/ for example.
