### ISSUE TITLE
Regression with latest Amplify version for Auth and API

### ISSUE THREAD

**Issue by OlivierPT** [aws/aws-amplify#868]
Do you want to request a feature or report a bug?

Bug

What is the current behavior?

I use OAuth authentication and HostedUI on my application.
With the "aws-amplify" and "aws-amplify-react" latest versions, a "signIn" event sent to the Hub component and the rest of the application after OAuth authentication is not sent anymore,  as it was with the following versions:
- "aws-amplify": "^0.3.3",
- "aws-amplify-react": "^0.1.43",

Latest versions that not work for me:
- "aws-amplify": "^0.3.4",
- "aws-amplify-react": "^0.1.47",

In addition, when simulating the event by testing the userSession, it happens that the API component is not anymore able to connect to AppSync with the Connect component. I guess it a consequence of the first issue but I have no clue.

When I downgrade to  "aws-amplify": "^0.3.3" and aws-amplify-react": "^0.1.43", everything is working well.

I didn't have the time analyse deeper the issue and I prefer to referenced quick because it seems to be a blocking one for those who use HostedUI.

What is the expected behavior?

After signin, token parsing and session loading, AuthClass should fire a SignIn event as it was before and Auth and API configuration should be loaded properly to enable AppSync API call.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Latest versions that not work for me:
- "aws-amplify": "^0.3.4",
- "aws-amplify-react": "^0.1.47",

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
@OlivierPT could you try amplify@^0.4.1 as the latest version has some fix around Auth.

**Comment by OlivierPT** [comment]
Hi,

Unfortunately, there is no change with amplify@^0.4.1 :(

I use the Hub component to listen to "auth" events as mentionned in the documentation: 
`Hub.listen('auth', this, `'SignInAWS');`

and then:

`onHubCapsule(capsule) {
    logger.debug('capsule:', capsule);
    const { channel, payload } = capsule;
    if (channel === 'auth') { this.onAuthEvent(payload); }
  }

  onAuthEvent(payload) {
    const { event, data } = payload;
    logger.debug('data:',data);
    switch (event) {
      case 'signIn':
        logger.debug('user signed in');
        this.props.onStateChange('signedIn');
        break;
      case 'signUp':
        logger.debug('user signed up');
        break;
      case 'signOut':
        logger.debug('user signed out');
        this.redirectToHostedUI();
        break;
      case 'signIn_failure':
        logger.debug('user sign in failed');
        this.redirectToHostedUI();
        break;
      default: 
        logger.debug('default');
        logger.debug('event:',event);
    }
  }
`

But I never receive any event despite the use is signed (I can get UserInfo in parallele).

Do I need to change something after the update?

**Comment by powerful23** [comment]
@OlivierPT are you using `withAuthenticator`? I noticed if you are using that hoc to wrap your `app` component, then this `app` class won't be registered into `Hub` before you sign in so you will miss the `signIn` event. Also please make sure you have bind `this` with `onHubCapsule` like `this.onHubCapsule = this.onHubCapsule.bind(this);`

**Comment by OlivierPT** [comment]
Hi @powerful23 ,

I don't use `withAuthenticator` but `<Authenticator>` so I guess it is the same : 
Currently, my code is like that:

`
<Authenticator hideDefault="true">
          <SignInAWS {...this.props} checkTimeout={3}/>
          <AppAuthPiece />
</Authenticator>
`

So, I tried to put my <SignInAWS> component (that listen to the auth events outside the <Authenticator> component and I also added the bind line in the constructor of my component
`
<div>
<SignInAWS {...this.props} checkTimeout={3}/>
    <Authenticator hideDefault="true">
    <AppAuthPiece />
</Authenticator>
</div>
`

=> But no change, no event...

Moreover, I think it is an issue to not receive events inside the <Authenticator> before being signedIn since some (most) of the event are before being signed. Isn't it?

Also, I add a workaround to send myself the signIn event if I find a valid user session, then, my App is showing up but I get an error when trying to use an AppSync API.

Again, this is fully working with aws-amplify@0.3.3... I would love to understand what change!

**Comment by OlivierPT** [comment]
I just did few other tests... And the issue seems to come from `aws-amplify-react` and not from `aws-amplify` since my code is working well with

    "aws-amplify": "^0.4.1",
    "aws-amplify-react": "^0.1.43"

I hope it can help...

**Comment by powerful23** [comment]
@OlivierPT Thanks for your feedback! So which version of `aws-amplify-react` is working for you? 0.1.43?

**Comment by OlivierPT** [comment]
Yes, it is 0.1.43. This configuration

`"aws-amplify": "^0.4.1",
"aws-amplify-react": "^0.1.43"`

With this configuration, I have also a "new" and annoying behavior: when switching between screen (using react-router, client-side rendering), the component associated to authState = "signIn", "signedOut"... is showing up quickly and then my app is back... 

So... I guess something change in the way to manage authState and the associated events...

**Comment by OlivierPT** [comment]
Hi,

I re-tried to update my project to "aws-amplify": "^0.4.1" and "aws-amplify-react": "^0.1.47" today and I don't get the error as mentioned in this issue! I didn't had to update/change any part of my code so... maybe the issue was coming from a dependencie!?

Anyway, I close the issue.

Thank you
