### ISSUE TITLE
Is IdentityPoolId available in aws-cognito user-pool?

### ISSUE THREAD

**Issue by rathanDev** [aws/aws-amplify#870]
Documentation mention this below
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                IdentityPoolId : '...', // your identity pool id here
                Logins : {
                    // Change the key below according to the specific region your user pool is in.
                    'cognito-idp.<region>.amazonaws.com/<YOUR_USER_POOL_ID>' : 
                     result.getIdToken().getJwtToken()
                }
 });

Aws-cognito has user-pool(identifiled by userPoolId) and identity-pool(identified by identityPoolId). So user pool has no IdentityPoolId.

**Comment by mlabieniec** [comment]
@rathanDev the identityPoolId isn't related to the cognito user pool. These are essentially two different services User Pools / Federated Identities. Federated Identities uses a identityPoolId. The above code is describing retrieving credentials from an Amazon Cognito Federated Identities pool (which can contain multiple identity providers). User Pools can be an identity provider of a Federated Identities pool, which in turn would provide an identityPoolId which is associated with a pool that could contain many identities, one of which could be a user pool (social providers..etc.).

**Comment by jordanranz** [comment]
Closing this issue. Please reopen if you have any further questions.
