### ISSUE TITLE
ReferenceError: window is not defined using aws-amplify 0.4.1 (latest)

### ISSUE THREAD

**Issue by araleius** [aws/aws-amplify#882]
> Do you want to request a feature or report a bug?

A bug.

> What is the current behavior?

I have an API gateway service I run locally with sam local and I use ```aws-amplify``` for my CD/CI tests. I use [jest](https://facebook.github.io/jest/) as a test runner and node as the [testEnvironment](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string).

Today I upgraded my ```aws-amplify``` version from: ```0.2.7``` to ```0.4.1```. When I try to run my tests the suite fails to run. This is the bit of the error stack that points to a problem when ```aws-amplify``` is initialized:

```
ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/aws-amplify/lib/Common/RNComponents/index.js:24:20)
      at Object.<anonymous> (node_modules/aws-amplify/lib/Common/index.js:40:10)
      at Object.<anonymous> (node_modules/aws-amplify/lib/Analytics/Analytics.js:50:16)
```

And here's a bit of the file referenced at the top of the stack:

```
...
exports.AppState = AppState;
// if not in react native, just use local storage
var AsyncStorage = window.localStorage;
exports.AsyncStorage = AsyncStorage;
```

It seems there's an assumption that the context is a browser if "not in react native". 

> What is the expected behavior?

The expected behavior is ```aws-amplify``` can be used, or configured to use, server-side and does not assume it is running in a browser. For my use case (just issuing authenticated requests against API gateway) this used to be the case. 

Trivia: I actually started the Amplify upgrade because I thought the new version had addressed other issues related to running server-side: #493 

> Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

* Amplify: ```0.4.1```
* Jest: ```22.4.4```
* Node: ```v8.7.0```

> You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

the return of the window!

My current workaround is keep using the old version of Amplify. I'd rather not do this much longer since I like to keep my tests using the same version as used by my javascript frontend application (which does use Amplify in the browser) and in general I don't want my actual application to run behind the latest version.

**Comment by araleius** [comment]
The usage of ```window``` seems to have been introduced with the ["minor change"](https://github.com/aws/aws-amplify/commit/3a33a68b83353c54d031e04bca76a2addc02f28d#diff-da1380b7d2d46b59c3aa1c0c6c6a323f).

**Comment by michaelmerrill** [comment]
I'm also running into this issue. Specifically in [GoogleOAuth.ts](https://github.com/aws/aws-amplify/blob/27bd3d9eff99ed2dd07b70e57bb0731ff2849b63/packages/aws-amplify/src/Common/OAuthHelper/GoogleOAuth.ts#L20)

**Comment by shaila-rahman** [comment]
I'm also facing similar issue in mocha environment with typescript. 

Issue:
ReferenceError: window is not defined
    at Object.<anonymous> --\node_modules\@aws-amplify\core\src\RNComponents\index.ts:22:22

Versions I'm using:
@aws-amplify: 6.4.1
node: 8.9.4
npm: 6.4.1

Any has any solution?

**Comment by powerful23** [comment]
@shaila-rahman thanks for reporting. will merge a fix later on

**Comment by natebushman** [comment]
@powerful23  Hey, thanks for addressing this.  Do you have any idea when a solution will appear in the latest stable aws-amplify NPM module?  And will it also fix issue [876](https://github.com/aws-amplify/amplify-js/issues/876)?


Like many others, we'd love to be able to use aws-amplify with Node.js in order to run test scripts and utility scripts.  However even with the most recent version of aws-amplify (1.1.4) we get the following error when our Node.js scripts try to pull in aws-amplify:

/Users/nate/dev/tests/node_modules/@aws-amplify/core/lib/RNComponents/index.js:24
**var AsyncStorage = window.localStorage;
                   ^

ReferenceError: window is not defined**
    at Object.<anonymous> (/Users/nate/dev/tests/node_modules/@aws-amplify/core/lib/RNComponents/index.js:24:20)

We were able to get an older verison of amplify (0.4.8) working with Node.js by modifying the module's source (definitely not an ideal solution) but we haven't yet figured out a hack to get aws-amplify 1.1.4 working with Node.js.

**Comment by jakebenn** [comment]
Since the older, Node-compatible JavaScript SDK (https://github.com/amazon-archives/amazon-cognito-identity-js) is no longer supported, and the new JavaScript SDK, Amplify, doesn't support Node, does that mean that Amazon officially no longer supports server-side JavaScript for Cognito?

**Comment by anklos** [comment]
@powerful23 @jakebenn I am still facing the same issue with latest amplify, any advice? Many thanks!
