### ISSUE TITLE
NEW_PASSWORD_REQUIRED not handled when using USER_PASSWORD_AUTH

### ISSUE THREAD

**Issue by zoul0813** [aws/aws-amplify#883]
Do you want to request a feature or report a bug?  Reporting a bug

What is the current behavior?

When using USER_PASSWORD_AUTH within amazon-cognito-identity-js, the `authenticateUserInternal` function does not handle the **NEW_PASSWORD_REQUIRED** challenge and returns an "UnknownError".

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

```
let cognitoUser = Auth.createCognitoUser(username);
cognitoUser.setAuthenticationFlowType('USER_PASSWORD_AUTH');
let authDetails = new AuthenticationDetails({
    Username: username,
    Password: password
});
cognitoUser.authenticateUser(authDetails, {
    onSuccess: (user) => {
        // success
    },
    onFailure: (err) => {
        // failure
    },
    newPasswordRequired: (userAttrs, reqAttrs) => {
        // handle NEW_PASSWORD_REQUIRED challenge
    }
});
```

What is the expected behavior?

The `newPasswordRequired` callback should be called 

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

aws-amplify 0.4.1
amazon-cognito-identity-js 2.0.6

I'm unsure if this worked in previous versions as I was using USER_SRP_AUTH before but am now working on setting up user migration from a legacy system which requires me to use USER_PASSWORD_AUTH to trigger the migration lambda.

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

There is no relevant/useful debug output, but `src/CognitoUser.js` clearly does not handle the `if (challengeName === 'NEW_PASSWORD_REQUIRED') { ... }` case.

**Comment by CoreyMartin** [comment]
@zoul0813 Were you able to work around this at all? Facing the same problem and use case - we're currently migrating users and need to use USER_PASSWORD_AUTH.

**Comment by zoul0813** [comment]
No, I wound up using a hack that is likely only useful in my particular use case.
