### ISSUE TITLE
Using storage for unconfirmed user

### ISSUE THREAD

**Issue by Rtg147** [aws/aws-amplify#890]
Hi,
I am trying to upload an user profile picture to s3 using storage and its  level:'protected' feature. For that the solution that i've imagined was to use the promise of the Auth.signup to login and get the user tokens bi login in the user. The problem is as the user just came to signup he is unconfirmed and it does not login. So how might we handle that type of case ? Can we use some credentials to tell storage class wich user to put ? @

**Comment by powerful23** [comment]
@Rtg147 Can you provide more infomation like what's the packages you are using? Also currently there is a issue with user sign up in `aws-amplify-react-native`.  #886

**Comment by Rtg147** [comment]
I mean is there a way to allow users to get a special credential for uncorfirmed with a role unconfirmed ?

**Comment by powerful23** [comment]
@Rtg147 I am afraid you can't since Cognito federated identity pool only suppors unauthenticated identities or authenticated ones.

**Comment by Rtg147** [comment]
@powerful23 
Yes I've seen. So i changed my flow in my UI after signup the user has to paste his confirmation code and then he can upload his pp and add others info details. I've seen that in fb they kinda do the same thing now instead of a link. So i imagine it's not a so bad idea ^^
