### ISSUE TITLE
Warning when installing aws-amplify-react-native

### ISSUE THREAD

**Issue by adrianhall** [aws/aws-amplify#9]
When you install aws-amplify-react-native, you get a warning:

```
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
warning aws-amplify-react-native > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
[2/4] 🚚  Fetching packages...
```

**Comment by richardzcode** [comment]
Unfortunately babel-preset-es2015 is a dependency of `amazon-cognito-identity-js`.

`aws-amplify-react-native` actually does not need babel-preset-es2015. We include this dependency just to prevent error from amazon-cognito-identity-js. Until that library fixed we have to include babel-preset-es2015.

Thanks,
Richard

**Comment by jamesjara** [comment]
Any update or pretending to update this?
