### ISSUE TITLE
Seeding anonymous identity when migrating to Amplify

### ISSUE THREAD

**Issue by brianfoody** [aws/aws-amplify#906]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
No way to switch anonymous users to from existing AWS auth to Amplify as they will be issued a new identity.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**
Install app with cognito js and sign in as anonymous user. Install update which switches to amplify. You will be issued a new identity

**What is the expected behavior?**
There needs to at least be a mechanism to advise amplify of the current users identity.

From looking at the code on Github I can tell that it's storing the value in AsyncStorage and retrieving it from there. 
// aws-amplify/../Auth.ts 
const identityId = await this._localStorage.getItem('CognitoIdentityId-' + identityPoolId);

I have tried to pre-populate that value in the AsyncStorage with the previous Cognito id using this code

import { AsyncStorage } from 'aws-amplify/lib/Common';
..
// Seed previous anonymous identity
await AsyncStorage.setItem('CognitoIdentityId-' + Config.identityPoolId, anonymousId)

// get anonymous id from cognito
// not equal to anonymousId above

The seeded value is not picked up by AWS amplify though. Could you please advise how I can achieve this?

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
0.4.1 on React native 0.54.0

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
@brianfoody How do you get that existing identityId? I can make Amplify to look for that existing one first before it generates a new one.

**Comment by brianfoody** [comment]
Hi @powerful23. Amplify already looks for an existing id though to remember anonymous users right? I would prefer to change my code to plug in to that and align with what you are doing so that we can formalise the approach for everyone.

Previously I was storing it using a LocalStorage class provided by AWS which saved it using AsyncStorage under;

`app-data: {
  anonymousId: "ap--"
}`

**Comment by brianfoody** [comment]
So this should do it?

`Amplify.configure({
      ...
      Analytics: {
        autoSessionRecord: false,
      }`

**Comment by brianfoody** [comment]
When can we expect a release with this code @powerful23 ?

**Comment by powerful23** [comment]
@nidsharm will publish a new version by this week.
