### ISSUE TITLE
Docs contain unreleased content (custom_headers in api config)

### ISSUE THREAD

**Issue by eddywashere** [aws/aws-amplify#918]
Do you want to request a feature or report a bug?

Documentation doesn't match what's in the stable release. I spent some time trying to figure out why my authorization header wasn't being sent to an api gateway endpoint. Turns out this was pushed recently: https://github.com/aws/aws-amplify/pull/910

It would be awesome to have versioned docs for this library.

**Comment by mbahar** [comment]
@eddywashere thanks for the feedback! We are planning to replace version info for the docs.
