### ISSUE TITLE
react example is NOT a PWA

### ISSUE THREAD

**Issue by whatsdis** [aws/aws-amplify#930]
I don't understand how the AWS Mobile React app found at https://console.aws.amazon.com/mobilehub/home?#/ is a PWA.

When I view it on my Galaxy s8, the login form is very tiny....

also when I preview it in other mobile modes via chrome inspector the same results...

this is disappointing to see Amazon label it as a PWA when it's not actually accessible.

**Comment by whatsdis** [comment]
Thank you, I didn't meant to be too harsh here and normally I wouldn't give a crap but I've spent the past year working on a large enterprise grade PWA React/Redux application so I couldn't help but point this out!

Any estimates on date?

**Comment by mlabieniec** [comment]
No problem! I don't currently have a date, but it is part of our backlog and should start in the next couple sprints.

**Comment by swaminator** [comment]
@whatsdis: We can't seem to find where you read that the React starter is a PWA. If you can send a screenshot that will be great!

**Comment by swaminator** [comment]
Closing this issue as OP hasn't responded to where he saw the PWA text. Please re-open if you identify where this text appears.
