### ISSUE TITLE
Getting error during signup in some phones not in all.

### ISSUE THREAD

**Issue by halaharr** [aws/aws-amplify#933]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
During signup it works in some phones and on simulators but does not work on some phone. Not sure why it will not work on those phones. Getting the following error:
**"Attribute did not confirm to the schemaL name: The attribute is required preferred_username: The attribute is requires"**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
Sign up user succfully.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
"aws-amplify": "^0.2.9",

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.
<img width="192" alt="screen shot 2018-05-28 at 11 55 09 am" src="https://user-images.githubusercontent.com/16997826/40622304-c1651400-626e-11e8-9240-8fca4f251d2e.png">

**Comment by halaharr** [comment]
If that is the case it should not be working on any phone. It works on some phone. I am passing in data as per the doc.

const data = await Auth.signUp({
      username: signUpData.email.trim().toLowerCase(),
      password: signUpData.password,
      attributes: {
        email: signUpData.email.trim().toLowerCase(),
        phone_number: signUpData.phone_number,
        given_name: signUpData.name.split(' ')[0],
        family_name: signUpData.name.split(' ')[1],
        birthdate: '01-01-1990',
        picture: ''
      }
    });

**Comment by mlabieniec** [comment]
Hm, this is strange.... Do you have any info on which phones/OS/version that are failing?

**Comment by halaharr** [comment]
It worked on iPhone 6 plus  but did not work on iPhone 6.

**Comment by mlabieniec** [comment]
Is that consistent on the iPhone 6 device or sporadic ? I'm not able to reproduce yet. Also I just noticed you are using a pretty old version 0.2. Can you give the latest a try and see if you are able to reproduce on the iPhone 6 device?

**Comment by halaharr** [comment]
It is happening all the time. It also happened yesterday on iPhone 7. It works fine on simulator or my iPhone 6 Plus. I will try the latest version. Thanks

**Comment by mlabieniec** [comment]
@halaharr were you able to test this out and find anymore information with the latest?

**Comment by halaharr** [comment]
Hi,
     Thanks for looking into the issue. It was a issue on my side. The same app is used to login for two different types of customers. I change the AWS config depending on who is logging in. In one particular use case I forgot to change the config. I really appreciate you looking into it.

Thanks
