### ISSUE TITLE
No userPool error with react native 

### ISSUE THREAD

**Issue by amls** [aws/aws-amplify#934]
I keep getting userpool error when I try to authenticate using auth from aws-amplify below are my dev dependencies, been trying to reinstall, making a new project from the start but gets me nowhere 
>  "amazon-cognito-identity-js": "^2.0.6",
>     "aws-amplify": "^0.4.1",
>     "aws-amplify-react-native": "^0.2.12",
>     "npm": "^5.7.1",
>     "react": "16.0.0",
>     "react-native": "0.51.0",
>     "react-navigation": "^2.0.2"

**Comment by amls** [comment]
have you found a fix @whatsdis  ?

**Comment by segheysens** [comment]
@amls Can this be reopened? I'm receiving the "No Userpool" error as well, with:
```
"react-native": "0.55.4",
"aws-amplify": "^0.4.4",
"aws-amplify-react-native": "^0.2.15",
```
I've confirmed my User Pool exists, and that there are Confirmed users in the pool.

**Comment by amls** [comment]
Yes, I just forgot adding this in my App.js file, right above export default like this

```
import AWSConfig from './aws-exports'
Amplify.configure(AWSConfig);


export default class App extends React.Component {
```
