### ISSUE TITLE
Error: User is not authenticated when .setDeviceStatusRemembered()

### ISSUE THREAD

**Issue by davidgatti** [aws/aws-amplify#943]
# Do you want to request a feature or report a bug?

Report a bug

# What is the current behavior?

When I login the user, I use `.getDevice()` to check if the browser is remembered or not. if not, I do redirect the logged in user to a special page where they have two options: either remember the browser or not. When on this new page the logged in user triggers `.setDeviceStatusRemembered()` function I get the following error:

```
Error: User is not authenticated
    at e.setDeviceStatusRemembered (amazon-cognito-identity.min.js:40)
    at HTMLButtonElement.<anonymous> (remember:106)
    at HTMLButtonElement.dispatch (jquery-3.2.1.slim.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.slim.min.js:3)
```

The screenshot bellow shows that the user is saved using the cookies, since in my scenario I will redirect the user to a different sub domain, meaning once logged in you don't stay on the same page.

![screen shot 2018-05-30 at 8 50 00 am](https://user-images.githubusercontent.com/411114/40703800-aa53ca4e-63e6-11e8-8dcd-e675943d1f2c.png)

This is how I create the user based on the saved session:

```
//
//	Create the user based on the information that is saved
//
var cognitoUser = userPool.getCurrentUser();

//
//	Populate the credentials from the data that is in local storage
//
cognitoUser.getCachedDeviceKeyAndPassword();
```

And the source code can be seen [here](https://github.com/0x4447/access.0x4447.com/blob/master/_input/views/remember.html) for your connivance

# What is the expected behavior?

I expect to have the `on_success` function to be triggered, once I call the `.setDeviceStatusRemembered()` function

# Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

- Amplify: since you don't put the version number in your source code I have no idea, I just copied the code from this repo a week ago, so whatever version was released a week ago.
- latest chrome, and latest safari

# You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

I did and no extra information was outputted.

**Comment by davidgatti** [comment]
Any day now ;)

**Comment by davidgatti** [comment]
Got it.

**Comment by emailismail** [comment]
@davidgatti 
Can you please update how you resolved this.

**We are trying to do this.**
- Use Cognito Auth flow to get auth code and then redirect to browser and then read this auth code from backend and generate cognito tokens(Id_token, aws_token, refresh_token).

We are using AWS hosted Cognito UI. The above thing is working perfectly the only challenge being device tracking is not working. The reason we are doing this is we dont want to store refresh_token in the browser.

So for the device tracking purpose we are ok to self host the Cognito UI or AmplifyJS, but we are still not able to figure out how to do this. In your comment you mentioned you got it, can you please share the solution.


@yuntuowang 

Thanks for all the support you are providing here in GitHub.

Do you have any idea how this will work any documentation on it as well? 

Regards,
Ismail
