### ISSUE TITLE
setPreferredMFA returning a 400: "User has not set up software token mfa"

### ISSUE THREAD

**Issue by CHR15-** [aws/aws-amplify#944]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

`setPreferredMFA(user, SMS);` causes a 400 to be raised by cognito, responding with: 
"User has not set up software token mfa"

We only have SMS enabled, but amplify is sending:

```
SMSMfaSettings: {PreferredMfa: true, Enabled: true}
SoftwareTokenMfaSettings: {PreferredMfa: false, Enabled: false}
```

I'm guessing including SoftwareTokenMfaSettings in the payload is causing an issue?

**What is the expected behavior?**

for `SoftwareTokenMfaSettings` to be omitted from the payload and receive an SMS text. The error is being checked from either: https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/dist/Widget/SelectMFAType.js#L114

or

https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L398

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

0.2.14.. tried rolling back to 0.2.13 and forward to 0.4.1 but same issue

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
@CHR15- we will bypass this error when you are only setting the MFA preference to 'SMS'. https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L406 So can you confirm that SMS is actually enabled afterwards.

**Comment by powerful23** [comment]
Feel free to reopen it if necessary.
