### ISSUE TITLE
Access to non-amplify features post Amilfy-Auth

### ISSUE THREAD

**Issue by tarundhillon** [aws/aws-amplify#953]
Do you want to request a feature or report a bug?
Access to non-amplify features post Amplify-Auth

I am trying to use credentials from Amplify-Auth to access other AWS features such as SQS. 

1. user is signed in using --
`Auth.signIn(username, password)
`
2. Fetch credentials and use to initialise SQS 
```
Auth.currentCredentials().then(credentials => {
      this.sqs = new AWS.SQS({
        credentials: credentials,
        region : 'eu-west-2'
      })
    });

```
3. make an SQS call 
`this.sqs.receiveMessage(params, (data)=>console.log('data::',data));`

The IAM user has access to the following policies 
- AmazonSQSFullAccess
- IAMFullAccess 
- AmazonMobileAnalyticsFullAccess
- AWSMobileHub_FullAccess
- CloudFrontFullAccess
- AmazonCognitoPowerUser

Result 
I get Access denied error 
_Error: Access to the resource https://sqs.eu-west-2.amazonaws.com/ is denied._

Questions 
1. Given the IAM policies, can I access non Amplify AWS features using Amplify Auth credentials ? 
2. How can I update AWS.config.credentials which will allow me to access all AWS APIs ?

Any suggestions / directions will be much appreciated. 

Thanks

**Comment by nidsharm** [comment]
Hi @tarundhillon,

The AWS credentials returned to you by Auth.signin can be used to access all AWS resources in your account.  Can you try updating the credentials on AWS config before initializing SQS? 

You can use : 
```
AWS.config.update({region: REGION, credentials: credentials});
```
to update your config with credentials. Do let us know if you face any other issues.

**Comment by tarundhillon** [comment]
Thanks !! I have tried to update AWS.config as proposed it but still getting the same error... seems like an issue with AIM

**Comment by mlabieniec** [comment]
@tarundhillon did you use the awsmobile-cli to create your project? If so, it will setup a Federated Identities Pool AND a User Pool. So you should have access to both unless you setup yourself and are using the hosted UI. Your code looks correct (I tested with Route53 and Kinesis)...usually the only reason you'd get this permission denied error would be either the Auth or UnAuth Role (which ever you are using) does not have the correct permissions in the IAM policy....is the "AmazonSQSFullAccess" policy on your Auth or UnAuth role in Cognito Federated Identities?

**Comment by tarundhillon** [comment]
i have used awsmobile-cli to setup the project and I have both Federated Identities pool and User pool setup as part of the configuration automatically. But for my auth flow I have created a user using Cognito Pool and I use the username & password for the auth steps listed above, hence I believe I am not using Federated Identities Pool.

I have done further digging around and found that the credentials are being updated correctly, the problem now is with the IAM policies not being picked up by the **Role - 
 APPNAME_auth_MOBILEHUB_2026850xxx**   as it only applies to **Trusted Entities - Identity Provider: cognito-identity.amazonaws.com**

When I apply policies to **Role - APPNAME_unauth_MOBILEHUB_2026850xxx**, everything works fine. So wondering now to apply a auth role while using Cognito Pool only?

Thanks for your help.

**Comment by mlabieniec** [comment]
@tarundhillon You can do this with [Groups](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html). If you create a group you can assign an IAM role to it. You can also signin directly to User Pools (not federating with identity pools) using the [Hosted UI](https://aws.github.io/aws-amplify/media/authentication_guide#using-amazon-cognito-hosted-ui) option.

**Comment by tarundhillon** [comment]
@mlabieniec thanks .. by default the APPNAME_auth_MOBILEHUB_2026850xxx was Role added to the Group. The issue in my case was that since the user was created manually in the Cognito Pool I had to reset the password because authState wasn't signedIn

```
>       this.cognitoUser.completeNewPasswordChallenge('new password',  [], {
>         onSuccess: (session)=>console.log('password changed success',session),
>         onFailure: (err)=>console.log('failure', err) 
>       });
```
This link was also helpful. 
https://stackoverflow.com/questions/40287012/how-to-change-user-status-force-change-password

Thanks for the help.
