### ISSUE TITLE
Converting unauthenticated users to authenticated using the withAuthenticated react HOC

### ISSUE THREAD

**Issue by ajhool** [aws/aws-amplify#96]
I'm having some trouble with the authentication flow for converting Cognito unauthenticated users to authenticated users. Does the withAuthenticated react HOC allow for converting an unauthenticated user into an authenticated user? 

Example use-case: 
First, an anonymous user selects their favorite color as "blue", which is persisted to an anonymous Cognito user.
Second, the user then attempts to enter an area that is wrapped by the withAuthenticator component, triggering the federated sign in / sign up flow.
Third, the user receives authenticated credentials -- their "blue" preference is now associated with the authenticated account.

**Comment by jkettmann** [comment]
Any updates on this?

**Comment by richardzcode** [comment]
Hi @ajhool @jkettmann , in general open the door to mutate one user's property by another identity always triggers security concern. Especially from an anonymous identity. As a common library it has to be very careful on this.

In particular project though I do understand it is a decision of app owner. What I would do in this case is to handle the conversion in app logic. One approach could be to save those data in localStorage / memory, then after sign in decide apply or not.

```
import { Cache } from 'aws-amplify';

...
Cache.setItem('guest_preferences', { color: 'blue'});
...
```

Then somewhere after sign in

```
if (firstTimeSignIn) {
  const preferences = Cache.getItem('guest_preferences');
  if (preferences && someOtherValidation) {
    apply(preferences);
  }
}
```

**Comment by ajhool** [comment]
@jkettmann I'm excited to see where Amplify goes but have found it to be a little too constrained for my own use-cases at the moment, so I've been working with ordinary components. MobileHub is great for boilerplate, has configurable auth UIs for android/ios/js, and is a little more flexible -- it's been working for me to building app skeletons.

**Comment by mlabieniec** [comment]
@jkettmann feel free to re-open this if you feel like we can do a better job of automating this process. it seems like @richardzcode solution should work well since we we really wouldn't have much context around what the user would want to do with these preferences.
