### ISSUE TITLE
InvalidParameterException when deleted user signs up again

### ISSUE THREAD

**Issue by hrmoller** [aws/aws-amplify#964]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
The below error is thrown when a deleted user signs up again, but the user is added to the user pool anyways and no confirmation mail is sent.

```js
{
	code: "InvalidParameterException"
	message: "Cannot perform specific action because there does not exist a valid use pool domain associated with the user pool"
	name: "InvalidParameterException"
}
```

1. New user signs up successfully using a custom form that implements `Auth.signUp`
2. The new user is deleted manually using the AWS Console
3. The user signs up again and then the above error is thrown in the client console. But checking the user pool in the AWS Console the user is present again but no confirmation mail is sent.

**What is the expected behavior?**
When a user is deleted from a user pool, whether it's manually or programmatically, it should be possible for that user to sign up again just as if he/she was a completely new user.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
`"aws-amplify": "^0.4.1"`

The error is verified in FF (58.0b5), Chrome (69.0.3445.0) and Safari (11.1) all on macOS 10.13.4

I don't know if worked probably in earlier versions as I've just started using AWS Amplify.

**You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.**
Doesn't seem to bring anything new to the table.

**Comment by hrmoller** [comment]
Just a short follow up to the above.

1. It seems as even though the user is deleted in the AWS Console it isn't really removed which in my eyes is annoying, but also troubles GDPR compliance as users should be removed completely.

2. Using the AWS CLI (`aws cognito-idp admin-delete-user`) seems to do the job and remove the user as expected. When a user signs up again with the same credentials everything happens as expected.

**Comment by hrmoller** [comment]
Well the issue seems to have disappeared now. I'll monitor and close this issue if I can't reproduce shortly.

**Comment by mlabieniec** [comment]
@hrmoller thanks for reporting this. @yuntuowang are you guys aware of any issues here?

**Comment by yuntuowang** [comment]
Hi @mlabieniec, we are not aware of this. Thanks @hrmoller, let me know if this issue still happen. We will look into it at the meantime.

**Comment by hrmoller** [comment]
Seeing this again

**Comment by hrmoller** [comment]
@yuntuowang @mlabieniec so now it occurs again. Let me now if you need any pool IDs on anything
