### ISSUE TITLE
AWS Amplify Permission denied

### ISSUE THREAD

**Issue by sarchak** [aws/aws-amplify#969]
I am trying to access an API gateway endpoint using AWS amplify but I keep getting permission denied.

However, I can directly access the api using the api gateway url directly.
Any idea as to what the reason could be?

Here is my setup
CloudFront -> ReactApp -> API Gateway

I have mandatorySignIn: false in Amplify configure. Also for the endpoint I am testing here are the configuration.
```
Authorization None
API Key Not required
```

**Comment by sarchak** [comment]
Another interesting point is that it works fine when testing locally but when deployed to production I get Access Denied

**Comment by sarchak** [comment]
Figured it out.

**Comment by hrmoller** [comment]
Anything you wanna share?

**Comment by sarchak** [comment]
I was missing the root object for the cloudfront domain.
