### ISSUE TITLE
aws-amplify-react does not verify contact information after "challenged" login

### ISSUE THREAD

**Issue by youngbob** [aws/aws-amplify#977]
#### Do you want to request a feature or report a bug?

Bug.

#### What is the current behavior?

If the user signs in and there is no "challenge" (such as `NEW_PASSWORD_REQUIRED` or `SMS_MFA`), the `SignIn` component will then call `Auth.verifiedContact(user)`, which will optionally move the state to `verifyContact` and seems to have the side effect of setting `attributes` on the authData/user. If the state instead changes to `requireNewPassword`, `confirmSignIn`, or `TOTPSetup` first, then the state transitions to `signedIn` (after challenge completion) without ever calling `verifyContact`. The user data set on `authData` does not have any `attributes` set either, though they are available on `authData.challengeParam.userAttributes`.

#### What is the expected behavior?

Each challenge step that moves the state to `signedIn` should first check the contact information like the `SignIn` component does. Once the user is signedIn, the user attributes should be set on the authData.

#### Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

aws-amplify-react 0.1.47

#### You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

Good to know, thanks.

**Comment by powerful23** [comment]
Hi I just include the fix in another pr which also fix other issues around `verifyContact` component.
