### ISSUE TITLE
code: "UnknownError", message: "Unkown error" When Sign in Using AWS-AMPLIFY

### ISSUE THREAD

**Issue by yonisetiawan** [aws/aws-amplify#990]
i have problem when i sign in using aws-amplify ?

```
import Amplify, {Auth} from 'aws-amplify';
import Config from '../lib/Config/Index.js';
Amplify.configure(Config);

Auth.signIn(this.state.email, this.state.password)
      .then(user => console.log(user))
      .catch(err => console.log(err));
```

i get error like this

`{code: "UnknownError", message: "Unkown error"}`

i already set "NO" on `Do you want to remember your user's devices?`

<img width="659" alt="screen shot 2018-06-06 at 11 22 04 am" src="https://user-images.githubusercontent.com/14344276/41022148-d7e85ef0-6992-11e8-98a3-4b5e12d1472f.png">
<img width="636" alt="screen shot 2018-06-06 at 11 21 55 am" src="https://user-images.githubusercontent.com/14344276/41022150-d82c2c8e-6992-11e8-9149-ff79ba566c52.png">
<img width="461" alt="screen shot 2018-06-06 at 11 21 41 am" src="https://user-images.githubusercontent.com/14344276/41022151-d8655b80-6992-11e8-938f-ba5bcb2614da.png">

**Comment by mlabieniec** [comment]
@yuntuowang do you have any insight here on why this would be returning unknown error?

**Comment by yonisetiawan** [comment]
Done 

How to solve 👍
disable optional value on CONFIG

like this 

```
Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
    identityPoolId: process.env.REACT_APP_IDENTITY_POOL_ID,
    // REQUIRED - Amazon Cognito Region
    region: process.env.REACT_APP_REGION,
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: process.env.REACT_APP_USER_POOL_ID,
    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: process.env.REACT_APP_USER_POOL_WEB_CLIENT_ID,
    // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
    //    mandatorySignIn: process.env.REACT_APP_MANDATORY_SIGNIN,
    // OPTIONAL - Configuration for cookie storage
    //cookieStorage: {
    // REQUIRED - Cookie domain (only required if cookieStorage is provided)
    //    domain: process.env.REACT_APP_COOKIESTORAGE_DOMAIN,
    // OPTIONAL - Cookie path
    //    path: process.env.REACT_APP_COOKIESTORAGE_PATH,
    // OPTIONAL - Cookie expiration in days
    //  expires: process.env.REACT_APP_COOKIESTORAGE_EXPIRES,
    // OPTIONAL - Cookie secure flag
    //    secure: process.env.REACT_APP_COOKIESTORAGE_SECURE,
    //}
  },
```

**Comment by yonisetiawan** [comment]
change to be 


`global.fetch = require('node-fetch');
const Amplify = require( 'aws-amplify' ).default;
const Auth = Amplify.Auth;

Amplify.configure( {
    Auth: {
        // REQUIRED - Amazon Cognito Identity Pool ID
        identityPoolId: 'us-east-2:...',
        // REQUIRED - Amazon Cognito Region
        region: 'us-east-2',
        // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'us-east-2_', // email & password
        // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: '', // email & password
    }
} );

     Auth.signIn( e, password )
        .then(user => console.log(user))
        .catch(err => console.error('[ERR]', err));`
